pom.xml
Running `mvn dependency:tree` I see snakeyaml 1.26 , so I expect it fixes the issue.
@gs-bracej - is this a valid solution, although we haven't quite figured out why this version conflict only happens on this module and not on others?
=> Fix snakeyaml version

legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/transformer/SetImplTransformers.java, legend-engine-executionPlan-execution/src/test/java/org/finos/legend/engine/plan/execution/result/transformer/TestSetImplTransformers.java
Serialization transformers for Boolean datatypes should handle numeric values, where zero means false and non-zero values means true.
=> Support numeric values in Boolean result serialization transformer

legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/url/DataProtocolHandler.java, legend-engine-shared-core/src/test/java/org/finos/legend/engine/shared/core/url/test/TestDataUrl.java
Identified a bug in url processing flow. Bug impacts use-cases where testdata contains special characters (#, ?)
=> fix url issue

legend-engine-language-pure-modelManager-sdlc/src/main/java/org/finos/legend/engine/language/pure/modelManager/sdlc/SDLCLoader.java, legend-engine-language-pure-modelManager-sdlc/src/main/java/org/finos/legend/engine/language/pure/modelManager/sdlc/alloy/AlloySDLCLoader.java
- Added a function to check if all packageableElementPointers exist in the loaded project data from the Alloy metadata server
- Return a runtime error if the pointers don't exist in the project, logging the missing paths
=> changes to support Prod Studio services registration

.github/workflows/docker.yml, legend-engine-server/Dockerfile
Add Docker security scan.
Also update `Dockerfile` to use a fixed version of `openjdk` base image instead of `openjdk:11` which is equivalent to the `latest` tag. Otherwise, we are not confident of which `openjdk` image we're using and thus, making debugging harder - For example, see https://github.com/aquasecurity/trivy/issues/885
Context https://github.com/finos/legend/issues/360
=> Add Docker security scan

legend-engine-executionPlan-execution/src/test/java/org/finos/legend/engine/plan/execution/result/test/serialization/TestTemporaryFile.java
Evaluate whether on mac first since IS_OS_LINUX || IS_OS_UNIX is true on a Mac
=> Fix MacOSX tests (#115)

legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/mapping/MappingParseTreeWalker.java, legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestMappingGrammarRoundtrip.java, legend-engine-language-pure-store-relational/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalGrammarRoundtrip.java
When compiling included mapping, substitute store "[dbInc->db]" syntax was not parsed to graph
=> Add support for storeSubPath in included mapping

legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalDatabaseConnectionBuilder.java
If HelperRelationalBuilder.resolveDatabase fails, we still want to add
properties to the connection - common use case is if the connection is using a
place holder element for which database resolution will fail but we still want
to construct a connection
=> Ensure properties are always added to RelationalDBConnection

legend-engine-executionPlan-execution-store-relational/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/manager/strategic/RelationalConnectionManager.java, legend-engine-executionPlan-execution-store-relational/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/manager/strategic/StrategicConnectionExtension.java
Allow extra authentication strategy transformer to be provided as plugins
Example - Oauth with SnowflakeDatasourceSpec
=> Allow extra authentication strategy transformer to be provided as plugins

legend-engine-executionPlan-execution-store-relational/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/serialization/RelationalResultToJsonDefaultSerializer.java, legend-engine-executionPlan-execution-store-relational/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/serialization/RelationalResultToPureFormatSerializer.java
We need to add this check as db2 closes out the resultSet after streaming last row and fails on next call
(https://www.ibm.com/support/pages/invalid-operation-result-set-closed-error-data-server-driver-jdbc)
=> Check if resultSet is closed before invoking next

legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDomainCompilationFromGrammar.java, legend-engine-language-pure-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/core/CoreLexerGrammar.g4, legend-engine-language-pure-store-relational/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/RelationalDatabaseConnectionLexerGrammar.g4
We use time zone in numeric format for relational database connection that is specified as (('+' | '-')(Digit)(Digit)(Digit)(Digit))
When this is available in Core Lexer, the parser can sometimes take a part of expression for a time zone e.g. 
greaterThanEqual($this.start, $this.end **-1000** ) and fail as a result.
Proposed solution is to move time zone from Core Lexer to Relational Database Connection Lexer.
Note that this is not affecting time zone that is a part of date - that part is still untacked as we are using timeZone fragment there, not TIMEZONE from lexer.
=> Fix issue with number in expression being parsed as time zone

legend-engine-executionPlan-execution-store-relational-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/authentication/strategy/DelegatedKerberosAuthenticationStrategy.java
If a non-null username is passed in HikariConfig, getConnection call is made with [username and password](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/PoolBase.java#L364). Avoid this in case of DelegatedKerberos authentication strategy and rely on performing the call as a particular subject (Subject.doAs). In the case that some database driver requires _user_ datasource property to be set for DelegatedKerberos authentication strategy, it should be handled in the respective database manager.
=> Use null login for DelegatedKerberos authentication strategy

legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperValueSpecificationBuilder.java, legend-engine-language-pure-grammar-api/src/test/java/org/finos/legend/engine/language/pure/grammar/api/test/TestJsonToGrammarApi.java, legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/DEPRECATED_PureGrammarComposerCore.java, legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperMappingGrammarComposer.java, legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperValueSpecificationGrammarComposer.java, legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestDomainGrammarRoundtrip.java, legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestLambdaPrettyRendering.java, legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestLambdaRoundtrip.java
We made a few modifications to how lambda JSON is transformed to text. See the list below for details:
Before:
```
|test::Person.all()
->filter
(
f|$f.name->startsWith('ok') &&
(true ||
(3 == 4))
)
->groupBy
(
[
], 
[
agg(x|$x.lastName, x|$x->distinct()->someFunc(true, 'someString', 90) + $x.lastName)
], 
[
'LastName'
]
)->distinct()->sort([
'LastName'->asc()
])->take(30)
```
After:
```
|test::Person.all()->filter(
f|$f.name->startsWith('ok') &&
(true || (3 == 4))
)->groupBy(
[],
[
agg(
x|$x.lastName,
x|$x->distinct()->someFunc(
true,
'someString',
90
) + $x.lastName
)
],
['LastName']
)->distinct()->sort(
[
asc('LastName')
]
)->take(30)
```
=> Grammar composer: Make formatting indentation more consistent and fix `pretty` rendering for lambda

legend-engine-executionPlan-execution-store-relational-connection/pom.xml, legend-engine-executionPlan-execution-store-relational-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/snowflake/SnowflakeManager.java, legend-engine-executionPlan-execution-store-relational-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/specifications/SnowflakeDataSourceSpecification.java, legend-engine-executionPlan-execution-store-relational-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/specifications/keys/SnowflakeDataSourceSpecificationKey.java, legend-engine-executionPlan-execution-store-relational-connection/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/SnowflakeDataSourceSpecificationTest.java, legend-engine-executionPlan-execution-store-relational-connection/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/TestConnectionObjectProtocol_server.java, legend-engine-executionPlan-execution-store-relational/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/manager/strategic/DataSourceSpecificationKeyGenerator.java
Quote snowflake identifiers when quoteIdentifiers flag is set in connection.
This is required to connect to warehouse/database whose names are in case other than upper_case
=> Quote snowflake identifiers when quoteIdentifiers flag is set in connection

.gitignore, legend-engine-application-query/pom.xml, legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/api/QueryAPI.java, legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/configuration/QueryAPIConfiguration.java, legend-engine-server/pom.xml, legend-engine-server/src/main/java/org/finos/legend/engine/server/Server.java, legend-engine-server/src/main/java/org/finos/legend/engine/server/ServerConfiguration.java, legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig.json, legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/vault/PropertiesVaultImplementation.java, legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/vault/Vault.java, legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/vault/VaultImplementation.java, legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/vault/VoidVault.java
Continuation of #333 and related to https://github.com/finos/legend-studio/issues/325
=> Rework Query APIs to get configuration from Vault

legend-engine-query-pure/src/test/java/org/finos/legend/engine/query/pure/api/test/inMemory/TestM2MGrammarCompileAndExecute.java
Add test for decimal value fix in legend-pure (https://github.com/finos/legend-pure/pull/299)
Test needs to be in legend-engine, as the legend-pure JSON deserializer cannot handle the decimal value used in this test.
Note: this test will fail until [this](https://github.com/finos/legend-pure/pull/299) is merged and released in legend-pure
=> M2M: Test with large decimal values

legend-engine-server/Dockerfile
Trying to fix issue with Docker build, since `Bullseye` is the latest stable version of `Debian`, while waiting for `openjdk` to bump this for their `debian-based` image (which I'm not too sure when would that happen), we can go with this first.
I figured [this conversation](https://github.com/zulu-openjdk/zulu-openjdk/issues/107) prompted that `CVE-2021-3711` is resolved by this upgrade.
=> Upgrade openjdk:11.0.12-bullseye for Docker image

legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/api/ApplicationQuery.java, legend-engine-language-pure-dsl-data-space/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/DataSpaceLexerGrammar.g4, legend-engine-language-pure-dsl-data-space/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/DataSpaceParserGrammar.g4, legend-engine-language-pure-dsl-data-space/src/main/java/org/finos/legend/engine/language/pure/dsl/dataSpace/compiler/toPureGraph/DataSpaceCompilerExtension.java, legend-engine-language-pure-dsl-data-space/src/main/java/org/finos/legend/engine/language/pure/dsl/dataSpace/grammar/from/DataSpaceParseTreeWalker.java, legend-engine-language-pure-dsl-data-space/src/main/java/org/finos/legend/engine/language/pure/dsl/dataSpace/grammar/to/DataSpaceGrammarComposerExtension.java, legend-engine-language-pure-dsl-data-space/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/dataSpace/DataSpace.java, legend-engine-language-pure-dsl-data-space/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestDataSpaceCompilationFromGrammar.java, legend-engine-language-pure-dsl-data-space/src/test/java/org/finos/legend/engine/language/pure/dsl/text/grammar/test/TestDataSpaceGrammarParser.java, legend-engine-language-pure-dsl-data-space/src/test/java/org/finos/legend/engine/language/pure/dsl/text/grammar/test/TestDataSpaceGrammarRoundtrip.java, legend-engine-language-pure-dsl-service/pom.xml, legend-engine-language-pure-dsl-service/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ServiceLexerGrammar.g4, legend-engine-language-pure-dsl-service/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ServiceParserGrammar.g4, legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/compiler/toPureGraph/ServiceCompilerExtensionImpl.java, legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/from/ServiceParseTreeWalker.java, legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/to/ServiceGrammarComposerExtension.java, legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/service/Service.java, legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceCompilationFromGrammar.java, legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceGrammarRoundtrip.java, legend-engine-language-pure-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/domain/DomainParserGrammar.g4, legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestDomainGrammarRoundtrip.java
=> Add support for tagged values and stereotypes in `Service` and `DataSpace`

legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/domain/DomainParseTreeWalker.java, legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestLambdaRoundtrip.java
Without this change the second %latest parameter will be lost, which is causing execution to fail
=> Fix lambda with biTemporal class in property expression

legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalBuilder.java, legend-engine-language-pure-store-relational/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalCompilationFromGrammar.java
The columns referenced on the milestone details needs to exists on the table schema definition.  If a user forgets to define it, they could get cryptic errors inside pureToSql.  This bugfix ensure we throw early, on the compilation phase, and that the error is meaningful to the user to understand how to action it.
=> Add milestone column validations to ensure they exists on table definition

legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/PlanExecutor.java, legend-engine-language-pure-dsl-service-execution/src/main/java/org/finos/legend/engine/language/pure/dsl/service/execution/AbstractServicePlanExecutor.java, legend-engine-language-pure-dsl-service-execution/src/main/java/org/finos/legend/engine/language/pure/dsl/service/execution/OperationalContext.java, legend-engine-language-pure-dsl-service-execution/src/main/java/org/finos/legend/engine/language/pure/dsl/service/execution/ServiceRunner.java, legend-engine-language-pure-dsl-service-execution/src/main/java/org/finos/legend/engine/language/pure/dsl/service/execution/ServiceRunnerInput.java, legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/test/TestServiceRunner.java, legend-engine-language-pure-dsl-service-execution/src/test/resources/org/finos/legend/engine/pure/dsl/service/execution/test/simpleM2MService.pure
This PR allows configuration of graphFetch batch memory limit when executing services using service-execution JAR.
Benefits:
1. Allow graph fetch executions with large objects in JAR execution flow (which exceed 50MB limit)
2. Improve query performance by using large batch sizes when executing in a dedicated runtime
=> Allow configuration of graphFetch batch memory limit in ServiceRunner API

legend-engine-language-pure-modelManager-sdlc/src/main/java/org/finos/legend/engine/language/pure/modelManager/sdlc/alloy/AlloySDLCLoader.java
This is to make `AlloySDLCLoader` work with https://github.com/finos/legend-depot as right now the metadata server calls are hardcode with prefix `/metadata/api`
=> Make AlloySDLCLoader to account for more generic metadata server URLs

legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/test/runner/service/ServiceTestGenerationHelper.java, legend-engine-test-runner-service/src/test/java/org/finos/legend/engine/test/runner/service/TestRuntimeGenerationForServiceTests.java
Currently If Runtime path is provided is service spec, while generating H2 runtime for testing , it returns the original runtime instead of generating a new H2 runtime. Handled this case with this commit
=> generate test Runtime for runtime pointer provided in service spec

legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperRelationalGrammarComposer.java, legend-engine-language-pure-store-relational/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalConnectionGrammarRoundtrip.java
SchemaTo field in postprocessing mappers was being dropped if SchemaTo=SchemaFrom. It was causing failures in Studio when switching to text mode . As Studio tried to fetch grammar from Legend-sdlc but this 'schemaTo' field was being dropped , causing failure in compilation. Added Round trip test for same case
=> corrected SchemaTo field being dropped in postprocessing mappers in toGrammar Api

legend-engine-external-format-flatdata-runtime/src/test/java/org/finos/legend/engine/external/format/flatdata/read/test/TestFlatDataQueries.java, legend-engine-external-format-xml-runtime/src/test/java/org/finos/legend/engine/external/format/xml/test/TestXmlQueries.java, legend-engine-external-shared-format-model/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/externalSource/ExternalSourceSpecificationLexerGrammar.g4, legend-engine-external-shared-format-model/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/externalSource/ExternalSourceSpecificationParserGrammar.g4, legend-engine-external-shared-format-model/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ExternalFormatConnectionCompilerExtension.java, legend-engine-external-shared-format-model/src/main/java/org/finos/legend/engine/language/pure/grammar/from/ExternalFormatConnectionGrammarParserExtension.java, legend-engine-external-shared-format-model/src/main/java/org/finos/legend/engine/language/pure/grammar/from/externalSource/ExternalSourceSpecificationParseTreeWalker.java, legend-engine-external-shared-format-model/src/main/java/org/finos/legend/engine/language/pure/grammar/to/ExternalFormatGrammarComposerExtension.java, legend-engine-external-shared-format-model/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestExternalFormatConnectionCompilation.java, legend-engine-external-shared-format-model/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestExternalFormatConnectionGrammarParser.java, legend-engine-external-shared-format-model/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestExternalFormatConnectionGrammarRoundtrip.java, legend-engine-external-shared-format-runtime/src/main/java/org/finos/legend/engine/external/shared/runtime/ExternalFormatExecutionExtension.java, legend-engine-external-shared-format-runtime/src/main/java/org/finos/legend/engine/external/shared/runtime/read/ExecutionHelper.java, legend-engine-external-shared-format-runtime/src/test/java/org/finos/legend/engine/external/shared/runtime/test/TestExternalFormatQueries.java, legend-engine-protocol-external-shared-format/src/main/java/org/finos/legend/engine/external/shared/ExternalFormatProtocolExtension.java, legend-engine-protocol-external-shared-format/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/external/shared/ParameterExternalSourceExecutionNode.java, legend-engine-protocol-external-shared-format/src/main/java/org/finos/legend/engine/protocol/pure/v1/packageableElement/external/shared/ParameterExternalSource.java, legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/test/runner/service/ServiceTestGenerationHelper.java
This PR adds support for having function/service parameters as sources of external format connections.
Depends on https://github.com/finos/legend-pure/pull/363. Build will fail till legend-pure version uptick happens with this change.
=> Add support for function/service parameters as sources of external format connections

legend-engine-executionPlan-execution-store-relational/pom.xml, legend-engine-executionPlan-execution-store-relational/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/RelationalGraphFetchUtils.java, legend-engine-executionPlan-execution-store-relational/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/full/graphFetch/cache/TestPlanExecutionWithGraphFetchCrossKeyCache.java, legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/cache/graphFetch/GraphFetchCacheKey.java
Depends on https://github.com/finos/legend-pure/pull/390. Build will fail till legend-pure version uptick happens.
This PR (combined with above legend-pure PR) makes graph fetch cross property caches serializable, thereby allowing remote cache implementations or other kinds of serializable caches implementations to be used in the context of graph fetch cross store property queries.
=> Make graph fetch cross key caches serializable

legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/test/runner/service/ServiceTestRunner.java, legend-engine-test-runner-service/src/test/java/org/finos/legend/engine/test/runner/service/TestServiceTestRunner.java, legend-engine-test-runner-service/src/test/resources/legend-sdlc-test-services-with-multi-param.json
**Overview**
Process test parameters so that they are wrapped in a single ConstantResult. This fixes a bug where service test runs fail due to unexpectedly encountering parameters wrapped in nested ConstantResult objects.
**Testing**
Unit test added to test a service with multi-parameter tests and ensures the service test executes correctly.
=> Fix processing of multiple service test parameters

.github/workflows/build.yml, legend-engine-server/pom.xml
Add Docker snapshot build to be used for integration testing of Legend application stack. The immediate usage right now is for Studio E2E testing.
I have tested this. See my repo at https://github.com/akphi/legend-test-space/runs/4439338167?check_suite_focus=true
=> add Docker snapshot build for integration testing

pom.xml
I'm trying to see if this fixes the problem with Docker snapshot publish. I don't think so since when I inspect the pipeline, the correct version of the plugin is downloaded anyway.
@maoo Could you reset the values of `DOCKER_USERNAME` and `DOCKER_PASSWORD` to be similar to what I have in SDLC? With the same configuration, SDLC is publishing snapshot to Docker now
https://github.com/finos/legend-sdlc/runs/4444460063?check_suite_focus=true
Not with Engine
https://github.com/finos/legend-engine/runs/4460971860?check_suite_focus=true
```
Error:  unauthorized: incorrect username or password
Warning:  An attempt failed, will retry 1 more times
...
Error:  toomanyrequests: too many failed login attempts for username or IP address
...
Error:  Failed to execute goal …
```
=> minor update to the POM

legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/CompileContext.java, legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PureModel.java, legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/TestCompilerContext.java
Unless user uses auto-imports
Also project specific import's resolutions won't be cached
=> Cache common imports instead of resolving them each time

legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/domain/date/PureDate.java, legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/util/Library.java
Switch to using long values for microsecond computations on PureDate.
This PR will fail to build until https://github.com/finos/legend-pure/pull/415 is merged in legend-pure
Mapping execution test has been added to the legend-pure PR
=> Use long for PureDate microsecond computations

legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/json/JsonSerializer.java, legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/serialization/ExecutionResultObjectMapperFactory.java, legend-engine-executionPlan-execution/src/test/java/org/finos/legend/engine/plan/execution/result/test/serialization/TestExecutionResultObjectMapperFactory.java, legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/ObjectMapperFactory.java, legend-engine-shared-core/src/test/java/org/finos/legend/engine/shared/core/test/TestObjectMapperFactory.java
This prevents exceptions on streams that are sensitive the close call.
=> Prevent jackson from closing the output stream when generating JSON

legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/identity/Identity.java, legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/identity/credential/AnonymousCredential.java, legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/identity/factory/DefaultIdentityFactory.java, legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/identity/factory/IdentityFactory.java
This PR introduces minor, backwards compatible changes to the Identity API.
These changes are required for other PRs. See #495 #485
=> Update Identity API

legend-engine-executionPlan-execution-store-relational/pom.xml, legend-engine-executionPlan-execution-store-relational/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/RelationalExecutor.java, legend-engine-executionPlan-execution-store-relational/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/execution/TestRelationalExecutor.java, legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/helpers/freemarker/FreeMarkerExecutor.java
Freemarker exceptions were not bubbling up properly, and query template (before freemarker) were executed, leading to sql exceptions.  By bubbling the freemarker errors, it should be more clear what is the problem.
=> Fix relational executor freemarker exception handling

legend-engine-executionPlan-execution-external-store-service/src/test/java/org/finos/legend/engine/plan/execution/stores/service/utils/ServiceStoreTestUtils.java, legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/PlanExecutor.java, legend-engine-language-pure-dsl-service-execution/pom.xml, legend-engine-language-pure-dsl-service-execution/src/main/java/org/finos/legend/engine/language/pure/dsl/service/execution/AbstractServicePlanExecutor.java, legend-engine-language-pure-dsl-service-execution/src/main/java/org/finos/legend/engine/language/pure/dsl/service/execution/ServiceParameter.java, legend-engine-language-pure-dsl-service-execution/src/main/java/org/finos/legend/engine/language/pure/dsl/service/execution/ServiceRunner.java, legend-engine-language-pure-dsl-service-execution/src/main/java/org/finos/legend/engine/language/pure/dsl/service/execution/ServiceVariable.java, legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/TestServiceRunner.java
This PR adds new APIs to ServiceRunner to be able to:
- Get the service result type - useful to know how to parse the results of the execution (tds, graph, constant value, etc)
- Get the list of variables the service expects and details of these variables - useful when operating on the ServicerRunner interface rather than on the SDLC generated instance.  
With the changes, the PR also ensure all the run/execution APIs support the same features, reducing confusion among users.
This also moves execution logic from legend-sdlc, letting SDLC define the service and its arguments, and engine to define how these will be use and executed.
=> Add new APIs to ServiceRunner to allow better programmatic executions

legend-engine-executionPlan-execution-store-inMemory/src/test/java/org/finos/legend/engine/plan/execution/stores/inMemory/TestPlanExecutor.java, legend-engine-executionPlan-execution-store-inMemory/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/FakeRelationalStoreExecutorBuilder.java, legend-engine-executionPlan-execution-store-inMemory/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/FakeServiceStoreExecutorBuilder.java, legend-engine-executionPlan-execution-store-inMemory/src/test/resources/META-INF/services/org.finos.legend.engine.plan.execution.stores.StoreExecutorBuilder, legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/PlanExecutor.java
This PR fixes a bug in the factory method that accepts store executor configurations as input.
The bug is that the factory creates an executor of type T if and only if a configuration for type T is also provided as input.
The desired behavior is that the factory creates executors for all types T.
If a configuration for type T is provided as input, the corresponding builder is invoked with this configuration. Otherwise the no-arg build method is invoked.
=> Fix bug in plan executor construction

legend-engine-language-pure-dsl-service-execution/src/main/java/org/finos/legend/engine/language/pure/dsl/service/execution/AbstractServicePlanExecutor.java, legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/SimpleRelationalServiceRunnerTDS.java, legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/TestServiceRunner.java, legend-engine-language-pure-dsl-service-execution/src/test/resources/plans/org/finos/service/SimpleRelationalService.json, legend-engine-language-pure-dsl-service-execution/src/test/resources/plans/org/finos/service/SimpleRelationalServiceRunnerTDS.json
This rollbacks this changes: https://github.com/finos/legend-engine/pull/518/files#diff-d7d199bf41928d214e88941922d2af5b7581f9871f35e9d9ed90931cce5dc0d4R289
=> Rollback ServiceRunner result processing to ensure proper RelationalResult processing

.github/workflows/docker.yml, legend-engine-server/Dockerfile
=> update Docker checker and openjdk image

legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalBuilder.java, legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/grammar/from/RelationalGrammarParserExtension.java, legend-engine-language-pure-store-relational/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalCompilationFromGrammar.java
- Add proper handling localPropertyMappings (information added: type and multiplicity)
- Add proper handling for relational filters (filterName field should not be empty as it is used in protocol transofmartions)
- Propagate stores information in relational association mappings parsing (otherwise protocol transformation may fail)
=> Add missing steps in relational parsing and compiling

legend-engine-executionPlan-execution-store-relational-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/authentication/strategy/DelegatedKerberosAuthenticationStrategy.java, legend-engine-executionPlan-execution-store-relational-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/DataSourceWithStatistics.java
This PR refactors the delegated auth strategy to use the Identity API.
=> Refactor Kerberos auth to use identity/flow

legend-engine-language-pure-grammar-api/src/test/java/org/finos/legend/engine/language/pure/grammar/api/test/TestGrammarGraphFetchApi.java, legend-engine-language-pure-grammar-api/src/test/java/org/finos/legend/engine/language/pure/grammar/api/test/TestGrammarLambdaApi.java, legend-engine-language-pure-grammar-api/src/test/java/org/finos/legend/engine/language/pure/grammar/api/test/TestGrammarModelApi.java, legend-engine-language-pure-grammar-api/src/test/java/org/finos/legend/engine/language/pure/grammar/api/test/TestGrammarValueSpecificationApi.java, legend-engine-language-pure-store-relational-grammar-api/pom.xml, legend-engine-language-pure-store-relational-grammar-api/src/test/java/org.finos.legend.engine.language.pure.grammar.api.relationalOperationElement.test/TestRelationalOperationElementApi.java, legend-engine-query-graphQL/src/test/java/org/finos/legend/engine/query/graphQL/api/grammar/test/TestGrammarApi.java, legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/api/grammar/GrammarAPI.java, legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/operational/errorManagement/ExceptionTool.java, legend-engine-shared-core/src/test/java/org/finos/legend/engine/shared/core/api/TestGrammar.java
This applies to non-batch `grammarToJson` endpoints:
- `/grammarToJson/model`
- `/grammarToJson/valueSpecification`
- `/grammarToJson/lambda`
- `/grammarToJson/graphFetch`
- `/grammarToJson/relationalOperationElement`
When there's a parsing error, these endpoint return `200` with the return body as the error. We should throw this error instead and I opt for using error code `400: Bad Request`
=> throw error when non-batch `grammarToJson` endpoints fail

.github/workflows/database-databricks-integration-test.yml
Signed-off-by: aamend <antoine.amend@gmail.com>
There are multiple strategies to ensure availability of compute on databricks for integration tests
- keep small single node cluster alive 24x7
- terraform / provision cluster on demand
- create instance pool and idle interactive clusters that get kicked in upon tests
- start / stop clusters via simple REST call
Although we may evaluate the Terraform route when provisioning data + tables + clusters and test the entire stack E2E (including SQL output), it may be overkill just to test JDBC connection. We recommend HTTP route for now (abstracted via the python `databricks-cli` module). This PR for option 4 (calls databricks API through github action)
cc: @epsstan
=> Starting databricks cluster prior to test

legend-engine-language-pure-dsl-service/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ServiceLexerGrammar.g4, legend-engine-language-pure-dsl-service/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ServiceParserGrammar.g4, legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/from/ServiceParseTreeWalker.java, legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceCompilationFromGrammar.java
This will enable users add tests for services that have parameters with multiplicity [*]
=> Support list parameters for service tests

.github/workflows/database-databricks-integration-test.yml
This PR removes the cluster start/stop workflow steps.
When multiple PRs are pushed to master, each PR triggers a workflow which executes cluster start/stop.
The cluster start/stop actions are not idempotent and throw errors (e.g when the action tries to start the cluster but the cluster is already running).
For now, we are switching the cluster to a long running cluster and removing the start/stop.
We will switch to using serverless Databricks when it becomes available.
@aamend
=> Update Databricks integration test to use a long running cluster

legend-engine-language-external-store-service/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperServiceStoreClassMappingBuilder.java, legend-engine-language-external-store-service/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceStoreMappingCompilationFromGrammar.java
Currently we are not correctly updating generated embedded set implementations for multi-level nesting while compiling service store mapping. 
Changes in this PR fix this flow
=> Fix service store mapping builder

legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
Currently, only one method is public, typeOne.  Changing the other methods will allow extensions to take advantage the same way they use typeOne, and avoid dupliacation.
=> Change method visibility to allow extensions to access these utilities

legend-engine-pure-ide-light/README.md, legend-engine-pure-ide-light/src/main/java/org/finos/legend/engine/ide/PureIDELight.java
Make location of legend-pure repository configurable in Pure IDE Light when building repositories
=> IDE Light: Make Legend-Pure core files location configurable

.github/workflows/build.yml, .github/workflows/test-result.yml, README.md, pom.xml
publish CI test results so we can see failure as annotations and debug quicker
plugin doc: https://github.com/marketplace/actions/publish-unit-test-results
example: https://github.com/gomichutsk-stormborn/java-sample
=> publish test results

.github/workflows/test-result.yml, legend-engine-external-shared-format-model/src/main/java/org/finos/legend/engine/language/pure/grammar/from/ExternalFormatConnectionParseTreeWalker.java, legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/CorePureGrammarParser.java, legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/ParseTreeWalkerSourceInformation.java, legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/PureGrammarParser.java, legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/data/embedded/HelperEmbeddedDataGrammarParser.java, legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/test/assertion/HelperTestAssertionGrammarParser.java, legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestGrammarRoundtrip.java, legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/RelationalDatabaseConnectionParseTreeWalker.java, legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/RelationalGrammarParserExtension.java, legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/RelationalParseTreeWalker.java, legend-engine-xt-serviceStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/data/contentPattern/HelperContentPatternGrammarParser.java
Before, if we want to call `/grammarToJson/model` with `returnSourceInformation=false`, we would get an `NullPointerException`.
We also enforce that model grammar roundtrip are to be run with `returnSourceInformation=false`, since there's no need for the source information as well as we could use that method to test for the case when `returnSourceInformation=false`
=> fix NPE exceptions when grammar parser works with external format and relational DB connections

legend-engine-executionPlan-dependencies/pom.xml, legend-engine-executionPlan-execution-api/pom.xml, legend-engine-executionPlan-execution-store-inMemory/pom.xml, legend-engine-executionPlan-execution/pom.xml, legend-engine-extensions-collection-execution/pom.xml, legend-engine-extensions-collection-generation/pom.xml, legend-engine-external-shared-format-runtime/pom.xml, legend-engine-xt-flatdata-runtime/pom.xml, legend-engine-xt-xml-runtime/pom.xml, pom.xml
This prevents logback and dropwizard as a dependency on the generation and execution modules that gitlab projects will depend on.  This also slightly improve how enforcer required java version is defined to ensure all definitions are using the same value.
=> Stricter enforce rule on execution and generation collection modules

legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/object/StreamingObjectResultJSONSerializer.java
If the result has no activities associated with it, the exiting code will throw index out of bound since we always try to serialize at least one activity.  This change, reuse the object serialization to ensure we stream objects consistently, and support empty collections.
=> Avoid index out of bound exception if result has no activities

legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperValueSpecificationGrammarComposer.java, legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestDomainGrammarRoundtrip.java, legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestLambdaRoundtrip.java
- Fix JSON to grammar transformation when the first parameter to a function is an instance of Applied Function. 
- Ensured correct grammar generation when using eq (equals) applied function by avoiding the -> syntax.
=> Fix JSON to Grammar transformation when Applied functions are passed as parameters.

legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/CorePureProtocolExtension.java, legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/assertion/status/AssertionStatus.java, legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/result/TestResult.java, legend-engine-server/pom.xml, legend-engine-server/src/main/java/org/finos/legend/engine/server/Server.java, legend-engine-testable/pom.xml, legend-engine-testable/src/main/java/org/finos/legend/engine/testable/TestableRunner.java, legend-engine-testable/src/main/java/org/finos/legend/engine/testable/api/Testable.java, legend-engine-testable/src/main/java/org/finos/legend/engine/testable/model/RunTestsInput.java, legend-engine-testable/src/main/java/org/finos/legend/engine/testable/model/RunTestsResult.java, legend-engine-testable/src/main/java/org/finos/legend/engine/testable/model/RunTestsTestableInput.java
- rename `doTest` to `runTest`
- wire up subType Jackson decorators for test assertion and test results
- handle zipkin input for testable inputs
=> minor testable api fixes

legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/grammar/from/PersistenceParseTreeWalker.java, legend-engine-xt-persistence-grammar/src/test/java/org/finos/legend/engine/language/pure/dsl/persistence/grammar/test/TestPersistenceGrammarParser.java, legend-engine-xt-persistence-grammar/src/test/java/org/finos/legend/engine/language/pure/dsl/persistence/grammar/test/TestPersistenceGrammarRoundtrip.java
Users who select ingestMode = AppendOnly are not able to set filterDuplicates equal to true.
=> Fix handling of filter duplicates attribute in persistence DSL.

legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/authentication/AuthenticationStrategy.java
This logic its flawed on few places, and some users have seen exceptions out of it when running service execution jars.
For example, the logic assume the iterator will yield a next value always.  it also checks for null out of the iterator in some places, but still assume the object its not null on others.
=> Remove debugger logic that lead to NPE

legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/models/executionPlan.pure
This PR contains the following changes
- Adds property `isChildrenExecutionParallelizable` to protocol class of ExecutionNode which would be used for triggering parallel execution
- Add protocol classes needed for union and merge execution refactor
=> Add union/merge nodes in protocol and add parallel execution property

legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocol/vX_X_X/models/executionPlan.pure
Prepare for external format refactor. These models will be needed in a protocol version for the refactoring.
=> Add protocol models for externalize & internalize nodes

legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/TestServiceRunner.java, legend-engine-language-pure-dsl-service-execution/src/test/resources/org/finos/legend/engine/pure/dsl/service/execution/test/simpleRelationalService.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbExtension.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/query/datePeriods.pure
Fixed the FreeMarker syntax in SQL generation as part of execution plan for property With Path to generate a valid SQL.
=> Fix FreeMarker in SQL generation as part of execution plan for property With Path.

legend-engine-language-pure-compiler-api/pom.xml, legend-engine-language-pure-compiler-api/src/main/java/org/finos/legend/engine/language/pure/compiler/api/Compile.java, legend-engine-language-pure-compiler-api/src/test/java/org/finos/legend/engine/language/pure/compiler/api/test/TestCompileApi.java, legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/operational/errorManagement/ExceptionError.java
If EngineException cause is a PureExcetpion, jackson fails to serialize the response given self reference on some of the get methods.
=> Standardize compile error handling to avoid infinite loop when serializing

legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/TestServiceRunner.java, legend-engine-language-pure-dsl-service-execution/src/test/resources/org/finos/legend/engine/pure/dsl/service/execution/test/simpleRelationalService.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan_execution.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/functions/tests/testIsEmpty1.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/postprocessor/defaultPostProcessor/processInOperation.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/relationalMappingExecution.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbExtension.pure, legend-engine-xt-relationalStore-sqlserver-pure/src/main/resources/core_relational_sqlserver/relational/tests/dbSpecificTests/customSqlServerTests.pure
Ensure collection parameter and optional parameters with TimeZone are handled correctly on the execution plan when null/not provided by user WITH User Tests.
Feature enhancement.
- These changes provide additional support for optionality for collection parameters on an execution plan. This gives users flexibility to not provide any value for the optional parameter during plan execution.
- Provided support on the execution plan for Optional Datetime Parameter with TimeZone present, when null or not provided by the end user.
- Fixes the issue of plan execution failure in case the service has an optional collection parameter of multiplicity [*] and user does not provide any parameter to the service.
- Fixes the issue of plan execution failure in case the service has datetime parameter with a …
=> Ensure collection parameter and optional parameters with TimeZone are handled when null.

legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/collectionsLibrary.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/functionInMapping.pure
Enhancement
This PR adds Java generation for _defualtIfEmpty_ function making it usable in M2M mappings. With _defaultIfEmpty_ function, users can avoid _isEmpty_ _if_ checks, thereby making the code clean and more readable.
Yes, users can now use _defaultIfEmpty_ function in their Studio projects and services
=> Add support for defaultIfEmpty function in M2M mappings

legend-engine-server/pom.xml, legend-engine-server/src/main/java/org/finos/legend/engine/server/Server.java, pom.xml
Enhancement
This PR enables the engine serve to source its configuration from environment variables.
This is useful in cases where the runtime configuration is dynamic and injected as part of the runtime environment. E.g. instead of hard coding the Gitlab OAuth client id and secret in the server's config file, they can be injected into the runtime (e.g. Docker) as env variables. The server config file can then refer to these environment variables.
Not applicable.
No
=> Enable server to read configuration via environment variables

legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/compiler/toPureGraph/HelperMasterRecordDefinitionBuilder.java, legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/from/MasteryParseTreeWalker.java, legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/to/HelperMasteryGrammarComposer.java, legend-engine-xt-mastery-grammar/src/test/java/org/finos/legend/engine/language/pure/dsl/mastery/compiler/test/TestMasteryCompilationFromGrammar.java
Bug Fix
- Previously Strings in Mastery grammar were being wrapper in extra quotations, this is to fix that.
- An optional service in the grammar (parse service) was throwing a null pointer in the compiler when it was not provided
=> Fix parsing of strings in Mastery grammar

legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java, legend-engine-language-pure-dsl-generation/src/main/java/org/finos/legend/engine/language/pure/dsl/generation/extension/ArtifactGenerationExtension.java, legend-engine-language-pure-dsl-generation/src/main/java/org/finos/legend/engine/language/pure/dsl/generation/extension/ArtifactGenerationExtensionLoader.java, legend-engine-xt-data-space-generation/pom.xml, legend-engine-xt-data-space-generation/src/main/java/org/finos/legend/engine/generation/DataSpaceAnalyticsArtifactGenerationExtension.java, legend-engine-xt-data-space-generation/src/test/java/org/finos/legend/engine/generation/TestDataSpaceAnalyticsArtifactGenerationExtension.java, legend-engine-xt-data-space-generation/src/test/resources/models/DataspaceModel.pure
Enhancement
Related to https://github.com/finos/legend-sdlc/issues/504
=> minor updates to ArtifactGenerationExtension

legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/legendJavaPlatformBinding/bindPlanToLegendJavaPlatform.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/autoMapping.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/chain/dataQualityChain.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/chain/filterChain.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/chain/parametersChain.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/chain/simpleChain.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/constraints.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/dataQuality.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/filterInMapping.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/functionInMapping.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/graphWithAssociations.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/graphWithoutAssociations.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/merge.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/multiStepFunctions.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/multiplicities.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/nilHandling.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/propertyUnion.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/qualifiedProperties.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/simpleObject.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/sourceAssociationRequiredByMapping.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/testExplosion.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/testUnitMeasure.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/toFromSameName.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/userFunctions.pure
Bug Fix
Model-to-model unit tests currently pass empty extensions. Though they work when run via Legend server (with plan generation happening on server), local plan generation fails due to required extensions not being passed.
No
=> Make M2M tests use defaultExtensions

legend-engine-xt-persistence-component/pom.xml, pom.xml
Maven javadoc plugin requires additional configuration to resolve references to classes produced by annotation processors. PR #921 introduced use of Immutables (limited to persistence modules only) which triggered this limitation.
Resolves a bug introduced by work on #920
None.
No.
=> Fix for javadoc that references classes produced by annotation processor (#921)

legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/functions/tests/testModelGroupBy.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tds/tests/testGroupBy.pure
Bug Fix
Current sql generation logic checks whether a query has a group by or not by inspecting the size of group by columns (which evaluates to false in case of empty grouping columns). This can lead to incorrect SQL when further TDS operations like `filter` are applied on top. In the case of `filter`, generated sql contains a `where` clause using an aggregated column (example: `where count(*) > 10`) which is incorrect. This PR fixes this bug by isolating such non-terminal group by queries with empty grouping columns.
No
=> Isolate non-terminal group by with empty columns

legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ClassMappingSecondPassBuilder.java, legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ClassMappingThirdPassBuilder.java, legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PackageableElementFifthPassBuilder.java, legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PureModel.java, legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestMappingCompilationFromGrammar.java, legend-engine-xt-analytics-mapping-pure/src/main/resources/core_analytics_mapping/modelCoverage/analyticsTest.pure
This change fixes compiler validation of ~src  classes in model to model mappings to align with a feature that allows src to be a subtype. of the expected type 
Fixes an issue related to the compilation of unions in model to model mappings
Yes  - the compilation of model to model mappings is changed
=> fix compiler for union subtypes

.github/workflows/build.yml, legend-engine-xt-persistence-component/pom.xml
Bug fix
Update definition of GH workflow action that invokes javadoc.
~~We trigger the APT code generator before running javadoc for offending xt-persistence-component modules.~~
We run a blanket install before generating javadoc.
This is necessary because source code in those modules have forward references to generated code, which trips up the javadoc.
Addresses bug introduced in #920
None
No
=> Fix Maven Deploy workflow action

.github/workflows/build.yml
Bug fix
This PR splits our deployment action into two separate maven commands.
- The first does an install on the project, solely to kick-off APT code generation.
- The second generates javadoc (which would fail without APT code generation) and performs deploy
These commands were previously smushed into a single command, but this triggered a bug in maven-jar-plugin which fails when executing JAR twice in a build for a module with no source files.
None
None
No
=> Split deploy task into two commands to workaround maven-jar-plugin bug.

legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/relationalExtension.pure
This fixes gap in relational type inference for a column. It is a bug fix
This fixes gap in relational type inference for a column.  This is needed because this information is used when a tds join is created on top of such query, In its absence query fails to generate sql
No issue raised, ad-hoc fix
Yes, this will fix join queries written on top of queries similar to one attached below. This will also populate additional info in execution plan, which should not have any negative impact 
```
{|Address.all()->groupBy([x | 'constant'], [agg(x | $x.name, y | $y->count())], ['Constant', 'Constant Count'])}
```
=> Add source data type info for constant columns

legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/milestoning/tests/testBusinessDateMilestoning.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
Bug fix
This PR fixes milestoning filter propagation to isolated subselect queries
No issues raised
Yes, this propagate filters to sub-select queries which were not happening as of now, also this might change sql gen for exists/isEmpty/isNotEmpty processing from join with null check to exists clause
=> Fix milestoning date propagation to sub select query

legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/DatasourceSpecificationBuilder.java, legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalConnectionCompilationRoundtrip.java
Bugfix
Currently, the Snowflake db spec model and grammar allow users to provide a role.  This role was not propagate to pure, ending not been use on the execution plans, and leading to confusion on user on why queries to Snowflake were failing.
This PR fixes this bug, and add test case to validate correct behavior.
Fixes #
Not directly.  Users already can specify role on Snowflake DB spec.   This could yield to different execution behavior if they were indeed specifying this since this was previously ignored.
=> Make sure role on Snowflake DB spec is properly propagated to pure

legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperValueSpecificationGrammarComposer.java, legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestDomainGrammarRoundtrip.java
Bug Fix
Studio automatically re-formats arithmetic operations expressed as a/(b/c) to a/b/c, which creates incorrect result equivalent to a/(b*c).
Change will properly preserve the user preferred precedence for execution.
No
=> Adjust Parentheses for jsonToGrammar

legend-engine-extensions-collection-generation/pom.xml, legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/TestBatch.java, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/test/testable.pure, legend-engine-server/pom.xml, legend-engine-testable/src/main/java/org/finos/legend/engine/testable/TestableRunner.java, legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-physical-plan/pom.xml, legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/pom.xml, legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-core/pom.xml, legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/pom.xml, legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/pom.xml, legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/pom.xml, legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/compiler/toPureGraph/HelperPersistenceBuilder.java, legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/compiler/toPureGraph/PersistenceCompilerExtension.java, legend-engine-xt-persistence-test-runner/pom.xml, legend-engine-xt-persistence-test-runner/src/main/java/org/finos/legend/engine/testable/persistence/extension/PersistenceTestH2Connection.java, legend-engine-xt-persistence-test-runner/src/test/java/org/finos/legend/engine/testable/persistence/ingestmode/TestPersistenceBase.java, legend-engine-xt-persistence-test-runner/src/test/java/org/finos/legend/engine/testable/persistence/ingestmode/appendonly/TestAppendOnlyWithAllowDuplicates.java, legend-engine-xt-persistence-test-runner/src/test/java/org/finos/legend/engine/testable/persistence/ingestmode/appendonly/TestAppendOnlyWithFilterDuplicates.java, legend-engine-xt-persistence-test-runner/src/test/java/org/finos/legend/engine/testable/persistence/ingestmode/delta/bitemporal/TestPersistenceBitemporalDelta.java, legend-engine-xt-persistence-test-runner/src/test/java/org/finos/legend/engine/testable/persistence/ingestmode/delta/unitemporal/TestPersistenceUnitemporalDelta.java, legend-engine-xt-persistence-test-runner/src/test/java/org/finos/legend/engine/testable/persistence/ingestmode/snapshot/nontemporal/TestNonTemporalSnapshot.java, legend-engine-xt-persistence-test-runner/src/test/java/org/finos/legend/engine/testable/persistence/ingestmode/snapshot/unitemporal/TestPersistenceUnitemporalSnapshot.java, pom.xml
Cleanup.
Make persistence component and persistence test runner more consistent with other Legend modules and related cleanup. Specifically:
- Fix multiplicity of TestBatch.batchId in pure model
- Use dependency management for version and scope control
- Fix newlines and line breaks
- Remove vestigial maven properties
None.
Cleanup for https://github.com/finos/legend-engine/pull/963.
No.
=> Tidy up persistence component and persistence test runner.

legend-engine-language-pure-dsl-generation/src/main/java/org/finos/legend/engine/language/pure/dsl/generation/compiler/toPureGraph/GenerationCompilerExtensionImpl.java, legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/compiler/toPureGraph/ServiceCompilerExtensionImpl.java, legend-engine-xt-data-space-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/DataSpaceCompilerExtension.java, legend-engine-xt-diagram-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/DiagramCompilerExtension.java, legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/compiler/toPureGraph/MasteryCompilerExtension.java, legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/compiler/toPureGraph/PersistenceCompilerExtension.java, legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/RelationalCompilerExtension.java, legend-engine-xt-serviceStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ServiceStoreCompilerExtension.java, legend-engine-xt-text-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/TextCompilerExtension.java
Bug fix
This is a fix needed so that function `getUserPathForPackageableElement` could work properly for the elements fixed.
`getUserPathForPackageableElement()` calls `getName()` which actually call `CoreInstance.id` instead of `CoreInstance.name` so when we build the elements, we must set both their name using `._name(...)` and their `id` using the constructor. This results in unfortunately bugs like:
```java
getUserPathForPackageableElement(<some element with path something::Weird>);
// returns "something"
```
This will mess up logic in many places, especially impact the artifact generation mechanism introduced in https://github.com/finos/legend-sdlc/pull/481
Fixes #
No
=> fix ID instantiation of some element to make `getUserPathForPackageableElement()` works properly

.github/workflows/database-bigquery-integration-test.yml, .github/workflows/database-databricks-integration-test.yml, .github/workflows/database-databricks-sql-generation-integration-test.yml, .github/workflows/database-mssqlserver-integration-test.yml, .github/workflows/database-mssqlserver-sql-generation-integration-test.yml, .github/workflows/database-postgresql-integration-test.yml, .github/workflows/database-postgresql-sql-generation-integration-test.yml, .github/workflows/database-redshift-integration-test.yml, .github/workflows/database-redshift-sql-generation-integration-test.yml, .github/workflows/database-snowflake-integration-test.yml, .github/workflows/database-snowflake-sql-generation-integration-test.yml, .github/workflows/release.yml
Github Setup
It allows us to support 2 groups of permissions on github, ones who can do releases, and ones who can run integration tests. We need to give more people write access to legend repo to run integration tests. But, without this separation, they can do releases too.
None
No, only developers who run github workflows might be affected
=> Use separate github env for release and allow manual running of integration tests

.gcp/cloud-build/cloudbuild.yaml, .github/workflows/trigger-gcp-build.yml
This change improves the GCP build trigger.
The GitHub action that triggers a GCP build will now stream the build's logs. This has the desired side effect that now the GitHub action will last as long as the GCP build and give an indicator on whether the GCP build succeeded or failed.
=> Streaming GCP build logs

legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphExtension.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/tests/testSourceTreeCalc.pure
This PR introduces some changes in property tree generation and also add some tests.
This PR fixes following bug -
when passing subtype to mapping functions and accessing suppertype properties inside that function then property tree was not generated correctly. 
NA
Yes
=> fixed subtype problem and added tests

legend-engine-extensions-collection-generation/pom.xml, legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/dbTestRunner/shared.pure
Fix
Pure gives warning currently, when engine is enabled, but no test connection for dbType exists. This causes the integration test to pass silently, even without actually executing against test db instance. Make that warning into an error, so that test stops in such cases and fails.
None
No. It is backward compatible. Tc is green.
=> throw error instead of warning from pure when engine is enabled but test conn not found

pom.xml
Increase nexus plugin staging timeout from the default 5 minutes to 10 minutes.
Improvement
This PR increases the timeout on the Nexus staging plugin. The 'release' action seems to be failing on the nexus timeout errors.
See https://pipelines.actions.githubusercontent.com/serviceHosts/519cc083-62da-4ea5-a01d-dfb72b89ad92/_apis/pipelines/1/runs/10770/signedlogcontent/2?urlExpires=2022-10-03T21%3A25%3A30.3480938Z&urlSigningMethod=HMACV1&urlSignature=FCamCU0kMLXMjub5TihwazhLBZO8lUL5WKNSvE84l9s%3D 
See https://help.sonatype.com/repomanager2/staging-releases/configuring-your-project-for-deployment 
No
=> Increase nexus plugin staging timeout

.gcp/cloud-build/build.sh, .gcp/cloud-build/cloudbuild.yaml
This changes the configuration for the GCP build job - now attempting to use a private cloud-build pool 
Building in GCP with a private pool allows us greater control over the type of machines that can execute our builds.
=> Updating GCP build config

.gcp/cloud-build/build.sh, .github/workflows/trigger-gcp-build.yml
This PR changes the GCP trigger action to specify the region the build is executed in.
When using a private pool for GCP builds, the builds are locked to the region the pool is created in - this requires us to pass a --region flag when invoking gcloud commands
=> Specifying GCP region

legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRuntimeBuilder.java
Bug Fix
On processing of legacy runtimes, the second pass visitor needs to be executed to accommodate extra processing of new connection parameters
Fixes #
No
=> properly process connections for LegacyRuntime

legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/ExecutionNodeExecutor.java, legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/state/ExecutionState.java, legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/AllocationExecutionNode.java, legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/ExecutionNode.java, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/models/executionPlan.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/transfers/executionPlan.pure, legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/RelationalExecutor.java, legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/RelationalExecutionNodeExecutor.java, legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/RealizedRelationalResult.java, legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/AlloyTestServer.java, legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/full/tdsJoin/TestTDSJoinRealizedResults.java, legend-engine-xt-relationalStore-executionPlan/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/full/tdsJoin/TestTDSJoin.json, legend-engine-xt-relationalStore-executionPlan/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/full/tdsJoin/TestTDSJoinExpectedFail.json
Bug Fix/ Feature Improvement
Modifies the way plan is generated by separating authDependency on the plan and transformAllocation, which helps resolve logical fallacy occurring with setting TA inside execution nodes, that later is used to determine if plan is realized in Memory.
PR responds to a keystone raised by user where plan fails to execute because it is unexpectedly realizing in Memory for their TDS Join operation.
=> Apply fix for false realizeInMemory calls during plan execution (edited)

pom.xml
dependencies
Upgrades legend-pure version to 3.7.0. This introduces an improvement in the compiler to reduce unnecessary re-processing during type inference. In some cases, such as chained filter expressions, this can speed up compilation by many orders of magnitude.
Functionally, no, but this introduces an improvement to the Pure compiler, which may improve Pure compilation time for some users. In some cases, the improvement may be substantial and quite noticeable.
=> Upgrade legend-pure version to 3.7.0

legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/RelationalParseTreeWalker.java, legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalCompilationFromGrammar.java, legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalMappingGrammarRoundtrip.java
Bug Fix
This fixes a compiler issue that led to an incorrect database name in the returned grammar after round trip
Yes , it will change grammar printing of join chains to be more specific in  certain scenarios
=> fix issue with printing of database  names in join chains

README.md, legend-engine-pure-ide-light/src/main/resources/ideLightConfig.json, legend-engine-server-integration-tests/config/config.json, legend-engine-server/config/config.json, legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig.json, legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withFlowProvider.json, legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withMetadataFromIDELight.json, legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withVault.json, legend-engine-xt-relationalStore-sqlserver-execution-tests/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withSqlServerTestConnection.json, legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withDatabricksTestConnection.json, legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withH2TestConnection.json, legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withPostgresTestConnection.json, legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withRedshiftTestConnection.json, legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withSnowflakeTestConnection.json, pom.xml
Also updated doc at https://github.com/finos/legend/pull/542
=> standardize engine port to `60xx` range

README.md, legend-engine-server-integration-tests/config/config.json, legend-engine-server/config/config.json, legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig.json, legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withFlowProvider.json, legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withMetadataFromIDELight.json, legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withVault.json, legend-engine-xt-relationalStore-sqlserver-execution-tests/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withSqlServerTestConnection.json, legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withDatabricksTestConnection.json, legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withH2TestConnection.json, legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withPostgresTestConnection.json, legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withRedshiftTestConnection.json, legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withSnowflakeTestConnection.json
standardize Engine port to `6300` since port `6000` was a reserved port for `X Window System` - https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=6000
=> standardize Engine port to 6300

README.md, legend-engine-pure-ide-light/src/main/resources/ideLightConfig.json, legend-engine-server-integration-tests/config/config.json, legend-engine-server/config/config.json, legend-engine-server/src/main/java/org/finos/legend/engine/server/Server.java, legend-engine-server/src/main/java/org/finos/legend/engine/server/ServerConfiguration.java, legend-engine-server/src/main/resources/docker/config/config.json, legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig.json, legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withFlowProvider.json, legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withMetadataFromIDELight.json, legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withVault.json, legend-engine-xt-relationalStore-sqlserver-execution-tests/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withSqlServerTestConnection.json, legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withDatabricksTestConnection.json, legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withH2TestConnection.json, legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withPostgresTestConnection.json, legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withRedshiftTestConnection.json, legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withSnowflakeTestConnection.json
Allow specifying session cookie name to help with local development (when we have multiple Legend applications)
see https://stackoverflow.com/questions/16789495/two-applications-on-the-same-server-use-the-same-jsessionid
=> allow specifying session cookie name

.github/workflows/build.yml, pom.xml
@kevin-m-knight-gs pointed out that because we set `maven.test.failure.ignore=true` in PR CI, `maven-surefire-plugin` ends up not reporting failure at all, causing `test reporter` to be unaware of failure - which is bad 🤯 
We found the evidences from these 2 pipelines
https://github.com/finos/legend-engine/pull/1019/checks?check_run_id=8735398516
https://github.com/finos/legend-engine/pull/1020/checks?check_run_id=8735893546
The first is a good commit
The second is a bad commit, not getting caught in the PR CI
I'm doing it to see if the error bubbles up properly. Also I want to see if this change affects the `test reporter` anyhow, in which case, we would probably want to remove the test reporter altogether because it's just not suitable for our use case it would seem.
=> unignore test failure in PR builds

legend-engine-test-server-shared/src/main/java/org/finos/legend/engine/server/test/shared/TestServerConfiguration.java, legend-engine-xt-relationalStore-sqlserver-execution-tests/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withSqlServerTestConnection.json, legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withDatabricksTestConnection.json, legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withH2TestConnection.json, legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withPostgresTestConnection.json, legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withRedshiftTestConnection.json, legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withSnowflakeTestConnection.json
Enhancement
This PR instructs the test server to ignore unknown properties in the server's JSON configuration.
PR #1020 introduced a new configuration property which is not recognized or needed by the test server. 
Fixes #
No
=> Update test server config to ignore unknown properties

legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan_generation.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphFetchExecutionPlan.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/XStore.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/mappingExtension.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/modelToModel.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/router_execution.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/router_main.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/chain.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/inMemory.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/storeContract.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/platform/executionPlan/executionPlan_generation.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/platform/storeContract.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/transform/fromPure/toSQLString.pure
This cleans-up routing logic
This cleans-up routing logic by removing advancedRouting field
Relates to : https://github.com/finos/legend-engine/issues/703 
No
=> [Router clean up] Remove advanced routing

legend-engine-testable/src/main/java/org/finos/legend/engine/testable/assertion/TestAssertionHelper.java, legend-engine-testable/src/main/test/java/org/finos/legend/engine/testable/assertion/TestTestAssertionEvaluator.java, legend-engine-xt-persistence-test-runner/src/main/java/org/finos/legend/engine/testable/persistence/assertion/PersistenceTestAssertionEvaluator.java
Bug
Current JSON assertion code uses float type for decimal values which can lead to incorrect results due to rounding off and loss in precision.
=> Deserialize float value as BigDecimal in JSON assertion

pom.xml
Dependency change
This is to avoid using dependency wit new discovered [vulnerability](https://www.cve.org/CVERecord?id=CVE-2022-42889).
N/A
N/A
N/A
=> Bump apache commons text from 1.8 to 1.10.0

legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/IRelationalCompilerExtension.java, legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/RelationalCompilerExtension.java
Feature Enhancement
- This change gives us access to connection information in the postprocessor during compile time
- This is useful when we want to do postprocessing based on the type of database
Fixes #
No
=> enhance relational compiler extension - Allow connection to flow to postprocessor

legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/lineage/scanRelations/scanRelations.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/lineage/scanRelations/scanRelationsTestWithViewsAndUnions.pure
Bug Fix
Fixes the way we scan properties in unions that use views and chained joins
Fixes #
Yes, enables calculation of lineage tree
=> Fix Relational Tree Scanning for Union with Views

legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/helpers/ExecuteNodeParameterTransformationHelper.java, legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/compiler/toPureGraph/HelperServiceBuilder.java, legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/from/ServiceParseTreeWalker.java, legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/to/HelperServiceGrammarComposer.java, legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/service/ServiceTest.java, legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/domain/ParameterValue.java, legend-engine-query-pure/pom.xml, legend-engine-query-pure/src/main/java/org/finos/legend/engine/query/pure/api/Execute.java, legend-engine-query-pure/src/test/java/org/finos/legend/engine/query/pure/api/test/inMemory/TestExecutionUtility.java, legend-engine-query-pure/src/test/java/org/finos/legend/engine/query/pure/api/test/inMemory/TestM2MGrammarCompileAndExecute.java, legend-engine-query-pure/src/test/java/org/finos/legend/engine/query/pure/api/test/inMemory/TestQueryExecutionWithParameters.java, legend-engine-query-pure/src/test/resources/relationalQueryExecutionInputEnumZeroOne.json, legend-engine-query-pure/src/test/resources/relationalQueryExecutionInputZeroMany.json, legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/api/model/ExecuteInput.java, legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/testable/service/extension/ServiceTestRunner.java, legend-engine-testable/src/main/java/org/finos/legend/engine/testable/helper/PrimitiveValueSpecificationToObjectVisitor.java
Feature Request
In Studio, We want to remove the usage of let statements when executing queries with parameters.
The use of let statements makes it difficult for engine to do type matching causing bugs when executing queries with parameters.
As a result we should move over and use engine to execute the queries with parameters.
Fixes https://github.com/finos/legend-engine/issues/1018
Links to https://github.com/finos/legend-studio/issues/1535
=> Add parameter values option to execute api

pom.xml
Upgrade legend-pure to 3.7.1. This version contains a fix for a bug in compiled mode in Pure where invalid Java code was being generated for valid Pure code (see [this commit](https://github.com/finos/legend-pure/commit/78647d64411c4bf25f3a6f245f3a7b3204484acc)).
The fix mentioned above can potentially affect some user Pure code.
=> Upgrade legend-pure version to 3.7.1

legend-engine-pure-code-compiled-core/src/main/resources/core/external/language/java/generation/conventions.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/external/language/java/metamodel.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/langLibrary.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/qualifiedProperties.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/shared.pure
Bug Fix
Match functions may return zero, one, or many values. This worked without error in PURE, but in Alloy users encounter issues with generated java because for different return multiplicities and for returning an empty list [ ] 
Changes are to generate valid java code when encountered a null.
=> M2M - Match Return Multiplicity & Null

legend-engine-xt-serviceStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/service/showcase/jsonApis/ServiceStoreJsonShowcaseTest.java, legend-engine-xt-serviceStore-executionPlan/src/test/resources/showcase/json/testGrammar.pure, legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/executionPlan/executionPlan_generation.pure
BugFix
If a property is being referenced multiple times in a parameter resolution logic of service store mapping, current platform logic has a bug that causes issues resolving correct service mapping for the query.
This PR fixes this bug
Fixes # https://github.com/finos/legend-engine/issues/1099
=> Fix service store mapping processing bug

legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/dbTestRunner/shared.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/helperFunctions/helperFunctions.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/helperFunctions/toDDL.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/defaultExtension.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/suite/sqlQueryTests/aggregateFunctions/groupBy.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/suite/sqlQueryTests/dynaFunctions/date.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/suite/sqlQueryTests/shared.pure, legend-engine-xt-relationalStore-test-server/src/main/java/org/finos/legend/engine/server/test/shared/ExecuteInRelationalDb.java
BugFix
Generic ddl functions were defaulting to H2 impl, instead of relaying to appropriate db extension
No. It should not affect existing h2 tests, but allow running setup based tests for other dbs, which expect different ddl sql than H2
=> relay to appropriate extension instead of h2 for ddl commands

legend-engine-xt-serviceStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/service/showcase/jsonApis/ServiceStoreJsonShowcaseTest.java, legend-engine-xt-serviceStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/service/utils/ServiceStoreTestUtils.java, legend-engine-xt-serviceStore-executionPlan/src/test/resources/showcase/json/testGrammar.pure, legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/executionPlan/javaRuntime/executionPlanNodes/serviceParametersResolution/serviceParametersResolution.pure
Enhancement
Currently, users are not able to use user-defined functions inside their parameter-building logic in service store mapping. This PR adds support to this feature
Fixes # https://github.com/finos/legend-engine/issues/1108
Yes, users will be able to use user-defined functions in service store mapping
=> Support user defined functions in service store parameter gen logic

legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/ServiceExecutor.java, legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/plugin/ServiceExecutionNodeExecutor.java, legend-engine-xt-serviceStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/service/showcase/jsonApis/ServiceStoreJsonShowcaseTest.java, legend-engine-xt-serviceStore-executionPlan/src/test/resources/showcase/json/mappings/stub.json, legend-engine-xt-serviceStore-executionPlan/src/test/resources/showcase/json/testGrammar.pure, legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/executionPlan/executionPlan_generation.pure
Bug Fix
In the current state, users can bypass parameter building in service store mapping and are able to directly add query/header params in the processed URL by adding lambda params with the same name.
Adding lambda parameters with the same name ensures that we have Result in executionState against that parameter and the current logic has a flaw that makes this sufficient to process query params.
This PR blocks such behavior.
Fixes # https://github.com/finos/legend-engine/issues/1106 
Yes, It blocks wrong usages of service store
=> Disable non-mapped service parameters to be populated while processing the url

legend-engine-server/Dockerfile
It seems that `openjdk` no longer publish docker images for jdk11 - https://github.com/docker-library/openjdk/issues/505
So per their recommendation, we are trying out the alternative - `eclipse-temurin`
=> update java Docker image to `eclipse-temurin:11.0.17_8-jdk-jammy`

README.md, legend-engine-pure-ide-light/src/main/resources/ideLightConfig.json
bug fix
update Pure IDE port to 9200 to avoid port conflicts with printer port 9100
https://www.speedguide.net/port.php?port=9100
Fixes #
No
=> update Pure IDE port to 9200 to avoid port conflicts

legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/milestoning/milestoning.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/milestoning/tests/testBusinessDateMilestoning.pure
Bug fix 
Current SQL generation logic has a bug that impacts allVersions use-cases querying from milestoned tables. Our logic to build milestoning filters is flawed which causes issues and milestoned filters to end up in the query.
This PR fixes this bug
No issue was raised
Yes, it fixes SQL generated for impacted use-case
=> Fix sql generation for AllVersions query

.github/workflows/build-large-runner.yml
Adding a test action that uses large GitHub runners
This new action will allow us to easily test the availability of the large runners without having to perform a release.
=> Adding build action with the large runner

.github/workflows/release-large-runner.yml
This PR corrects the way that additional maven parameters need to be set when calling release:perform
This change should correctly pass the argLine parameter when calling release:perform
=> Setting arguments for release:perform

legend-engine-pure-code-compiled-core/src/test/java/org/finos/legend/engine/pure/code/core/Test_Pure_Core.java, legend-engine-xt-relationalStore-executionPlan-connection/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/DbSpecificTests.java, legend-engine-xt-relationalStore-pure/src/test/java/org/finos/legend/pure/code/core/relational/Test_Pure_Relational.java, pom.xml
Improvement
This PR is aimed at significantly reducing the build job log size making it readable and easy to monitor (old build log size: 17.6MB, new build log size: 2.5MB)
Fixes https://github.com/finos/legend-engine/issues/1146
No
=> Make workflow logs readable

legend-engine-xt-mastery-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/MasteryLexerGrammar.g4, legend-engine-xt-mastery-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/MasteryParserGrammar.g4, legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/from/MasteryParseTreeWalker.java, legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/to/HelperMasteryGrammarComposer.java, legend-engine-xt-mastery-grammar/src/test/java/org/finos/legend/engine/language/pure/dsl/mastery/compiler/test/TestMasteryCompilationFromGrammar.java
Merging changes to use identifiers for RecordSources and RecordPartitions.
Ensures IDs for RecordSources and RecordPartitions are identifiers.
Also requires an Alloy test fix, after teh Studio release Alloy will break until this PR is merged.
https://gitlab.aws.site.gs.com/data-engineering/data-architecture-qubits/Alloy/-/merge_requests/501 
Yes in Studio.
https://github.com/finos/legend-studio/pull/1607
=> Refactor IDs to use identifiers 2 (Revert 1091) 

.github/workflows/ossrh-close-staging-repo.yml
This is a new action to attempt to manually close an OSSRH staging repo in case the release action fails on that step.
We've observed issues with the Sonatype server that cause the uploaded artifacts to not get released. This new action attempts to re-try the artifact release step.
=> Adding a manual action to close an OSSRH staging repo

legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/helpers/ExecutionNodeSerializerHelper.java, legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/json/JsonStreamingResult.java, legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/serialization/ExecutionResultObjectMapperFactory.java, legend-engine-executionPlan-execution/src/test/java/org/finos/legend/engine/plan/execution/result/test/json/TestJsonStreamingResult.java, legend-engine-protocol-pure/pom.xml, legend-engine-protocol-pure/src/test/java/org/finos/legend/engine/protocol/test/TestCompatibilityAndMigration.java, legend-engine-testable/src/test/java/org/finos/legend/engine/testable/assertion/TestTestAssertionEvaluator.java, legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/RelationalResult.java, legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/execution/TestExecutionPlan.java, legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/full/graphFetch/dataTypes/TestRelationalGraphFetchExecutionDataTypes.java, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/javaRuntime/executionPlanNodes/graphFetch/graphFetchRelational.pure
Enhancement 
Enhance the service Result classes, providing the result output on a Java json object (jackson JsonNode), allowing for more simpler and efficient consumption of result when results are meant to be consume by a Java process.
Before, all results were required to be written to output stream, not a format that is easy to consume efficiently on a Java process.
Fixes #
=> Ability to consume java Json representation of results

.github/workflows/ossrh-close-staging-repo.yml
This updates the OSSRH action to close and release the Nexus staging repo
The maven release plugin often fails to close the staging repository in Nexus after uploading the artifacts. This new action will allow us to manually retry closing and releasing the staging repository. This means we don't need to trigger a full new release in case of that failure.
=> Close and release staging repo action

legend-engine-language-pure-dsl-service/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ServiceLexerGrammar.g4, legend-engine-language-pure-dsl-service/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ServiceParserGrammar.g4, legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/compiler/toPureGraph/ServiceCompilerExtensionImpl.java, legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/from/ServiceParseTreeWalker.java, legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/to/HelperServiceGrammarComposer.java, legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/service/ServiceTest.java, legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceGrammarParser.java, legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceGrammarRoundtrip.java, legend-engine-pure-code-compiled-core/src/main/resources/core/legend/service/metamodel.pure, legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/testable/service/extension/ServiceTestRunner.java, legend-engine-test-runner-service/src/test/java/org/finos/legend/engine/testable/service/TestServiceTestSuite.java, legend-engine-test-runner-service/src/test/resources/testable/service/serviceGrammarForFailedTestModel.pure, legend-engine-test-runner-service/src/test/resources/testable/service/serviceGrammarModel.pure, legend-engine-test-runner-service/src/test/resources/testable/service/serviceGrammarWithFailedServiceTestKeys.pure, legend-engine-test-runner-service/src/test/resources/testable/service/serviceGrammarWithServiceTestKeys2.pure, legend-engine-test-runner-service/src/test/resources/testable/service/serviceGrammarWithTestKeys1.pure
Feature Development
Adding a new component to Service Grammar, specifically inside Service Test Block for MultiExecution
Fixes # Issues where User faces inability to run tests for incomplete environments when wishing to test some environments only
Yes, user will be able to select env keys for each test in multiexec services
=> Creating Keys for MultiExec Test Blocks 11-17-22

.github/workflows/build.yml, .github/workflows/release-large-runner.yml, .github/workflows/release.yml
This PR moves the flags for setting a maven build to use 4 threads.
This change is necessary to allow the process that's forked by the release:perform command to execute a maven build with multiple threads.
=> Update large runner release flags

legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/planner/BitemporalDeltaPlanner.java, legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/bitemporal/BitemporalDeltaWithBatchIdTest.java
Bug fix
Bitemporal Delta Milestoning uses some constant aliases for columns/tables in the SQLs generated. The aliases used have been too generic, such as "start_date" which may conflict with actual user columns. This PR prefixes such internally used aliases with "legend_presistence_" (for example, the column alias "start_date" will now become "legend_persistence_start_date") so as to prevent such collisions.
Fixes #
No
=> Persistence: Bitemporal Milestoning Prefixing Table/Column Aliases

legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/GraphQL.java, legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/debug/GraphQLDebug.java, legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/execute/GraphQLExecute.java
new feature
Currently, GraphQL API endpoints only allow specifying the SDLC project coordinate to fetch model data, we would like to allow specifying pure model context data as input for more flexibility
This will work when https://github.com/finos/legend-depot/pull/139 is merged
=> make GraphQL API endpoints support fetching models from depot/metadata server

legend-engine-xt-relationalStore-grammar/pom.xml, legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalBuilder.java, legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalCompilationFromGrammar.java, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/relationalMappingExecution.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/testRelationalExtension.pure
What type of PR is this?
New feature
What does this PR do / why is it needed ?
It adds compilation check for incompatible type is mapping
Which issue(s) this PR fixes:
Fixes #
Other notes for reviewers:
Does this PR introduce a user-facing change?
yes
=> Throw warnings for incompatible types in relational property mappings

legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/Milestoning.java, legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PackageableElementSecondPassBuilder.java, legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDomainCompilationFromGrammar.java
Ensure that generated milestoning simple Date properties are not overriden by users. In addition, provides warnings to users in this scenario.
The generated properties have associated stereotypes which impact relational processing, when the properties are overriden it changes the relational milestoning functionality.
Fixes #
Yes, users will now see Warnings when they use property names which conflict with the milestoning ones i.e. processingDate and businessDate
=> prevent overriding of generated milestoning date properties

legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/bindPlanToLegendJavaPlatform.pure, legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/graphFetchCommon.pure, legend-engine-xt-relationalStore-javaPlatformBinding-pure/src/main/resources/core_relational_java_platform_binding/legendJavaPlatformBinding/executionPlanTest.pure
Bugfix
Fixes bug on handle java binding of execution plans where the graph fetch node is inside a sequence node.
N/A
No
=> Support nested sequence node on java binding

legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/debug/GraphQLDebug.java, legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/execute/GraphQLExecute.java, legend-engine-xt-graphQL-query/src/test/java/org/finos/legend/engine/query/graphQL/api/test/TestGraphQLAPI.java
Deprecated code removal
Removing deprecated GraphQL APIs which do not take extensions as inputs
No
=> Remove deprecated GraphQL API constructors

legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/qualifiedProperties.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/shared.pure, legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/booleanLibrary.pure
Support usage of == condition for property mappings in Model to Model Mappings
Extend the support for Model to Model Mappings with properties that are mapped on == condition which possibly hold null value
No
=> M2M - Update equals on property returning null

legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/fromPure/sdl/fromPure_sdl.pure, legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/deprecated/tests/generationTests.pure, legend-engine-xt-graphQL-query/src/test/java/org/finos/legend/engine/query/graphQL/api/test/TestGraphQLFileGeneration.java, legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/schema.graphql
Issue Fix
Fixes the empty hanging schema present in generated GraphQL schemas. It's needed as current schema generated is considered invalid by one or more graphql engines.
Fixes #
Yes
=> GraphQL - Fix empty schema

legend-engine-service-post-validation-runner/src/main/java/org/finos/legend/engine/service/post/validation/runner/ServicePostValidationRunner.java
- Improvement
Updates the exception thrown when an assertion ID isn't found to be more user friendly, e.g.:
`Assertion nonExistentAssertion not found, expected one of [noFirstNamesWithLetterT, rowCountGreaterThan10]`
Yes - user experience change in exception
=> Add all valid assertion IDs to assertion not found exception

legend-engine-executionPlan-generation/src/main/java/org/finos/legend/engine/plan/generation/PlanGenerator.java
Improvement
This enhance plan generation when running with the debug flag.
If an exception occurred, the debug information was not displayed anywhere.  This will include the details on the exception to help developers understand the plan generations steps taken before the error.
Fixes #
=> Include debug details when plan generation fails

legend-engine-language-pure-modelManager-sdlc/src/main/java/org/finos/legend/engine/language/pure/modelManager/sdlc/SDLCLoader.java, legend-engine-language-pure-modelManager-sdlc/src/main/java/org/finos/legend/engine/language/pure/modelManager/sdlc/api/MetadataServerInfo.java, legend-engine-language-pure-modelManager-sdlc/src/main/java/org/finos/legend/engine/language/pure/modelManager/sdlc/configuration/PureServerConnectionConfiguration.java, legend-engine-language-pure-modelManager-sdlc/src/main/java/org/finos/legend/engine/language/pure/modelManager/sdlc/pure/PureServerLoader.java, legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/context/PureSDLC.java, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/invocations/execution.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/invocations/testBuildExecutionInput.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/invocations/testbuilExecutionInput.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/models/executionPlan.pure
Improvement
This change gives flexibility to choose a metadata url in Pure Sdlc. We use it to build Pure Metadata URL. We allow a list of allowed hosts to be specified in the server configuration, and we check that the specified override url is one of them.
No
=> Provide Pure metadata url override in Pure SDLC

legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/test/runner/service/ServiceTestRunner.java
ServiceTest_Legacy test can be empty when expecting MultiExecutionTest instance.
Avoid null pointer exception in certain code paths execution.
Null Pointer Exception
N/A
No
=> If tests is null, log and return

legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/memSql/memSqlExtension.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/transform/fromPure/tests/testToSQLString.pure
- Bug Fix
`firstDayOfQuarter()` function currently returns incorrect values when used on a MemSql runtime.
This PR fixes the dyna function to generate the correct sql
Fixes #
=> Fix firstDayOfQuarter dynafunc for memsql

legend-engine-xt-java-runtime-compiler/src/main/java/org/finos/legend/engine/external/language/java/runtime/compiler/compiled/JavaRuntimeCompilerCompiledExtension.java, legend-engine-xt-java-runtime-compiler/src/main/java/org/finos/legend/engine/external/language/java/runtime/compiler/shared/PureCompileAndExecuteJava.java, legend-engine-xt-java-runtime-compiler/src/main/java/org/finos/legend/engine/external/language/java/runtime/compiler/shared/PureResultBuilder.java, legend-engine-xt-java-runtime-compiler/src/main/resources/core_external_language_java_compiler/compiler.pure, legend-engine-xt-java-runtime-compiler/src/test/java/org/finos/legend/engine/external/language/java/runtime/compiler/AbstractTestCompileAndExecuteJava.java, legend-engine-xt-java-runtime-compiler/src/test/java/org/finos/legend/engine/external/language/java/runtime/compiler/compiled/TestCompileAndExecuteJavaCompiled.java, legend-engine-xt-java-runtime-compiler/src/test/java/org/finos/legend/engine/external/language/java/runtime/compiler/shared/TestCompileAndExecuteJava.java, legend-engine-xt-java-runtime-compiler/src/test/java/org/finos/legend/engine/external/language/java/runtime/compiler/shared/TestPureResultBuilder.java, legend-engine-xt-java-runtime-compiler/src/test/resources/org/finos/legend/engine/external/language/java/runtime/compiler/shared/InvalidJavaClass.java, legend-engine-xt-java-runtime-compiler/src/test/resources/org/finos/legend/engine/external/language/java/runtime/compiler/shared/ValidJavaClass.java
Enhancement
Adds the Java return value to meta::external::language::java::compiler::ExecutionResult, which is returned by compileAndExecuteJava. It is included if and only if the execution completes successfully. Note that executing a void method will result in a return value of Java null.
It adds an optional additional value to the return value of a native function.
=> Add Java return value to compileAndExecuteJava result

legend-engine-external-shared-format-model/src/main/java/org/finos/legend/engine/external/shared/format/model/ExternalFormatExtension.java, legend-engine-external-shared-format-model/src/main/java/org/finos/legend/engine/external/shared/format/model/transformation/fromModel/ExternalFormatSchemaGenerationExtension.java, legend-engine-external-shared-format-model/src/main/java/org/finos/legend/engine/external/shared/format/model/transformation/toModel/ExternalFormatModelGenerationExtension.java, legend-engine-external-shared-format-model/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/SchemaSetCompiler.java, legend-engine-external-shared-format-model/src/test/java/org/finos/legend/engine/external/shared/format/model/transformation/toModel/TestExampleSchemaToModelGeneration.java, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/executionPlan_generation.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/externalFormat/externalFormatContract.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/schemaSet/metamodel.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/schemaSet/metamodel_diagram.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/transformation/tests/externalFormatContract.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/extensions/extension.pure, legend-engine-xt-flatdata-pure/src/main/resources/core_external_format_flatdata/externalFormatContract.pure, legend-engine-xt-flatdata-pure/src/main/resources/core_external_format_flatdata/metamodel/metamodel.pure, legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/fromPure/sdl/fromPure_sdl.pure, legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/toPure/introspection/toPure_introspection.pure, legend-engine-xt-haskell-pure/src/main/resources/core_external_language_haskell/transformation.pure, legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/binding/shared.pure, legend-engine-xt-json-pure/src/main/resources/core_external_format_json/externalFormatContract.pure, legend-engine-xt-json-pure/src/main/resources/core_external_format_json/metamodel/metamodel.pure, legend-engine-xt-protobuf-pure/src/main/resources/core_external_format_protobuf/metamodel/metamodel.pure, legend-engine-xt-xml-pure/src/main/resources/core_external_format_xml/externalFormatContract.pure, legend-engine-xt-xml-pure/src/main/resources/core_external_format_xml/metamodel/metamodel.pure
Improvement
External Format Contract Refactor, this PR brings in 2 changes
- Deleting `SchemaDetail`: Currently we are enforcing each external format to define a schema metamodel which should extend SchemaDetail. With this change, we are removing this so that external format developers don't have to know the internals of the platform to model their schema metamodel. In essence, we are relaxing this in order to make integration more smooth.
- Changing ExternalFormatContract: We are replacing property `sourceRecordTree` with properties `internalizeReturnsChecked` & `sourceRecordSerializeTree`. Again checked is an internal platform concern and in the happy path, external format developers should not have to worry about it. Moving forward if a developer wants to provide record-level lineage …
=> External Format Contract Refactor

.github/workflows/database-databricks-integration-test.yml, legend-engine-xt-relationalStore-executionPlan-connection-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/ExternalIntegration_TestConnectionAcquisitionWithFlowProvider_Databricks.java, legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/authentication/strategy/ApiTokenAuthenticationStrategy.java, pom.xml
- Databricks SQL warehouse do not support extra properties in JDBC connection
- Enable integration tests by using serverless endpoints
- Improvement
Although databricks JDBC connection works for standard (all purpose) clusters, we may need to execute queries against [SQL warehouse](https://www.databricks.com/product/databricks-sql), specifically designed for SQL compute. The latter does not accept additional properties in JDBC connection URLs, hence changes in [ApiTokenAuthenticationStrategy.java](legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/authentication/strategy/ApiTokenAuthenticationStrategy.java)
By moving to SQL compute, we benefit from serverless offering so that compute is always on …
=> Databricks serverless endpoint (enabling integration testing)

legend-engine-external-format-jsonSchema/src/main/java/org/finos/legend/engine/external/format/jsonSchema/schema/generations/JSONSchemaConfig.java, legend-engine-pure-code-compiled-core/src/main/resources/core/external/format/json/fromJSONSchema.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/external/format/json/jsonSchema.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/external/format/json/tests/sharedSchema.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/external/format/json/tests/testToJsonSchema.pure
Improvement
Add support for generating json schemas that include all subtypes of a specific class on an anyOF collection so that the schema successfully passes validation for more then one subtype match an instance of data
=> json schema feature updates to enable polymorphism

legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/debug/GraphQLDebug.java, legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/execute/GraphQLExecute.java
Bug Fix
This PR allows users to use the dev GraphQL endpoints with both user and group SDLC workspaces. 
Previously, the code only supported user workspaces (isGroupWorkspace was hardcoded to false). 
Now there are 2 new API endpoints 
```
/workspace/{wsId}
/groupWorkspace/{wsId}
```
that are routed to the appropriate SDLC APIs to load models. 
In addition, the previous API is being deprecated and will be removed in the next release of engine.
Fixes #
Yes. New APIs are being introduced.  Existing APIs have been deprecated but not deleted.
=> Update GraphQL API endpoints with user/group workspace parameters.

.github/workflows/database-postgresql-integration-test.yml, .github/workflows/database-postgresql-sql-generation-integration-test.yml, .github/workflows/database-snowflake-integration-test.yml, .github/workflows/database-snowflake-sql-generation-integration-test.yml
Improvement
Publishes test results from the Snowflake/Postgres  workflows to Github actions.
This is so that other workflow actions can download these results (artifacts) and assemble reports etc. 
We are already doing this in a couple of places -
https://github.com/finos/legend-engine/blob/master/.github/workflows/test-result.yml 
https://github.com/finos/legend-engine/blob/master/.github/workflows/summarize-sql-generation-integration-tests.yml 
This PR publishes the full/raw Junit output instead of a summary. 
Once we get the report generation working for Snowflake/Postgres, we can roll out to the other database workflows and also cleanup other summary artifacts that the workflows are currently publishing.
Fixes #
No
=> Update Snowflake/Postgres workflows to upload test results as Github artifacts

legend-engine-xt-persistence-cloud-grammar/pom.xml, legend-engine-xt-persistence-grammar/pom.xml, legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/compiler/toPureGraph/PersistenceCompilerExtension.java, legend-engine-xt-persistence-pure/src/main/resources/core_persistence/persistence/validations_rules.pure, legend-engine-xt-persistence-pure/src/main/resources/core_persistence/test/validation_rules_test.pure
Bug Fix
Persistence validation generates an execution plan as a workaround to examine the return type of TDS services.
This PR ensures all plan generation extensions are passed through when this execution plan is generated. 
None.
None.
No.
=> Persistence validation fix

legend-engine-protocol/src/main/java/org/finos/legend/engine/protocol/AnyDeserializer.java, legend-engine-protocol/src/test/java/org/finos/legend/engine/protocol/TestAnyDeserializer.java
Bug Fix
Handles LongNode values to be deserialized to Long
Fixes #
No
=> Handle LongNode in AnyDeserializer

legend-engine-xt-authentication-implementation-core/src/main/java/org/finos/legend/authentication/credentialprovider/CredentialProvider.java, legend-engine-xt-authentication-implementation-core/src/test/java/org/finos/legend/authentication/TestDefaultCredentialCreation.java
Improvement
If the incoming credential type is same as output credential type, we can directly return the incoming credential. There is no need to look for intermediation rules. It will reduce the effort to add default intermediation rules for every authentication spec.
Fixes #
No
=> Add logic for returning default incoming credential in CredentialProvider

legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/preeval/preeval.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/preeval/tests.pure
Bug Fix
Fixes an issue in preval in the case where AggregateValue uses in scope constant variables within an automap, in the map or agg functions.
No
=> Preeval - handle constants in AggregateValue automaps

legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/logicalplan/LogicalPlanFactory.java, legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/logicalplan/datasets/SelectionAbstract.java, legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/main/java/org/finos/legend/engine/persistence/components/relational/ansi/sql/visitors/SelectionVisitor.java, legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/logicalplan/operations/SelectTest.java, legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/util/LogicalPlanFactoryTest.java, legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-core/src/main/java/org/finos/legend/engine/persistence/components/relational/api/RelationalIngestorAbstract.java, legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-core/src/main/java/org/finos/legend/engine/persistence/components/relational/sqldom/common/Clause.java, legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-core/src/main/java/org/finos/legend/engine/persistence/components/relational/sqldom/schemaops/statements/SelectStatement.java, legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-core/src/test/java/org/finos/legend/engine/persistence/components/relational/sqldom/schemaops/SelectExpressionTest.java
Bug Fix
Bug fix for SQL that checks if the table is empty.
Bug fix for SQL that checks if the table is empty.
The old sql was not compliant with Snowflake
Rewrote the SQL that is now compliant with Snowflake and added related tests.
NO
=> Persistence Component: Fix for empty table check SQL for snowflake

legend-engine-xt-analytics-search-generation/pom.xml, legend-engine-xt-analytics-search-pure/pom.xml
Bug Fix
Bumps version of legend-engine-xt-analytics-search-generation-* modules to match rest of project.
https://github.com/finos/legend-engine/pull/1465 contained new modules but was merged after a new development iteration began.
N/A
No
=> Bump version of legend-engine-xt-analytics-search-generation-* modules

legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/testable/service/extension/ServiceTestRunner.java, legend-engine-test-runner-service/src/test/java/org/finos/legend/engine/testable/service/TestServiceTestSuite.java, legend-engine-test-runner-service/src/test/resources/testable/service/serviceGrammarTestWithOptimizedWorkflow.pure
Improvement 
Changing the instances of connection set up and closeable for execution parameters by limiting their setup and close to 1 per test suite. Previously, a multi exec service with 3 execution parameters and 3 test cases (that is running against all keys), would setup the same runtime 3 times per test suite, which caused latency in build for users. 
Fixes # Build time issues, code optimization for multiexecution services.
No, but they should be able to experience shorter build times
=> Optimizing Connection Data setup for MultiExecution Services

legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/preeval/preeval.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/preeval/tests.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/serialization/toPureGrammar.pure
Improvement
Simplifies $x->filter(f | false) to []
Simplifies $x->filter(f | true) to $x
No
=> Preval - simplify filter with constant boolean return

legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperMappingBuilder.java, legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperModelBuilder.java, legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalBuilder.java, legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestEmbeddedRelationalCompilationFromGrammar.java, legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalCompilationFromGrammar.java, legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalCompilationFromProtocol.java, legend-engine-xt-relationalStore-grammar/src/test/resources/mappingWithMappedPropertyFromAssociation.json
Bug Fix
Fixes # https://github.com/finos/legend-studio/issues/1991
This is very similar to https://github.com/finos/legend-engine/pull/1149
Sometimes, clients could send protocol models with `PropertyPointer.class` pointing at an association instead of a class, for this reason, we need to properly resolve the owner of the property when building the graph
=> fix property mapping not properly resolving from associations property

.github/workflows/build.yml, pom.xml
Bug Fix
`javadoc` must not be triggered in default branch build as it will fail if we don't call `compile` beforehand due to code generators like `Immutables` which is currently used in persistence code. As such, we will not call it for now.
Also, for the build order, make sure we build all XT modules before engine server and collections modules.
=> fix javadoc and cleanup build order

legend-engine-language-pure-modelManager-sdlc/src/main/java/org/finos/legend/engine/language/pure/modelManager/sdlc/SDLCLoader.java, legend-engine-language-pure-modelManager-sdlc/src/main/java/org/finos/legend/engine/language/pure/modelManager/sdlc/alloy/AlloySDLCLoader.java
Improvement
We want to refactor metadata api execution by allowing a provision for replacing default client with a auth-based client provider.
=> Override default client with authentication for metadata API execution 

legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/store/routing.pure
Bug Fix
Recent changes ended routing the from parameters incorrectly, bypassing specialized functions.  This move to use the routing function that will handle this specialized functions correctly.
Fixes #
=> Use routeFunctionExpression on from to ensure we respect special functions

.github/workflows/build.yml
Improvement
This forces the `Build CI` to run only once at a time per PR to prevent contributors who push a lot of commits within a short period of time wasting CI minutes on our billed large runner - a compromise we can take to reduce operational expense.
Fixes #
=> ci: add concurrency to build job to save runner minutes

.github/workflows/clean-after-failed-release.yml
This PR adds an action for to clean up the repository in case of a release failure
The staging process in OSSHR may fail when doing a release and the staging repo could be dropped (in this case we delete the release tag and commits from the master branch and run a new release action)
It helps clean up the git repo after a failed release
=> Action for handling release failures

legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/api/QueryStoreManager.java, legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/model/Query.java, legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/model/QuerySearchSpecification.java, legend-engine-application-query/src/test/java/org/finos/legend/engine/application/query/api/TestQueryStoreManager.java
This PR adds a new field `lastUpdateTimeStamp` info for a query 
Fixes #
=> Persist createAt, lastUpateAt timestamp info for a query

legend-engine-xt-analytics-search-generation/src/main/java/org/finos/legend/engine/generation/SearchDocumentArtifactGenerationExtension.java, legend-engine-xt-analytics-search-generation/src/test/java/org/finos/legend/engine/generation/TestSearchDocumentArtifactGenerationExtension.java
Bug Fix
Switch the filename for artifacts generated by SearchDocumentArtifactGenerationExtension to be static rather than using the element's path to avoid scenarios where the filename is too large for the filesystem.
N/A
=> Switch to static filename for SearchDocumentArtifactGenerationExtension

legend-engine-xt-relationalStore-trino-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/specifications/TrinoDatasourceSpecificationRuntime.java
setting trust store password for trino driver properties
Improvement
It is setting one of the properties - sslTrustStorePassword required for trino jdbc connection
This a fix to new change
No
=> setting trust store password

legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PackageableElementFirstPassBuilder.java
Bug Fix
Adds name to PackageableRuntime and PackageableConnection in PackageableElementFirstPassBuilder
=> Add name to PackageableRuntime and PackageableConnection in PackageableElementFirstPassBuilder

legend-engine-xt-relationalStore-trino-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/authentication/strategy/TrinoDelegatedKerberosAuthenticationStrategyRuntime.java, legend-engine-xt-relationalStore-trino-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/specifications/TrinoDatasourceSpecificationRuntime.java
Add default value for Trino KerberosDelegation when Delegated Auth Strategy used
This is required for legend to make use of ContextBasedSubjectProvider from Trino instead of LoginBasedSubjectProvider when delegated Kerberos as the strategy is used,  without this property Auth flow will call LoginBasedSubjectProvider and is expected to throw exception if there is no keyTab or Credential Cache is present.
Fixes # 
Kerberos error 
Unable to obtain Principal Name for authentication.
This should've been the default property when Subject.doAs is wrapped to get the TrinoConnection()
No Changes expected
=> Add default value for Trino KerberosDelegation when Delegated Auth Strategy used

legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java, legend-engine-xt-nonrelationalStore-mongodb-executionPlan/src/README.md, legend-engine-xt-nonrelationalStore-mongodb-grammar-integration/pom.xml, legend-engine-xt-nonrelationalStore-mongodb-grammar-integration/src/main/java/org/finos/legend/engine/language/pure/grammar/integration/plan/MongoDBPlanGeneratorExtension.java, legend-engine-xt-nonrelationalStore-mongodb-javaPlatformBinding-pure/src/main/resources/core_nonrelational_mongodb_java_platform_binding/mongodbStoreLegendJavaPlatformBindingExtension.pure, legend-engine-xt-nonrelationalStore-mongodb-javaPlatformBinding-pure/src/main/resources/core_nonrelational_mongodb_java_platform_binding/test/testSetup.pure, legend-engine-xt-nonrelationalStore-mongodb-pure/src/main/resources/core_nonrelational_mongodb/extensions/extensions.pure
Improvement - Part of the fix to avoid adding Mongo-extensions to core-configuration.  The extensions are loaded via PlanGenerator interface
Clean up extensions to a single pure function - for ease of use in welcome.pure (development purposes)
=> Load mongo extensions via PlanGeneratorExtension interface

legend-engine-pure-code-compiled-core/src/main/resources/core/pure/lineage/scanProperties.pure
Performance improvement
Improve the performance of lineage calculation by only generating the debug string if printing debug info. By side effect, this should improve plan generation time.
This should reduce lineage calculation time, thereby reducing plan generation time.
=> In scanProperties, only generate debug string if printing debug info

legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphExtension.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/tests/sourceTreeCalc/testSourceTreeCalc.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/simpleObject.pure
Bugfix
Fixes sourcetree calculation in certain cases involving union and mapping filters. 
When performing a union on two classes with properties of the same name, if one mapping in the union has a filter then we incorrectly duplicate properties in parts of the source tree
No
=> Fix bug in sourcetree calculation of unions with filters

legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/platformBinding/typeInfo/typeInfo.pure
Improvement
Improve performance of plan binding by reducing the amount of string concatenation, particularly in calls to elementToPath.
This should result in a modest speed improvement in plan binding.
=> In typeInfo.pure, reduce calls to elementToPath

legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperModelBuilder.java, legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PackageableElementFirstPassBuilder.java, legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PureModel.java, legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/extension/CompilerExtensions.java, legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/extension/Processor.java, legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestAggregationAwareCompilationFromGrammar.java, legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDomainCompilationFromGrammar.java, legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestMappingCompilationFromGrammar.java, legend-engine-language-pure-compiler/src/test/resources/functionExample.json, legend-engine-language-pure-compiler/src/test/resources/functionWithLambdaVariable.json, legend-engine-language-pure-compiler/src/test/resources/queryWithPathVariable.json, legend-engine-test-runner-service/src/test/java/org/finos/legend/engine/test/runner/service/TestRuntimeGenerationForServiceTests.java, legend-engine-xt-mastery-grammar/src/test/java/org/finos/legend/engine/language/pure/dsl/mastery/compiler/test/TestMasteryCompilationFromGrammar.java, legend-engine-xt-morphir/pom.xml, legend-engine-xt-morphir/src/test/java/org/finos/legend/engine/external/language/morphir/tests/TestMorphirFileGeneration.java, legend-engine-xt-morphir/src/test/resources/org/finos/legend/engine/external/language/morphir/tests/simpleFileGeneration.json, legend-engine-xt-serviceStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperServiceStoreClassMappingBuilder.java
Bug fix
This adds a validation in the compiler that checks for three things. First, that each element has a non-null, non-empty name. Second, that the name of Pure element created in the first pass matches the name of the protocol element it was created from. Third, that the name in unique within its package. Violation of any of these results in a compilation error.
In passing, this abstracts out the package creation, setting the package on the new element, and adding the new element as a child of the package.
All existing extensions that were in violation have been fixed. However, this should make it easier to prevent future extensions from being in violation, as it will be easy to detect the problem when compiling in tests.
This should have no immediate effect, as all offending …
=> Compiler validation for element names

legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PackageableElementFirstPassBuilder.java, legend-engine-language-pure-compiler/src/test/resources/functionExample.json, legend-engine-language-pure-compiler/src/test/resources/functionWithLambdaVariable.json, legend-engine-language-pure-compiler/src/test/resources/queryWithPathVariable.json
Bug Fix
To preserve backward compatibility, this eases the [new compiler validations](https://github.com/finos/legend-engine/pull/1644) on element names to allow function names to differ between the protocol and the compiled model.
No
=> Allow function name to be different between protocol and model

legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/mappingExtension.pure, legend-engine-pure-ide-light/pom.xml, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/functions/tests/projection/testFilter.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/relationalMappingExecution.pure
Bug Fix
Freemarker functions are currently generated for only enumeration mappings at the top level. This PR extends it to those from included mappings
=> Generate freemarker functions for included enumeration mappings

legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphExtension.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/tests/sourceTreeCalc/testSourceTreeCalc.pure
Bugfix
Fix source tree calculation for union mappings where one union element is starting from the source and another from property access
=> Sourcetree Calc: Fix unions with differing source property levels

legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/StreamResultToTempTableVisitor.java
Bug Fix
SF commands for temp table creation do not expect header to be present in CSV file. However, the flag is not uniform across all types of results currently being handled for a database type. As a result, extra row with header (column names) is added to the temp table in case of TDS cross store joins.
=> Uniform withHeader flag in temp table creation for different result types

legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/full/functions/in/TestPlanExecutionForIn.java, legend-engine-xt-relationalStore-executionPlan/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/full/functions/in/tempTableExecutionPlanWithPostProcessor.json, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/postprocessor/defaultPostProcessor/processInOperation.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/postprocessor/postProcessor.pure
Bug Fix
Having an IN operation in a lambda triggers user post processor multiple times.
This change avoids it in processInOperation and as we have user post processor on root which will come at the end, query processing should be fine.
No
=> Avoid rerunning user post processor in processIN

legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphExtension.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/tests/sourceTreeCalc/testSourceTreeCalc.pure
Bugfix
Handle multiple paths via $src in M2M mappings - in particular this fixes an issue where a top level mapping passes down the $src object to both a union and non-union mapping, where the mappings access a common set of properties. 
This fixes a case missed in a previous commit https://github.com/finos/legend-engine/pull/1605
=> SourceTreeCalc: Fix union and non-union traversal via root object

legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/api/QueryStoreManager.java, legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/model/Query.java, legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/model/QueryParameterValue.java, legend-engine-application-query/src/test/java/org/finos/legend/engine/application/query/api/TestQueryStoreManager.java
Add `defaultParameterValues` to Query for QueryStore for Query Application. 
Motivation is to be able to save user's default parameter values, so saved queries are easier and more intuitive to execute. 
Improvement to Legend Query workflow
Add `defaultParameterValues` to Query 
Fixes #
=> add defaultParameterValues to Query

legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/mathLibrary.pure, legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/mathLibraryTests.pure
Improvement
It adds sqrt() function to Alloy (along with test for it). Right now when trying to use sqrt() in Alloy Studio the following error pops up: "meta::pure::functions::math::sqrt_Number_1__Float_1_ is not supported yet!"
It's just one line adding a call to Math.sqrt() similar to how functions like sin() work.
No
=> feature: added sqrt function with test (alloy)

legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/util/Library.java, legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/collectionsLibrary.pure, legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/collectionsLibraryTests.pure
Bug Fix
If you call reverse() function in Alloy Studio it will throw Java error "void cannot be converted to java.util.List<>"
The one described above.
The issue was cause by the fact that someone assumed that Collections.reverse() returns the reversed collection, but it acutally returns void and modifies the collection passed as an argument.
No.
=> fixed reverse function (alloy) and added test for it

legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/routing/router_routing.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/tds/tds.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tds/tests/testTDSConcatenate.pure
- Improvement
Add TDS concatenate method that takes multiple additional TDSs.  This avoids having to perform lots of sequential individual concatenates, which can lead to unnecessary of deep level function call depth.
Instead of ``concatenate($a, conctenate($b, concatenate($c, $d)))``, you can now do ``$a->concatenate([$b,$c,$d])``
=> Add TDS concatenate method that takes multiple additional TDSs

legend-engine-extensions-collection-execution/pom.xml, legend-engine-extensions-collection-execution/src/test/java/org/finos/legend/engine/extensions/collection/execution/TestExtensions.java, legend-engine-xt-nonrelationalStore-mongodb-executionPlan/pom.xml, legend-engine-xt-nonrelationalStore-mongodb-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/mongodb/MongoDBExecutor.java, legend-engine-xt-nonrelationalStore-mongodb-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/mongodb/MongoDBStoreExecutionExtension.java, legend-engine-xt-nonrelationalStore-mongodb-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/mongodb/compiler/MongoDBDocumentFormatJavaCompilerExtension.java, legend-engine-xt-nonrelationalStore-mongodb-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/mongodb/plugin/MongoDBExecutionNodeExecutor.java, legend-engine-xt-nonrelationalStore-mongodb-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/mongodb/result/MongoCursorResult.java, legend-engine-xt-nonrelationalStore-mongodb-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/mongodb/result/MongoDBResult.java, legend-engine-xt-nonrelationalStore-mongodb-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/mongodb/specifics/IMongoDocumentDeserializeExecutionNodeSpecifics.java, legend-engine-xt-nonrelationalStore-mongodb-executionPlan/src/main/resources/META-INF/services/org.finos.legend.engine.plan.execution.nodes.helpers.platform.ExecutionPlanJavaCompilerExtension, legend-engine-xt-nonrelationalStore-mongodb-grammar-integration/src/main/java/org/finos/legend/engine/language/pure/grammar/integration/MongoDBCompilerExtension.java, legend-engine-xt-nonrelationalStore-mongodb-grammar-integration/src/main/java/org/finos/legend/engine/language/pure/grammar/integration/util/MongoDBCompilerHelper.java, legend-engine-xt-nonrelationalStore-mongodb-javaPlatformBinding-pure/src/main/resources/core_nonrelational_mongodb_java_platform_binding/mongodbStoreLegendJavaPlatformBindingExtension.pure, legend-engine-xt-nonrelationalStore-mongodb-javaPlatformBinding-pure/src/main/resources/core_nonrelational_mongodb_java_platform_binding/test/pureSetup.txt
Improvement
Replace ExternalFormatInternalize execution node(that was using InputStream as input) with MongoDocumentFormatInternalize execution node that takes MongoCursor as input & iterate through that to build the result json.
Minor clean up - No special processing for associated processing while constructing property mapping
=> Support streaming from Mongo cursor

legend-engine-xt-analytics-search-pure/src/main/resources/core_analytics_search/trans.pure, legend-engine-xt-analytics-search-pure/src/main/resources/core_analytics_search/transTest.pure
Bug Fix
- Fixes `Cannot cast a collection of size 0 to multiplicity [1]` error if a DataSpace does not have a description defined.
- Added test cases to cover document generation for DataSpace with and without a description.
=> Fix DataSpace Search Document Generation

legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
Bug Fix
Add divide decimal with scale to Handlers
This allows the Engine compiler to be able to handle both divide functions defined in the Pure language
=> Add divide decimal with scale to Handlers

legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/store/cluster.pure
Bug Fix
On the interpreted flow, the dynamic eval function complains the input is not of the right type.  The type is NonExecutableValueSpecificatioin wrapping a FunctionExpression.
Fixes #
=> Use evaluateAndDeactivate to avoid bug on interpreted mode

legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/graphFetchCommon.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/relationalGraphFetch.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/helperFunctions/helperFunctions.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/mapping/embedded/testInlineEmbeddedNested.pure
Improvement
Users can now do graphFetch queries with InlineMappings, only TDS is supported earlier.
No
=> Enable graphFetch for InlineMappings

pom.xml
The current version of jacoco-maven-plugin (0.8.5) is not compatible with JDK 17. This upgrades to 0.8.10, which is.
No, this change will affect only the build.
=> Upgrade jacoco-maven-plugin version to 0.8.10

legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/extension/ConnectionFactoryExtension.java, legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/data/EmbeddedDataHelper.java, legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/modelToModel/connection/ModelStoreTestConnectionFactory.java, legend-engine-pure-code-compiled-core/src/main/resources/core/legend/service/metamodel.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/data/data.pure, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/test/testable.pure, legend-engine-test-runner-mapping/src/main/java/org/finos/legend/engine/testable/mapping/extension/MappingTestRunner.java, legend-engine-test-runner-mapping/src/main/java/org/finos/legend/engine/testable/mapping/extension/MappingTestRunnerContext.java, legend-engine-xt-nonrelationalStore-mongodb-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/mongodb/testsupport/MongoDBStoreTestConnectionFactory.java, legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/test/RelationalConnectionFactory.java, legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/test/ServiceStoreTestConnectionFactory.java
Addressing some points of discussion on https://github.com/finos/legend-engine/pull/1600
- move StoreTestData to `data.pure`
- remove pmcd from connectinTestFactory to prevent inproper usage of interface.
=> minor cleanups for mapping testable #1600

legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperValueSpecificationBuilder.java, legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDomainCompilationFromGrammar.java, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/store/routing.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/tests/testSubTypeGraphFetch.pure
- Improvement
This PR allows usage union mapping with  subTypeGraphFetchTree at root level. 
Fixes #
- Added routing support for union mapping.
- Added check for duplicate properties at root and subType level.
NA
Yes
=> Support union mapping with subTypeGraphFetchTree at root level

legend-engine-xt-relationalStore-executionPlan-connection-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/TestLocalH2ConnectionCreation.java, legend-engine-xt-relationalStore-executionPlan-connection/src/main/resources/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/h2/h2NorthwindDdl.sql
- Improvement
Fix for if the stored proc ``loadNorthwindData()`` is invoked more than once
Fixes issue reported at https://github.com/finos/legend-engine/pull/1869#issuecomment-1579339347
=> Fix for DB schema clean up when running data setup stored proc

legend-engine-xt-relationalStore-executionPlan-connection-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/TestLocalH2ConnectionCreation.java
- Bug Fix
Resolve test failures (from checking specific connection counts for a given user in other tests)
userAcquiresSingleConnection (org.finos.legend.engine.plan.execution.stores.relational.connection.test.TestLocalH2ConnectionCreation) failed
userAcquiresConcurrentConnectionsToDifferentDbs (org.finos.legend.engine.plan.execution.stores.relational.connection.test.TestLocalH2ConnectionCreation) failed
=> Update TestLocalH2ConnectionCreation.java to resolve test failure

legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/ExecutionDispatcher.java, legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/PostgresWireProtocol.java, legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/Session.java, legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/handler/legend/LegendResultSet.java, legend-engine-xt-sql-postgres-server/src/test/java/org/finos/legend/engine/postgres/PostgresServerTest.java
Bug Fix
Add support for empty queries
`Connection.isValid` in Postgres JDBC driver invokes an empty query and expects an empty response.
This PR forwards the empty query to the empty session handler
=> Handle empty queries

legend-engine-xt-sql-postgres-server/pom.xml, legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/ExecutionDispatcher.java, legend-engine-xt-sql-postgres-server/src/test/java/org/finos/legend/engine/postgres/ExecutionDispatcherTest.java, legend-engine-xt-sql-postgres-server/src/test/java/org/finos/legend/engine/postgres/PostgresServerTest.java
Improvement
Add support for `SHOW TRANSACTION` queries.
These queries are executed during the pool creation of HikariCP to validate the connection.
`SHOW TRANSACTION` queries are temporary routed to metadata handler until it can be supported in Alloy SQL
No
=> Add support for SHOW TRANSACTION queries

legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/RelationalExecutionNodeExecutor.java, legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/full/graphFetch/crossStore/TestConnectionPoolHygiene.java
Improvement
We try to delete temporary tables with the same name before creating them in cross-store GraphFetch.
There is a chance that one of the cross store executions fails and leaves temporary tables active.
This change makes sure that execution does not interfere with other cross store executions running using the same connection pool.
This will not be needed when we handle drops through the connection in cross store and gracefully drop on connection close.
No
=> xstore graphfetch -Try dropping temp table before creating it 

legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/operational/errorManagement/ExceptionError.java, legend-engine-xt-sql-postgres-server/pom.xml, legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/PostgresWireProtocol.java, legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/Session.java, legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/handler/legend/LegendTdsClient.java, legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/handler/legend/LegendTdsClientException.java, legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/utils/ExceptionUtil.java, legend-engine-xt-sql-postgres-server/src/test/java/org/finos/legend/engine/postgres/PostgresServerTest.java, legend-engine-xt-sql-postgres-server/src/test/java/org/finos/legend/engine/postgres/handler/legend/LegendTdsTestClient.java, legend-engine-xt-sql-query/src/test/java/org/finos/legend/engine/query/sql/api/CatchAllExceptionMapper.java, legend-engine-xt-sql-query/src/test/java/org/finos/legend/engine/query/sql/api/execute/SqlExecuteTest.java, legend-engine-xt-sql-query/src/test/java/org/finos/legend/engine/query/sql/api/sources/TestSQLSourceProvider.java
Improvement
This PR adds functionality to propagate execution errors to the Legend SQL client.
Previously, all queries appear to have succeeded with empty result set.
No
=> Propagate execution errors to Legend SQL client

legend-engine-xt-relationalStore-executionPlan-connection/pom.xml, legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/AlloyH2Server.java, legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/authentication/strategy/DefaultH2AuthenticationStrategy.java, legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/h2/H2Manager.java, legend-engine-xt-relationalStore-executionPlan/pom.xml, legend-engine-xt-relationalStore-h2-1.4.200-execution/pom.xml, legend-engine-xt-relationalStore-h2-1.4.200-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/LegendH2Extensions_1_4_200.java, pom.xml
Bug Fix
This PR introduce further backward compatibility on H2, allowing projects importing engine to still run 1.4.200, given them more time to migrate to 2.1.x
Fixes #
=> Allow engine to still work with legacy H2 version 1.4.200

legend-engine-xt-relationalStore-executionPlan-connection-api/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/api/schema/SchemaExportation.java, legend-engine-xt-relationalStore-executionPlan-connection-api/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/api/schema/TestSchemaExploration.java
fix an issue with schema exploration endpoint when the pattern is empty, the generated database would be empty
=> fix schema exploration endpoint when pattern is empty

legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastBooleanStringTest.java, legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastBooleanTest.java, legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastCustomMapTest.java, legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastCustomNestedTest.java, legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastCustomPrimitiveStringTest.java, legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastCustomPrimitiveTest.java, legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastCustomTest.java, legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastDoubleStringTest.java, legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastDoubleTest.java, legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastIntegerStringTest.java, legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastStringQuotesTest.java, legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastStringTest.java, legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastTestBase.java, legend-engine-xt-changetoken-pure/pom.xml, legend-engine-xt-changetoken-pure/src/main/resources/core_pure_changetoken.definition.json, legend-engine-xt-changetoken-pure/src/main/resources/core_pure_changetoken/cast_generation.pure, legend-engine-xt-changetoken-pure/src/main/resources/core_pure_changetoken/changetoken_test.pure
Support Map or embedded JSON string for value of ConstValue as defaultValue property of AddField change token
To allow generation of Java code that can upcast/downcast changetokens with adding field of other types then simple integer.
N/A
N/A
N/A
=> Extend change tokens functionality

.github/workflows/build.yml
Bug Fix
This reduce the scope of the m2 cache to just the repository directory.  The current scope include settings.xml, which could contain secrets on some instances.
Fixes #
=> Avoid caching setting xml given it could have secrets stored on it

legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/fromPure/introspection/fromPure_Introspection.pure, legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/fromPure/introspection/tests/simpleTest.pure
Improvement
For large models our current algorithm takes a lot of time, traversing each path. Refactoring it to memorize past results.
Fixes #
Test fails currently as seen here https://github.com/finos/legend-engine/pull/1965 due to timeout
=> GraphQL - adding memorization to types traversal

legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/grammar/to/HelperPersistenceComposer.java
- Bug Fix
A null check is needed for ServiceOutputTargets, a V2-only construct, in case user is using V1 spec.
Fixes #
No
=> Persistence: Fix null check for Spec V2

legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/serialization/TDSResultToCSVSerializer.java, legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/serialization/TDSResultToPureFormatSerializer.java, legend-engine-pure-code-compiled-core/src/main/resources/core/pure/tds/tds.pure, legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-V7-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/elasticsearch/v7/result/ElasticsearchTDSResultHelper.java, legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-V7-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/elasticsearch/v7/result/ExecutionRequestVisitor.java, legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-V7-pure-metamodel/src/main/resources/core_elasticsearch_seven_metamodel/functions/pure_to_elasticsearch.pure, legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test_aggregation_average.pure, legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test_aggregation_count.pure, legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test_aggregation_max.pure, legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test_aggregation_min.pure, legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test_aggregation_sum.pure
Improvement
This further improves elasticsearch aggregation support. 
- Support for `sum` on Float and Number TDS columns
- Support for `max` aggregation
- Support for `min` aggregation
- Support for `average` aggregation
Further improve test coverage of these aggregations, including edge case where the are no results to max/min.
BugFix TDS aggregations to return `TDSNull` when aggregation function does not returns any value.
Fixes #
~~TDS BugFix could affect some users~~ Integration testing does not show any immediate impact.
=> Improvements to Elasticsearch aggregations

legend-engine-test-runner-service/src/test/java/org/finos/legend/engine/testable/service/TestServiceTestSuite.java, legend-engine-test-runner-service/src/test/resources/testable/relational/legend-testable-relational-service-csv-test-data.pure, legend-engine-test-runner-service/src/test/resources/testable/relational/legend-testable-relational-service-embeddedData.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/helperFunctions/helperFunctions.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/DDL/testDDL.pure, legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/testSuite/naming/naming.pure
Bug Fix
This PR is not backwards compaitble.
Some user tests in prod need to be updated.
Before: 
After: 
https://github.com/finos/legend-engine/assets/73408381/9c2923ce-4b9a-4bdf-98f8-eb81c1475533
Fixes #
=> support comma in column value for service test csv data

legend-engine-server/pom.xml
- Bug Fix
Legend server needs to depend on the new grammar module added for persistence spec V2, so that studio can correctly recognise the new structure
Fixes #
No
=> Persistence: Add V2 dependency for legend server

legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/DEPRECATED_PureGrammarComposerCore.java, legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestDomainGrammarRoundtrip.java
Bugfix
Fix grammar composer for divide function that takes in a scale with decimal types - we should not use the infix operator for this function (as we do for normal divide function)
Yes - grammar composer will correctly produce Pure syntax for divide with scale function
=> Pure Grammar: Handle divide with scale in grammar composer

legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/operational/errorManagement/ExceptionTool.java
- Bug Fix
To be compliant with OpenTracing standards, the 'error' tag in Spans needs to be a Boolean, and so any error message needs to occupy a different tag.
=> Setting error span according to opentracing

legend-engine-core-executionPlan-execution/legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/PlanExecutor.java, legend-engine-core-executionPlan-execution/legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/graphFetch/AdaptiveBatching.java, legend-engine-core-executionPlan-execution/legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/graphFetch/AdaptiveGraphBatchStats.java, legend-engine-core-executionPlan-execution/legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/graphFetch/GraphFetchExecutionConfiguration.java, legend-engine-core-executionPlan-execution/legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/ExecutionNodeExecutor.java, legend-engine-core-executionPlan-execution/legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/state/ExecutionState.java, legend-engine-core-executionPlan-execution/legend-engine-executionPlan-execution/src/test/java/org/finos/legend/engine/plan/execution/graphFetch/TestAdaptiveBatching.java, legend-engine-language-pure-dsl-service-execution/src/main/java/org/finos/legend/engine/language/pure/dsl/service/execution/AbstractServicePlanExecutor.java, legend-engine-server/src/main/java/org/finos/legend/engine/server/Server.java, legend-engine-server/src/main/java/org/finos/legend/engine/server/ServerConfiguration.java, legend-engine-xts-flatdata/legend-engine-xt-flatdata-runtime/src/main/java/org/finos/legend/engine/external/format/flatdata/FlatDataRuntimeExtension.java, legend-engine-xts-flatdata/legend-engine-xt-flatdata-runtime/src/test/java/org/finos/legend/engine/external/format/flatdata/read/test/TestFlatDataQueries.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/RelationalExecutionNodeExecutor.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/TestPlanExecutionWithAdaptiveBatching.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/relationalGraphFetch.pure
- Improvement
We introduce an adaptive batching algorithm to choose the root batch size in Graph Fetch to utilize maximum memory per batch
- The batch size chosen by the algorithm is almost certain to perform better than the default batch size for varying query complexities. 
- The graph fetch specification is made configurable.
- This relieves users of the responsibility to benchmark and choose the optimal batch size for their queries.
No
=> Support adaptive batching in Graph Fetch 

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/autogeneration/relationalToPure.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/autogeneration/tests/relationalToPure.pure
**What type of PR is this?**
- Improvement
**What does this PR do / why is it needed ?**
Given a database schema, autogenerate classes, associations, and mapping. This improves developer experience for users trying to create a first set of models on an existing database table
**Which issue(s) this PR fixes:**
Fixes #
**Other notes for reviewers:**
**Does this PR introduce a user-facing change?**
=> Autogenerate classes, associations, and mapping from relationalStore

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSemiStructuredFlattening.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/semiStructuredFlattening.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbExtension.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/snowflake/snowflakeExtension.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/extensionDefaults.pure
- Bug Fix
This PR fixes lateral join syntax in snowflake extension.
Previously, ON clause could be specified for a lateral table function (other than SQL UDTFs) or an outer lateral join to a table function (other than SQL UDTF).
Now, ON clause for a lateral table function (other than SQL UDTFs) or an outer lateral join to a table function (other than SQL UDTF) is not allowed.
This has been notified in Snowflake 2023_04 Behaviour Change Release
Fixes #
No
=> Fix Lateral Joins in Snowflake

legend-engine-xts-persistence/legend-engine-xt-persistence-cloud-grammar/src/test/java/org/finos/legend/engine/pure/dsl/persistence/cloud/compiler/test/TestPersistenceCloudCompilationFromGrammar.java, legend-engine-xts-persistence/legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/compiler/toPureGraph/PersistenceCompilerExtension.java, legend-engine-xts-persistence/legend-engine-xt-persistence-grammar/src/test/java/org/finos/legend/engine/language/pure/dsl/persistence/compiler/test/TestPersistenceCompilationFromGrammar.java, legend-engine-xts-persistence/legend-engine-xt-persistence-grammar/src/test/java/org/finos/legend/engine/language/pure/dsl/persistence/compiler/test/TestPersistenceContextCompilationFromGrammar.java
- Improvement
Adding warning to discourage users from creating new Persistence V1 specs while migration takes place
Fixes #
=> Persistence V2: Add warning for V1 spec

legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/operational/prometheus/MetricsHandler.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan-connection/pom.xml, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/DataSourceWithStatistics.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/state/ConnectionStateManager.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan-connection/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/state/TestConnectionStateManager.java
fixes metric accuracy for connection pools. 
creating metrics of active, total and idle connections for every active connection pool instance that is updated every 10 minutes 
Fixes #
No
=> Add pool connection metrics in synchronized housekeeper (2)

legend-engine-xts-persistence/legend-engine-xt-persistence-target-relational-grammar/src/main/antlr4/org/finos/legend/pure/grammar/from/antlr4/PersistenceRelationalParserGrammar.g4, legend-engine-xts-persistence/legend-engine-xt-persistence-target-relational-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/relational/compiler/toPureGraph/HelperPersistenceRelationalBuilder.java, legend-engine-xts-persistence/legend-engine-xt-persistence-target-relational-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/relational/grammar/from/PersistenceRelationalParseTreeWalker.java, legend-engine-xts-persistence/legend-engine-xt-persistence-target-relational-grammar/src/test/java/org/finos/legend/engine/language/pure/dsl/persistence/relational/compiler/test/TestPersistenceRelationalCompilationFromGrammar.java, legend-engine-xts-persistence/legend-engine-xt-persistence-target-relational-grammar/src/test/java/org/finos/legend/engine/language/pure/dsl/persistence/relational/grammar/test/TestPersistenceRelationalGrammarRoundTrip.java
- Improvement
This allows user to specify target table name with the schema name (optionally). Hence user can specify table name by either "TABLE_NAME" or "SCHEMA_NAME.TABLE_NAME"
Fixes #
=> Persistence V2: Allow user to specify schema name under table field

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/DatabaseType.java
Improvement
SingleStore Managed services will reuse MemSQL DatabaseType
No
=> Remove SingleStore dbtype to use MemSQL

legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/TestServiceRunner.java, legend-engine-language-pure-dsl-service-execution/src/test/resources/org/finos/legend/engine/pure/dsl/service/execution/test/simpleM2MService.pure, legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/generation/expressionGeneration.pure
Bug Fix
Multiple uses of the same function for different paths in the same "match" statement with common variable names causes a conflict. Change is to compare the type and not just name to reuse the variables.
No
=> Resolve Variable Conflict in Java Generation

legend-engine-xts-iceberg/legend-engine-xt-iceberg-test-support/pom.xml, legend-engine-xts-iceberg/legend-engine-xt-iceberg-test-support/src/main/java/org/finos/legend/tableformat/iceberg/testsupport/Icebox.java, legend-engine-xts-iceberg/legend-engine-xt-iceberg-test-support/src/test/java/org/finos/legend/tableformat/iceberg/testsupport/IceboxTest.java, legend-engine-xts-iceberg/pom.xml, pom.xml
Improvement
This adds a class that to help test Iceberg integration.  The class, Icebox, uses Testcontainer to create the required resources to test these:
- LocalStack container for Iceberg storage on S3 
- Postgres container used for an Iceberg JDBC Catalog
- Trino container used as SQL engine to read/write Iceberg tables
The Icebox allow to interact with the Iceberg files thru any of the axis:
- Using the Catalog to navigate namespaces, tables, and snapshots
- Using SQL thru Trino
- Direct inspection of S3 objects
=> Add Iceberg test support

legend-engine-pure-code/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/modelToModel.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/tests/union/testUnionRootLevel_relational.pure
Bug fix
Allows Platform Execution nodes to be used in model chain/m2m graph fetch flows. 
These occur for example when a ROUTER_UNION is selected as the root of a mapping.
Fixes #
ROUTER_UNION is an in-memory union as opposed to STORE_UNION which is a Union in the database SQL.
Yes
=> Allow routing of root router unions in m2m graphfetch

legend-engine-xts-persistence/legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/grammar/to/HelperPersistenceComposer.java, legend-engine-xts-persistence/legend-engine-xt-persistence-grammar/src/test/java/org/finos/legend/engine/language/pure/dsl/persistence/grammar/test/TestPersistenceGrammarV2Roundtrip.java
Bug fix
fixing the composer for the optional attribute graphFetchPath as part of the persistence test runner. 
None
No
=> Persistence test runner : Fixing the composer for graphFetchPath attribute

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/query/testView.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/relationalSetUp.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/testModel/simpleTestModel.pure
Bug Fix
When we map on views and do a filter operation on lambda, it constructs a self join.
Changes will add a match expression for ViewSelectSQLQuery  and a validation while adding Self Join
No
=> Match on ViewSelectSQLQuery for Self Join

legend-engine-xts-service/legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/test/runner/service/ServiceTestRunner.java
When running platform regression, services that fail on assertion does not log what the assertion function was.  This makes it complicated to understand what could be the root cause.
Fixes #
=> Log failure of service assert lambdas

legend-engine-xts-mastery/legend-engine-xt-mastery-protocol/pom.xml
Bug fix
Exclude org.finos.legend.pure:* from legend-engine-language-pure-dsl-generation dependency in legend-engine-xt-mastery-protocol
No
=> Add dependency exclusion in legend-engine-xt-mastery-protocol

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tds/tests/testGroupBy.pure
Bug Fix
Queries containing filters with distinct and groupBy were dropping the filters leading to incorrect sql generation. Hence The solution was to included the dropped filters. 
Yes
=> Fix pure to sql for filter with distinct and groupBy

legend-engine-xts-sql/legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/fromPure.pure, legend-engine-xts-sql/legend-engine-xt-sql-query/src/test/java/org/finos/legend/engine/query/sql/api/execute/SqlExecuteTest.java, legend-engine-xts-sql/legend-engine-xt-sql-query/src/test/resources/proj-1.pure
Bug Fix
Legend SQL queries on services that use date parameters are failing due to invalid parameter values. Error :`IllegalArgumentException: Invalid provided parameter(s): [Unable to process 'Date' parameter...`
The validator expects a LocalDate or String value while we are passing an instance of StrictDate.
This PR updates SQL-to-pure to send the string value so that the validator can parse it.
No
=> Legend SQL - Use string-ified date instance as parameter values

pom.xml
Ensure we use maven version 3.6.2 and above. This is due to a bugfix for exclusions and wildcards for artefact filters (https://issues.apache.org/jira/browse/MNG-6713)
This was fixed in Maven 3.6.2 (https://maven.apache.org/docs/3.6.2/release-notes.html)
=> Ensure Maven version is at least 3.6.2

legend-engine-xts-graphQL/legend-engine-xt-graphQL-relational-extension/src/main/java/org/finos/legend/engine/query/graphQL/extension/relational/directives/TotalCountDirective.java, legend-engine-xts-graphQL/legend-engine-xt-graphQL-relational-extension/src/test/java/org/finos/legend/engine/query/graphQL/extension/relational/directives/TestTotalCountDirective.java
Improvement
We will be returning limit and offset in output along with total count directive. It also extends totalCount directive to return some metadata in future which could include traceid, sql, etc
Fixes #
Yes
=> Add limit offset in output for TotalCountDirective

.github/workflows/database-athena-sql-generation-integration-test.yml, .github/workflows/database-bigquery-sql-generation-integration-test.yml, .github/workflows/database-databricks-sql-generation-integration-test.yml, .github/workflows/database-h2-sql-generation-integration-test.yml, .github/workflows/database-mssqlserver-sql-generation-integration-test.yml, .github/workflows/database-postgresql-integration-test.yml, .github/workflows/database-postgresql-sql-generation-integration-test.yml, .github/workflows/database-redshift-sql-generation-integration-test.yml, .github/workflows/database-singlestore-integration-test.yml, .github/workflows/database-singlestore-sql-generation-integration-test.yml, .github/workflows/database-snowflake-integration-test.yml, .github/workflows/database-snowflake-sql-generation-integration-test.yml, .github/workflows/database-spanner-sql-generation-integration-test.yml, .github/workflows/database-trino-sql-generation-integration-test.yml
Fix
Right now, the path for finding test results is incorrect. Updating it for each workflow which tries to publish test results to find xml files in relevant module's target/surefire-reports directory.
Fixes #
| Repo | Run Link | Has Test Results |
|-------|-----------|-------------------|
|abhishoya-gs/legend-engine|https://github.com/abhishoya-gs/legend-engine/actions/runs/6065331278|:white_check_mark:|
|finos/legend-engine|https://github.com/finos/legend-engine/actions/runs/6067460153|:x:|
No
=> DbSpecific test summary generation - fix surefire reports path in workflow

legend-engine-core/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PureModel.java
Bug fix
Set the class loader properly for finding repositories for static PureModel metadata.
Presently, it uses the current thread's context class loader, which means that the class loader used depends on which thread is current when the field is initialized. This makes for unpredictable behavior. And in some circumstances, this could mean that the class loader used to find repositories is different from the class loader used to load the metadata itself.
No
=> Set the class loader properly for PureModel metadata code repositories

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/relationalGraphFetch.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/tests/testGraphFetchMilestoning.pure
Improvement
Change composite PK not null check generated in graph fetch to AND. SQL standard 2003 states that NOT NULL constraint on composite PK columns is implicit (and many relational databases enforce this constraint). Hence, AND check should work and should also improve performance.
=> Change composite PK not null check generated in graph fetch to AND

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/relationalExtension.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/testRelationalExtension.pure
Bug Fix
This add support for numeric/decimal types inside Dyna functions, allowing the code to infer its type.
Fixes #
=> Add decimal and numeric to dyna function type inference

legend-engine-xts-sql/legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/fromPure.pure, legend-engine-xts-sql/legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/tests/testTranspile.pure
Remove redundant `isTrue` for an `or` expression
Bug Fix
The generated sql for `is not distinct from` fails to compile snowflake 
Issue does not occur when the redundant `isTrue` is removed from the pure expression for `is not distinct from` 
No
=> Fix `is not distinct from` sql-to-pure

legend-engine-xts-service/legend-engine-language-pure-dsl-service-generation/pom.xml, legend-engine-xts-service/legend-engine-language-pure-dsl-service-generation/src/main/java/org/finos/legend/engine/language/pure/dsl/service/generation/ownership/OwnershipValidator.java, legend-engine-xts-service/legend-engine-language-pure-dsl-service-pure/src/main/resources/core_service/service/metamodel.pure, legend-engine-xts-service/legend-engine-language-pure-dsl-service/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ServiceLexerGrammar.g4, legend-engine-xts-service/legend-engine-language-pure-dsl-service/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ServiceParserGrammar.g4, legend-engine-xts-service/legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/compiler/toPureGraph/HelperServiceBuilder.java, legend-engine-xts-service/legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/compiler/toPureGraph/ServiceCompilerExtensionImpl.java, legend-engine-xts-service/legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/from/ServiceParseTreeWalker.java, legend-engine-xts-service/legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/to/ServiceGrammarComposerExtension.java, legend-engine-xts-service/legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/protocol/pure/v1/ServiceProtocolExtension.java, legend-engine-xts-service/legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/service/DeploymentOwnership.java, legend-engine-xts-service/legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/service/Ownership.java, legend-engine-xts-service/legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/service/Service.java, legend-engine-xts-service/legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/service/UserListOwnership.java, legend-engine-xts-service/legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceCompilationFromGrammar.java, legend-engine-xts-service/legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceGrammarRoundtrip.java
Improvement
Add an ownership concept to the service metamodel that is meant to be extensible. Also add two extensions of the ownership and an interface that defines the validation contract. 
Change is backward compatible and has corresponding internal changes
Yes
=> Uplift Service Ownership

legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-V7-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/elasticsearch/v7/plugin/ElasticsearchV7ExecutionNodeExecutor.java, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/test/java/org/finos/legend/engine/plan/execution/stores/elasticsearch/test/TestElasticsearchExecutionPlanFromGrammarIntegration.java, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/test/resources/grammarForPlanIntegrationTesting.pure
Bug fix 
instead of passing the execution node object itself, we pass a cloned object so the actual query is not affected with size updating
No
=> Allow Elastic Search Executions to run multiple times

legend-engine-xts-mastery/legend-engine-xt-mastery-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/MasteryLexerGrammar.g4, legend-engine-xts-mastery/legend-engine-xt-mastery-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/MasteryParserGrammar.g4, legend-engine-xts-mastery/legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/compiler/toPureGraph/BuilderUtil.java, legend-engine-xts-mastery/legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/compiler/toPureGraph/IMasteryCompilerExtension.java, legend-engine-xts-mastery/legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/compiler/toPureGraph/MasteryCompilerExtension.java, legend-engine-xts-mastery/legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/from/IMasteryParserExtension.java, legend-engine-xts-mastery/legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/from/MasteryParseTreeWalker.java, legend-engine-xts-mastery/legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/from/MasteryParserExtension.java, legend-engine-xts-mastery/legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/to/IMasteryComposerExtension.java, legend-engine-xts-mastery/legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/to/MasteryGrammarComposerExtension.java, legend-engine-xts-mastery/legend-engine-xt-mastery-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mastery/runtime/MasteryRuntime.java, legend-engine-xts-mastery/legend-engine-xt-mastery-pure/src/main/resources/core_mastery/mastery/metamodel.pure, legend-engine-xts-mastery/legend-engine-xt-mastery-pure/src/main/resources/core_mastery/mastery/metamodel_diagram.pure
add mastery runtime grammar and protocol changes
=> add mastery runtime grammar and protocol changes

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-athena/legend-engine-xt-relationalStore-athena-pure/src/main/resources/core_relational_athena.definition.json, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-athena/legend-engine-xt-relationalStore-athena-pure/src/main/resources/core_relational_athena/relational/connection/connectionEqualityTest.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-athena/legend-engine-xt-relationalStore-athena-pure/src/main/resources/core_relational_athena/relational/connection/metamodel.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-athena/legend-engine-xt-relationalStore-athena-pure/src/test/java/org/finos/legend/pure/code/core/Test_Pure_Relational_ConnectionEquality.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-bigquery/legend-engine-xt-relationalStore-bigquery-pure/src/main/resources/core_relational_bigquery.definition.json, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-bigquery/legend-engine-xt-relationalStore-bigquery-pure/src/main/resources/core_relational_bigquery/relational/runtime/connection/bigQuerySpecification.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-bigquery/legend-engine-xt-relationalStore-bigquery-pure/src/main/resources/core_relational_bigquery/relational/runtime/connection/connectionEqualityTest.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-bigquery/legend-engine-xt-relationalStore-bigquery-pure/src/test/java/org/finos/legend/pure/code/core/Test_Pure_Relational_ConnectionEquality.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-databricks/legend-engine-xt-relationalStore-databricks-pure/src/main/resources/core_relational_databricks.definition.json, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-databricks/legend-engine-xt-relationalStore-databricks-pure/src/main/resources/core_relational_databricks/relational/connection/connectionEqualityTest.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-databricks/legend-engine-xt-relationalStore-databricks-pure/src/main/resources/core_relational_databricks/relational/connection/metamodel.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-databricks/legend-engine-xt-relationalStore-databricks-pure/src/test/java/org/finos/legend/pure/code/core/Test_Pure_Relational_ConnectionEquality.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-dbExtension-archetype/src/main/resources/archetype-resources/legend-engine-xt-relationalStore-__dbtype__-pure/src/main/resources/core_relational___dbtype__.definition.json, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-dbExtension-archetype/src/main/resources/archetype-resources/legend-engine-xt-relationalStore-__dbtype__-pure/src/main/resources/core_relational___dbtype__/relational/connection/connectionEqualityTest.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-dbExtension-archetype/src/main/resources/archetype-resources/legend-engine-xt-relationalStore-__dbtype__-pure/src/test/java/org/finos/legend/pure/code/core/Test_Pure_Relational_ConnectionEquality.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-redshift/legend-engine-xt-relationalStore-redshift-pure/src/main/resources/core_relational_redshift/relational/connection/metamodel.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-pure/src/main/resources/core_relational_snowflake.definition.json, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-pure/src/main/resources/core_relational_snowflake/relational/connection/connectionEqualityTest.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-pure/src/main/resources/core_relational_snowflake/relational/connection/metamodel.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-pure/src/test/java/org/finos/legend/pure/code/core/Test_Pure_Relational_ConnectionEquality.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-spanner/legend-engine-xt-relationalStore-spanner-pure/src/main/resources/core_relational_spanner/relational/runtime/connection/spannerSpecification.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/contract/storeContract.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/extensions/extension.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/runtime/connection/authenticationStrategy.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/runtime/connection/datasourceSpecification.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/testRelationalExtension.pure
Improvement
Connection equality is not currently implemented for for relational database connections.
This has been introduced in the store contract using equality key based checks.
Tests added for athena, databricks, snowflake, bigquery and generic. More tests for spanner, redshift etc to follow
Fixes #
No
=> Connection equality added for relational database connections

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/RelationalExecutionNodeExecutor.java
- Bug Fix
always run drop temp table commands before returning the connection back to the pool in relational graph fetch.
Fixes #
No
=> always run drop temp table commands before closing conn in relational graphFetch

legend-engine-core/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/Milestoning.java, legend-engine-core/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDomainCompilationFromGrammar.java, legend-engine-pure/legend-engine-pure-code/legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/milestoning/MilestonedM2M.pure, legend-engine-pure/legend-engine-pure-code/legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/milestoning/model.pure
- Bug Fix
While processing the milestoned property legend compiler creates a qualified property with an expression for filtering milestoned dates, But if that milestoned property is of [1] multiplicity it does not appends toOne() at the end of function expression which causes issues.
Yes
=> Fix milestoned qualified property generation for toOne multiplicity

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/snowflake/SnowflakeCommands.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-execution/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/TestSnowflakeCommands.java
fix bug while creating temporary tables for snowflake for bit type
- Bug Fix
This PR fixes creating temporary tables in snowflake for bit datatype fields
NA
NA
No
=> fix bug while creating temporary tables in snowflake for bit type

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/RelationalExecutionNodeExecutor.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/TestHelpers.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/LoadFromResultSetAsValueTuplesTempTableStrategy.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/relationalGraphFetch.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/vX_X_X/extension/extension_relational.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/vX_X_X/models/executionPlan_relational.pure
Bug Fix
We don't handle single quotes in values during temp table population in result set temp table strategy.
For example, in `INSERT INTO TEMP_TABLE (NAME) VALUES ('A'1')` we don't escape the single quote in `A'1`, this PR fixes that.
**What's the solution?**
I am introducing a new quoteCharacterReplacement: String[0..1] field in result set temp table strategy which will carry the information for replacing quote character as per db type. This information will be present in execution plan. For now, we only use this temp table strategy with snowflake.
**Testing**
Adding a unit test in engine. Integration testing with Snowflake can be done internally.
Fixes #
Requires protocol cut for enabling it in production
No
=> Handle single quotes in values in result set temp table strategy

legend-engine-core/legend-engine-core-test/legend-engine-test-runner-shared/src/main/java/org/finos/legend/engine/test/runner/shared/JsonNodeComparator.java, legend-engine-core/legend-engine-core-test/legend-engine-testable/src/test/java/org/finos/legend/engine/testable/assertion/TestTestAssertionEvaluator.java
Bug Fix
On service test execution when we compare the JSON, the assert fails when there is an Integral Node and a Non-Integral Node even though the actual node value is exactly same (with no decimal value on the Non-Integral node).
The changeset is to also to compare the actual value and not just node types.
We see this issue for values with exponent notation that round of to proper Integral numbers and this is because we are enabling the Deserialization Feature USE_BIG_DECIMAL_FOR_FLOATS.
We can enable the ACCEPT_FLOAT_AS_INT but USE_BIG_DECIMAL_FOR_FLOATS takes precedence over USE_BIG_DECIMAL_FOR_FLOATS and so its of no use.
One approach is to preProcess before Jackson handles but we decided not to do that as it could significantly increase service test execution time.
=> Compare JSON Values for Integral vs Non-Integral

legend-engine-core/legend-engine-core-executionPlan-execution/legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/domain/date/PureDate.java, legend-engine-core/legend-engine-core-executionPlan-execution/legend-engine-executionPlan-execution/src/test/java/org/finos/legend/engine/plan/execution/dependencies/domain/date/test/TestPureDate.java
Bug Fix
fix pureDate formatting of subseconds of precision > milliseconds
- required when memsql tries to load a csv file with dateTime column into a temp table, where column type is DATETIME (6) and actual data has different number digits in second part eg -2023-07-06 16:56:53.000000123
- only occurs when memsql has strict compatibility checks i.e data_conversion_compatibility_level >= 7.0
Fixes #
=> Fix pure date formatting

legend-engine-pure/legend-engine-pure-code/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/routing/router_routing.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/functions/tests/projection/testSimple.pure
Bug Fix
Fix toOne() in router_routing when processing column specification parameters
NOTE: this is a PR onto the release branch - will raise a PR for master branch separately
=> Fix router to handle dynamic column specifications

legend-engine-xts-sql/legend-engine-xt-sql-grammar/src/main/java/org/finos/legend/engine/language/sql/grammar/from/SQLGrammarParser.java, legend-engine-xts-sql/legend-engine-xt-sql-grammar/src/test/java/org/finos/legend/engine/language/sql/grammar/test/roundtrip/TestSQLRoundTrip.java
Improvement
Allow SQL parser to just parse expressions.  This will allow grammars to contain partial sql expressions like where clauses
Fixes #
=> Allow parsing sql expressions

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-memsql/legend-engine-xt-relationalStore-memsql-execution-tests/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/tests/api/dynamicTestConnections/MemSQLTestContainer.java
Limit the SingleStore max cached blob size to prevent out-of-memory error
=> Limit the SingleStore max cached blob size to prevent out-of-memory error

legend-engine-xts-sql/legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/fromPure.pure, legend-engine-xts-sql/legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/tests/testTranspile.pure
Improvement/Bug Fix
1. further alias issue resolutions
2. handle date strings in arithmetic
=> Legend SQL - assortment of updates

legend-engine-xts-graphQL/legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/fromPure/introspection/fromPure_Introspection.pure, legend-engine-xts-graphQL/legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/transformation/tests/testIntrospectionQuery.pure
Bug Fix
Fixes introspection for pure models with fields on Any type.
Any type is a programming construct but can occur in models / dependency models. This doesn't carry significance in modelling. So, we can filter out fields with any type in introspection.  
Fixes #
In tests it's a delta change in model but not in assert since code is filtering out such fields.
=> GraphQL - Filter out fields with any type during introspection

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-memsql/legend-engine-xt-relationalStore-memsql-pure/src/main/resources/core_relational_memsql/relational/sqlQueryToString/memSQLExtension.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-memsql/legend-engine-xt-relationalStore-memsql-pure/src/main/resources/core_relational_memsql/relational/tests/mapping/sqlFunction/testSqlFunctionsInMapping.pure
Improvement 
dateDiff() now allows DurationUnit YEARS, MONTHS, WEEKS, DAYS, HOURS, MINUTES, SECONDS, MILLISECONDS
We use TIMESTAMPDIFF for all duration units. We were previously using time_to_sec(timediff()) for seconds;
time_to_sec(timediff()) has the TIME limitation. [The TIME object can only express intervals between -838:59:59 and 838:59:59.](https://docs.singlestore.com/cloud/reference/sql-reference/date-and-time-functions/timediff/)
Parameters being passed to generateDateDiffExpressionForMemSQL are changed because timestampdiff does date2 - date1, unlike timediff and datediff that do date1-date2
No
=> Fix MemSQL Dynafunction dateDiff()

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-sybaseiq/legend-engine-xt-relationalStore-sybaseiq-pure/src/main/resources/core_relational_sybaseiq/relational/sqlQueryToString/sybaseIQExtension.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-sybaseiq/legend-engine-xt-relationalStore-sybaseiq-pure/src/main/resources/core_relational_sybaseiq/relational/sqlQueryToString/tests/testSybaseIQIsEmpty.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-sybaseiq/legend-engine-xt-relationalStore-sybaseiq-pure/src/main/resources/core_relational_sybaseiq/relational/sqlQueryToString/tests/testSybaseIQTDSFilter.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbExtension.pure
- Bug Fix
SybaseIQ doesn't support Boolean Literals. This pr includes two changes that are related boolean handling in sybase.
Change in dbExtension (this applies to all the dbs that don't support boolean literals) - 
Scope of this change is dyna functions (that aren't boolean operations) and can take Boolean operations as parameters.
For such functions, we need to explicitly handle the return value of boolean operations. We do that by wrapping the boolean operation parameters in a case statement.
Change in sybaseIqExtension -
The having clause is always expected to return a boolean. We use wrapAsBooleanOperation() on the having string to handle the boolean operations.
Fixes #
No
=> SybaseIQ SQL generation fixes - Handling boolean operations

legend-engine-core/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRuntimeBuilder.java, legend-engine-core/legend-engine-core-test/legend-engine-test-runner-mapping/src/main/java/org/finos/legend/engine/test/runner/mapping/MappingTestRunner.java, legend-engine-core/legend-engine-core-test/legend-engine-test-runner-mapping/src/main/java/org/finos/legend/engine/testable/mapping/extension/MappingTestRunner.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalDatabaseConnectionBuilder.java
Bug fix for broken Service tests
=> Instantiate dummy database if user passes string as element

legend-engine-xts-sql/legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/fromPure.pure, legend-engine-xts-sql/legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/tests/testTranspile.pure
Bug Fix
Fixes issue with order by on extension column
=> Legend SQL - fix orderby on extend column

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/functions/tests/projection/testFilters.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/mapping/innerJoin/testIsolation.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/mapping/innerJoin/testIsolationSetUp.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/mapping/join/advancedRelationalSetUp.pure
- Bug Fix
This PR will fix sqlGeneration for filters without aliases(like 'x' = 'x').
Yes
=> Fix sqlGeneration for filters without aliases

legend-engine-xts-graphQL/legend-engine-xt-graphQL-query/pom.xml, legend-engine-xts-graphQL/legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/cache/GraphQLCacheKey.java, legend-engine-xts-graphQL/legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/cache/GraphQLDevCacheKey.java, legend-engine-xts-graphQL/legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/cache/GraphQLProdCacheKey.java, legend-engine-xts-graphQL/legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/cache/GraphQLProdDataspaceCacheKey.java, legend-engine-xts-graphQL/legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/cache/GraphQLProdMappingRuntimeCacheKey.java, legend-engine-xts-graphQL/legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/execute/GraphQLExecute.java, legend-engine-xts-graphQL/legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/execute/directives/DefaultGraphQLDirectiveExtension.java, legend-engine-xts-graphQL/legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/execute/directives/IGraphQLDirectiveExtension.java, legend-engine-xts-graphQL/legend-engine-xt-graphQL-query/src/test/java/org/finos/legend/engine/query/graphQL/api/test/TestGraphQLAPI.java, legend-engine-xts-graphQL/legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/Project1_Workspace1.pure, legend-engine-xts-graphQL/legend-engine-xt-graphQL-relational-extension/src/main/java/org/finos/legend/engine/query/graphQL/extension/relational/directives/TotalCountDirective.java
Improvement
Introducing GraphQL APIs which take dataspace path as input and picks up mapping/runtime from defaul execution context.
Fixes #
=> Graphql Dataspace API

legend-engine-core/legend-engine-core-language-pure/legend-engine-language-pure-modelManager-sdlc/src/test/java/org/finos/legend/engine/language/pure/modelManager/sdlc/TestSDLCLoader.java, legend-engine-core/legend-engine-core-language-pure/legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/PureClientVersions.java, legend-engine-core/legend-engine-core-language-pure/legend-engine-protocol-pure/src/test/java/org/finos/legend/engine/protocol/test/TestProtocolUpdates.java
increasing protocol version for production
=> change production protocol to v1_33.0

legend-engine-xts-mastery/legend-engine-xt-mastery-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/MasteryParserGrammar.g4, legend-engine-xts-mastery/legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/compiler/toPureGraph/HelperMasterRecordDefinitionBuilder.java, legend-engine-xts-mastery/legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/from/MasteryParseTreeWalker.java, legend-engine-xts-mastery/legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/to/HelperMasteryGrammarComposer.java, legend-engine-xts-mastery/legend-engine-xt-mastery-grammar/src/test/java/org/finos/legend/engine/language/pure/dsl/mastery/compiler/test/TestMasteryCompilationFromGrammar.java
This Pull Request introduces enhancements to the Precedence Rules Specification within the Mastery module. The key improvements include:
1. Support for Compound Filter Expressions:
> - Previous Capability: The system could interpret and capture simple path filters following the structure Widget{$.widgetId == 'value'}.
> - New Capability: It now accommodates compound expressions, allowing for more complex filter definitions. For example, a filter can now include combined conditions such as Widget{$.widgetId == '1234' && $.type == 'woggle'}.
2. Enum Path Specification:
> - Issue: A previously identified bug prevented the system from processing path specifications that pointed to an Enum type. This limitation restricted the rules to only accept paths leading to a Class or Primitive type.
> - …
=> Extend Precedence Rules Specification to Support Compound Filters and Enums

legend-engine-config/legend-engine-extensions-collection-generation/pom.xml, legend-engine-config/legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java
=> add missing extensions in legend extension collections

legend-engine-xts-mastery/legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/to/HelperMasteryGrammarComposer.java, legend-engine-xts-mastery/legend-engine-xt-mastery-grammar/src/test/java/org/finos/legend/engine/language/pure/dsl/mastery/compiler/test/TestMasteryCompilationFromGrammar.java, legend-engine-xts-mastery/legend-engine-xt-mastery-grammar/src/test/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/test/TestMasteryGrammarRoundtrip.java
Bug Fix
When there are precedence rules defined on the master record definition, if none of them are source precedence rules then an extra comma is being added by the composer.
=> Fix mastery composer - extra comma being added when no source precedence rules

legend-engine-xts-graphQL/legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/bindingCommon.pure, legend-engine-xts-graphQL/legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/fromPure/sdl/tests/simpleTest.pure, legend-engine-xts-graphQL/legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/toPure/sdl/tests/simpleTest.pure
=> Update GraphQL extends directive to include class argument, include StrictDate in GraphQL SDL tests

legend-engine-pure/legend-engine-pure-code/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/tds/tds.pure, legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light/pom.xml, legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light/src/main/java/org/finos/legend/engine/ide/PureIDELight.java, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-V7-pure-metamodel/src/main/resources/core_elasticsearch_seven_metamodel/functions/pure_to_elasticsearch.pure, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/java/org/finos/legend/engine/plan/execution/stores/elasticsearch/test/shared/ElasticsearchCommands.java, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test_aggregation.pure, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test_project.pure, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test_project_boolean.pure, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test_project_date.pure, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test_project_float.pure, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test_project_integer.pure, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test_project_keyword.pure, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test_project_text.pure
=> ES support for distinct and restrict functions

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/RelationalExecutionNodeExecutor.java
Bug fix
Fixes NPE in cross store graph fetch
Fixes #
Yes, bug fix
=> fix: use parent temp table strategy in cross store node

legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-V7-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/elasticsearch/v7/result/ExecutionRequestVisitor.java, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-V7-pure-metamodel/src/main/resources/core_elasticsearch_seven_metamodel/functions/pure_to_elasticsearch.pure, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-V7-pure-metamodel/src/main/resources/core_elasticsearch_seven_metamodel/functions/tds_utils.pure, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test.pure, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test_aggregation.pure, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test_filter_date.pure
Improvement
When grouping by fields that are bucketing using if/else, is more efficient to use filters bucket aggregation rather than scripting a runtime field to group by after.  This will avoid the scripting, which can be resource intensive.   
Fixes #
=> Improve efficiency on some elasticsearch queries grouping by computed if/else fields

legend-engine-pure/legend-engine-pure-code/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/tds/tds.pure, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-V7-executionPlan/pom.xml, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-V7-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/elasticsearch/v7/result/ElasticsearchTDSResultHelper.java, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-V7-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/elasticsearch/v7/result/ExecutionRequestVisitor.java, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-V7-protocol/src/main/java/org/finos/legend/engine/protocol/store/elasticsearch/v7/metamodel/tds/AbstractResultPathVisitor.java, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-V7-pure-metamodel/src/main/resources/core_elasticsearch_seven_metamodel/functions/pure_to_elasticsearch.pure, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-V7-pure-metamodel/src/main/resources/core_elasticsearch_seven_metamodel/functions/specification_utils.pure, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-V7-pure-metamodel/src/main/resources/core_elasticsearch_seven_metamodel/functions/tds_utils.pure, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-V7-pure-metamodel/src/main/resources/core_elasticsearch_seven_metamodel/protocol/v1_33_0/serialization.pure, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-V7-pure-metamodel/src/main/resources/core_elasticsearch_seven_metamodel/protocol/vX_X_X/serialization.pure, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test.pure, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test_aggregation.pure, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test_aggregation_count.pure, legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test_sort.pure
=> ES support for count(*) and bugfixes on sorting group by results

legend-engine-xts-graphQL/legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/bindingCommon.pure, legend-engine-xts-graphQL/legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/fromPure/sdl/fromPure_sdl.pure, legend-engine-xts-graphQL/legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/fromPure/sdl/tests/simpleTest.pure, legend-engine-xts-graphQL/legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/toPure/introspection/toPure_introspection.pure, legend-engine-xts-graphQL/legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/toPure/sdl/tests/simpleTest.pure, legend-engine-xts-graphQL/legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/toPure/sdl/toPure_sdl.pure, legend-engine-xts-graphQL/legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/deprecated/generation.pure
Support custom scalars for Pure Integer type during GraphQL SDL generation
=> Support custom scalars for Pure Integer type during GraphQL SDL generation

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-postgres/legend-engine-xt-relationalStore-postgres-execution-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/tests/api/dynamicTestConnections/PostgresTestContainers.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-postgres/legend-engine-xt-relationalStore-postgres-execution-tests/src/test/resources/postgres/init.sql, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-postgres/legend-engine-xt-relationalStore-postgres-pure/src/main/resources/core_relational_postgres/relational/sqlQueryToString/postgresExtension.pure
Improvement
Add dyna function support for functions - matches, sha1, sha256 for Postgres DB
References:
1. RegExp matching: https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-POSIX-REGEXP
2. Hashing: https://www.postgresql.org/docs/current/pgcrypto.html
=> Improve Postgres SQL support - RegExp matching, Hashing

legend-engine-core/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PureModel.java, legend-engine-core/legend-engine-core-shared/legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/operational/logs/LogInfo.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/RelationalCompilerExtension.java
- Improvement
- Bug Fix
Fix and improve compilation timing and logging in PureModel.
Both the event types and durations had become inaccurate. In particular, significant durations were being missed. This change brings the even types up to date with the current compilation steps and includes the entire time spent in compilation. Additionally, precision is improved by using nanoseconds rather than milliseconds.
Also, the opentracing APIs being used were deprecated. This change updates them to non-deprecated APIs.
No
=> Improve compilation timing and logging

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/RelationalExecutionNodeExecutor.java
- Bug Fix
Fixes Graphfetch executions in Snowflake when the data has a special character(\)
In graphfetch executions, we create temp tables using insert statements for Snowflake. 
The tuples for insert statements are created from the resultset. They go through the ResultSetNormalizer in FreeMarkerExecutor, so we shouldn't be doing it again in the graphfetch normalizer. (The ResultSetNormalizer.normalizeToSql() isn't idempotent)
Fixes # 
No
=> Upgrade resultset normalizer - temp table creation for snowflake in GraphFetch

legend-engine-xts-mongodb/legend-engine-xt-nonrelationalStore-mongodb-executionPlan-test/src/main/resources/core_mongodb_execution_test/mongodb_execution_tests.pure, legend-engine-xts-mongodb/legend-engine-xt-nonrelationalStore-mongodb-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/mongodb/plugin/MongoDBExecutionNodeExecutor.java, legend-engine-xts-mongodb/legend-engine-xt-nonrelationalStore-mongodb-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/visitors/BaseTypeValueVisitorImpl.java, legend-engine-xts-mongodb/legend-engine-xt-nonrelationalStore-mongodb-pure/src/main/resources/core_nonrelational_mongodb/metamodel/mongodbStore.pure, legend-engine-xts-mongodb/legend-engine-xt-nonrelationalStore-mongodb-pure/src/main/resources/core_nonrelational_mongodb/pureToDatabaseCommand/pureToDatabaseCommand.pure
Improvement
Enables MongoDB plan generation/execution to work with parameters/variables
- Add VariableTypeValue to represent a variable placeholder
- Use existing FreeMarker processor to replace plan variable placeholders during execution
- Handle VariableExpressions and remove cast to InstanceValue within equals/comparison expression processors
=> Support variable expressions in MongoDB plan generation

legend-engine-core/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperModelBuilder.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalBuilder.java
Bug Fix
Clean up HelperRelationalBuilder and HelperModelBuilder, principally to remove unnecessary casts to generated "_Impl" classes. The unnecessary casts can lead to exceptions at runtime if the instance is of a different type (such as a "_LazyImpl" class).
No
=> Clean up HelperRelationalBuilder and HelperModelBuilder

legend-engine-xts-changetoken/legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastCustomArrayEmbeddedTest.java, legend-engine-xts-changetoken/legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastCustomNullKeywordTest.java, legend-engine-xts-changetoken/legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastCustomNullStringTest.java, legend-engine-xts-changetoken/legend-engine-xt-changetoken-pure/src/main/resources/core_pure_changetoken/cast_generation_util.pure, legend-engine-xts-changetoken/legend-engine-xt-changetoken-pure/src/main/resources/core_pure_changetoken/cast_generation_util_deprecated.pure
Bug Fix
If change-tokens customer is still using deprecated format (with JSON serialized as string) it should provide full functionality. Fix null handling, etc.
cast_generation_util_deprecated will be removed as soon as deprecated format is not needed anymore.
No
=> Handle null for optional field

legend-engine-core/legend-engine-core-shared/legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/url/EngineUrlStreamHandlerFactory.java
TreeMap implementation has been changed in Java 15 to optimize some functions. As a result running embedded service executions concurrently in the same JVM can now throw concurrent modification exceptions when running on JVM 15 onwards. 
Note that TreeMap has never been threadsafe - just that exceptions are now thrown on Java 15 onwards. 
Switching to a threadsafe map implementation to avoid exceptions being thrown for concurrent executions of the same service on the same JVM. 
References:
https://www.oracle.com/java/technologies/javase/15-relnote-issues.html
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8227666
https://hg.openjdk.org/jdk/jdk/rev/65b345254ca3
=> Make EngineUrlStreamHandlerFactory safe wrt to changes in JDK15+

legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/api/ApplicationQuery.java, legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/api/QueryStoreManager.java, legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/model/Query.java, legend-engine-application-query/src/test/java/org/finos/legend/engine/application/query/api/TestQueryStoreManager.java
improvement
Introduce a new API to update query version and update query protocol to record originalVersionId
Fixes #
=> Introduce a new API to update provided query fields and update query protocol to record originalVersionId

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-memsql/legend-engine-xt-relationalStore-memsql-pure/src/main/resources/core_relational_memsql/relational/sqlQueryToString/memSQLExtension.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/SnowflakeConnectionExtension.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/specifications/SnowflakeDataSourceSpecification.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/specifications/keys/SnowflakeDataSourceSpecificationKey.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-grammar/pom.xml, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/SnowflakeLexerGrammar.g4, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/SnowflakeParserGrammar.g4, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/SnowflakeCompilerExtension.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/SnowflakeGrammarParserExtension.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/SnowflakeGrammarComposerExtension.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestSnowflakeConnectionGrammarCompiler.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestSnowflakeConnectionGrammarRoundtrip.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/specification/SnowflakeDatasourceSpecification.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-pure/pom.xml, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-pure/src/main/resources/core_relational_snowflake/relational/connection/metamodel.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-pure/src/main/resources/core_relational_snowflake/relational/executionPlan/tests/executionPlanTestSnowflake.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-pure/src/main/resources/core_relational_snowflake/relational/protocols/pure/vX_X_X/extension/extension_snowflake.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-pure/src/main/resources/core_relational_snowflake/relational/protocols/pure/vX_X_X/extension/metamodel_conection.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-pure/src/main/resources/core_relational_snowflake/relational/sqlQueryToString/snowflakeExtension.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-sparksql/legend-engine-xt-relationalStore-sparksql-pure/src/main/resources/core_relational_sparksql/relational/sqlQueryToString/sparkSQLExtension.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-sybaseiq/legend-engine-xt-relationalStore-sybaseiq-pure/src/main/resources/core_relational_sybaseiq/relational/sqlQueryToString/sybaseIQExtension.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/relationalGraphFetch.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/postprocessor/defaultPostProcessor/processInOperation.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbExtension.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/db2/db2Extension.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/h2/h2Extension1_4_200.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/h2/h2Extension2_1_214.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/extensionDefaults.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/testSuite/testTempTableSqlStatements.pure
- Improvement
Allow users to specify the DB and schema where temp tables can be created in Snowflake. Add two optional properties - tempTableDb and tempTableSchema - to the Snowflake Datasource specification. If these aren't specified, we fall back to the defaults mentioned in [the documentation](https://github.com/finos/legend-engine/blob/master/docs/store/extensions/Relational/Databases/snowflake/README.md)
This currently can only be used for the GraphFetch Flow
Fixes #
This needs a protocol release
Yes
=> Add Optional Fields for Specifying Database and Schema Names for Temporary Tables in Snowflake

legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/executionPlan_generation.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/externalFormat/routing.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/platform/routing.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/printer/printer.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/router_main.pure, legend-engine-xts-java/legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/store/m2m/m2mLegendJavaPlatformBindingExtension.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/router/tests/testRouting1.pure
Improvement
Fix Routing of MultiExpressions involving platform function
Fixes #
=> Fix Routing of MultiExpressions involving platform function

legend-engine-xts-analytics/legend-engine-xts-analytics-lineage/legend-engine-xt-analytics-lineage-pure/src/main/resources/core_analytics_lineage/fullAnalytics.pure, legend-engine-xts-analytics/legend-engine-xts-analytics-lineage/legend-engine-xt-analytics-lineage-pure/src/main/resources/core_analytics_lineage/tests/lineageTestModels.pure
Bug fix 
db lineage computation was previously exploding for some cases as it was processing table creation for the same properties several times. 
Fixes #
No, but it allows users to experience actually being able to register their services and without much significant latency
=> Improve dblineage computation

legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphExtension.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/tests/sourceTreeCalc/testSourceTreeCalc.pure
- Bug Fix
Fixes a bug in sourcetree calculation when the source of a mapping is wrapped in a new instance of a wrapper class before being passed to a property mapping. Source tree calculation assumes that the owner of the mapping (ie the source) will be the root of any property access paths; this PR fixes that assumption
=> SourceTreeCalc: handle owner class nested in property tree

legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light-http-server/pom.xml, legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light-http-server/src/main/java/org/finos/legend/engine/ide/PureIDEServer.java, legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light-http-server/src/main/java/org/finos/legend/engine/ide/api/PureRuntimeOptions.java, legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light-http-server/src/main/java/org/finos/legend/engine/ide/session/PureSession.java
Allow dynamic settings for Pure runtime options such such as execution plan debugging options
=> Pure IDE Light: Add support for Pure runtime options

legend-engine-core/legend-engine-core-base/legend-engine-core-executionPlan-execution/legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/helpers/freemarker/FreeMarkerExecutor.java, legend-engine-core/legend-engine-core-base/legend-engine-core-executionPlan-execution/legend-engine-executionPlan-execution/src/test/java/org/finos/legend/engine/plan/execution/nodes/helpers/freemarker/TestFreeMarkerExecutor.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/full/functions/in/TestPlanExecutionForIn.java
Earlier, we had a flag that we could set to true and rollback to old code flow if anything broke with the new flow. Now we are removing this flag and keeping 1 flow after a week in 4.40.0 release 
Fixes #2564 
No
=> Remove overrideFlag from freemarker processing 

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalDatabaseConnectionBuilder.java
We need to catch the exceptions to keep it backward compatible
=> revert HelperRelationalDatabaseConnectionBuilder.java to previous version

legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/api/QueryStoreManager.java, legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/model/Query.java, legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/model/QueryDataSpaceExecutionContext.java, legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/model/QueryExecutionContext.java, legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/model/QueryExplicitExecutionContext.java, legend-engine-application-query/src/test/java/org/finos/legend/engine/application/query/api/TestQueryStoreManager.java, legend-engine-application-query/src/test/java/org/finos/legend/engine/application/query/utils/TestQuerySerialization.java
Bug Fix/Enhancement. 
Deprecates direct proeprties "runtime" and "mapping" as some queries will not provide these directly but implicit resolve them through another execution source.
This include dataSpace with has an executionKey that points to mapping/runtime. 
This fixes some opening bugs with dataSpace
- query does not persist execution key causing failures if user changes runtime/mapping
- if more than one execution key, query will always default to default exec context even if user did not save the query with that. 
- further allows us saving other forms of sources -> Service ? InLine (for usage of from())
Further improvements:
- We can migrate all queries to use new QueryExecutionContext class. Will be in separate PR
Fixes #
=> add execution context to query

legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/metaExtension.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/platform/executionPlan/executionPlan_generation.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/printer/printer.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/router_main.pure, legend-engine-core/legend-engine-core-query-pure-http-api/pom.xml, legend-engine-core/legend-engine-core-query-pure-http-api/src/test/java/org/finos/legend/engine/query/pure/api/test/inMemory/TestExecuteFunctionExecutionPlan.java, legend-engine-xts-java/legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/generation/expressionGeneration.pure, legend-engine-xts-java/legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/store/m2m/m2mLegendJavaPlatformBindingExtension.pure
Improvement
Improve handling of PlanVarPlaceHolders in platform executions
Changes:
1. Remove RoutedVariablePlaceHolder concept in routing as this class does not have any type information (which is required when generating Java and other flows). Create PlanVarPlaceHolder instances instead
2. For a platform node, required variable inputs should include PlanVarPlaceHolders in addition to VariableExpressions (sometimes, VariableExpressions are resolved to PlanVarPlaceHolders during routing) 
3. During routing, when VariableExpression resolves to PlanVarPlaceHolder, create InstanceValue with the correct type and multiplicity (which is present in PlanVarPlaceHolder)
4. Support Java generation for PlanVarPlaceHolders just like VariableExpressions
Fixes #
=> Improve handling of PlanVarPlaceHolders in platform executions

legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/simpleObject.pure, legend-engine-xts-java/legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/generation/conventions.pure, legend-engine-xts-java/legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/generation/expressionGeneration.pure, legend-engine-xts-java/legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/metamodel_factories.pure
M2M execution relies on source fetch tree computation to generate the list of Pure classes to generate Java code for. 
However, if a function is passed an empty argument then there is no property access and hence nothing is present in the source tree informing the platform that Java code should be generated for the corresponding parameter type. As a result the compilation of Java code present in the execution plan fails due to missing classes. 
This change fixes that by processing the parameters and generating code for parameter types that are not part of the Java standard library or engine conventions library.  If we happen to have already generated code for the parameter type earlier in the plan generation (e.g the class is mentioned in the source fetch tree) then the Java generation …
=> Java Generation: Generate classes for concrete function parameters 

legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperMappingGrammarComposer.java, legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/PureGrammarComposerUtility.java, legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestDomainGrammarRoundtrip.java, legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestLambdaRoundtrip.java, legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestMappingGrammarRoundtrip.java, legend-engine-xts-data-space/legend-engine-xt-data-space-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/DataSpaceGrammarComposerExtension.java
Bug Fix
When identifiers are using in the form My::Enum.123_ABC, it fail as the `.` token seems to confuse ANTLR and cannot be parsed.  This forces any identifier that starts with numbers to be quoted to allow ANTLR to understand the limit of each token.
Fixes #
=> Identifiers that start with numbers should be quoted

legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/lineage/scanProject.pure, legend-engine-xts-analytics/legend-engine-xts-analytics-lineage/legend-engine-xt-analytics-lineage-pure/src/main/resources/core_analytics_lineage/tests/scanProjectTests.pure
Bug Fix
This change fixes the calculation for report lineage. Queries which only have groupBys in their lambda with no project used to fail report lineage generation, this change should fix this behaviour.
No
=> fixing calculation of report linage for queries with only groupBy

legend-engine-xts-graphQL/legend-engine-xt-graphQL-http-api/src/test/java/org/finos/legend/engine/query/graphQL/api/test/TestGraphQLFileGeneration.java, legend-engine-xts-graphQL/legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/toPure/introspection/tests/travel/testTravelX.pure
Bug Fix
Set line separator to \n when reading expected result from file in testTravelX.pure so that the test works regardless of the underlying OS. Previously, the test would fail when run on Windows because the default line separator is \r\n.
No
=> Set line separator to \n when using readFile to read expected results for tests

legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar-http-api/src/main/java/org/finos/legend/engine/language/pure/grammar/api/grammarToJson/GrammarToJson.java, legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar-http-api/src/main/java/org/finos/legend/engine/language/pure/grammar/api/jsonToGrammar/JsonToGrammar.java
Bug Fix
Deprecate some methods that are present only for backward compatibility.
No
=> Deprecate backward compatibility methods in GrammarToJson and JsonToGrammar

legend-engine-xts-data-space/legend-engine-xt-data-space-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/DataSpaceGrammarComposerExtension.java
fix failing to generate grammar if there is no execution context key in dataspace template query
Bug Fix
fix failing to generate grammar if there is no execution context key in dataspace template query
Fixes #
=> fix failing to generate grammar if there is no execution context key in dataspace template query

legend-engine-xts-java/legend-engine-xt-javaPlatformBinding-PCT/src/test/java/org/finos/legend/engine/pure/code/core/java/binding/Test_JAVA_RelationFunction_PCT.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-duckdb/legend-engine-xt-relationalStore-duckdb-PCT/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/duckdb/pct/Test_Relational_DuckDB_RelationFunctions_PCT.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-h2/legend-engine-xt-relationalStore-h2-PCT/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/h2/pct/Test_Relational_H2_RelationFunctions_PCT.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-postgres/legend-engine-xt-relationalStore-postgres-PCT/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/postgres/pct/Test_Relational_Postgres_RelationFunctions_PCT.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-PCT/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/snowflake/pct/Test_Relational_Snowflake_RelationFunctions_PCT.java, pom.xml
following the changes in https://github.com/finos/legend-pure/pull/830
the problem is `pureToSQL` is not properly handling column names with special characters like spaces (therefore, required to be quoted). This is a much more involved change so for now we just add PCT test failure assertion
=> add assertion failure for PCT test failing for columns with space

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/DataSourceStatistics.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/state/ConnectionStateManager.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan-connection/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/state/TestConnectionManagement.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan-connection/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/state/TestConnectionStateManager.java
Bug Fix
When the connection pool is created for the first time, if the pool data-source cannot be built due to some exception, the incomplete pool(with null data source) should not be cached in the state manager and should get evicted immediately
The house keeping task should also be able to evict pools having non zero connection error statistics if no active connections are made from it during the specified duration
Fixes #
=> Fix connection eviction

legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/external/format/json/modelSerialization.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/external/format/json/tests/testToJson.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/external/format/json/toJSON.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/constraints/constraintsModelDiagram.pure
Bug
Fix toJSON for constraints. Previously, they were transformed to JSON as PackageableElements using their package path. But this is inappropriate since they do not have a package path. Now they have a substantive transformation.
=> Fix toJSON for constraints

legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/chain.pure, legend-engine-xts-analytics/legend-engine-xts-analytics-lineage/legend-engine-xt-analytics-lineage-pure/pom.xml, legend-engine-xts-analytics/legend-engine-xts-analytics-lineage/legend-engine-xt-analytics-lineage-pure/src/main/resources/core_analytics_lineage/fullAnalytics.pure, legend-engine-xts-analytics/legend-engine-xts-analytics-lineage/legend-engine-xt-analytics-lineage-pure/src/main/resources/core_analytics_lineage/tests/m2mAnalytics.pure
Fixes to handle M2M mappings and better error message for unsupported property mapping types. 
This will allow M2M mappings to be processed but lineage will not be fully complete for graphfetch queries. More work is needed here
=> Fixes to handle M2M mappings

legend-engine-xts-dataquality/legend-engine-xt-dataquality-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/DataQualityCompilerExtension.java, legend-engine-xts-dataquality/legend-engine-xt-dataquality-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/TestDataQualityCompilationFromGrammar.java, legend-engine-xts-dataquality/legend-engine-xt-dataquality-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/DataQualityParserGrammar.g4, legend-engine-xts-dataquality/legend-engine-xt-dataquality-grammar/src/main/java/org/finos/legend/engine/language/dataquality/grammar/from/DataQualityTreeWalker.java, legend-engine-xts-dataquality/legend-engine-xt-dataquality-grammar/src/test/java/org/finos/legend/engine/language/dataquality/grammar/from/TestDataQualityParsing.java, legend-engine-xts-dataquality/legend-engine-xt-dataquality-pure-test/src/main/resources/core_dataquality_test/dataquality_test.pure, legend-engine-xts-dataquality/legend-engine-xt-dataquality-pure/src/main/resources/core_dataquality/generation/dataquality.pure, legend-engine-xts-dataquality/legend-engine-xt-dataquality-pure/src/main/resources/core_dataquality/metamodel/metamodel.pure
- Improvement/Bug fix
1. Handles only structural constraints selection, this was supported in spec but was failing in lambda generation.
```
Person{
age
}
```
2. Handles only model constraint selection. this was failing in parsing which is now handled.
```
Person<isOfLegalAge>{
}
```
3. Throws exception when an empty tree is found. This is added as a constraint on the dataquality tree metamodel class.
```
Person{
}
```
No
=> Handle edge cases in dataquality fetch trees

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/functions/tests/testSliceTakeLimitDrop.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
- Bug Fix
This will address the improper query composition issue when user uses the table reference with limit clause and filter condition in sequence. This change will create proper sub query for limit clause first and then it will apply where clause. 
No
=> Fix SQL generation for composition of filter, limit functions in Relation API

legend-engine-xts-persistence/legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-duckdb/pom.xml
Persistence: keep duckdb versions consistent to avoid flakey test failures in the persistence duckdb module. 
(Error message is the same as documented here https://duckdb.org/docs/internals/storage.html#error-message-when-opening-an-incompatible-database-file)
Looks like https://github.com/finos/legend-engine/pull/2956 inadvertently added back the old version of duckdb that was updated in https://github.com/finos/legend-engine/pull/2968
=> Persistence: keep duckdb versions consistent

legend-engine-config/legend-engine-repl/legend-engine-repl-client/src/main/java/org/finos/legend/engine/repl/client/Client.java, legend-engine-config/legend-engine-repl/legend-engine-repl-data-cube/src/main/java/org/finos/legend/engine/repl/dataCube/server/REPLServer.java
=> datacube: allow passing in URL template

legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlanFeature.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan_generation.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/test/testExecutionPlanFeatureFlag.pure
Add equality keys to ExecutionOptionContext to ensure routing identities cross store routing correctly based on this exec ctx
Fixes #
=> Add equality keys to ExecutionOptionContext

legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-functions-relation-pure/src/main/resources/core_functions_relation/relation/functions/transformation/distinct.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-runtime-java-extension-compiled-functions-relation/src/main/java/org/finos/legend/pure/runtime/java/extension/external/relation/compiled/RelationExtensionCompiled.java, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-runtime-java-extension-compiled-functions-relation/src/main/java/org/finos/legend/pure/runtime/java/extension/external/relation/compiled/RelationNativeImplementation.java, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-runtime-java-extension-compiled-functions-relation/src/main/java/org/finos/legend/pure/runtime/java/extension/external/relation/compiled/natives/DistinctAll.java, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-runtime-java-extension-interpreted-functions-relation/src/main/java/org/finos/legend/pure/runtime/java/extension/external/relation/interpreted/RelationExtensionInterpreted.java, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-runtime-java-extension-interpreted-functions-relation/src/main/java/org/finos/legend/pure/runtime/java/extension/external/relation/interpreted/natives/Distinct.java, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-runtime-java-extension-shared-functions-relation/src/main/java/org/finos/legend/pure/runtime/java/extension/external/relation/shared/TestTDS.java, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-runtime-java-extension-shared-functions-relation/src/test/java/org/finos/legend/pure/runtime/java/extension/relation/TestTestTDS.java, legend-engine-xts-java/legend-engine-xt-javaPlatformBinding-PCT/src/test/java/org/finos/legend/engine/pure/code/core/java/binding/Test_JAVA_RelationFunction_PCT.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
make sure `relation:distinct` works like SQL DISTINCT where the specified columns will be the only columns remain after execution
=> relation: fix distinct()

legend-engine-config/legend-engine-repl/README.md, legend-engine-config/legend-engine-repl/legend-engine-repl-app-assembly/assemble/assembly.xml, legend-engine-config/legend-engine-repl/legend-engine-repl-app-assembly/assemble/pom.xml, legend-engine-config/legend-engine-repl/legend-engine-repl-app-assembly/assemble/repl.bat, legend-engine-config/legend-engine-repl/legend-engine-repl-app-assembly/assemble/repl.sh, legend-engine-config/legend-engine-repl/legend-engine-repl-app-assembly/pom.xml, legend-engine-config/legend-engine-repl/legend-engine-repl-client/pom.xml, legend-engine-config/legend-engine-repl/legend-engine-repl-data-cube/pom.xml, legend-engine-config/legend-engine-repl/pom.xml, legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light-http-server/pom.xml, pom.xml
Improvement
This introduce a new assembly module for REPL that create scripts to run all the flavors of REPL: default, relational, datacube.
This is the first step to unify how to access and run the REPLs, and the next step is to have a single main, and allow users to select the features they want, reducing duplication and confusion on what REPL to use.
=> Package all flavors of REPL the same way for easy access and debugging

legend-engine-xts-data-space/legend-engine-xt-data-space-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/DataSpaceCompilerExtension.java, legend-engine-xts-dataquality/legend-engine-xt-dataquality-compiler/pom.xml, legend-engine-xts-dataquality/legend-engine-xt-dataquality-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/DataQualityCompilerExtension.java, legend-engine-xts-dataquality/legend-engine-xt-dataquality-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/TestDataQualityCompilationFromGrammar.java, legend-engine-xts-dataquality/legend-engine-xt-dataquality-generation/src/main/java/org/finos/legend/engine/generation/dataquality/DataQualityLambdaGenerator.java
- Bug Fix
The data space compiler extension sets the executables and diagrams as null in the dataspace metamodel when they are null in the protocol. Since they have [*] multiplicity, the validate method of the metamodel expects them to be non-null or empty. This bug leads to NPEs when validate method is called on the dataspace element.
No
=> fix null executables diagrams in dataspace metamodel

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/functions/tests/testConcatenate.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
- Bug Fix
This PR will remove unwanted 'having' clause in 'UNINON ALL' sql query generated using concatenation operation. This was only happening when 'filter' is used post 'groupBy' clause in concatenation.
NA
=> Concatenate grouping filter fix

legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-functions-relation-pure/src/main/resources/core_functions_relation/relation/functions/transformation/extend.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-functions-relation-pure/src/main/resources/core_functions_relation/relation/functions/transformation/groupBy.pure, pom.xml
This will allow relation operations like `groupBy` to use `max()`, `min()`, `uniqueValueOnly`, etc.
Relies on https://github.com/finos/legend-pure/pull/856
=> relation: allow nullable aggregation functions in aggColSpec

legend-engine-xts-analytics/legend-engine-xts-analytics-lineage/legend-engine-xt-analytics-lineage-pure/src/main/resources/core_analytics_lineage/tests/lineageTests.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/contract/storeContract.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/lineage/scanRelations/scanRelations.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/relationalMappingExecution.pure
=> Add support for multi cluster query to lineage

legend-engine-xts-sql/legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/ExecutionDispatcher.java, legend-engine-xts-sql/legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/Messages.java, legend-engine-xts-sql/legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/PostgresServerException.java, legend-engine-xts-sql/legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/PostgresWireProtocol.java, legend-engine-xts-sql/legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/ResultSetReceiver.java, legend-engine-xts-sql/legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/Session.java, legend-engine-xts-sql/legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/handler/PostgresPreparedStatement.java, legend-engine-xts-sql/legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/handler/empty/EmptyPreparedStatement.java, legend-engine-xts-sql/legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/handler/jdbc/JDBCSessionFactory.java, legend-engine-xts-sql/legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/handler/legend/LegendPreparedStatement.java, legend-engine-xts-sql/legend-engine-xt-sql-postgres-server/src/test/java/org/finos/legend/engine/postgres/PostgresServerAsyncTest.java, legend-engine-xts-sql/legend-engine-xt-sql-postgres-server/src/test/java/org/finos/legend/engine/postgres/PostgresServerTest.java
Improvement
This PR allows users to set fetch size so that entire result set is not loaded to memory
- The `BEGIN` command is silently ignored since it is not applicable for the read only use case of Legend SQL
- No impact for clients which do not invoke `setFetchSize`
=> [Legend SQL] Support fetch size

legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/chain.pure, legend-engine-xts-analytics/legend-engine-xts-analytics-lineage/legend-engine-xt-analytics-lineage-pure/pom.xml, legend-engine-xts-analytics/legend-engine-xts-analytics-lineage/legend-engine-xt-analytics-lineage-pure/src/main/resources/core_analytics_lineage/fullAnalytics.pure, legend-engine-xts-analytics/legend-engine-xts-analytics-lineage/legend-engine-xt-analytics-lineage-pure/src/main/resources/core_analytics_lineage/tests/m2mAnalytics.pure
Initial support graphFetch M2M queries in lineage computation - currently only computes target lineage for mappings. 
Fix some casts to handle unsupported mapping types
=> Initial M2M Graphfetch support in lineage computation

legend-engine-xts-sql/legend-engine-xt-sql-postgres-server/pom.xml, legend-engine-xts-sql/legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/PostgresWireProtocol.java, legend-engine-xts-sql/legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/Session.java, legend-engine-xts-sql/legend-engine-xt-sql-postgres-server/src/test/java/org/finos/legend/engine/postgres/PostgresServerTest.java
So that subsequent queries are successful
Bug Fix
Currently if one query fails in a session, all subsequent queries also give same error message even before they get executed.
This PR isolates each query so that queries are run irrespective of previous failures.
No
=> [Legend SQL] Handle failure in session

legend-engine-xts-persistence/legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/main/java/org/finos/legend/engine/persistence/components/relational/snowflake/sqldom/schemaops/values/StagedFilesField.java, legend-engine-xts-persistence/legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/BulkLoadTest.java, legend-engine-xts-persistence/legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/test/java/org/finos/legend/engine/persistence/components/relational/snowflake/sqldom/schemaops/CopyStatementTest.java
- Bug Fix
Add quoting around element path for bulk load (snowflake) so that parquet files can load columns which start with numbers
Fixes #
=> Persistence Component: Add quoting around element path for bulk load (snowflake)

legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/pom.xml, legend-engine-core/legend-engine-core-shared/legend-engine-shared-core/pom.xml, legend-engine-xts-analytics/legend-engine-xts-analytics-lineage/legend-engine-xt-analytics-lineage-pure/pom.xml, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-PCT/legend-engine-pure-runtime-java-extension-compiled-functions-relationalStore-PCT/pom.xml, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-PCT/legend-engine-pure-runtime-java-extension-shared-functions-relationalStore-PCT/pom.xml, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-duckdb/legend-engine-xt-relationalStore-duckdb-PCT/pom.xml, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-postgres/legend-engine-xt-relationalStore-postgres-PCT/pom.xml, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-PCT/pom.xml, pom.xml
Clean up dependency warnings in poms - remove duplicate dependencies mainly
=> Clean up dependency warnings in poms

legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/pom.xml, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/test/java/org/finos/legend/engine/pure/code/core/TestCoreCompiledStateIntegrity.java, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-json/legend-engine-pure-functions-json-pure/src/test/java/org/finos/legend/engine/pure/code/core/functions/json/TestFunctionsJsonCompiledStateIntegrity.java, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-functions-relation-pure/src/test/java/org/finos/legend/engine/pure/code/core/functions/relation/TestFunctionsRelationCompiledStateIntegrity.java, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-standard/legend-engine-pure-functions-standard-pure/src/test/java/org/finos/legend/engine/pure/code/core/functions/standard/TestFunctionsStandardCompiledStateIntegrity.java, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-unclassified/legend-engine-pure-functions-unclassified-pure/src/test/java/org/finos/legend/engine/pure/code/core/functions/unclassified/TestFunctionsUnclassifiedCompiledStateIntegrity.java, legend-engine-xts-diagram/legend-engine-xt-diagram-pure-metamodel/pom.xml, legend-engine-xts-diagram/legend-engine-xt-diagram-pure-metamodel/src/test/java/org/finos/legend/pure/code/core/TestCoreDiagramMetamodelCompiledStateIntegrity.java, legend-engine-xts-diagram/legend-engine-xt-diagram-pure/pom.xml, legend-engine-xts-diagram/legend-engine-xt-diagram-pure/src/test/java/org/finos/legend/pure/code/core/TestCoreDiagramCompiledStateIntegrity.java, legend-engine-xts-java/legend-engine-xt-javaGeneration-featureBased-pure/pom.xml, legend-engine-xts-java/legend-engine-xt-javaGeneration-featureBased-pure/src/test/java/org/finos/legend/engine/pure/code/core/TestCoreExternalLanguageJavaFeatureBasedGenerationCompiledStateIntegrity.java, legend-engine-xts-java/legend-engine-xt-javaGeneration-pure/pom.xml, legend-engine-xts-java/legend-engine-xt-javaGeneration-pure/src/test/java/org/finos/legend/engine/pure/code/core/TestCoreExternalLanguageJavaCompiledStateIntegrity.java, legend-engine-xts-java/legend-engine-xt-javaPlatformBinding-externalFormat-pure/pom.xml, legend-engine-xts-java/legend-engine-xt-javaPlatformBinding-externalFormat-pure/src/test/java/org/finos/legend/engine/pure/code/core/TestCoreJavaPlatformBindingExternalFormatCompiledStateIntegrity.java, legend-engine-xts-java/legend-engine-xt-javaPlatformBinding-pure/pom.xml, legend-engine-xts-java/legend-engine-xt-javaPlatformBinding-pure/src/test/java/org/finos/legend/engine/pure/code/core/TestCoreJavaPlatformBindingCompiledStateIntegrity.java, legend-engine-xts-json/legend-engine-xt-json-javaPlatformBinding-pure/pom.xml, legend-engine-xts-json/legend-engine-xt-json-javaPlatformBinding-pure/src/test/java/org/finos/legend/engine/pure/code/core/json/binding/TestCoreExternalFormatJsonJavaPlatformBindingCompiledStateIntegrity.java, legend-engine-xts-json/legend-engine-xt-json-pure/pom.xml, legend-engine-xts-json/legend-engine-xt-json-pure/src/test/java/org/finos/legend/engine/pure/code/core/json/TestCoreExternalFormatJsonCompiledStateIntegrity.java, legend-engine-xts-text/legend-engine-xt-text-pure-metamodel/pom.xml, legend-engine-xts-text/legend-engine-xt-text-pure-metamodel/src/test/java/org/finos/legend/engine/pure/code/core/text/TestCoreTextMetamodelCompiledStateIntegrity.java, legend-engine-xts-xml/legend-engine-xt-xml-javaPlatformBinding-pure/pom.xml, legend-engine-xts-xml/legend-engine-xt-xml-javaPlatformBinding-pure/src/test/java/org/finos/legend/engine/pure/code/core/xml/binding/TestCoreExternalFormatXmlJavaPlatformBindingCompiledStateIntegrity.java, legend-engine-xts-xml/legend-engine-xt-xml-pure/pom.xml, legend-engine-xts-xml/legend-engine-xt-xml-pure/src/test/java/org/finos/legend/pure/code/core/external/format/xml/TestCoreExternalFormatXmlCompiledStateIntegrity.java
Improvement
Add compiled state integrity tests for several modules. Ideally, every module which defines a Pure repo should have such a test.
In passing, fix typos in the names of some existing compiled state integrity tests, and clean up the test for core.
No
=> Add compiled state integrity tests for several modules

legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/metaExtension.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/tests/metaExtension.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/tests/metaExtention_funcs.pure, legend-engine-xts-graphQL/legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/fromPure/sdl/fromPure_sdl.pure, legend-engine-xts-graphQL/legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/fromPure/sdl/tests/simpleTest.pure, legend-engine-xts-graphQL/legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/toPure/sdl/tests/simpleTest.pure
GraphQL SDL generation from Pure should handle deeply nested hierarchies with explicit transitive implements
=> GraphQL SDL generation from Pure should handle deeply nested hierarchies with explicit transitive implements

legend-engine-xts-hostedService/legend-engine-xt-hostedService-generation/src/main/java/org/finos/legend/engine/language/hostedService/generation/deployment/HostedServiceArtifactGenerationExtension.java, legend-engine-xts-snowflakeApp/legend-engine-xt-snowflakeApp-generator/src/main/java/org/finos/legend/engine/language/snowflakeApp/generator/SnowflakeAppArtifactGenerationExtension.java
Remove lineage generation code
Fixes #
=> Remove lineage generation code

legend-engine-xts-persistence/legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/logicalplan/datasets/DatasetReferenceImplAbstract.java, legend-engine-xts-persistence/legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/java/org/finos/legend/engine/persistence/components/RelationalSchemaEvolutionServiceTest.java
- Improvement
Fix DatasetReference to have dataset optional properties. Currently users were not able to set this parameter.
This will enable us to evolve the schema of iceberg tables
Fixes #
NO
=> Persistence Component : Iceberg tables - Fix dataset Reference to have dataset optional properties

legend-engine-config/legend-engine-repl/legend-engine-repl-client/src/main/java/org/finos/legend/engine/repl/client/Client.java, legend-engine-config/legend-engine-repl/legend-engine-repl-client/src/main/java/org/finos/legend/engine/repl/core/commands/Doc.java, legend-engine-config/legend-engine-repl/legend-engine-repl-data-cube/src/main/java/org/finos/legend/engine/repl/dataCube/commands/DataCubeWalkthrough.java, legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light-http-server/src/main/java/org/finos/legend/engine/ide/api/concept/Concept.java, legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light-http-server/src/main/java/org/finos/legend/engine/ide/api/execution/test/TestRun.java, legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light-http-server/src/main/java/org/finos/legend/engine/ide/api/find/FindInSources.java, legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light-http-server/src/main/java/org/finos/legend/engine/ide/session/PureSession.java, legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light-pure/src/main/resources/pure_ide/concepts.pure, legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light-pure/src/main/resources/pure_ide/testing.pure, legend-engine-xts-java/legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/pct_java.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-PCT/legend-engine-pure-functions-relationalStore-PCT-pure/src/main/resources/core_external_test_connection/pct_relational.pure, pom.xml
https://github.com/user-attachments/assets/c3cd6265-779e-4265-a2d4-43c9e201a4a8
https://github.com/user-attachments/assets/98ba5145-5051-4c26-9679-f2623cf72ad2
https://github.com/user-attachments/assets/f28a7bac-2afa-4450-942a-712955482556
https://github.com/user-attachments/assets/35961eab-8b52-4438-b206-14c650ff4d0e
https://github.com/user-attachments/assets/5a23d639-bf46-478a-ba30-f0889b08dc36
https://github.com/user-attachments/assets/7a19c9dd-7366-4870-b732-1050c1951726
https://github.com/user-attachments/assets/4136afaa-029b-42e7-a384-668ff198677f
=> pure ide: improvements

legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/mappingExtension.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/routing/router_routing.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/tests/mapping/enumeration/testEnumerationMapping.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/tests/mapping/enumeration/testEnumerationMappingDomain.pure
Bug Fix
- Fix property sequence on routing when resolving variable to also update the generic type along with value on ExtendedRoutedValueSpecification
- Update the assert on processIfForEnum to correctly identify the distinct Enum transformers by doing an equality check only on the relevant properties
=> Fix property sequence on routing

legend-engine-xts-analytics/legend-engine-xts-analytics-mapping/legend-engine-xt-analytics-mapping-pure/src/main/resources/core_analytics_mapping/modelCoverage/analytics.pure, legend-engine-xts-analytics/legend-engine-xts-analytics-mapping/legend-engine-xt-analytics-mapping-pure/src/main/resources/core_analytics_mapping/modelCoverage/analyticsTest.pure, legend-engine-xts-analytics/legend-engine-xts-analytics-mapping/legend-engine-xt-analytics-mapping-pure/src/main/resources/core_analytics_mapping/modelCoverage/mappedEntityBuilder.pure
Improvement
apply property filter on mapping analysis
Fixes #
=> apply property filter on mapping analysis

.gs-project.yml, legend-engine-config/legend-engine-repl/legend-engine-repl-client/src/main/java/org/finos/legend/engine/repl/autocomplete/parser/ParserFixer.java, legend-engine-config/legend-engine-repl/legend-engine-repl-client/src/test/java/org/finos/legend/engine/repl/TestParserFixer.java, legend-engine-config/legend-engine-repl/legend-engine-repl-relational/pom.xml, legend-engine-config/legend-engine-repl/legend-engine-repl-relational/src/main/java/org/finos/legend/engine/repl/relational/autocomplete/RelationalCompleterExtension.java, legend-engine-config/legend-engine-repl/legend-engine-repl-relational/src/test/java/org/finos/legend/engine/repl/TestCompleter.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-PCT/legend-engine-pure-functions-relationalStore-PCT-pure/src/main/resources/core_external_test_connection/pct_relational.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalBuilder.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/RelationalCompilerExtension.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationStoreAccessorFromGrammar.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalMapperCompilationFromGrammar.java
Bug Fix
Fix how schema looks ups are done on relation accessor. The code currently assumes the first schema on the DB was is the `"default"` schema. This fix explicitly uses schema named "default". This also improve completions to look into default schema, and also suggest schema names.
Fixes #
=> Schema support in relation accessor 

legend-engine-xts-persistence/legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/main/java/org/finos/legend/engine/persistence/components/relational/snowflake/SnowflakeSink.java
- Bug Fix
The new BulkLoad stats: bytes scanned and incoming record count return null results when the file is empty. Adding null checks around.
=> Persistence Component: Fix NPE in BulkLoad stats

legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ClassMappingFirstPassBuilder.java, legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestMappingCompilationFromGrammar.java, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphExtension.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/mappingExtension.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_33_0/scan/buildBasePureModel.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/scan/buildBasePureModel.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/simpleObject.pure, legend-engine-xts-java/legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/generation/conventions.pure, legend-engine-xts-java/legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/inMemory/graphFetchInMemory.pure
Allow primitive types to be used as a source for mappings in M2M mappings. This implementation doesn't handle filters which can be added should support for this be required.
=> M2M: Allow primitive types to be used as a source for mappings

legend-engine-xts-functionActivator/legend-engine-xt-functionActivator-generation/src/main/java/org/finos/legend/engine/functionActivator/generation/FunctionActivatorGenerator.java, legend-engine-xts-functionActivator/legend-engine-xt-functionActivator-generation/src/main/java/org/finos/legend/engine/functionActivator/postDeployment/PostDeploymentActionDeploymentContract.java, legend-engine-xts-functionActivator/legend-engine-xt-functionActivator-generation/src/main/java/org/finos/legend/engine/functionActivator/postDeployment/PostDeploymentActionLoader.java, legend-engine-xts-functionActivator/legend-engine-xt-functionActivator-generation/src/main/java/org/finos/legend/engine/functionActivator/postDeployment/PostDeploymentGeneration.java, legend-engine-xts-functionActivator/legend-engine-xt-functionActivator-http-api/src/main/java/org/finos/legend/engine/functionActivator/validation/FunctionActivatorValidator.java, legend-engine-xts-hostedService/legend-engine-xt-hostedService-api/src/main/java/org/finos/legend/engine/language/hostedService/api/HostedServiceService.java, legend-engine-xts-hostedService/legend-engine-xt-hostedService-generation/src/main/java/org/finos/legend/engine/language/hostedService/generation/HostedServiceArtifactGenerator.java, legend-engine-xts-hostedService/legend-engine-xt-hostedService-generation/src/main/java/org/finos/legend/engine/language/hostedService/generation/deployment/HostedServiceArtifactGenerationExtension.java
=> Update post deployment actions contract

legend-engine-xts-sql/legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/ExecutionDispatcher.java, legend-engine-xts-sql/legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/SystemSchemas.java, legend-engine-xts-sql/legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/handler/txn/TxnIsolationPreparedStatement.java, legend-engine-xts-sql/legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/handler/txn/TxnIsolationSessionHandler.java, legend-engine-xts-sql/legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/handler/txn/TxnIsolationStatement.java, legend-engine-xts-sql/legend-engine-xt-sql-postgres-server/src/test/java/org/finos/legend/engine/postgres/ExecutionDispatcherTest.java, legend-engine-xts-sql/legend-engine-xt-sql-postgres-server/src/test/java/org/finos/legend/engine/postgres/PostgresServerTest.java
- Improvement
Some SQL clients such as Hikari and ODBC driver check transaction isolation level during startup.
The current approach uses in-memory H2 to respond to those queries, and works fine for Hikari/JDBC clients.
However, H2 doesn't support the ODBC query format (`SHOW transaction_isolation`).
This PR introduces a custom handler for transaction isolation queries, so that the ODBC query format can be supported too.
Adds support for system schema `pg_type`, which is queried during ODBC driver startup.
Routed to in-memory H2.
No
=> [Legend SQL] Support second format of transaction isolation query

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-pure/src/main/resources/core_relational_snowflake/relational/executionPlan/tests/executionPlanTestSnowflake.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-pure/src/main/resources/core_relational_snowflake/relational/sqlQueryToString/snowflakeExtension.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/graphFetch/relationalGraphFetch.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/graphFetch/tests/testSimpleRelationalGraphFetch.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbExtension.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/sqlQueryToString/extensionDefaults.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/sqlQueryToString/testSuite/testTempTableSqlStatements.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/tests/relationalSetUp.pure
Bug Fix
Currently quotes aren't used for temp tables in graph fetch flow when quoteIdentifiers flag is set on the connection. This MR fixes that for H2 and Snowflake in the Pure flow.
Fixes #
=> Fix for temp tables with quoted identifiers flag

legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol/src/main/java/org/finos/legend/engine/protocol/AnyDeserializer.java
Bug Fix
Rollback to use a vanilla mapper, since if the incoming mapper has the JSR310 module, it would deserialize LocalDate out of IntNode, leading to incorrect behaviors.
Fixes #
=> Rollback usage of incoming object codec

legend-engine-xts-dataquality/legend-engine-xt-dataquality-generation/src/main/java/org/finos/legend/engine/generation/dataquality/DataQualityLambdaGenerator.java, legend-engine-xts-dataquality/legend-engine-xt-dataquality-pure/src/main/resources/core_dataquality/generation/dataquality.pure
- Bug Fix
fixes multiplicity and generic type of param in runtime expression
No
=> fix multiplicity and generic type of param in runtime expression

legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/Compiler.java, legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/CompilerTest.java, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/models/metamodel.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/transfers/metamodel.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/pom.xml, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationFunctions.java
Improvement
With this new API, we dont need to chose between returning the type or the relation type.  
This will allow to consolidate, and let the client, thru introspection of the GenericType, decide if is Relation or packageable type.
Fixes #
=> Introduce compiler api to get generic type of a Lambda

legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core.definition.json, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-functions-relation-pure/src/main/resources/core_functions_relation/relation/functions/write/write.pure, legend-engine-xts-java/legend-engine-xt-javaPlatformBinding-PCT/src/test/java/org/finos/legend/engine/pure/code/core/java/binding/Test_JAVA_RelationFunction_PCT.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-PCT/legend-engine-pure-functions-relationalStore-PCT-pure/src/main/resources/core_external_test_connection/pct_relational.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-duckdb/legend-engine-xt-relationalStore-duckdb-PCT/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/duckdb/pct/Test_Relational_DuckDB_RelationFunctions_PCT.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-h2/legend-engine-xt-relationalStore-h2-PCT/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/h2/pct/Test_Relational_H2_RelationFunctions_PCT.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-postgres/legend-engine-xt-relationalStore-postgres-PCT/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/postgres/pct/Test_Relational_Postgres_RelationFunctions_PCT.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/RelationalExecutor.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/RelationalExecutionNodeExecutor.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/SQLExecutionNode.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/contract/storeContract.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/executionPlan/executionPlan.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/metamodel/metamodel.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/mutation/relationalMutation.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/protocols/pure/vX_X_X/extension/extension_relational.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/protocols/pure/vX_X_X/models/executionPlan_relational.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/relationalMappingExecution.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbExtension.pure
Implement write API for read/write from/to same connection
=>  Implement write API for read/write from/to same connection

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-pure/src/main/resources/core_relational_snowflake/relational/sqlQueryToString/snowflakeExtension.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-pure/src/main/resources/core_relational_snowflake/relational/tests/tabularFunctionModel.txt, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-pure/src/main/resources/core_relational_snowflake/relational/tests/testTabularFunctionQuery.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/RelationalLexerGrammar.g4, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/RelationalParserGrammar.g4, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalBuilder.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/RelationalParseTreeWalker.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperRelationalGrammarComposer.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/RelationalGrammarComposerExtension.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalCompilationFromGrammar.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalGrammarRoundtrip.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-http-api/src/test/java/org.finos.legend.engine.language.pure.grammar.api.relationalOperationElement.test/TestRelationalOperationElementApi.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/TabularFunction.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/postprocessor/defaultPostProcessor/reAliasQuery.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/postprocessor/defaultPostProcessor/trimColumnNamePostProcessor.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbExtension.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/debugPrint/debugPrintExtension.pure, legend-engine-xts-snowflakeApp/legend-engine-xt-snowflakeApp-pure/src/main/resources/core_snowflakeapp/tests/testSnowflakeAppGeneration.pure
Improvement
Add query generation on tabular Function
Fixes #
=> Add query generation on tabular Function[Phase1]

legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light-http-server/pom.xml, legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light-http-server/src/main/java/org/finos/legend/engine/ide/PureIDEServer.java, legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light-http-server/src/main/java/org/finos/legend/engine/ide/api/debug/Debugging.java, legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light-http-server/src/main/java/org/finos/legend/engine/ide/session/PureSession.java, legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light-interpreted-functions/pom.xml, legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light-interpreted-functions/src/main/java/org/finos/legend/engine/pure/ide/interpreted/PureIDEExtensionInterpreted.java, legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light-interpreted-functions/src/main/java/org/finos/legend/engine/pure/ide/interpreted/debug/DebugPureIDE.java, legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light-interpreted-functions/src/main/java/org/finos/legend/engine/pure/ide/interpreted/debug/DebugState.java, legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light-interpreted-functions/src/main/java/org/finos/legend/engine/pure/ide/interpreted/debug/FunctionExecutionInterpretedWithDebugSupport.java, legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light-interpreted-functions/src/main/resources/META-INF/services/org.finos.legend.pure.runtime.java.interpreted.extension.InterpretedExtension, legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light-pure/src/main/resources/pure_ide/debug.pure, legend-engine-pure/legend-engine-pure-ide/pom.xml
Front end changes: https://github.com/finos/legend-studio/pull/3752
=> Add support to debug Pure IDE executions

legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/functionInMapping.pure, legend-engine-xts-java/legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/generation/conventions.pure, legend-engine-xts-java/legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/langLibrary.pure
Bug Fix
There was an existing bug with the new operator being used in a M2M mapping: this change makes sure properties with multiplicity * are assigned a non-null empty list when the user does not specify a value in the vall to new and thus avoids a null pointer exception when the user accesses such properties.
=> Bug fix for new operator in m2 m

legend-engine-xts-persistence/legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-physical-plan/src/main/java/org/finos/legend/engine/persistence/components/util/SqlUtils.java, legend-engine-xts-persistence/legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-bigquery/src/main/java/org/finos/legend/engine/persistence/components/relational/bigquery/executor/BigQueryExecutor.java, legend-engine-xts-persistence/legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-core/src/main/java/org/finos/legend/engine/persistence/components/relational/executor/RelationalExecutor.java, legend-engine-xts-persistence/legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/main/java/org/finos/legend/engine/persistence/components/relational/snowflake/SnowflakeSink.java
- Bug Fix
1. In multi-dataset cases, staging filters are saved as strings (hence quoted) instead of numbers. Fixed the placeholder handlings that caused it.
2. Newly added stats for bulk load: bytes scanned and incoming records are coming as strings. Added casting to save them as numbers.
Fixes #
=> Persistence Component: Fix staging filters saved as String + Fix new stats for Bulk Load coming as String

legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light-http-server/src/main/java/org/finos/legend/engine/ide/PureIDELight_NoExtension.java, legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light-http-server/src/main/java/org/finos/legend/engine/ide/PureIDEServer.java, legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light-http-server/src/main/java/org/finos/legend/engine/ide/ServerConfiguration.java, legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light-http-server/src/main/java/org/finos/legend/engine/ide/session/PureSession.java, legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light-http-server/src/main/resources/ideLightConfig.json
Make choice of which function interpreter to use in IDE Light configurable at runtime
=> IDE Light: make debug version of interpreter a config option

legend-engine-xts-functionActivator/legend-engine-xt-functionActivator-pure/src/test/java/org/finos/legend/engine/code/core/TestCoreFunctionActivatorCompiledStateIntegrity.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-trino/legend-engine-xt-relationalStore-trino-pure/src/test/java/org/finos/legend/pure/code/core/TestCoreRelationalTrinoCompiledStateIntegrity.java, pom.xml
Upgrade legend-pure to 5.31.1. This fixes several bugs, including those causing the sporadic test failures related to [PR 3344](https://github.com/finos/legend-engine/pull/3344).
No
=> Upgrade legend-pure to 5.31.1

legend-engine-xts-analytics/legend-engine-xts-analytics-lineage/legend-engine-xt-analytics-lineage-pure/src/main/resources/core_analytics_lineage/fullAnalytics.pure, legend-engine-xts-analytics/legend-engine-xts-analytics-search/legend-engine-xt-analytics-search-pure/src/main/resources/core_analytics_search/trans.pure
Improvement
Adds a configuration for the `computeLineage` function to allow for opting out of some types of calculations.
This allows for computationally expensive calculations to be skipped if only a subset of lineage is required.
Updated the SearchDocumentArtifactGenerationExtension to only calculate `reportLineage` as this is all that is required. This will dramatically speed up calculation for some Service elements.
=> Add ability to opt-out of some lineage calculations

legend-engine-xts-serviceStore/legend-engine-xt-serviceStore-pure/src/test/java/org/finos/legend/pure/code/core/TestCoreServicestoreCompiledStateIntegrity.java, legend-engine-xts-sql/legend-engine-xt-sql-pure/src/test/java/org/finos/legend/engine/code/core/TestCoreExternalQuerySqlCompiledStateIntegrity.java
- Improvement
- Ignore integrity tests that are taking longer than 1min while we work on the permanent fix to speed up the slow tests.
- no user-facing change
=> Ignoring 2 slow integrity test classes

legend-engine-xts-java/legend-engine-xt-javaPlatformBinding-externalFormat-pure/src/main/resources/core_java_platform_binding_external_format/legendJavaPlatformBinding/externalFormat/shared.pure, legend-engine-xts-xml/legend-engine-xt-xml-pure/src/main/resources/core_external_format_xml/executionPlan/tests/executionPlanTest.pure, legend-engine-xts-xml/legend-engine-xt-xml-pure/src/main/resources/core_external_format_xml/executionPlan/tests/simple.pure
Generate Java code for qualified properties in ExternalFormats flow, specifically for data classes representing the model that is used for internalize/externalize
=> External Format Java Gen: generate code for qualified properties

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-memsql/legend-engine-xt-relationalStore-memsql-pure/src/main/resources/core_relational_memsql/relational/sqlQueryToString/memSQLExtension.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-memsql/legend-engine-xt-relationalStore-memsql-pure/src/main/resources/core_relational_memsql/relational/tests/mapping/sqlFunction/testSqlFunctionsInMapping.pure
- Bug Fix
Issue - Generated SQL for parseFloat in memSQL truncates floating point numbers to integers
|           | Before Fix                                | After Fix                         |
|-----    | ------                                       | ------                              |
|Query  |   cast('3.14159' as decimal)     |   '3.14159' :> DOUBLE   |
|Result  |     3                                          |      3.14159                    |
=> Fix parseFloat dyna function for memSQL

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-sqlDialectTranslation-pure/src/main/resources/core_external_store_relational_sql_dialect_translation/functionRegistry/postgresNativeFunctions/numeric/log.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-sqlDialectTranslation-pure/src/main/resources/core_external_store_relational_sql_dialect_translation/functionRegistry/postgresNativeFunctions/string/lpad.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-sqlDialectTranslation-pure/src/main/resources/core_external_store_relational_sql_dialect_translation/functionRegistry/postgresNativeFunctions/string/rpad.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-sqlDialectTranslation-pure/src/main/resources/core_external_store_relational_sql_dialect_translation/sqlTyping/sqlTypes.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-sqlDialectTranslation-pure/src/main/resources/core_external_store_relational_sql_dialect_translation/sqlTyping/typeInference.pure
Improvement
SQL Dialect Function Translation Improvements
No
=> SQL Dialect Function Translation Improvements

legend-engine-xts-bigqueryFunction/legend-engine-xt-bigqueryFunction-api/src/main/java/org/finos/legend/engine/language/bigqueryFunction/api/BigQueryFunctionService.java, legend-engine-xts-bigqueryFunction/legend-engine-xt-bigqueryFunction-api/src/main/java/org/finos/legend/engine/language/bigqueryFunction/deployment/BigQueryFunctionDeploymentManager.java, legend-engine-xts-functionActivator/legend-engine-xt-functionActivator-deployment/pom.xml, legend-engine-xts-functionActivator/legend-engine-xt-functionActivator-deployment/src/main/java/org/finos/legend/engine/functionActivator/deployment/DeploymentManager.java, legend-engine-xts-functionActivator/legend-engine-xt-functionActivator-generation/pom.xml, legend-engine-xts-functionActivator/legend-engine-xt-functionActivator-generation/src/main/java/org/finos/legend/engine/functionActivator/generation/FunctionActivatorGenerator.java, legend-engine-xts-functionActivator/legend-engine-xt-functionActivator-generation/src/main/java/org/finos/legend/engine/functionActivator/postDeployment/PostDeploymentActionDeploymentContract.java, legend-engine-xts-functionActivator/legend-engine-xt-functionActivator-generation/src/main/java/org/finos/legend/engine/functionActivator/postDeployment/PostDeploymentGeneration.java, legend-engine-xts-functionActivator/legend-engine-xt-functionActivator-generation/src/main/java/org/finos/legend/engine/functionActivator/validation/FunctionActivatorResult.java, legend-engine-xts-functionActivator/legend-engine-xt-functionActivator-generation/src/main/java/org/finos/legend/engine/functionActivator/validation/FunctionActivatorValidator.java, legend-engine-xts-functionActivator/legend-engine-xt-functionActivator-generation/src/main/java/org/finos/legend/engine/functionActivator/validation/FunctionActivatorWarning.java, legend-engine-xts-functionActivator/legend-engine-xt-functionActivator-http-api/src/main/java/org/finos/legend/engine/functionActivator/api/FunctionActivatorAPI.java, legend-engine-xts-functionActivator/legend-engine-xt-functionActivator-http-api/src/main/java/org/finos/legend/engine/functionActivator/service/FunctionActivatorService.java, legend-engine-xts-functionActivator/legend-engine-xt-functionActivator-protocol/src/main/java/org/finos/legend/engine/protocol/functionActivator/deployment/ExtraDeploymentConfigurations.java, legend-engine-xts-functionActivator/legend-engine-xt-functionActivator-protocol/src/main/java/org/finos/legend/engine/protocol/functionActivator/deployment/FunctionActivatorDeploymentDetails.java, legend-engine-xts-hostedService/legend-engine-xt-hostedService-api/src/main/java/org/finos/legend/engine/language/hostedService/api/HostedServiceService.java, legend-engine-xts-hostedService/legend-engine-xt-hostedService-generation/src/main/java/org/finos/legend/engine/language/hostedService/generation/HostedServiceArtifactGenerator.java, legend-engine-xts-hostedService/legend-engine-xt-hostedService-generation/src/main/java/org/finos/legend/engine/language/hostedService/generation/deployment/HostedServiceArtifactGenerationExtension.java, legend-engine-xts-hostedService/legend-engine-xt-hostedService-generation/src/main/java/org/finos/legend/engine/language/hostedService/generation/deployment/HostedServiceDeploymentManager.java, legend-engine-xts-hostedService/legend-engine-xt-hostedService-protocol/src/main/java/org/finos/legend/engine/protocol/hostedService/deployment/HostedServiceDeploymentDetails.java, legend-engine-xts-hostedService/legend-engine-xt-hostedService-protocol/src/main/java/org/finos/legend/engine/protocol/hostedService/deployment/HostedServiceDeploymentResult.java, legend-engine-xts-memsqlFunction/legend-engine-xt-memsqlFunction-api/src/main/java/org/finos/legend/engine/language/memsql/api/MemSqlFunctionService.java, legend-engine-xts-memsqlFunction/legend-engine-xt-memsqlFunction-api/src/main/java/org/finos/legend/engine/language/memsql/deployment/MemSqlFunctionDeploymentManager.java, legend-engine-xts-snowflakeApp/legend-engine-xt-snowflakeApp-api/src/main/java/org/finos/legend/engine/language/snowflakeApp/api/SnowflakeAppService.java, legend-engine-xts-snowflakeApp/legend-engine-xt-snowflakeApp-api/src/main/java/org/finos/legend/engine/language/snowflakeApp/deployment/SnowflakeAppDeploymentManager.java, legend-engine-xts-snowflakeApp/legend-engine-xt-snowflakeApp-api/src/test/java/org/finos/legend/engine/language/snowflakeApp/api/TestValidation.java, legend-engine-xts-snowflakeApp/legend-engine-xt-snowflakeApp-generator/src/main/java/org/finos/legend/engine/language/snowflakeApp/generator/SnowflakeAppGenerator.java
=> Add additional validations to hosted service

legend-engine-xts-dataquality/legend-engine-xt-dataquality-grammar/src/main/java/org/finos/legend/engine/language/dataquality/grammar/to/DataQualityGrammarComposerExtension.java, legend-engine-xts-dataquality/legend-engine-xt-dataquality-grammar/src/test/java/org/finos/legend/engine/language/dataquality/grammar/from/TestDataQualityParsing.java, legend-engine-xts-dataquality/legend-engine-xt-dataquality-grammar/src/test/java/org/finos/legend/engine/language/dataquality/grammar/to/TestDataQualityRoundtrip.java
- Bug Fix
Runtime field was not added to the composer in the dataquality relation validation specification which this merge request fixes.
No
=> fix runtime field in dq relation validation composer

legend-engine-xts-dataquality/legend-engine-xt-dataquality-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/TestDataQualityCompilationFromGrammar.java, legend-engine-xts-dataquality/legend-engine-xt-dataquality-pure-test/src/main/resources/core_dataquality_test/dataquality_test.pure, legend-engine-xts-dataquality/legend-engine-xt-dataquality-pure/src/main/resources/core_dataquality/generation/dataquality.pure
- Bug Fix
Resolved incorrect "Constraint :[mustHaveOneRuntime] violated in the Class DataQualityRelationValidation" failures when other overloads of the "from" method
No breaking change expected.
=> Changes for DataQualityValidation constraints to check additional "from" functions

legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-functions-relation-pure/pom.xml, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-functions-relation-pure/src/main/resources/core_functions_relation.definition.json, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-functions-relation-pure/src/main/resources/core_functions_relation/relation/functions/graph/project.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-functions-relation-pure/src/main/resources/core_functions_relation/relation/functions/iteration/filter.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-functions-relation-pure/src/main/resources/core_functions_relation/relation/functions/slice/drop.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-functions-relation-pure/src/main/resources/core_functions_relation/relation/functions/slice/limit.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-functions-relation-pure/src/main/resources/core_functions_relation/relation/functions/slice/slice.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-functions-relation-pure/src/main/resources/core_functions_relation/relation/functions/transformation/concatenate.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-functions-relation-pure/src/main/resources/core_functions_relation/relation/functions/transformation/extend.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-functions-relation-pure/src/main/resources/core_functions_relation/relation/functions/transformation/groupBy.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-functions-relation-pure/src/main/resources/core_functions_relation/relation/functions/transformation/rename.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-functions-relation-pure/src/main/resources/core_functions_relation/relation/functions/transformation/select.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-functions-relation-pure/src/main/resources/core_functions_relation/relation/tests/composition.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-runtime-java-extension-compiled-functions-relation/pom.xml, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-runtime-java-extension-compiled-functions-relation/src/test/java/org/finos/legend/pure/runtime/java/extension/relation/compiled/pure/TestPCTReport.java, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-runtime-java-extension-interpreted-functions-relation/pom.xml, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-runtime-java-extension-interpreted-functions-relation/src/test/java/org/finos/legend/pure/runtime/java/extension/relation/interpreted/pure/TestPCTReport.java, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-runtime-java-extension-shared-functions-relation/pom.xml, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-standard/legend-engine-pure-functions-standard-pure/src/main/resources/core_functions_standard/math/aggregator/percentile.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-standard/legend-engine-pure-functions-standard-pure/src/main/resources/core_functions_standard/math/aggregator/stdDevPopulation.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-standard/legend-engine-pure-functions-standard-pure/src/main/resources/core_functions_standard/math/aggregator/stdDevSample.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-standard/legend-engine-pure-functions-standard-pure/src/main/resources/core_functions_standard/math/aggregator/variancePopulation.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-standard/legend-engine-pure-functions-standard-pure/src/main/resources/core_functions_standard/math/aggregator/varianceSample.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-standard/legend-engine-pure-functions-standard-pure/src/test/java/org/finos/legend/pure/code/core/tests/TestPCTReport.java, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-standard/legend-engine-pure-runtime-java-extension-compiled-functions-standard/src/test/java/org/finos/legend/pure/runtime/java/extension/functions/standard/compiled/TestPCTReport.java, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-standard/legend-engine-pure-runtime-java-extension-interpreted-functions-standard/src/test/java/org/finos/legend/pure/runtime/java/extension/functions/standard/interpreted/TestPCTReport.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-memsql/legend-engine-xt-relationalStore-memsql-PCT/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/memsql/pct/TestPCRReport.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-spanner/legend-engine-xt-relationalStore-spanner-PCT/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/spanner/pct/Test_Relational_Spanner_RelationFunctions_PCT.java
Improvement
Update assertion in PCT tests that contains unordered tds. Allow the tds being unsorted during testing
Fixes #
=> update PCT testcases assertions to make result in sorted order

legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java, legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestCompilationFromGrammar.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-PCT/legend-engine-pure-functions-relationalStore-PCT-pure/src/main/resources/core_external_test_connection/pct_relational.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/RelationalParserGrammar.g4, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/RelationalCompilerExtension.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/RelationalParseTreeWalker.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperRelationalGrammarComposer.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalCompilationFromGrammar.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalGrammarRoundtrip.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/transform/fromPure/pureToRelational.pure, pom.xml
Fix usage of double quotes in Schema. Remove ambiguity with precise primitive type names.
=> Fix usage of double quotes in Schema. Remove ambiguity with precise primitive type names.

legend-engine-xts-flatdata/legend-engine-xt-flatdata-model/src/test/java/org/finos/legend/engine/external/format/flatdata/grammar/driver/TestFixedWidth.java, legend-engine-xts-flatdata/legend-engine-xt-flatdata-shared/src/main/java/org/finos/legend/engine/external/format/flatdata/driver/core/FixedWidthDriverDescription.java, legend-engine-xts-flatdata/legend-engine-xt-flatdata-shared/src/main/java/org/finos/legend/engine/external/format/flatdata/driver/core/FixedWidthReadDriver.java
FlatData: option for FixedWidth final column to read to EoL
Allow column specification for final column to accept EOL to tell driver to read the rest of the line. 
EOL only accepted for final column to handle files with variable lengths on final field. 
Example schema, where the final column will read from index 3 upto the EoL (in this case the default EoL character since no new line character is specified in the schema definition)
```
section default: FixedWidth
{
scope.untilEof;
Record 
{
Title {1:2} : STRING;
Surname: {3:EOL} : STRING;
}
}
```
=> FlatData: option for FixedWidth final column to read to EoL

docs/compiler/compiler-extension-processor.md
- Inform developers about the new changes in the compiler, where prerequisite elements can now be intra-type dependencies (between elements of different types), which will be used to determine the order of compilation in the third pass
=> Update compiler documentation

legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/DEPRECATED_PureGrammarComposerCore.java, legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperDomainGrammarComposer.java, legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/PureGrammarComposer.java, legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/PureGrammarComposerContext.java, legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/PureGrammarComposerUtility.java, legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestGrammarRoundtrip.java, legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestDomainGrammarRoundtrip.java
- Bug Fix
Add option to legend grammar composer to generate enum values without single quotes for legend-pure compatibility
=> Option to Pure grammar composer to not quote enum values

legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan_generation.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure, pom.xml
- Improvement
Trigger preprocessFunction configured on runtime to be able to rewrite a function expression before preval and routing if needed (prior to plan generation)
=> Trigger preprocessFunction prior to plan generation

legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/CompileContext.java, legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PureModel.java, legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestCompilationFromGrammar.java
Cache search imports results in Pure graph to avoid duplicate lookups
=> Cache search imports results in Pure graph to avoid duplicate lookups

legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/CompileContext.java, legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PureModel.java, legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestCompilationFromGrammar.java
- Resolve only user-defined packageable elements
- Assign null sentinel value to be of type Class, so that it can be used for both types and packageable elements
- Increase the timeout for caching search imports test case
=> Resolve only user-defined packageable elements

legend-engine-xts-arrow/legend-engine-xt-arrow-runtime/src/test/java/TestArrowNodeExecutor.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-h2/legend-engine-xt-relationalStore-h2-execution-2.1.214/src/test/java/org/h2/legendTests/TestH2Abstract.java
Switch some tests to in memory to avoid using the same DB file (~/test) for different tests. This isolates test data from different modules and avoid potential issues due to shared data
=> Switch to using H2 inmemory for some tests

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/helperFunctions/helperFunctions.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/lineage/scanRelations/scanRelationsTests.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbExtension.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/tests/mapping/relation/relationMappingSetup.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/tests/mapping/relation/tests.pure
From respective to mapping from a relation function, this forces the alias name of a relation column mapped to a property to be quoted.  This is consistent with how we handle alias of relational table accessors, and when casting to a relation.
To ensure this works, this also aims to fix places where column and column names are compared, to ensure the quotes dont interfere.
=> Relation function always quote columns as these are case sensitive

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-databricks/legend-engine-xt-relationalStore-databricks-PCT/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/databricks/pct/Test_Relational_Databricks_RelationFunctions_PCT.java
Bug fix
Adding expected failures to databricks for enhanced listagg tests with rows.
=> Adding databricks listagg failures (#3825)

legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ValueSpecificationBuilder.java, legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java, legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/constant/classInstance/relation/ColSpec.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationFunctions.java, pom.xml
Fix column type issue when using col(i.e:~) in select and other funcs
=> Fix column type issue when using col(i.e:~) in select and other funcs

legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-functions-relation-pure/src/main/resources/core_functions_relation/relation/functions/transformation/groupBy.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-runtime-java-extension-compiled-functions-relation/src/main/java/org/finos/legend/pure/runtime/java/extension/external/relation/compiled/RelationNativeImplementation.java, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-runtime-java-extension-compiled-functions-relation/src/main/java/org/finos/legend/pure/runtime/java/extension/external/relation/compiled/natives/GroupBy.java, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-runtime-java-extension-compiled-functions-relation/src/main/java/org/finos/legend/pure/runtime/java/extension/external/relation/compiled/natives/GroupByArray.java, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-runtime-java-extension-interpreted-functions-relation/src/main/java/org/finos/legend/pure/runtime/java/extension/external/relation/interpreted/RelationExtensionInterpreted.java, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-runtime-java-extension-interpreted-functions-relation/src/main/java/org/finos/legend/pure/runtime/java/extension/external/relation/interpreted/natives/GroupBy.java, legend-engine-xts-dataquality/legend-engine-xt-dataquality-pure-test/src/main/resources/core_dataquality_test/dataquality_test.pure, legend-engine-xts-dataquality/legend-engine-xt-dataquality-pure/src/main/resources/core_dataquality/generation/dataquality.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationFunctions.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
- Improvement
- This is required so can do aggregate operations at the table level, for example to get row count of table (select count(*) from table)
- Changing the data quality generated queries to use this new functionality to get row count instead of doing it with an extend using size operator which was not correct as this was producing an aggregated level operation at row level
- Adding a new function for group by instead of making colspec parameter as optional in existing one as this was failing in pure compiler as the generic type of the optional param was used as part of the return type (Z+R) and the complier was complaining that "can't resolve some type parameters in: X". Can look into investigating this later but for now added these as separate functions which reuse existing …
=> Add support for groupby with no cols to allow aggregations at table level

legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-functions-relation-pure/src/main/resources/core_functions_relation/relation/functions/eval.pure, legend-engine-xts-java/legend-engine-xt-javaPlatformBinding-PCT/src/test/java/org/finos/legend/engine/pure/code/core/java/binding/Test_JAVA_RelationFunction_PCT.java
Improvement
- Rename evalcol.pure to eval.pure to match pct function name to be consistent with the conventions
=> Rename evalcol.pure to eval.pure to match pct function name

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/RelationalExecutionNodeExecutor.java, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/full/multiExpression/TestConnectionManagementWithMultiExpressionQuery.java
Bug Fix
Close single record primitive results to avoid filling up pool
=> Close single record primitive results to avoid filling up pool

legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-compiler/pom.xml, legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PropertyMappingBuilder.java, legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestMappingCompilationFromGrammar.java, legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/test/resources/localCrossStoreJoins.pure, legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/test/resources/localCrossStoreJoinsWMilestoning.pure, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-unclassified/legend-engine-pure-runtime-java-extension-compiled-functions-unclassified/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/function/TestFunctionDefinitionModify.java, legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-unclassified/legend-engine-pure-runtime-java-extension-interpreted-functions-unclassified/src/test/java/org/finos/legend/pure/runtime/java/interpreted/function/TestFunctionDefinitionModify.java
Improvement - enable xstore without reference to mapping ids
enable xstore without reference to mapping ids - so we can define XStore without any reference to physical data
yes - new feature
=> enable xstore without reference to mapping ids

legend-engine-xts-dataquality/legend-engine-xt-dataquality-generation/src/main/java/org/finos/legend/engine/generation/dataquality/DataQualityLambdaGenerator.java, legend-engine-xts-dataquality/legend-engine-xt-dataquality-pure-test/src/main/resources/core_dataquality_test/dataquality_test.pure, legend-engine-xts-dataquality/legend-engine-xt-dataquality-pure-test/src/main/resources/core_dataquality_test/dataquality_test_utils.pure, legend-engine-xts-dataquality/legend-engine-xt-dataquality-pure/src/main/resources/core_dataquality/generation/dataquality.pure
- Improvement
At the moment you can only run one validation/rule within a data quality validation at once. This change provides the ability to run all rules within a data quality validation at once to improve the performance and reduce the number of queries required on the underlying db. Changes:
- Union all sub queries together (for each dq rule in the validation)
- Normalize schema so that output is union of all columns of sub queries
=> Optimisation for ability to run all DQ validations at once

legend-engine-config/legend-engine-extensions-collection-generation/pom.xml, legend-engine-config/legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java, legend-engine-config/legend-engine-server/legend-engine-server-http-server/pom.xml, legend-engine-xts-dataquality/legend-engine-xt-dataquality-api/pom.xml, legend-engine-xts-dataquality/legend-engine-xt-dataquality-compiler/pom.xml, legend-engine-xts-dataquality/legend-engine-xt-dataquality-generation/pom.xml, legend-engine-xts-dataquality/legend-engine-xt-dataquality-grammar/pom.xml, pom.xml
- Bug Fix
SDLC server did not have the data quality composer available in the class path so it was not able to serialise the data quality elements to .pure files and instead would commit the files as .json.
=> Add data quality dependency to make available in SDLC server

legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-pure/src/main/resources/core_relational_snowflake/relational/sqlQueryToString/snowflakeExtension.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/protocols/pure/v1_33_0/extension/extension_relational.pure, legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/legend-engine-xt-relationalStore-core-pure/src/main/resources/core_relational/relational/protocols/pure/v1_33_0/models/executionPlan_relational.pure
Ensure isResultColumnsDynamic flag is serialized properly in v1_33_0
Reasons for not being able to reproducing issues faced by users using pivot() in their services is that
1. PCT framework uses the vX_X_X serializer, which correctly serializes the isResultColumnDynamic boolean flag. However, for any other environments, we default to v1_33_0 (https://github.com/finos/legend-engine/blob/master/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/PureClientVersions.java#L31).
2. there is currently no mechanism to test quoteIdentifiers flag in relational connection.
This fix was tested via user's service locally.
=> Ensure isResultColumnsDynamic flag is serialized properly in v1_33_0

legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/tests/metaExtension.pure
- Temporarily remove assertion until relation type set correctly in compiler - it is being set as "Any" instead of "RelationType" in compiled mode
=> Temporarily remove assertion until relation type set correctly in compiler

legend-engine-xts-dataquality/legend-engine-xt-dataquality-pure-test/src/main/resources/core_dataquality_test/dataquality_test.pure, legend-engine-xts-dataquality/legend-engine-xt-dataquality-pure/src/main/resources/core_dataquality/generation/dataquality.pure
- Improvement
- When executing multiple DQ validations at once against the same source data we should not need to evaluate that source data multiple times for each validation. Instead we should assign that to a variable so the query engine makes use of CTEs to optimise this query.
=> Optimization of DQ query to leverage CTEs
