finos/legend-engine

- pom.xml
> Upgrade versions for httpclient and httpcore

- legend-engine-server/pom.xml
- legend-engine-shared-core/pom.xml
- pom.xml
Upgrade legend shared version and fix package groups.
> upgrade legend shared

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
- legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDomainCompilationFromGrammar.java
Add generic max function to Handlers
> Add generic max collection function

- legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/context/PureSDLC.java
- legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/context/SDLC.java
Change to support semi and prod service registration from Alloy Studio
> Move up packageableElementPointers property from PureSDLC to SDLC

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ConnectionBuilder.java
- legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestConnectionCompilationFromGrammar.java
- legend-engine-language-pure-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/modelConnection/ModelConnectionLexerGrammar.g4
- legend-engine-language-pure-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/modelConnection/ModelConnectionParserGrammar.g4
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/CorePureGrammarParser.java
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/connection/ModelConnectionParseTreeWalker.java
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/DEPRECATED_PureGrammarComposerCore.java
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperConnectionGrammarComposer.java
- legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/parser/TestConnectionGrammarParser.java
- legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestConnectionGrammarRoundtrip.java
- legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestRuntimeGrammarRoundtrip.java
- legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/modelToModel/connection/ModelChainConnection.java
grammar and grammar compilation support for model chain connections
> add grammar support for modelChainConnection

- legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/compilation/GeneratePureConfig.java
- legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/util/Library.java
Adding implementation for legend pure function "first". Fixed generatePureConfig
> update Engine Dependency Library

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperModelBuilder.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PropertyMappingBuilder.java
- legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestMappingCompilationFromGrammar.java
A bug was identified in Legend engine compiler. It impacts use-cases where we map properties of temporal types
> fix processing of milestoned properties in mapping

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
> Add generateGuid function to Handlers

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PureModel.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ValueSpecificationBuilder.java
- legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDomainCompilationFromGrammar.java
- legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromProtocol/TestDomainCompilationFromProtocol.java
- legend-engine-language-pure-compiler/src/test/resources/packageWithCorrectStrictTimeDomain.json
- legend-engine-language-pure-compiler/src/test/resources/packageWithWrongStrictTimeDomain.json
- legend-engine-language-pure-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/core/CoreFragmentGrammar.g4
- legend-engine-language-pure-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/core/CoreLexerGrammar.g4
- legend-engine-language-pure-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/core/M3ParserGrammar.g4
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/domain/DateParseTreeWalker.java
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/domain/DomainParseTreeWalker.java
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/domain/ParserTreeWalkerUtility.java
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/domain/StrictTimeParseTreeWalker.java
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/DEPRECATED_PureGrammarComposerCore.java
- legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestLambdaRoundtrip.java
- legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/ValueSpecification.java
- legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/ValueSpecificationVisitor.java
- legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/raw/CStrictTime.java
- legend-engine-protocol-pure/src/test/resources/mappingWithLegacyEnumValueMapping.json
Support a new primitive type StrictTime on Alloy side
> Support a new primitive type StrictTime

- legend-engine-executionPlan-execution-store-inMemory/src/main/java/org/finos/legend/engine/plan/execution/stores/inMemory/plugin/StoreStreamReadingExecutionNodeContext.java
- legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/ExecutionNodeExecutor.java
- legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/helpers/platform/DefaultExecutionNodeContext.java
- legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/ResultNormalizer.java
enabling sourcing of graphFetch result
> enabling sourcing of graphFetch result

- legend-engine-language-pure-compiler-api/src/main/java/org/finos/legend/engine/language/pure/compiler/api/Compile.java
- legend-engine-query-pure/src/main/java/org/finos/legend/engine/query/pure/api/Execute.java
- legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/operational/prometheus/MetricsHandler.java
Add metrics for compile and execute
> Add metrics for compile and execute

- README.md
- legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig.json
See https://github.com/finos/legend/pull/376
> Update sample config file to match installation guide

- legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/serialization/TemporaryFile.java
- legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/operational/prometheus/MetricsHandler.java
> uplift metrics handling

- legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/AuthenticationStrategyBuilder.java
- legend-engine-language-pure-store-relational/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalConnectionCompilationRoundtrip.java
Fix delegated kerberos auth compiler to include serverPrincipal property
> Fix delegated kerberos auth compiler

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/Milestoning.java
- legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDomainCompilationFromGrammar.java
Fix the bug for date propagation plus inheritance.
Add one more QualifiedProperty for the milestoning class in the Engine.
> Fix the bug for date propagation plus inheritance

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/CompileContext.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PackageableElementFirstPassBuilder.java
- legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDomainCompilationFromGrammar.java
- legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromProtocol/TestDomainCompilationFromProtocol.java
- legend-engine-language-pure-compiler/src/test/resources/functionWithUnderscores.json
- legend-engine-language-pure-grammar-api/src/test/java/org/finos/legend/engine/language/pure/grammar/api/test/TestJsonToGrammarApi.java
- legend-engine-language-pure-grammar-api/src/test/resources/functionWithUnderscores.json
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/DEPRECATED_PureGrammarComposerCore.java
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperValueSpecificationGrammarComposer.java
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/PureGrammarComposerUtility.java
- legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestDomainGrammarRoundtrip.java
Fix the bug for function underscore naming convention issue in the Engine.
> Fix the bug for function underscore naming convention issue in the Engine

- legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalDatabaseConnectionBuilder.java
- legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/RelationalCompilerExtension.java
- legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/DatabaseConnection.java
add quoteIdentifiers property to DatabaseConnection
> add quoteIdentifiers property to DatabaseConnection

- legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/grammar/from/RelationalParseTreeWalker.java
- legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/grammar/to/RelationalGrammarComposerExtension.java
> Fix for parsing multigrain filters

- legend-engine-executionPlan-execution-store-relational/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/manager/ConnectionManagerSelector.java
- legend-engine-language-pure-store-relational/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/RelationalDatabaseConnectionLexerGrammar.g4
- legend-engine-language-pure-store-relational/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/RelationalDatabaseConnectionParserGrammar.g4
- legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/grammar/from/RelationalDatabaseConnectionParseTreeWalker.java
- legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/grammar/to/RelationalGrammarComposerExtension.java
- legend-engine-language-pure-store-relational/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalConnectionCompilationRoundtrip.java
- legend-engine-language-pure-store-relational/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalConnectionGrammarRoundtrip.java
add quoteIdentifier to database connection grammar
> add quoteIdentifier to database connection grammar

- legend-engine-executionPlan-execution-store-relational-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/specifications/SnowflakeDataSourceSpecification.java
- legend-engine-executionPlan-execution-store-relational-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/specifications/keys/SnowflakeAccountType.java
- legend-engine-executionPlan-execution-store-relational-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/specifications/keys/SnowflakeDataSourceSpecificationKey.java
- legend-engine-protocol-relational/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/specification/SnowflakeDatasourceSpecification.java
Revert "added support for snowflake proxy and vps and role (#210)" and related changes
> Revert "added support for snowflake proxy and vps and role (#210)" and related changes

- legend-engine-executionPlan-execution-store-relational/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/manager/strategic/DataSourceIdentifiersCaseSensitiveVisitor.java
- legend-engine-executionPlan-execution-store-relational/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/DatabaseIdentifiersCaseSensitiveVisitor.java
- legend-engine-executionPlan-execution-store-relational/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/RelationalResult.java
- legend-engine-executionPlan-execution-store-relational/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/serialization/RelationalResultToCSVSerializer.java
- legend-engine-executionPlan-execution-store-relational/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/serialization/RelationalResultToJsonDefaultSerializer.java
- legend-engine-executionPlan-execution-store-relational/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/result/TestDatabaseIdentifiersCaseSensitiveVisitor.java
- legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/helpers/ExecutionNodeTDSResultHelper.java
- legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/builder/tds/TDSBuilder.java
- legend-engine-language-pure-store-relational/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/datasource/DataSourceSpecificationLexerGrammar.g4
- legend-engine-language-pure-store-relational/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/datasource/DataSourceSpecificationParserGrammar.g4
- legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/DatasourceSpecificationBuilder.java
- legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/grammar/from/datasource/DataSourceSpecificationParseTreeWalker.java
- legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperRelationalGrammarComposer.java
- legend-engine-language-pure-store-relational/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalConnectionCompilationRoundtrip.java
- legend-engine-language-pure-store-relational/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalConnectionGrammarRoundtrip.java
- legend-engine-protocol-relational/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/specification/SnowflakeDatasourceSpecification.java
Add support for specifying quotedIdentifiersIgnoreCase flag in snowflake datasourceSpecifications.
> add support for specifying quotedIdentifiersIgnoreCase flag

- legend-engine-configuration/src/main/java/org/finos/legend/engine/plan/generation/transformers/VersionPlanTransformer.java
Update version plan transformer
> Update version plan transformer

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/CompileContext.java
- legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDomainCompilationFromGrammar.java
- legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestDomainGrammarRoundtrip.java
Support calling meta functions when the full qualified name is specified
> Support calling meta functions when the full qualified name is specified

- legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperRelationalGrammarComposer.java
- legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/grammar/to/RelationalGrammarComposerExtension.java
- legend-engine-language-pure-store-relational/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalGrammarRoundtrip.java
This fixes issue #300 for engine
> Fixes: #300 Fix for SourceID omission

- legend-engine-language-pure-grammar-api/src/test/java/org/finos/legend/engine/language/pure/grammar/api/test/TestJsonToGrammarApi.java
- legend-engine-language-pure-grammar-api/src/test/resources/simpleFunctionWithParameters.json
- legend-engine-language-pure-grammar-api/src/test/resources/simpleFunctionWithoutParameters.json
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperValueSpecificationGrammarComposer.java
Fixed the bug in the function name generation
> Fixed the bug in the function name generation

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/FunctionHandler.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/builder/CompositeFunctionExpressionBuilder.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/builder/FunctionExpressionBuilder.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/builder/MultiHandlerFunctionExpressionBuilder.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/builder/RequiredInferenceSimilarSignatureFunctionExpressionBuilder.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/validator/PureModelContextDataValidator.java
- legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDomainCompilationFromGrammar.java
Support overloaded user-defined functions
> Support overloaded user-defined functions

- legend-engine-executionPlan-execution-store-relational/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/freemarker/TestFreemarkerTimeZoneProcessing.java
- legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/date/EngineDate.java
- legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/freemarker/PlanDateParameterDateFormat.java
- legend-engine-executionPlan-execution/src/test/java/org/finos/legend/engine/plan/execution/result/test/TestEngineDate.java
- legend-engine-executionPlan-execution/src/test/java/org/finos/legend/engine/plan/execution/validation/test/TestParametersValidation.java
Support DateTime plus TimeZone offset conversion to UTC time
> Support DateTime plus TimeZone offset conversion to UTC time

- legend-engine-language-pure-dsl-service-execution/pom.xml
- legend-engine-language-pure-dsl-service-execution/src/main/java/org/finos/legend/engine/language/pure/dsl/service/execution/AbstractServicePlanExecutor.java
- legend-engine-language-pure-dsl-service-execution/src/main/java/org/finos/legend/engine/language/pure/dsl/service/execution/ServiceRunner.java
- legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/test/TestServiceRunner.java
Changes to accommodate suggestions in this SDLC PR:
- https://github.com/finos/legend-sdlc/pull/259#discussion_r699480684
- https://github.com/finos/legend-sdlc/pull/259#discussion_r699599628
> Make AbstractServicePlanExecutor implement ServiceRunner and remove async execution

- legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDomainCompilationFromGrammar.java
- legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromProtocol/TestDomainCompilationFromProtocol.java
- legend-engine-language-pure-compiler/src/test/resources/functionWithDateTime.json
- legend-engine-language-pure-compiler/src/test/resources/functionWithDateTimeContainingPercent.json
- legend-engine-language-pure-grammar-api/src/test/java/org/finos/legend/engine/language/pure/grammar/api/test/TestJsonToGrammarApi.java
- legend-engine-language-pure-grammar-api/src/test/resources/functionWithDate.json
- legend-engine-language-pure-grammar-api/src/test/resources/functionWithDateContainingPercent.json
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/domain/DateParseTreeWalker.java
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/domain/GraphFetchTreeParseTreeWalker.java
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/domain/NavigationParseTreeWalker.java
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/domain/StrictTimeParseTreeWalker.java
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/DEPRECATED_PureGrammarComposerCore.java
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperValueSpecificationGrammarComposer.java
- legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestDomainGrammarRoundtrip.java
- legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/grammar/from/milestoning/MilestoningParseTreeWalker.java
Fix how Engine handles Date/DateTime in PMCD
> Fix how Engine handles Date/DateTime in PMCD

- legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDomainCompilationFromGrammar.java
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/domain/DomainParseTreeWalker.java
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/domain/NavigationParseTreeWalker.java
- legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestDomainGrammarRoundtrip.java
fix biTemporal Query Parser & Compiler
> fix biTemporal Query Compilation

- legend-engine-extensions-collection-generation/pom.xml
- legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java
- legend-engine-language-pure-dsl-data-space/pom.xml
- legend-engine-language-pure-dsl-data-space/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/DataSpaceLexerGrammar.g4
- legend-engine-language-pure-dsl-data-space/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/DataSpaceParserGrammar.g4
- legend-engine-language-pure-dsl-data-space/src/main/java/org/finos/legend/engine/language/pure/dsl/dataSpace/compiler/toPureGraph/DataSpaceCompilerExtension.java
- legend-engine-language-pure-dsl-data-space/src/main/java/org/finos/legend/engine/language/pure/dsl/dataSpace/grammar/from/DataSpaceParseTreeWalker.java
- legend-engine-language-pure-dsl-data-space/src/main/java/org/finos/legend/engine/language/pure/dsl/dataSpace/grammar/from/DataSpaceParserExtension.java
- legend-engine-language-pure-dsl-data-space/src/main/java/org/finos/legend/engine/language/pure/dsl/dataSpace/grammar/to/DataSpaceGrammarComposerExtension.java
- legend-engine-language-pure-dsl-data-space/src/main/java/org/finos/legend/engine/protocol/pure/v1/DataSpaceProtocolExtension.java
- legend-engine-language-pure-dsl-data-space/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/dataSpace/DataSpace.java
- legend-engine-language-pure-dsl-data-space/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.compiler.toPureGraph.extension.CompilerExtension
- legend-engine-language-pure-dsl-data-space/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.grammar.from.extension.PureGrammarParserExtension
- legend-engine-language-pure-dsl-data-space/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.grammar.to.extension.PureGrammarComposerExtension
- legend-engine-language-pure-dsl-data-space/src/main/resources/META-INF/services/org.finos.legend.engine.protocol.pure.v1.extension.PureProtocolExtension
- legend-engine-language-pure-dsl-data-space/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestDataSpaceCompilationFromGrammar.java
- legend-engine-language-pure-dsl-data-space/src/test/java/org/finos/legend/engine/language/pure/dsl/text/grammar/test/TestDataSpaceGrammarParser.java
- legend-engine-language-pure-dsl-data-space/src/test/java/org/finos/legend/engine/language/pure/dsl/text/grammar/test/TestDataSpaceGrammarRoundtrip.java
- legend-engine-language-pure-dsl-data-space/src/test/java/org/finos/legend/engine/protocol/pure/v1/test/TestDataSpaceProtocol.java
- legend-engine-language-pure-dsl-data-space/src/test/resources/dataSpace_TestData.json
- legend-engine-server/pom.xml
- legend-engine-test-reports/pom.xml
- pom.xml
Related to https://github.com/finos/legend-studio/issues/469
> add DSL DataSpace

- legend-engine-language-pure-modelManager-sdlc/src/main/java/org/finos/legend/engine/language/pure/modelManager/sdlc/alloy/AlloySDLCLoader.java
- legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/context/AlloySDLC.java
Add maven coordinates to AlloySDLC
> Add maven coordinates to AlloySDLC

- legend-engine-language-pure-store-relational/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/RelationalParserGrammar.g4
- legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/grammar/from/RelationalParseTreeWalker.java
- legend-engine-language-pure-store-relational/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalGrammarRoundtrip.java
Fix the relational grammar parser to support joinOperation in mapping
> Fix the relational grammar parser to support joinOperation in mapping

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PackageableElementFirstPassBuilder.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PackageableElementSecondPassBuilder.java
- legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDomainCompilationFromGrammar.java
Remove Duplicate Property Validation for Class & Class-Association
> Remove Duplicate Property Validation

- legend-engine-language-pure-store-relational/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/RelationalParserGrammar.g4
- legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/grammar/from/RelationalParseTreeWalker.java
- legend-engine-language-pure-store-relational/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalCompilationFromGrammar.java
Enable specifying database name in front of filter when there are no joins
> Enable specifying database name in front of filter when there are no joins

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
This PR adds required handlers for percentile function. Depends on https://github.com/finos/legend-pure/pull/385.
> Add handler for percentile function

- legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/grammar/to/RelationalGrammarComposerExtension.java
- legend-engine-language-pure-store-relational/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalMappingGrammarRoundtrip.java
See https://github.com/finos/legend-studio/issues/608
> Bug fix: Handle CR character in relational mapping tester grammar composer

- legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/test/runner/service/ServiceTestRunner.java
When running service test, gather metrics to measure:
- execution plan generation duration
- execution plan compilation duration
- service test execution duration
> Add metrics to ServiceTestRunner

- legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/RelationalCompilerExtension.java
- legend-engine-language-pure-store-relational/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalFunctionHandler.java
Add support for TDS rowValueDifference function
> Add support for rowValueDifference function

- legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/validation/FunctionParameterTypeValidator.java
- legend-engine-executionPlan-execution/src/test/java/org/finos/legend/engine/plan/execution/validation/test/TestParametersValidation.java
- legend-engine-language-pure-dsl-service/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ServiceParserGrammar.g4
- legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/from/ServiceParseTreeWalker.java
- legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/to/HelperServiceGrammarComposer.java
- legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceCompilationFromGrammar.java
- legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceGrammarParser.java
- legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceGrammarRoundtrip.java
- legend-engine-language-pure-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/core/M3ParserGrammar.g4
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/domain/DomainParseTreeWalker.java
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/domain/DomainParser.java
- legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/test/runner/service/ServiceTestRunner.java
- legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/test/runner/service/ValueSpecificationToResultVisitor.java
Grammar suport for test parameters
> Service Test Parameters Support

- legend-engine-application-query/pom.xml
- legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/api/ApplicationQuery.java
- legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/api/QueryStoreManager.java
- legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/model/Query.java
- legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/model/QuerySearchSpecification.java
- legend-engine-application-query/src/test/java/org/finos/legend/engine/application/query/api/TestQueryStoreManager.java
See context in https://github.com/finos/legend-studio/issues/633
> Introduce tagging mechanism for Query

- legend-engine-external-format-json-model/pom.xml
- legend-engine-external-format-json-model/src/main/java/org/finos/legend/engine/external/format/json/JsonExternalFormatExtension.java
- legend-engine-language-external-store-service/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ServiceStoreCompilerExtension.java
- legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/RelationalCompilerExtension.java
- legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/PureClientVersions.java
> Add pure protocol v1_22_0

- legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/grammar/from/RelationalParseTreeWalker.java
- legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperRelationalGrammarComposer.java
- legend-engine-language-pure-store-relational/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalGrammarComposer.java
- legend-engine-language-pure-store-relational/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalMappingGrammarParser.java
- legend-engine-language-pure-store-relational/src/test/resources/mappingWithLeftOuterJoin.json
This PR contains a fix for left_outer join type when it is being composed to grammar.
The change also contains making the joinType case sensitive, it would throw an error otherwise
> fixing the grammar with left outer join, throwing parser issue for 'inner'

- legend-engine-language-pure-store-relational/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/RelationalParserGrammar.g4
- legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalBuilder.java
- legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/grammar/from/RelationalParseTreeWalker.java
- legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperRelationalGrammarComposer.java
- legend-engine-language-pure-store-relational/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalCompilationFromGrammar.java
- legend-engine-language-pure-store-relational/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalMappingGrammarParser.java
- legend-engine-language-pure-store-relational/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalMappingGrammarRoundtrip.java
Support inner join in the filterMapping in Engine
> Support inner join in the filterMapping in Engine

- legend-engine-executionPlan-execution-store-relational-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/DataSourceSpecification.java
- legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/serialization/TemporaryFile.java
- legend-engine-language-pure-compiler-api/src/main/java/org/finos/legend/engine/language/pure/compiler/api/Compile.java
- legend-engine-language-pure-compiler-api/src/test/java/org/finos/legend/engine/language/pure/compiler/api/test/TestCompileApi.java
- legend-engine-query-pure/src/main/java/org/finos/legend/engine/query/pure/api/Execute.java
- legend-engine-query-pure/src/test/java/org/finos/legend/engine/query/pure/api/test/inMemory/TestM2MGrammarCompileAndExecute.java
- legend-engine-services-model-api/src/main/java/org/finos/legend/engine/plan/execution/service/api/ServiceModelingApi.java
- legend-engine-services-model/src/main/java/org/finos/legend/engine/plan/execution/service/ServiceModeling.java
- legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/operational/prometheus/MetricsHandler.java
- legend-engine-shared-javaCompiler/src/main/java/org/finos/legend/engine/shared/javaCompiler/EngineJavaCompiler.java
- legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/test/runner/service/ServiceTestRunner.java
Add new metrics, but don't remove old once yet - need to make sure they are gathering the same data first
> Metrics Handler Refactor first phase

- legend-engine-query-pure/src/main/java/org/finos/legend/engine/query/pure/api/Execute.java
Fix generate plan api to include params while compilation
> Fix generate plan api to include params while compilation

- legend-engine-executionPlan-execution-store-relational/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/AlloyTestServer.java
- legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/serialization/TemporaryFile.java
- legend-engine-executionPlan-execution/src/test/java/org/finos/legend/engine/plan/execution/result/test/serialization/TestTemporaryFile.java
Also tested these changes on Windows and Linux
> Allow build on Mac OSX

- legend-engine-executionPlan-execution-store-inMemory/pom.xml
- legend-engine-executionPlan-execution-store-inMemory/src/main/java/org/finos/legend/engine/plan/execution/stores/inMemory/plugin/InMemoryExecutionNodeExecutor.java
- legend-engine-executionPlan-execution-store-relational/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/RelationalExecutor.java
- legend-engine-executionPlan-execution-store-relational/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/StreamResultToTempTableVisitor.java
- legend-engine-executionPlan-execution-store-relational/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/RelationalExecutionNodeExecutor.java
- legend-engine-executionPlan-execution-store-relational/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/serialization/RealizedRelationalResultCSVSerializer.java
- legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/ExecutionNodeExecutor.java
- legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/graphFetch/GraphFetchResult.java
- legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/graphFetch/GraphObjectsBatch.java
Changes:
- Calculate summary statistics of memory utilization
- Add temp table creation SQLs to spans
- Add property details in case of relational graph fetch execution
> Improve tracing of graph fetch execution

- legend-engine-language-external-store-service/pom.xml
- legend-engine-language-external-store-service/src/main/java/org/finos/legend/engine/language/pure/grammar/from/ServiceStoreParseTreeWalker.java
- legend-engine-language-external-store-service/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperServiceStoreGrammarComposer.java
- legend-engine-language-external-store-service/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceStoreCompilationUtils.java
- legend-engine-language-external-store-service/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceStoreMappingCompilationFromGrammar.java
- legend-engine-language-external-store-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceStoreMappingGrammarParser.java
- legend-engine-language-external-store-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceStoreMappingGrammarRoundtrip.java
Add composer changes for service store mapping path offset feature
> Add composer changes for service store mapping path offset feature

- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/mapping/PureInstanceClassMappingParseTreeWalker.java
- legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/grammar/from/RelationalParseTreeWalker.java
- legend-engine-language-pure-store-relational/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalMappingGrammarParser.java
It seems there is a bug in parsing local mapping property for relational mapping. Instead of populating the owner of the property we are using local property type. 
This bug impacts studio compilation phase
> Fix local mapping property parsing

- legend-engine-executionPlan-execution-external-store-service/src/test/java/org/finos/legend/engine/plan/execution/stores/service/union/TestServiceStoreUnion.java
- legend-engine-executionPlan-execution-external-store-service/src/test/resources/union/mapping.pure
- legend-engine-executionPlan-execution-external-store-service/src/test/resources/union/model.pure
- legend-engine-executionPlan-execution-external-store-service/src/test/resources/union/pathContent.json
- legend-engine-executionPlan-execution-external-store-service/src/test/resources/union/serviceStore.pure
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PureModel.java
Depends on : https://github.com/finos/legend-pure/pull/410
> Add support for CrossStore union & refactor platform store plan generation

- legend-engine-language-pure-dsl-diagram/src/main/java/org/finos/legend/engine/language/pure/dsl/diagram/grammar/to/DiagramGrammarComposerExtension.java
- legend-engine-language-pure-grammar-api/src/test/java/org/finos/legend/engine/language/pure/grammar/api/test/TestJsonToGrammarApi.java
- legend-engine-language-pure-grammar-api/src/test/resources/diagramWithNoGenView.json
adding null checks to fix potential NullPointerException
> fix potential NullPointerException

- legend-engine-external-shared-format-model/src/main/java/org/finos/legend/engine/external/shared/format/model/api/ExternalFormats.java
Fixes serialization of pmcd for generated model.
> add pure protocol object mapper to external formats api

- legend-engine-executionPlan-execution-store-relational/pom.xml
- legend-engine-executionPlan-execution-store-relational/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/generation/connection/TestGeneration.java
Improved assertions in the existing test cases to allow newly added template functions without failing.
> Improved existing test cases to allow new template functions without failing.

- legend-engine-executionPlan-execution-external-store-service/src/main/java/org/finos/legend/engine/plan/execution/stores/service/ServiceExecutor.java
- legend-engine-executionPlan-execution-external-store-service/src/test/java/org/finos/legend/engine/plan/execution/stores/service/showcase/ServiceStoreJsonShowcaseTest.java
- legend-engine-executionPlan-execution-external-store-service/src/test/java/org/finos/legend/engine/plan/execution/stores/service/utils/TestServer.java
- legend-engine-executionPlan-execution-external-store-service/src/test/resources/showcase/json/mapping.pure
- legend-engine-executionPlan-execution-external-store-service/src/test/resources/showcase/json/serviceStore.pure
- legend-engine-language-external-store-service/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ServiceStoreLexerGrammar.g4
- legend-engine-language-external-store-service/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ServiceStoreParserGrammar.g4
- legend-engine-language-external-store-service/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperServiceStoreBuilder.java
- legend-engine-language-external-store-service/src/main/java/org/finos/legend/engine/language/pure/grammar/from/ServiceStoreParseTreeWalker.java
- legend-engine-language-external-store-service/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperServiceStoreGrammarComposer.java
- legend-engine-language-external-store-service/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceStoreCompilationFromGrammar.java
- legend-engine-language-external-store-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceStoreGrammarRoundtrip.java
- legend-engine-protocol-external-store-service/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/service/model/ServiceParameter.java
Add support for allow reserved config for service parameters - https://swagger.io/docs/specification/describing-parameters/ 
Depends on - https://github.com/finos/legend-pure/pull/443
> Add support for allow Reserved config for service parameters

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
Dependant on https://github.com/finos/legend-pure/pull/461
> Handlers for subType

- legend-engine-executionPlan-execution-store-relational/pom.xml
- legend-engine-executionPlan-execution-store-relational/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/AbstractTestSemiStructured.java
- legend-engine-executionPlan-execution-store-relational/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSemiStructuredJoinChainMapping.java
- legend-engine-executionPlan-execution-store-relational/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSemiStructuredParseJsonMapping.java
- legend-engine-executionPlan-execution-store-relational/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSimpleSemiStructuredMapping.java
- legend-engine-executionPlan-execution-store-relational/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/semiStructuredJoinChainMapping.pure
- legend-engine-executionPlan-execution-store-relational/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/semiStructuredParseJsonMapping.pure
- legend-engine-executionPlan-execution-store-relational/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/simpleSemiStructuredMapping.pure
- legend-engine-external-shared-format-model/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperExternalFormat.java
- legend-engine-language-external-store-service/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperServiceStoreClassMappingBuilder.java
- legend-engine-language-pure-store-relational/pom.xml
- legend-engine-language-pure-store-relational/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/RelationalLexerGrammar.g4
- legend-engine-language-pure-store-relational/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/RelationalParserGrammar.g4
- legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalBuilder.java
- legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/grammar/from/RelationalParseTreeWalker.java
- legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperRelationalGrammarComposer.java
- legend-engine-language-pure-store-relational/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalCompilationFromGrammar.java
- legend-engine-language-pure-store-relational/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalMappingGrammarParser.java
- legend-engine-language-pure-store-relational/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalMappingGrammarRoundtrip.java
- legend-engine-protocol-external-shared-format/src/main/java/org/finos/legend/engine/protocol/pure/v1/packageableElement/external/shared/BindingTransformer.java
- legend-engine-protocol-relational/pom.xml
- legend-engine-protocol-relational/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/mapping/RelationalPropertyMapping.java
- legend-engine-protocol-relational/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/datatype/DataType.java
- legend-engine-protocol-relational/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/datatype/SemiStructured.java
- legend-engine-server/pom.xml
- pom.xml
Depends on https://github.com/finos/legend-pure/pull/464
> Relational semi-structured query support (Snowflake)

- legend-engine-executionPlan-execution-external-store-service/src/main/java/org/finos/legend/engine/plan/execution/stores/service/ServiceExecutor.java
- legend-engine-executionPlan-execution-external-store-service/src/test/java/org/finos/legend/engine/plan/execution/stores/service/features/flags/TestServiceStoreParameterFlags.java
- legend-engine-executionPlan-execution-external-store-service/src/test/resources/features/flags/mappings/stub.json
- legend-engine-executionPlan-execution-external-store-service/src/test/resources/features/flags/testGrammar.pure
- legend-engine-language-external-store-service/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ServiceStoreLexerGrammar.g4
- legend-engine-language-external-store-service/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ServiceStoreParserGrammar.g4
- legend-engine-language-external-store-service/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperServiceStoreBuilder.java
- legend-engine-language-external-store-service/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperServiceStoreClassMappingBuilder.java
- legend-engine-language-external-store-service/src/main/java/org/finos/legend/engine/language/pure/grammar/from/ServiceStoreParseTreeWalker.java
- legend-engine-language-external-store-service/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperServiceStoreGrammarComposer.java
- legend-engine-language-external-store-service/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceStoreMappingCompilationFromGrammar.java
- legend-engine-language-external-store-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceStoreGrammarParser.java
- legend-engine-language-external-store-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceStoreGrammarRoundtrip.java
- legend-engine-protocol-external-store-service/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/service/model/ServiceParameter.java
Add support for optional parameters for service store (ref - https://swagger.io/docs/specification/describing-parameters/)
depends on - https://github.com/finos/legend-pure/pull/463
> Add support for optional parameters in service store

- legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/operational/prometheus/MetricsHandler.java
Change bucket sizes and simplify metrics labels
> Change bucket sizes and simplify metrics labels

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
This reverts commit 493f9ee1f0b9100cf2e3bdc0fb993d55fd36d6e2.
> Revert "Handlers for subType (#563)"

- legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/identity/credential/LegendKerberosCredential.java
> fix kerberos ticket iterator

- legend-engine-executionPlan-execution-store-authentication/src/main/java/org/finos/legend/engine/authentication/provider/DatabaseAuthenticationFlowProviderSelector.java
- legend-engine-executionPlan-execution-store-authentication/src/test/java/org/finos/legend/engine/authentication/TestDatabaseAuthenticationFlowProviderSelector.java
- legend-engine-executionPlan-execution-store-relational-connection-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/ExternalIntegration_TestConnectionAcquisitionWithFlowProvider_Databricks.java
- legend-engine-executionPlan-execution-store-relational-connection-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/ExternalIntegration_TestConnectionAcquisitionWithFlowProvider_SqlServer.java
This PR deletes the old API for enabling the flow provider using system properties.
> Delete old flow provider enable/disable APIs

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
Depends on https://github.com/finos/legend-pure/pull/493
> Add whenSubType handler

- legend-engine-executionPlan-execution-store-relational-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/AlloyH2Server.java
- legend-engine-executionPlan-execution-store-relational-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/LegendH2Extensions.java
- legend-engine-executionPlan-execution-store-relational-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/authentication/strategy/DefaultH2AuthenticationStrategy.java
- legend-engine-executionPlan-execution-store-relational/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/AbstractTestSemiStructured.java
- legend-engine-executionPlan-execution-store-relational/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSimpleSemiStructuredMapping.java
- legend-engine-executionPlan-execution-store-relational/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/simpleSemiStructuredMapping.pure
- legend-engine-test-runner-service/pom.xml
- legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/test/runner/service/ServiceTestGenerationHelper.java
Depends on https://github.com/finos/legend-pure/pull/490
> H2 semi-structured navigation using user defined function

- legend-engine-external-format-flatdata-shared/src/main/java/org/finos/legend/engine/external/format/flatdata/shared/driver/core/connection/BufferedReader.java
- legend-engine-external-format-flatdata-shared/src/test/java/org/finos/legend/engine/external/format/flatdata/shared/driver/TestBufferedReader.java
> Fix BOM handling for FlatData

- .github/workflows/release.yml
Updating the Release action to automatically compute the next SNAPSHOT version to use
> Updating Release action

- .github/workflows/database-redshift-integration-test.yml
- legend-engine-executionPlan-execution-store-authentication/src/main/java/org/finos/legend/engine/authentication/LegendDefaultDatabaseAuthenticationFlowProvider.java
- legend-engine-executionPlan-execution-store-authentication/src/main/java/org/finos/legend/engine/authentication/flows/RedshiftWithUserPasswordFlow.java
- legend-engine-executionPlan-execution-store-authentication/src/test/java/org/finos/legend/engine/authentication/TestDefaultSupportedFlows.java
- legend-engine-executionPlan-execution-store-relational-connection-tests/pom.xml
- legend-engine-executionPlan-execution-store-relational-connection-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/DbSpecificTests.java
- legend-engine-executionPlan-execution-store-relational-connection-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/ExternalIntegration_TestConnectionAcquisitionWithFlowProvider_Redshift.java
- legend-engine-executionPlan-execution-store-relational-connection-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/TestRedshiftMultithreading.java
- legend-engine-executionPlan-execution-store-relational-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/redshift/RedshiftManager.java
This PR adds a connection protocol integration test using a real Redshift cluster.
> Add Redshift integration tests

- legend-engine-language-external-store-service/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperServiceStoreClassMappingBuilder.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/Compiler.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ClassMappingSecondPassBuilder.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/CompileContext.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperMappingBuilder.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperModelBuilder.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperValueSpecificationBuilder.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/Milestoning.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/MilestoningDatePropagationHelper.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PropertyMappingBuilder.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PureModel.java
- legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalBuilder.java
- pom.xml
> Upgrade Pure to 1.53.0

- legend-engine-executionPlan-execution-store-relational/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSimpleSemiStructuredMapping.java
- legend-engine-executionPlan-execution-store-relational/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/simpleSemiStructuredMapping.pure
Depends on https://github.com/finos/legend-pure/pull/528
> Improve enumeration property handling in semi-structured queries

- legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/plugin/ServiceExecutionNodeExecutor.java
- legend-engine-xt-serviceStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/service/showcase/jsonApis/ServiceStoreJsonShowcaseTest.java
- legend-engine-xt-serviceStore-executionPlan/src/test/resources/showcase/json/mappings/stub.json
- legend-engine-xt-serviceStore-executionPlan/src/test/resources/showcase/json/testGrammar.pure
Fix service store working with optional query parameters
> Fix service store working with optional query parameters

- legend-engine-xt-persistence-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/PersistenceLexerGrammar.g4
- legend-engine-xt-persistence-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/PersistenceParserGrammar.g4
- legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/compiler/toPureGraph/HelperPersistenceBuilder.java
- legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/grammar/from/PersistenceParseTreeWalker.java
- legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/grammar/to/HelperPersistenceGrammarComposer.java
- legend-engine-xt-persistence-grammar/src/test/java/org/finos/legend/engine/language/pure/dsl/persistence/compiler/test/TestPersistenceCompilationFromGrammar.java
- legend-engine-xt-persistence-grammar/src/test/java/org/finos/legend/engine/language/pure/dsl/persistence/grammar/test/TestPersistenceGrammarParser.java
- legend-engine-xt-persistence-grammar/src/test/java/org/finos/legend/engine/language/pure/dsl/persistence/grammar/test/TestPersistenceGrammarRoundtrip.java
- legend-engine-xt-persistence-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/persistence/persister/transactionmilestoning/BatchIdAndDateTimeTransactionMilestoning.java
- legend-engine-xt-persistence-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/persistence/persister/transactionmilestoning/derivation/SourceSpecifiesInAndOutDateTime.java
- legend-engine-xt-persistence-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/persistence/persister/transactionmilestoning/derivation/SourceSpecifiesInDateTime.java
- legend-engine-xt-persistence-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/persistence/persister/transactionmilestoning/derivation/TransactionDerivation.java
- legend-engine-xt-persistence-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/persistence/persister/transactionmilestoning/derivation/TransactionDerivationVisitor.java
- legend-engine-xt-persistence-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/persistence/persister/validitymilestoning/DateTimeValidityMilestoning.java
- legend-engine-xt-persistence-pure/src/main/resources/core_persistence/persistence/metamodel.pure
- legend-engine-xt-persistence-pure/src/main/resources/core_persistence/persistence/metamodel_diagram.pure
Adapts the following engine PR to work post-refactoring: https://github.com/finos/legend-engine/pull/641
> Add transaction derivation to persistence protocol, parser, and compiler.

- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/SQLQueryToString.pure
This refactors windowColumnProcessor, semiStructuredObjectNavigationProcessor and joinStringsProcessor
> refactor SQLQueryToString fns into db extensions

- legend-engine-server/src/test/java/org/finos/legend/engine/server/test/pureClient/executionPlan/Test_ExecutionPlan_JavaPlatform_UsingPureClient.java
Depends on: https://github.com/finos/legend-pure/pull/554
> Enable pure test cases for java platform code generation

- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/relationalGraphFetch.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/postprocessor/defaultPostProcessor/processInOperation.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/postprocessor/defaultPostProcessor/processObjectReferenceIn.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/vX_X_X/transfers/metamodel_relational.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/relationalExtension.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/relationalMappingExecution.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/relationalTypeTranslations.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/testDataGeneration/testDataGeneration.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/testRelationalExtension.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/transform/fromPure/pureToRelational.pure
It depends on changes in legend-pure: https://github.com/finos/legend-pure/pull/457
> introduce db specific type

- legend-engine-external-format-avro/src/main/java/org/finos/legend/engine/external/format/avro/schema/generations/AvroGenerationConfig.java
config update for avro generation features depends on  https://github.com/finos/legend-pure/pull/565
> avro config update

- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSemiStructuredFlattening.java
- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSemiStructuredInheritanceMapping.java
- legend-engine-xt-relationalStore-executionPlan/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/semiStructuredFlattening.pure
- legend-engine-xt-relationalStore-executionPlan/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/semiStructuredInheritanceMapping.pure
- legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalBuilder.java
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/postprocessor/defaultPostProcessor/reAliasQuery.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/postprocessor/defaultPostProcessor/trimColumnNamePostProcessor.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/SQLQueryToString.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/transform/fromPure/tests/testToSQLString.pure
Depends on https://github.com/finos/legend-pure/pull/562
> Semi structured flatten, subtype navigation support

- .github/workflows/database-bigquery-integration-test.yml
- .github/workflows/database-mssqlserver-integration-test.yml
- .github/workflows/database-mssqlserver-sql-generation-integration-test.yml
- .github/workflows/database-redshift-integration-test.yml
- .github/workflows/database-redshift-sql-generation-integration-test.yml
- .github/workflows/database-snowflake-integration-test.yml
- README.md
Increase heap space for integration test builds + minor workflow refactoring
> Increase heap space for integration test builds + minor workflow refactoring

- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/SQLQueryToString.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/tests/testMemSQLCompatibility.pure
SQLQueryToString: Quote window keyword for MemSQL
> SQLQueryToString: Quote window keyword for MemSQL

- legend-engine-xt-relationalStore-pure/src/test/java/org/finos/legend/pure/code/core/relational/dbSpecific/Test_Pure_Relational_DbSpecific_H2.java
- legend-engine-xt-relationalStore-pure/src/test/java/org/finos/legend/pure/code/core/relational/dbSpecific/Test_Pure_Relational_DbSpecific_Redshift.java
- legend-engine-xt-relationalStore-pure/src/test/java/org/finos/legend/pure/code/core/relational/dbSpecific/Test_Pure_Relational_DbSpecific_Snowflake.java
- legend-engine-xt-relationalStore-pure/src/test/java/org/finos/legend/pure/code/core/relational/dbSpecific/Test_Pure_Relational_DbSpecific_SqlServer.java
Add missing copyrights to fix builds
> Add missing copyrights

- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/postprocessor/defaultPostProcessor/dbSpecificProcessor.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/postprocessor/defaultPostProcessor/processInOperation.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/postprocessor/defaultPostProcessor/trimColumnNamePostProcessor.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/postprocessor/postProcessor.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/relationalTypeTranslations.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/SQLQueryToString.pure
This completes in-file refactoring of sqlQueryToString
> refactor dyna fn sqlQueryToString

- legend-engine-pure-code-compiled-core-external-shared/src/main/resources/core_external_shared/executionPlan/executionPlan.pure
- legend-engine-pure-code-compiled-core-external-shared/src/main/resources/core_external_shared/executionPlan/model.pure
- legend-engine-pure-code-compiled-core-external-shared/src/main/resources/core_external_shared/extension.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan_generation.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/extensions/extension.pure
- legend-engine-xt-flatdata-pure/src/main/resources/core_external_format_flatdata/protocol_vX_X_X.pure
- legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/ServiceStoreExecutionExtension.java
- legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/plugin/ServiceExecutionNodeExecutor.java
- legend-engine-xt-serviceStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/service/showcase/jsonApis/ServiceStoreJsonShowcaseTest.java
- legend-engine-xt-serviceStore-executionPlan/src/test/resources/showcase/json/mappings/stub.json
- legend-engine-xt-serviceStore-executionPlan/src/test/resources/showcase/json/testGrammar.pure
- legend-engine-xt-serviceStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/ServiceStoreProtocolExtension.java
- legend-engine-xt-serviceStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/LimitExecutionNode.java
- legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/executionPlan/executionPlan.pure
- legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/executionPlan/executionPlan_generation.pure
- legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/executionPlan/executionPlan_print.pure
- legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/executionPlan/javaRuntime/executionPlanNodes/limit/limit.pure
- legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/vX_X_X/extension/extension_serviceStore.pure
- legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/vX_X_X/models/executionPlan_serviceStore.pure
- legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/pureToServiceStoreQuery/pureToServiceStoreQuery.pure
- legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/router/router_extension.pure
- legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/router/tests/testRouting.pure
- legend-engine-xt-xml-pure/src/main/resources/core_external_format_xml/protocol_vX_X_X.pure
> Service store supports take

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/executionNode/graphFetch/inMemory/graphFetchInMemory.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/propertyUnion.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/shared.pure
Fix an issue releted to union of subtypes on graphfetch queries
> Fix an issue releted to union of subtypes on graphfetch queries

- legend-engine-xt-analytics-mapping-pure/src/main/resources/core_analytics_mapping/modelCoverageAnalytics.pure
- legend-engine-xt-analytics-mapping-pure/src/main/resources/core_analytics_mapping/modelCoverageAnalyticsHelper.pure
- legend-engine-xt-analytics-mapping-pure/src/main/resources/core_analytics_mapping/modelCoverageAnalyticsTest.pure
- legend-engine-xt-analytics-mapping-pure/src/main/resources/core_analytics_mapping/modelCoverageMappedEntityBuilder.pure
loose primitive property type check for mapping algorithm
> Improve primitive property type check for mapping algorithm

- legend-engine-server/config/config.json
- legend-engine-xt-relationalStore-postgres-execution-tests/pom.xml
- legend-engine-xt-relationalStore-postgres-execution-tests/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/postgres/test/PostgresTestContainerWrapper.java
- legend-engine-xt-relationalStore-postgres-execution-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/postgres/test/TestPostgresTestContainerWrapper.java
- pom.xml
Add module that provides Postgres Docker container test capability.
> Middle tier authz - Postgres tests module

- legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestGrammarParser.java
- legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/identity/credential/middletier/MiddleTierUserPasswordCredential.java
- legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/authentication/strategy/MiddleTierUserNamePasswordAuthenticationStrategy.java
- legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/authentication/strategy/keys/MiddleTierUserNamePasswordAuthenticationStrategyKey.java
- legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/manager/strategic/AuthenticationStrategyKeyGenerator.java
- legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/manager/strategic/AuthenticationStrategyTransformer.java
- legend-engine-xt-relationalStore-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/authentication/AuthenticationStrategyLexerGrammar.g4
- legend-engine-xt-relationalStore-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/authentication/AuthenticationStrategyParserGrammar.g4
- legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/AuthenticationStrategyBuilder.java
- legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/RelationalGrammarParserExtension.java
- legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/authentication/AuthenticationStrategyParseTreeWalker.java
- legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperRelationalGrammarComposer.java
- legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalConnectionCompilationRoundtrip.java
- legend-engine-xt-relationalStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/RelationalProtocolExtension.java
- legend-engine-xt-relationalStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/authentication/MiddleTierUserNamePasswordAuthenticationStrategy.java
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/vX_X_X/invocations/execution_relational_testConnection.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/vX_X_X/models/metamodel_connection.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/vX_X_X/transfers/connection_relational.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/runtime/connection/authenticationStrategy.pure
Add middle tier credential and authentication strategy.
> Middle tier authz - Credential

- legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/serialization/SerializationFormat.java
- legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/RelationalResult.java
- legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/serialization/RelationalResultToCSVSerializerWithTransformersApplied.java
- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/execution/TestRelationalExecutor.java
Add CSV_FIXED serializationFormat
> Add CSV_FIXED serializationFormat

- legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/serialization/SerializationFormat.java
- legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/RelationalResult.java
Rename CSV_FIXED to CSV_TRANSFORMED
> Rename CSV_FIXED to CSV_TRANSFORMED

- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/sybaseIQExtension.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/transform/fromPure/tests/testToSQLString.pure
Add support for 'dayOfMonth' function in SybaseIQ
> Add support for 'dayOfMonth' function in SybaseIQ

- legend-engine-executionPlan-execution-authorizer/pom.xml
- legend-engine-extensions-collection-generation/pom.xml
- legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java
- legend-engine-language-pure-dsl-generation/src/main/java/org/finos/legend/engine/language/pure/dsl/generation/extension/Artifact.java
- legend-engine-language-pure-dsl-generation/src/main/java/org/finos/legend/engine/language/pure/dsl/generation/extension/ArtifactGenerationExtension.java
- legend-engine-server-integration-tests/pom.xml
- legend-engine-xt-data-space-api/pom.xml
- legend-engine-xt-data-space-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperDataSpaceBuilder.java
- legend-engine-xt-data-space-generation/pom.xml
- legend-engine-xt-data-space-generation/src/main/java/org/finos/legend/engine/generation/DataSpaceAnalyticsArtifactGenerationExtension.java
- legend-engine-xt-data-space-generation/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.dsl.generation.extension.ArtifactGenerationExtension
- legend-engine-xt-mastery-grammar/pom.xml
- legend-engine-xt-mastery-pure/pom.xml
- legend-engine-xt-persistence-cloud-grammar/pom.xml
- legend-engine-xt-relationalStore-executionPlan-authorizer/pom.xml
- legend-engine-xt-relationalStore-executionPlan-connection-authentication-default/pom.xml
- legend-engine-xt-relationalStore-executionPlan/pom.xml
- pom.xml
- Adds `ArtifactGenerationExtension` to provide specification for generating an artifact given a packageable elements
- Adds Dataspace implementation
> artifact generation + dataspace impl

- legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/data/HelperRelationalEmbeddedDataComposer.java
- legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalEmbeddedDataGrammarRoundtrip.java
This PR fixes a bug in composer
This PR fixes indentation rendered by composer for relational embedded data
Fixes #
Yes it would change indentation in text mode for studio users but this should be harmless
> Fix indentation for relational embedded data

- legend-engine-executionPlan-generation/src/main/java/org/finos/legend/engine/plan/platform/PlanPlatform.java
- legend-engine-pure-code-compiled-core/src/main/resources/core/external/language/java/generation/conventions.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan_generation.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/extensions/extension.pure
Deprecated code removal
This PR removes deprecated classes and functions in platform binding space
No
> Remove deprecated platform binding code

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/tests/executionPlanTests.pure
Remove recently added deprecated class usage
> Remove recently added deprecated class usage

- legend-engine-xt-persistence-component/pom.xml
Fix
This PR fixes the broken java doc for xt-persistence-component
Fixes #
This PR fixes the broken java doc for xt-persistence-component
No
> Fix java doc persistence comp

- legend-engine-xt-persistence-component/pom.xml
Fix
Fix the java doc build issue
Fixes #
Fix the broken java doc generation
No
> skip java doc for persistence component

- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/relationalExtension.pure
This reverts commit 809c449d2c357cc75d0ca03e153a2cab870cfeb2.
Fixes #
> Revert "Add source data type info for constant columns (#943)"

- legend-engine-xt-serviceStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperServiceStoreClassMappingBuilder.java
- legend-engine-xt-serviceStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceStoreMappingCompilationFromGrammar.java
Enhancement in error reporting
This PR throws better error message when a non-serializable model is used with service store
This relates to https://github.com/finos/legend-engine/issues/953 
Better error reporting for users
> Fix error message in case of non-serializable model used with service store mapping

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/data/diagram.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/test/diagram.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/metamodel/test/relationalTestDiagram.pure
- legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/metamodel/testDataMetamodelDiagram.pure
Fix/Add diagrams for testable/data models
Fix/Add diagrams for testable/data models
No issue raise
No
> Fix/Add diagrams for testable/data models

- legend-engine-server/Dockerfile
- legend-engine-server/src/main/resources/docker/config/config.json
- legend-engine-server/src/main/resources/docker/config/vault.properties
Enhancement
This PR adds a set of default configuration files into the server Docker image. 
This simplifies the running of the Docker images. Users can simply run the container by passing configuration values as environment variables instead of having to manage the configuration files. 
No
> Include default configuration files in Docker image

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperValueSpecificationBuilder.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/MilestoningDatePropagationContext.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/MilestoningDatePropagationHelper.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ProcessingContext.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/builder/CompositeFunctionExpressionBuilder.java
- legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestMilestonedPropertyUsageInFunctionExpresions.java
Bug fix
This PR fixes bug with milestoning date propagation. 
Fixes #
Yes
> Fix milestoning date propagation bug

- legend-engine-pure-code-compiled-core/src/main/resources/core/external/language/java/metamodel_factories.pure
This fixes a bug introduced by https://github.com/finos/legend-engine/pull/903
This fixes a bug causing performance issues
No issue raised
This fixes performance impact users are seeing
> Remove repeated call while merging generated java class

- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/postgresTests.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/redshiftTests.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/suite/sqlQueryTests/ObjectNamingTests/testValidNames.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/suite/sqlQueryTests/aggregateFunctions/groupBy.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/suite/sqlQueryTests/aggregateFunctions/windowColumn.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/suite/sqlQueryTests/selectSubClauses/filters.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/suite/sqlQueryTests/selectSubClauses/join.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/suite/sqlQueryTests/selectSubClauses/mixtureOfClauses.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/suite/sqlQueryTests/selectSubClauses/orderBy.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/suite/sqlQueryTests/selectSubClauses/union.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/suite/sqlQueryTests/selectSubClauses/view.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/suite/sqlQueryTests/shared.pure
- legend-engine-xt-relationalStore-sqlserver-pure/src/main/resources/core_relational_sqlserver/relational/tests/dbSpecificTests/sqlServerTests.pure
This PR add some basic db specific tests which can be run against all databases.
NA
Fixes #
NA
NA
No
> added select based db tests

- .github/workflows/database-postgresql-sql-generation-integration-test.yml
- .github/workflows/stale.yml
Enhancement
I want to make sure certain workflows that should not run in forks to not run in forks
_NA_
No
> turn off certain Github workflows in forks

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan_generation.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure
This PR fixes a bug to set the multiplicity for pure platform expression nodes and in turn correctly build out execution plans
NA
NA
No
> fix multiplicity for pure platform expression node 

- legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/api/ApplicationQueryException.java
Bug fix
This fixes a small bug with `Query APIs` where the error object is not a valid JSON object
_NA_
No
> minor fixes for query API error response

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/extensions/functions.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphExtension.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphFetch_routing.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/mappingExtension.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/router_cluster.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/router_main.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/router_printer.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/contract/storeContract.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
- legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/contract/storeContract.pure
This is a clean-up PR
This PR removes EmbeddedStore from our codebase to cleanup routing/other logic
This is a part of https://github.com/finos/legend-engine/issues/703 
No
> Remove Embedded Store

- legend-engine-xt-serviceStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperServiceStoreClassMappingBuilder.java
- legend-engine-xt-serviceStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceStoreMappingCompilationFromGrammar.java
Bug Fix
Fix service store mapping compiler bug introduced here : https://github.com/finos/legend-engine/pull/954
No issue raise
It faces issue users are facing compiling service store mapping
> Fix service store mapping compiler

- .gcp/cloud-build/build.sh
- .github/workflows/trigger-gcp-build.yml
This change fixes a bug in the GitHub action for GCP
The GCP region variable was not properly quoted - hence the variable was not specified
> Fixing quotes in GitHub actions

- .gcp/cloud-build/build.sh
This PR updates the GCP build script
This PR adjusts the the memory parameters for running the project build in GCP
> Updating GCP build script

- legend-engine-language-pure-modelManager-sdlc/src/main/java/org/finos/legend/engine/language/pure/modelManager/sdlc/SDLCLoader.java
- legend-engine-language-pure-modelManager-sdlc/src/main/java/org/finos/legend/engine/language/pure/modelManager/sdlc/alloy/AlloySDLCLoader.java
- legend-engine-shared-core/src/main/resources/ExceptionData.json
Improvement
Improve error messages for registering prod services
Fixes #
Improve error messages for failing to fetch metadata when registering a prod service
> Improve error messages for failing to fetch metadata

- pom.xml
Enhancement
Speeds up build
No
> Configure heap size of surefire plugin

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/lineage/scanMapping.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/lineage/scanProject.pure
- legend-engine-pure-ide-light/src/main/java/org/finos/legend/engine/ide/PureIDELight.java
- legend-engine-server/pom.xml
- legend-engine-server/src/main/java/org/finos/legend/engine/server/Server.java
- legend-engine-xt-analytics-lineage-api/pom.xml
- legend-engine-xt-analytics-lineage-api/src/main/java/org/finos/legend/engine/api/analytics/LineageAnalytics.java
- legend-engine-xt-analytics-lineage-api/src/main/java/org/finos/legend/engine/api/analytics/model/LineageAnalyticsInput.java
- legend-engine-xt-analytics-lineage-api/src/main/java/org/finos/legend/engine/api/analytics/model/graph/Edge.java
- legend-engine-xt-analytics-lineage-api/src/main/java/org/finos/legend/engine/api/analytics/model/graph/Graph.java
- legend-engine-xt-analytics-lineage-api/src/main/java/org/finos/legend/engine/api/analytics/model/graph/GraphNode.java
- legend-engine-xt-analytics-lineage-api/src/main/java/org/finos/legend/engine/api/analytics/model/report/Column.java
- legend-engine-xt-analytics-lineage-api/src/main/java/org/finos/legend/engine/api/analytics/model/report/ColumnLineage.java
- legend-engine-xt-analytics-lineage-api/src/main/java/org/finos/legend/engine/api/analytics/model/tree/PropertyPathTreeNode.java
- legend-engine-xt-analytics-lineage-api/src/main/java/org/finos/legend/engine/api/analytics/model/tree/RelationalTreeNode.java
- legend-engine-xt-analytics-lineage-pure/pom.xml
- legend-engine-xt-analytics-lineage-pure/src/main/java/org/finos/legend/pure/code/core/CoreExternalLineageAnalysisCodeRepositoryProvider.java
- legend-engine-xt-analytics-lineage-pure/src/main/resources/META-INF/services/org.finos.legend.pure.m3.serialization.filesystem.repository.CodeRepositoryProvider
- legend-engine-xt-analytics-lineage-pure/src/main/resources/core_analytics_lineage.definition.json
- legend-engine-xt-analytics-lineage-pure/src/main/resources/core_analytics_lineage/flow.pure
- legend-engine-xt-analytics-lineage-pure/src/main/resources/core_analytics_lineage/fullAnalytics.pure
- legend-engine-xt-analytics-lineage-pure/src/main/resources/core_analytics_lineage/graph.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/lineage/scanColumns/scanColumns.pure
- pom.xml
enhancement
introduce lineage analytics model and APIs
Fixes #
> Introduce lineage analytics module

- legend-engine-xt-analytics-lineage-api/pom.xml
- legend-engine-xt-analytics-lineage-pure/pom.xml
Fix build
Fix build
Fix build
Fixes #
Fix new modules version
> Fix new module versions

- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/full/graphFetch/dataTypes/TestRelationalGraphFetchExecutionDataTypes.java
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/javaRuntime/executionPlanNodes/graphFetch/graphFetchRelational.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/javaRuntime/executionPlanNodes/relationalClassInstantiation/relationalClassResult.pure
Bug
This PR fixes decimal handling in relational graph fetch execution
No
> Fix decimal handling in relational graph fetch execution

- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/milestoning/milestoning.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/milestoning/tests/testApplyMilestoningFilters.pure
Bug Fix
This PR has changes to handle semi structured relational elements in applyMilestoningFilters function
No
> Handle semi structured relational elements in milestoning filter application

- legend-engine-server/Dockerfile
Improvement
Update Dockerfile to individually copy files
N/A
No
> Fix dockerfile - Individually copy files

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan_generation.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphFetchExecutionPlan.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/modelToModel.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/router_cluster.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/chain.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/inMemory.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/store/platform/executionPlan/executionPlan_generation.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure
This PR cleans up plan gen/router code
Moves let function processing to platform store space
Relates to : https://github.com/finos/legend-engine/issues/703
No
> [Router Clean up] Move let function processing to platform store space

- legend-engine-xt-relationalStore-bigquery-execution-tests/src/test/resources/org/finos/legend/engine/server/test/flowProviderConfig.json
Fix
Fixes currently failing BigQuery Tests
Fixes #
No
> BigQuery Tests - fix flowProviderConfig.json

- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/full/functions/in/TestPlanExecutionForIn.java
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/postprocessor/defaultPostProcessor/pushFiltersDownToJoin.pure
Fix
Include VarPlaceHolder types for filter push down in relational post processing
Filter pushdown to the ON clause can improve relational query performance 
No
> relational filter push down VarPlaceHolder fix

- legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/test/runner/service/ServiceTestRunner.java
Bug fix
Fixes a NPE in the ServiceTestRunner.
Fixes #
No
> Fix NPE bug in ServiceTestRunner

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperModelBuilder.java
- legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestHelperModelBuilder.java
- legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRoundTripWithPureTransformation.java
- legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDomainCompilationFromGrammar.java
- legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestMilestonedPropertyUsageInFunctionExpresions.java
- legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/SimpleRelationalServiceRunner.java
- legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/TestServiceRunner.java
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/domain/DomainParseTreeWalker.java
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperValueSpecificationGrammarComposer.java
- legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestDomainGrammarRoundtrip.java
- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSemiStructuredFlattening.java
- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSemiStructuredInheritanceMapping.java
- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSemiStructuredJoinChainMapping.java
- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSemiStructuredParseJsonMapping.java
- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSimpleSemiStructuredMapping.java
**What type of PR is this?**
Feature Request
**What does this PR do / why is it needed ?**
update the path of Function from package::name to package::function signature
1. Update Engine parser so that the function signature will be used for function.name
2. SDLC identifies the old style (use functionName as the file name) functions, then creates a new entity that has functionName as its path  
3. Studio will create a ‘Delete’ action to delete this kind of entity above, then do a ‘Create’ operation to correct the gitlab file name
**Which issue(s) this PR fixes:**
Fixes #
**Other notes for reviewers:
Does this PR introduce a user-facing change?**
Related to https://github.com/finos/legend-sdlc/pull/515 and https://github.com/finos/legend-studio/pull/1339
Require Alloy changes
> Support function overloading

- legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/pom.xml
- legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/pom.xml
- legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/pom.xml
- legend-engine-xt-persistence-component/pom.xml
Cleanup.
PR #1056 started the creation of a common test suite for milestoned writes into relational sinks.
This PR ensures all test modules use Maven dependency management in line with the rest of the codebase.
None
None
No
> Cleanup test dependencies in persistence milestoning modules.

- legend-engine-pure-code-compiled-core/src/main/resources/core/external/language/java/generation/conventions.pure
- legend-engine-server/src/test/java/org/finos/legend/engine/server/test/pureClient/stores/Test_Relational_UsingPureClientTestSuite.java
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/query/datePeriods.pure
bug fix
This PR fixes a bug due to which platform code was not generated properly when dayOfWeek was used in the query and the query was run via alloy.
####Describe change being introduced by this PR.
I have used elementToPath() so that code matches the path of the object rather than matching the object iteself. And have added test and the path of test is added in the test suite so that the test should run via alloy.
NA
Yes
> fixed issue related to dayOfWeek

- legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/raw/CString.java
- legend-engine-protocol-pure/src/test/java/org/finos/legend/engine/protocol/test/TestCompatibilityAndMigration.java
- legend-engine-xt-graphQL-protocol/pom.xml
Backward compatibility bug fix
To parse and compile 'wrongly defined' protocol serialized files
> Ensure empty sets of type String and mul 1 translate to empty String

- legend-engine-xt-mastery-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/MasteryLexerGrammar.g4
- legend-engine-xt-mastery-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/MasteryParserGrammar.g4
- legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/from/MasteryParseTreeWalker.java
- legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/to/HelperMasteryGrammarComposer.java
- legend-engine-xt-mastery-grammar/src/test/java/org/finos/legend/engine/language/pure/dsl/mastery/compiler/test/TestMasteryCompilationFromGrammar.java
- legend-engine-xt-mastery-pure/src/main/resources/core_mastery/mastery/metamodel_diagram.pure
Reverts finos/legend-engine#1091
> Revert "Mastery id refactor"

- legend-engine-test-runner-service/src/test/java/org/finos/legend/engine/testable/service/TestServiceTestSuite.java
- legend-engine-test-runner-service/src/test/resources/testable/relational/legend-testable-relational-model.pure
- legend-engine-test-runner-service/src/test/resources/testable/relational/legend-testable-relational-service-enum-parameters.pure
Testcase for Studio Service test with enum as parameter(testables)
> Add tests for enum param in testables

- pom.xml
legend-pure version bump
Legend release
> Upgrade legend-pure version to 3.7.2

- legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/LegendH2Extensions.java
- legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/authentication/strategy/DefaultH2AuthenticationStrategy.java
- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSemiStructuredParseJsonMapping.java
- legend-engine-xt-relationalStore-executionPlan/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/semiStructuredParseJsonMapping.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/h2Extension.pure
Bug fix
This PR adds support for testing semi structured relational mappings with parseJson function usage
Fixes #1110 
No
> Support testing of semi structured mappings with parseJson

- legend-engine-xt-haskell-grammar/pom.xml
Fix haskell grammar pom
Fixes #
> Fix Haskell grammar pom

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperModelBuilder.java
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/domain/DomainParseTreeWalker.java
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperDomainGrammarComposer.java
- legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestGrammarParser.java
- legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestDomainGrammarRoundtrip.java
- legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/context/EngineErrorType.java
- legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/domain/AggregationKind.java
- legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/operational/errorManagement/EngineException.java
New Feature
Added support for property aggregation: `AggregationKind.None`, `AggregationKind.Shared`, `AggregationKind.Composite` like what we have in `legend-pure`
> add support for property aggregation

- legend-engine-external-shared-format-model/src/main/java/org/finos/legend/engine/external/shared/format/model/api/GenerateModelInput.java
- legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/format/GraphQLFormatExtension.java
> Fix GraphQL ExternalFormat configuration

- .github/workflows/build.yml
- .github/workflows/release.yml
- pom.xml
>  Configure Xmx - 3g to main proc, 2g to forked

- legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDomainCompilationFromGrammar.java
- legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestDomainGrammarRoundtrip.java
Improvement
This PR adds unit tests for parsing and compilation of graph fetch trees with qualified properties (taking in parameters which can be lists)
No
> Add parser and compiler tests for qualifiers in graph fetch tree

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/CompileContext.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperModelBuilder.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PureModel.java
- legend-engine-xt-diagram-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperDiagramBuilder.java
- legend-engine-xt-diagram-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestDiagramGrammarRoundtrip.java
Bug fix
Related to https://github.com/finos/legend-studio/issues/1593
Fixes #
> Fix a bug with diagram property view referencing association

- legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/simpleObjectXml.pure
Add test
Add Xml Test to showcase parsing of default value
Fixes #
> Add Xml Test to showcase parsing of default value

- legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/validation/ParameterValidationContextExecutor.java
- legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/TestServiceRunner.java
- legend-engine-language-pure-dsl-service-execution/src/test/resources/org/finos/legend/engine/pure/dsl/service/execution/test/enumServiceParameter.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan_generation.pure
- legend-engine-query-pure/src/test/java/org/finos/legend/engine/query/pure/api/test/inMemory/TestQueryExecutionWithParameters.java
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/relationalMappingExecution.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbExtension.pure
Extends support for optional enum parameters and for now give a proper message to user if trying with collection of enums as it is not supported at the moment.
No
> Optional & Collection Enum Parameter

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphFetchExecutionPlan.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_18_0/transfers/executionPlan.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/relationalGraphFetch.pure
> Remove deprecated graph fetch plan models

- .github/workflows/build-large-runner.yml
- .github/workflows/build.yml
- .github/workflows/release-large-runner.yml
- .github/workflows/release.yml
- pom.xml
The quotes for setting -Darguments on the maven release:perform command were wrong.
This fixes the way we pass -DargLine through -Darguments
> Fixing quotes for maven release command

- legend-engine-pure-ide-light/src/main/java/org/finos/legend/engine/ide/PureIDELight.java
Bug
Fix a bug in how repositories are loaded when starting Pure IDE Light
This will fix a bug for users of Pure IDE Light
> Fix repository loading in PureIDELight

- legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/TestServiceRunner.java
- legend-engine-language-pure-dsl-service-execution/src/test/resources/org/finos/legend/engine/pure/dsl/service/execution/test/simpleM2MService.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/dataQuality.pure
- legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/generation/conventions.pure
- legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/generation/expressionGeneration.pure
> Fixing StackOverFlow Issue For Alloy M2M Recursive Functions

- legend-engine-external-shared-format-model/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ExternalFormatCompilerExtension.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/executionPlan_generation.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/model.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/functions/functions.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/dataQuality/dataQuality.pure
- legend-engine-xt-flatdata-javaPlatformBinding-pure/src/main/resources/core_external_format_flatdata_java_platform_binding/legendJavaPlatformBinding/externalize.pure
- legend-engine-xt-flatdata-javaPlatformBinding-pure/src/main/resources/core_external_format_flatdata_java_platform_binding/legendJavaPlatformBinding/internalize.pure
- legend-engine-xt-flatdata-javaPlatformBinding-pure/src/main/resources/core_external_format_flatdata_java_platform_binding/legendJavaPlatformBinding/shared.pure
- legend-engine-xt-flatdata-runtime/src/test/java/org/finos/legend/engine/external/format/flatdata/read/test/TestFlatDataQueries.java
- legend-engine-xt-flatdata-runtime/src/test/resources/queries/externalizeResultWithSmallerTree.csv
- legend-engine-xt-json-javaPlatformBinding-pure/src/main/resources/core_external_format_json_java_platform_binding/legendJavaPlatformBinding/externalize.pure
- legend-engine-xt-json-pure/src/main/resources/core_external_format_json/executionPlan/tests/executionPlanTest.pure
- legend-engine-xt-json-runtime/src/test/java/org/finos/legend/engine/external/format/json/read/test/TestJsonSchemaQueriesDeprecated.java
- legend-engine-xt-json-runtime/src/test/resources/queries/firmTreeDefectsResultSubset.json
- legend-engine-xt-json-runtime/src/test/resources/queries/firmTreeResultSubset.json
Enhancement
Add support for externalize with GFT
Aligns with https://github.com/finos/legend-engine/issues/703
Yes, user will be able to provide tree with externalize function
> Add support for externalize with GFT

- legend-engine-server/src/main/java/org/finos/legend/engine/server/Server.java
- legend-engine-xt-graphQL-query/pom.xml
- legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/debug/GraphQLDebug.java
- legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/execute/GraphQLExecute.java
- legend-engine-xt-graphQL-query/src/test/java/org/finos/legend/engine/query/graphQL/api/test/TestGraphQLAPI.java
- legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/Project1_Workspace1.pure
- legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/Project2_Workspace1.pure
Bug Fix
This PR enables GraphQL APIs to be instantiated with extensions (from server configuration)
No
> Add ability to instantiate GraphQL APIs with extensions

- .github/workflows/database-bigquery-sql-generation-integration-test.yml
- .github/workflows/database-databricks-sql-generation-integration-test.yml
- .github/workflows/database-mssqlserver-sql-generation-integration-test.yml
- .github/workflows/database-postgresql-sql-generation-integration-test.yml
- .github/workflows/database-redshift-sql-generation-integration-test.yml
- .github/workflows/database-snowflake-sql-generation-integration-test.yml
- .github/workflows/database-spanner-sql-generation-integration-test.yml
- legend-engine-xt-relationalStore-bigquery-pure/src/main/resources/core_relational_bigquery.definition.json
- legend-engine-xt-relationalStore-bigquery-pure/src/main/resources/core_relational_bigquery/relational/sqlQueryToString/customBigQueryTests.pure
- legend-engine-xt-relationalStore-bigquery-pure/src/test/java/org/finos/legend/pure/code/core/Test_Pure_Relational_Custom_BigQuery.java
- legend-engine-xt-relationalStore-sqlserver-pure/src/main/resources/core_relational_sqlserver.definition.json
- legend-engine-xt-relationalStore-sqlserver-pure/src/main/resources/core_relational_sqlserver/relational/sqlQueryToString/customSqlServerTests.pure
- legend-engine-xt-relationalStore-sqlserver-pure/src/test/java/org/finos/legend/pure/code/core/Test_Pure_Relational_Custom_SqlServer.java
- legend-engine-xt-relationalStore-test-server/src/main/java/org/finos/legend/engine/server/test/shared/Relational_DbSpecific_UsingPureClientTestSuite.java
Test improvement
It prints summary of test results post db integration test workflow run, so that we don't have to go through build logs.
None
No
> print test summary post db integration test workflow run

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PureModel.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/Warning.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/extension/CompilerExtension.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/extension/CompilerExtensions.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/validator/MappingValidator.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/validator/MappingValidatorContext.java
- legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestCompilationFromGrammar.java
- legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDomainCompilationFromGrammar.java
- legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/IRelationalCompilerExtension.java
- legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/RelationalCompilerExtension.java
- legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/validation/RelationalValidator.java
- legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalCompilationFromGrammar.java
Add warnings to the relational compiler 
Alert users when their code does not compile correctly
Yes - warnings will be generated on the compiler and shown in studio.
> add warnings to relational compiler

- legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalBuilder.java
- legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalCompilationFromGrammar.java
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/relationalMappingExecution.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/testRelationalExtension.pure
New feature
It adds compilation check for incompatible type is mapping
Fixes #
yes
> Throw warnings for incompatible types in relational property mappings

- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/mapping/EnumerationMappingParseTreeWalker.java
- legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestMappingGrammarRoundtrip.java
Bug
Fix parsing of enum mapping with special characters
Fixes #
> Fix parsing of enum mapping with special characters

- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/milestoning/milestoning.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/milestoning/tests/testBusinessDateMilestoning.pure
Revert
Reverting AllVersions fix temporarily.
Fixes #
Yes
> Revert "Fix sql generation for AllVersions query (#1121)"

- legend-engine-pure-code-compiled-core-configuration/src/main/resources/core_configuration/coreExtensions.pure
- legend-engine-xt-flatdata-javaPlatformBinding-pure/src/main/resources/core_external_format_flatdata_java_platform_binding.definition.json
- legend-engine-xt-flatdata-javaPlatformBinding-pure/src/main/resources/core_external_format_flatdata_java_platform_binding/legendJavaPlatformBinding/descriptor.pure
- legend-engine-xt-flatdata-javaPlatformBinding-pure/src/main/resources/core_external_format_flatdata_java_platform_binding/legendJavaPlatformBinding/engineDependencies.pure
- legend-engine-xt-flatdata-javaPlatformBinding-pure/src/main/resources/core_external_format_flatdata_java_platform_binding/legendJavaPlatformBinding/executionPlanTest.pure
- legend-engine-xt-flatdata-javaPlatformBinding-pure/src/main/resources/core_external_format_flatdata_java_platform_binding/legendJavaPlatformBinding/externalize.pure
- legend-engine-xt-flatdata-javaPlatformBinding-pure/src/main/resources/core_external_format_flatdata_java_platform_binding/legendJavaPlatformBinding/internalize.pure
- legend-engine-xt-flatdata-javaPlatformBinding-pure/src/main/resources/core_external_format_flatdata_java_platform_binding/legendJavaPlatformBinding/shared.pure
- legend-engine-xt-flatdata-javaPlatformBinding-pure/src/test/java/org/finos/legend/engine/pure/code/core/Test_Pure_FlatDataJavaPlatformBinding.java
- legend-engine-xt-flatdata-runtime/src/main/java/org/finos/legend/engine/external/format/flatdata/FlatDataJavaCompilerExtension.java
- legend-engine-xt-flatdata-runtime/src/test/java/org/finos/legend/engine/external/format/flatdata/read/test/TestFlatDataQueries.java
- legend-engine-xt-json-javaPlatformBinding-pure/src/main/resources/core_external_format_json_java_platform_binding.definition.json
- legend-engine-xt-json-javaPlatformBinding-pure/src/main/resources/core_external_format_json_java_platform_binding/legendJavaPlatformBinding/descriptor.pure
- legend-engine-xt-json-javaPlatformBinding-pure/src/main/resources/core_external_format_json_java_platform_binding/legendJavaPlatformBinding/engineDependencies.pure
- legend-engine-xt-json-javaPlatformBinding-pure/src/main/resources/core_external_format_json_java_platform_binding/legendJavaPlatformBinding/executionPlanTest.pure
- legend-engine-xt-json-javaPlatformBinding-pure/src/main/resources/core_external_format_json_java_platform_binding/legendJavaPlatformBinding/externalize.pure
- legend-engine-xt-json-javaPlatformBinding-pure/src/main/resources/core_external_format_json_java_platform_binding/legendJavaPlatformBinding/internalize.pure
- legend-engine-xt-json-javaPlatformBinding-pure/src/test/java/org/finos/legend/engine/pure/code/core/Test_Pure_JsonJavaPlatformBinding.java
- legend-engine-xt-json-runtime/src/main/java/org/finos/legend/engine/external/format/json/JsonJavaCompilerExtension.java
- legend-engine-xt-json-runtime/src/test/java/org/finos/legend/engine/external/format/json/read/test/TestJsonSchemaQueries.java
- legend-engine-xt-json-runtime/src/test/java/org/finos/legend/engine/external/format/json/read/test/TestJsonSchemaQueriesDeprecated.java
- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/AbstractTestSemiStructured.java
- legend-engine-xt-serviceStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/service/utils/ServiceStoreTestUtils.java
- legend-engine-xt-xml-javaPlatformBinding-pure/src/main/resources/core_external_format_xml_java_platform_binding.definition.json
- legend-engine-xt-xml-javaPlatformBinding-pure/src/main/resources/core_external_format_xml_java_platform_binding/legendJavaPlatformBinding/descriptor.pure
- legend-engine-xt-xml-javaPlatformBinding-pure/src/main/resources/core_external_format_xml_java_platform_binding/legendJavaPlatformBinding/engineDependencies.pure
- legend-engine-xt-xml-javaPlatformBinding-pure/src/main/resources/core_external_format_xml_java_platform_binding/legendJavaPlatformBinding/internalize.pure
- legend-engine-xt-xml-javaPlatformBinding-pure/src/test/java/org/finos/legend/engine/pure/code/core/Test_Pure_XmlJavaPlatformBinding.java
- legend-engine-xt-xml-runtime/src/main/java/org/finos/legend/engine/external/format/xml/XmlJavaCompilerExtension.java
- legend-engine-xt-xml-runtime/src/test/java/org/finos/legend/engine/external/format/xml/test/TestXmlQueries.java
Enhancement/Refactoring
Rename external format Java platform binding packages
No
> Rename external format Java platform binding packages

- legend-engine-pure-runtime-compiler/src/main/java/org/finos/legend/engine/pure/runtime/compiler/compiled/natives/LegendCompileVS.java
- legend-engine-xt-graphQL-grammar-integration/src/test/java/org/finos/legend/engine/language/graphQL/grammar/integration/test/TestGraphQLEmbedded.java
Bug fix
Fix metadata source in compiled mode for `compileVS`
None
Enum comparison (between enum created in `compileVS` and enum created in pure) fails in compiled mode, but succeeds in interpreted mode.
This PR would fix above issue.
`compileVS` is only used by GraphQL, so this is a low risk/low impact change
There is no user-facing change introduced by this PR
> Specify metadata for LegendCompileVS

- CODEOWNERS
> add MauricioUyaguari as codeOwner

- legend-engine-language-pure-dsl-service/pom.xml
- legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/compiler/toPureGraph/HelperServiceBuilder.java
- legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceCompilationFromGrammar.java
- legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceGrammarRoundtrip.java
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/metaExtension.pure
Enhancement
Add support for registration of services with binding queries
Aligns with https://github.com/finos/legend-engine/issues/703
yes
> Add support for registration of services with binding queries

- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/milestoning/tests/businessDateMilestoningSetUp.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/milestoning/tests/testBusinessDateMilestoning.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
Bug fix
When filter operation was used inside view, Multiple filtering operation were not combined properly(with the help of and/or)
So this PR fixes that bug.
Filtering operations were simply concatenated previously because of which multiple filtering operations were present and that was causing issue, So PushExtraFilteringOperation function is used to combine those filtering operations with the help of OR/AND.
Yes
> fix bug in filterOnView

- legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/planner/BitemporalDeltaPlanner.java
Test Fix
Fixing the failing tests in Bitemporal Delta Milestoning
Because of merge issues, some tests where failing in Persistence.
This PR fixes the failing test.
Fix the logic for getRowsUpdated in Bitemporal Delta Milestoning
NO
> Persistence: Fix the failing test in Bitemporal Delta

- legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/TestServiceRunner.java
- legend-engine-language-pure-dsl-service-execution/src/test/resources/org/finos/legend/engine/pure/dsl/service/execution/test/simpleM2MService.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/inMemory/graphFetchInMemory.pure
> Updating M2M Error Message To Include Context On What Failed

- legend-engine-xt-relationalStore-grammar/pom.xml
- legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalBuilder.java
- legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalCompilationFromGrammar.java
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/relationalMappingExecution.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/testRelationalExtension.pure
Reverts finos/legend-engine#1205
Some complex queries are showing poor performance when executing this.
> Revert "Throw warnings for incompatible types in relational property mappings"

- legend-engine-pure-ide-light/src/main/resources/pure_ide/diagram.pure
Enhancement
This is needed to enhance Pure IDE capability
> Pure IDE: Expose source information for getDiagramInfo service

- legend-engine-external-shared-format-model/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ExternalFormatCompilerExtension.java
- legend-engine-external-shared-format-runtime/src/test/java/org/finos/legend/engine/external/shared/runtime/test/TestExternalFormatQueries.java
- legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceCompilationFromGrammar.java
- legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceGrammarRoundtrip.java
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/deprecated.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/executionPlan_diagram.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/executionPlan_generation.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/executionPlan_print.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/model.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/tests/executionPlanTests.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/extension.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/functions/functions.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/schemaSet/metamodel_diagram.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/data/data.pure
- legend-engine-xt-flatdata-pure/src/main/resources/core_external_format_flatdata/executionPlan/tests/executionPlanTest.pure
- legend-engine-xt-flatdata-runtime/src/test/java/org/finos/legend/engine/external/format/flatdata/read/test/TestFlatDataQueries.java
- legend-engine-xt-json-javaPlatformBinding-pure/src/main/resources/core_external_format_json_java_platform_binding/legendJavaPlatformBinding/executionPlanTest.pure
- legend-engine-xt-json-pure/src/main/resources/core_external_format_json/executionPlan/tests/executionPlanTest.pure
- legend-engine-xt-json-runtime/src/test/java/org/finos/legend/engine/external/format/json/read/test/TestJsonSchemaQueries.java
- legend-engine-xt-json-runtime/src/test/java/org/finos/legend/engine/external/format/json/read/test/TestJsonSchemaQueriesDeprecated.java
- legend-engine-xt-xml-pure/src/main/resources/core_external_format_xml/executionPlan/tests/executionPlanTest.pure
- legend-engine-xt-xml-runtime/src/test/java/org/finos/legend/engine/external/format/xml/test/TestXmlQueries.java
Cleanup
Remove Url support with internalize and stage for cleanup
Aligns with https://github.com/finos/legend-engine/issues/703
No
> Remove Url support with internalize and stage for cleanup

- .github/workflows/database-bigquery-sql-generation-integration-test.yml
- .github/workflows/database-databricks-sql-generation-integration-test.yml
- .github/workflows/database-mssqlserver-sql-generation-integration-test.yml
- .github/workflows/database-postgresql-sql-generation-integration-test.yml
- .github/workflows/database-redshift-sql-generation-integration-test.yml
- .github/workflows/database-snowflake-sql-generation-integration-test.yml
- .github/workflows/database-spanner-sql-generation-integration-test.yml
- .github/workflows/summarize-sql-generation-integration-tests.yml
Github workflow improvement
Default download-artifact action does not downloads artifacts from other workflows. Use a different action, which contains this functionality.
None
None
> use github action which downloads artifacts across workflows 

- legend-engine-extensions-collection-generation/pom.xml
- legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java
- legend-engine-language-pure-dsl-generation/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/fileGeneration/FileGenerationType.java
- legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/deprecated/generation.pure
- legend-engine-xt-graphQL-query/pom.xml
- legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/format/GraphQLGenerationConfigFromFileGenerationSpecificationBuilder.java
- legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/format/GraphQLGenerationExtension.java
- legend-engine-xt-graphQL-query/src/test/java/org/finos/legend/engine/query/graphQL/api/test/TestGraphQLFileGeneration.java
- legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/schema.graphql
- legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/simpleFileGeneration.json
Feature/Enhancement
This PR enables support for generation of graphql schema in studio pipelines
Fixes #
Yes
> GraphQL file generation in studio pipelines

- .github/workflows/summarize-sql-generation-integration-tests.yml
Github workflow improvement
Currently, summarization workflow skips failed actions. Set it to not skip them.
None
None
> download summary of failed actions too

- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/sybaseIQ/sybaseIQExtension.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/mapping/sqlFunction/testSqlFunctionsInMapping.pure
Revert parseDate implementation for Sybase IQ
Revert parseDate to handle previously handled scenarios (i.e. yyyyMMdd format)
N/A
Fixes #
No
> Revert parseDate implementation of sybase IQ

- docs/store/extensions/Relational/README.md
- docs/store/extensions/Relational/database-integration-tests/README.md
- docs/store/extensions/Relational/new-connector-tutorial.md
Documentation
documentation for adding new relational connectors
None
None
> documentation for adding new relational connectors

- pom.xml
Version upgrade
Upgrade legend pure version
Fixes #
> Upgrade legend pure version

- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/h2/h2Extension.pure
Always lowercase reservedKeyword Check
Bug fix
make sure we compare lowercase strings always 
Fixes #
Yes, users will now be able to execute tests
> Always lowercase reservedKeyword check

- docs/store/extensions/Relational/new-connector-tutorial.md
Documentation Improvement
add tutorial section on adding new data source or auth strategy specs
None
None
> add tutorial section on adding new data source or auth strategy specs

- legend-engine-pure-ide-light/src/main/resources/pure_ide/concepts.pure
bug fix
minor fixes for concept tree display in Pure IDE for function type parameter
Fixes #
> Pure IDE: minor fixes for concept tree display

- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/databricks/databricksExtension.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/memSql/memSqlExtension.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/testSuite/dynaFunctions/string.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/testSuiteCompletenessTests.pure
New feature
Add support for matches in dynaFunction for memSQL
Fixes #
yes
> Add support for matches in dynaFunction for memSQL

- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/memSql/customMemSQLTests.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/memSql/memSqlExtension.pure
Bug fix
boolean literals should not be enclosed in quotes for MemSQL queries.
Fixes #
> Memsql boolean literal processor fix

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/runtime/runtimeExtension.pure
Error reporting
Throw better error message for misconfigured runtime
Fixes #
Yes better error message
> Throw better error message for mis-configured runtime

- legend-engine-server/src/test/java/org/finos/legend/engine/server/test/pureClient/executionPlan/Test_ExecutionPlan_JavaPlatform_UsingPureClient.java
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/inMemory/graphFetchJson.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/inMemory/graphFetchXml.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/assertLibrary.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/booleanLibrary.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/collectionsLibrary.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/engineConventions.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/jacksonSupport.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/langLibrary.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/mathLibrary.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/metaLibrary.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/multiplicityLibrary.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/pureDateLibrary.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/runtimeLibrary.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/stringLibrary.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/booleanLibraryTests.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/collectionsLibraryTests.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/langLibraryTests.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/mathLibraryTests.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/metaLibraryTests.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/multiplicityLibraryTests.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/pureDateLibraryTests.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/runtimeLibraryTests.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/stringLibraryTests.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/testUtils.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/unitLibraryTests.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/unitLibrary.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/shared/common.pure
Refactoring/Enhancement
This PR renames library Java binding packages
No
> Rename library Java binding packages

- legend-engine-xt-protobuf-grammar/src/main/antlr4/org/finos/legend/engine/language/protobuf3/grammar/from/antlr4/Protobuf3.g4
- legend-engine-xt-protobuf-grammar/src/main/java/org/finos/legend/engine/language/protobuf3/grammar/from/Protobuf3GrammarParser.java
- legend-engine-xt-protobuf-grammar/src/main/java/org/finos/legend/engine/language/protobuf3/grammar/to/Protobuf3GrammarComposer.java
- legend-engine-xt-protobuf-grammar/src/test/java/org/finos/legend/engine/language/protobuf3/grammar/test/TestProtobuf3.java
- legend-engine-xt-protobuf-pure/src/main/resources/core_external_format_protobuf/metamodel/metamodel.pure
- legend-engine-xt-protobuf-pure/src/main/resources/core_external_format_protobuf/metamodel/metamodel_serialization.pure
- legend-engine-xt-protobuf-pure/src/main/resources/core_external_format_protobuf/transformation/fromPure/pureToProtobuf.pure
- legend-engine-xt-protobuf-pure/src/main/resources/core_external_format_protobuf/transformation/fromPure/tests/pureToProtobufTests.pure
- legend-engine-xt-protobuf/src/test/java/org/finos/legend/engine/external/format/protobuf/tests/TestProtobufFileGeneration.java
Enhancement
Add optional field support for protobuf
Fixes #
Yes, adds a new feature
> Add optional field support for protobuf

- legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/compiler/toPureGraph/ServiceCompilerExtensionImpl.java
Error Reporting
Throw warning if both legacy and strategic tests are used
Fixes #
yes, better warning for user
> Throw warning if both legacy and strategic tests are used

- docs/store/extensions/Relational/README.md
- docs/store/extensions/Relational/database-integration-tests/README.md
Docs Improvement
Improve db integration tests docs. Add a section on fixing db integration tests, apart from few minor things.
None
No
> improve db integration tests docs

- .github/workflows/database-athena-integration-test.yml
- .github/workflows/database-athena-sql-generation-integration-test.yml
- legend-engine-xt-relationalStore-athena-execution-tests/pom.xml
Github Workflow
download athena jar for running db integration tests, as it not available via maven
None
No
> download athena jar for running db integration tests

- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/memSql/customMemSQLTests.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/memSql/memSqlExtension.pure
> Adding WeekofYear DynaFunction For MEMSQL

- legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/generation/conventions.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/stringLibraryTests.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/tests/testSimpleRelationalGraphFetch.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/relationalSetUp.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/testModel/simpleTestModel.pure
> Adding Fix For Java Reserved Words When Used As Pure Class Properties

- legend-engine-protocol-generation/src/main/java/org/finos/legend/engine/protocol/generation/GenerateMetaClasses.java
- legend-engine-protocol-generation/src/main/java/org/finos/legend/engine/protocol/generation/GenerateTranslator.java
- legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/PackageableElement.java
- legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/connection/Connection.java
- legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/generation/conventions.pure
- legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/protocol/generation/generation.pure
- legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/protocol/generation/generation_conventions_helper.pure
- legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/protocol/generation/generation_test.pure
Enhancement
This PR enhances java generation to support generics. This is a prerequisite to be able to generate the Elasticsearch protocol given it leverage generics on some classes.
It also adds mechanism to provide custom conventions to protocol generation.  This allow to extend elements that already have protocol classes like Store and Connection.
Fixes #
> Enhance java generation to support generics and ways to extend protocol generation

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/data/core/EmbeddedDataCompilerHelper.java
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/data/embedded/ModelStoreDataParseTreeWalker.java
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/mapping/MappingParseTreeWalker.java
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/data/ModelStoreDataGrammarComposer.java
- legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestMappingGrammarRoundtrip.java
- legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/modelToModel/connection/ModelStoreTestConnectionFactory.java
Cleanup for m2m mapping test suites, we no more use the mechanism of generated bindings.
Fixes #866 
No
> cleanup model to model test suite parser and compiler

- legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/graphFetch/GraphObjectsBatch.java
- legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/TestServiceRunner.java
- legend-engine-language-pure-dsl-service-execution/src/test/resources/org/finos/legend/engine/pure/dsl/service/execution/test/simpleRelationalService.pure
- legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/RelationalExecutionNodeExecutor.java
- legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/graphFetch/RelationalGraphObjectsBatch.java
Bug Fix
Use custom batch size for relational graphfetch
Fixes #
yes
> Use custom batch size for relational graphfetch

- legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalBuilder.java
- legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalCompilationFromGrammar.java
feature improvement 
provides more help to users as they are editing by giving them warnings about duplicates in their tables
> create compilation warning for duplicate columns in a table

- .github/workflows/database-athena-sql-generation-integration-test.yml
- .github/workflows/database-bigquery-sql-generation-integration-test.yml
- .github/workflows/database-databricks-sql-generation-integration-test.yml
- .github/workflows/database-mssqlserver-sql-generation-integration-test.yml
- .github/workflows/database-postgresql-sql-generation-integration-test.yml
- .github/workflows/database-redshift-sql-generation-integration-test.yml
- .github/workflows/database-snowflake-sql-generation-integration-test.yml
- .github/workflows/database-spanner-sql-generation-integration-test.yml
- docs/store/extensions/Relational/README.md
- legend-engine-xt-relationalStore-test-server/src/main/java/org/finos/legend/engine/server/test/shared/Relational_DbSpecific_UsingPureClientTestSuite.java
Test Reporting Improvement
Detailed test summary for db integration workflows
None
No
> Detailed test summary for db integration workflows

- pom.xml
update legend pure to 3.8.3
update legend pure to 3.8.3 for next release
> update legend pure to 3.8.3

- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/contract/storeContract.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/tests/union/testUnionRootLevel_relational.pure
> fix root union support on relational graph fetch as router union

- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/memSql/customMemSQLTests.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/memSql/memSqlExtension.pure
> Revert memsql boolean literal processor

- legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/RelationalCompilerExtension.java
- legend-engine-xt-relationalStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/RelationalDatabaseConnection.java
- legend-engine-xt-relationalStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/postprocessor/PostProcessor.java
> revert adding precedence for Post processor

- legend-engine-xt-authentication-implementation-core/pom.xml
- legend-engine-xt-authentication-implementation-core/src/main/java/org/finos/legend/authentication/intermediationrule/impl/EncryptedPrivateKeyFromVaultRule.java
- legend-engine-xt-authentication-implementation-core/src/test/java/org/finos/legend/authentication/TestCredentialCreation_EncryptedApiKey.java
Enhancement 
Removes Snowflake and Guava dependencies from one of the core authentication modules.
N/A
No
> Refactor Legend authentication - Dependency cleanup

- legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java
- legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/fromPure/sdl/fromPure_sdl.pure
- legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/contract.pure
- legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/format/GraphQLSDLFormatExtension.java
- legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/format/ModelToGraphQLSchemaConfiguration.java
- legend-engine-xt-graphQL-query/src/main/resources/META-INF/services/org.finos.legend.engine.external.shared.format.model.ExternalFormatExtension
https://user-images.githubusercontent.com/29690824/212981802-8c8637cb-15ca-4491-82d4-a76769bd336c.mp4
> add graphQL SDL xt extension

- legend-engine-xt-authentication-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/authentication/compiler/toPureGraph/AuthenticationCompilerExtension.java
- legend-engine-xt-authentication-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/authentication/compiler/toPureGraph/HelperAuthenticationBuilder.java
- legend-engine-xt-authentication-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/authentication/compiler/toPureGraph/IAuthenticationCompilerExtension.java
- legend-engine-xt-authentication-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/authentication/grammar/from/AWSCredentialsParser.java
- legend-engine-xt-authentication-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/authentication/grammar/from/AuthenticationGrammarParserExtension.java
- legend-engine-xt-authentication-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/authentication/grammar/from/AuthenticationParseTreeWalker.java
- legend-engine-xt-authentication-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/authentication/grammar/from/CredentialVaultSecretParseTreeWalker.java
- legend-engine-xt-authentication-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/authentication/grammar/from/IAuthenticationGrammarParserExtension.java
- legend-engine-xt-authentication-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/authentication/grammar/from/SpecificationSourceCode.java
- legend-engine-xt-authentication-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/authentication/grammar/from/demo/AuthenticationDemoParseTreeWalker.java
- legend-engine-xt-authentication-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/authentication/grammar/to/AuthenticationGrammarComposerExtension.java
- legend-engine-xt-authentication-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/authentication/grammar/to/AuthenticationSpecificationComposer.java
- legend-engine-xt-authentication-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/authentication/grammar/to/IAuthenticationGrammarComposerExtension.java
- legend-engine-xt-authentication-grammar/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.dsl.authentication.compiler.toPureGraph.IAuthenticationCompilerExtension
- legend-engine-xt-authentication-grammar/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.dsl.authentication.grammar.from.IAuthenticationGrammarParserExtension
- legend-engine-xt-authentication-grammar/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.dsl.authentication.grammar.to.IAuthenticationGrammarComposerExtension
- legend-engine-xt-authentication-implementation-core/src/main/java/org/finos/legend/authentication/intermediationrule/impl/UserPasswordFromVaultRule.java
- legend-engine-xt-authentication-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/authentication/specification/UserPasswordAuthenticationSpecification.java
- legend-engine-xt-authentication-pure/src/main/resources/core_authentication/metamodel/metamodel_apikey.pure
- legend-engine-xt-authentication-pure/src/main/resources/core_authentication/pure/vX_X_X/transfers/authentication.pure
Enhancement
Add grammar parser/composer/compiler extensions for new authentication grammar 
N/A
N/A
N/A
> Refactor Legend Authentication : Add xt grammar extensions

- docs/authentication/code-examples.md
- legend-engine-xt-authentication-implementation-core/src/main/java/org/finos/legend/authentication/credentialprovider/CredentialProviderProvider.java
- legend-engine-xt-authentication-implementation-core/src/main/java/org/finos/legend/authentication/credentialprovider/impl/ApikeyCredentialProvider.java
- legend-engine-xt-authentication-implementation-core/src/main/java/org/finos/legend/authentication/credentialprovider/impl/PrivateKeyCredentialProvider.java
- legend-engine-xt-authentication-implementation-core/src/main/java/org/finos/legend/authentication/credentialprovider/impl/UserPasswordCredentialProvider.java
- legend-engine-xt-authentication-implementation-core/src/test/java/org/finos/legend/authentication/TestCredentialProviderProvider.java
- legend-engine-xt-authentication-implementation-gcp-federation/src/main/java/org/finos/legend/authentication/credentialprovider/impl/GCPWIFWithAWSIdPOAuthCredentialProvider.java
Improvement
Refactoring authentication APIs - Provide a simpler API to configure credential providers.
Fixes #
No
> Legend Authentication Refactoring - Update APIs

- pom.xml
Upgrade legend-pure version to 3.8.4 to get fixes to constraint compilation.
Errors in constraints will be reported to users at compile time.
> Upgrade legend-pure to 3.8.4

- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/functions/tests/testIn.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/advanced/testRelationalResultSourcing.pure
update the server version on the test to fix test failures
Fixes #
test failures
> update serverVersion on tests

- legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperRelationalGrammarComposer.java
- legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalGrammarRoundtrip.java
- Bug Fix
When trying to translate a first join as an INNER join, the returned string causes an unexpected token error due to structure. 
Fixes https://github.com/finos/legend-studio/issues/1826
> Fix first join JSON to grammar bug

- legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalBuilder.java
- legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalCompilationFromGrammar.java
Feature Improvement
Adds source information to "add warning" function and reframes test parameters to include expected warnings
> Improvements for compilation warning for duplicate columns

- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/functions/tests/testIn.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/advanced/testRelationalResultSourcing.pure
update service version to latest protocol version
Fixes #
> update service version to latest protocol version

- legend-engine-xt-persistence-api/pom.xml
- legend-engine-xt-persistence-api/src/main/java/org/finos/legend/engine/persistence/api/PersistencePlatformActionPayload.java
- legend-engine-xt-persistence-api/src/main/java/org/finos/legend/engine/persistence/api/PersistencePlatformActions.java
- legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/platform/PersistencePlatformActionRequest.java
- legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/platform/PersistencePlatformActionsExtension.java
- pom.xml
> Persistence API to take actions using the given platform

- legend-engine-xt-persistence-api/pom.xml
Bug Fix
Fix persistence api module version
Fixes #
> Fix persistence api module version

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
- legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDomainCompilationFromGrammar.java
- legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/TestServiceRunner.java
- legend-engine-language-pure-dsl-service-execution/src/test/resources/org/finos/legend/engine/pure/dsl/service/execution/test/simpleRelationalService.pure
- Improvement
This PR will insure that the date parameters passed to getAll(), getAllVersions() and getAllVersionsInRange() are correct based on the milestoning stereotype of the model. If parameters are not correct compilation error will be thrown.
Fixes this issue - https://jira.work.gs.com/browse/ALLOYEXEC-984
Nil
Yes
> added milestoning validation check on parameters of GetAll, GetAllVersions and GetAllVersionsInRange

- legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/store/shared/IResult.java
- legend-engine-pure-ide-light/pom.xml
- legend-engine-pure-ide-light/src/main/java/org/finos/legend/engine/ide/PureIDELight.java
- legend-engine-pure-runtime-execution/pom.xml
- legend-engine-pure-runtime-execution/src/main/java/org/finos/legend/engine/pure/runtime/execution/CoreExternalExecutionCodeRepositoryProvider.java
- legend-engine-pure-runtime-execution/src/main/java/org/finos/legend/engine/pure/runtime/execution/compiled/ExecutionExtensionCompiled.java
- legend-engine-pure-runtime-execution/src/main/java/org/finos/legend/engine/pure/runtime/execution/compiled/natives/LegendExecute.java
- legend-engine-pure-runtime-execution/src/main/java/org/finos/legend/engine/pure/runtime/execution/interpreted/ExecutionExtensionInterpreted.java
- legend-engine-pure-runtime-execution/src/main/java/org/finos/legend/engine/pure/runtime/execution/interpreted/natives/LegendExecute.java
- legend-engine-pure-runtime-execution/src/main/java/org/finos/legend/engine/pure/runtime/execution/shared/LegendExecute.java
- legend-engine-pure-runtime-execution/src/main/resources/META-INF/services/org.finos.legend.pure.m3.serialization.filesystem.repository.CodeRepositoryProvider
- legend-engine-pure-runtime-execution/src/main/resources/META-INF/services/org.finos.legend.pure.runtime.java.compiled.extension.CompiledExtension
- legend-engine-pure-runtime-execution/src/main/resources/META-INF/services/org.finos.legend.pure.runtime.java.interpreted.extension.InterpretedExtension
- legend-engine-pure-runtime-execution/src/main/resources/core_external_execution.definition.json
- legend-engine-pure-runtime-execution/src/main/resources/core_external_execution/execution.pure
- legend-engine-pure-runtime-execution/src/test/java/org/finos/legend/engine/pure/runtime/execution/LegendExecuteTest.java
- legend-engine-pure-runtime-execution/src/test/resources/testModels.txt
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/platform/executionPlanNodes/platform/serialize.pure
- pom.xml
Improvement
Creates a new native pure function that allow developers to create an execution plan, bind it to java platform, and execute it in Legend Engine, getting back the result in String/Json format.
This aims to improve the testing of execution plans from pure itself.
Fixes #
> Implement native pure function to create and execute plans in engine

- legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/PlanExecutor.java
Always set identity of executing user on ExecuteWithArgs flow
Fixes #
No
> Always set identity on ExecuteWithArgs

- legend-engine-xt-avro-pure/src/main/resources/core_external_format_avro/metamodel/metamodel.pure
- legend-engine-xt-avro-pure/src/main/resources/core_external_format_avro/transformation/serialization_avroSchemaToJSON.pure
- legend-engine-xt-avro-pure/src/main/resources/core_external_format_avro/transformation/tests/testAvroSchemaGenerator.pure
- legend-engine-xt-avro-pure/src/main/resources/core_external_format_avro/transformation/transformation_avroSchemaGenerator.pure
> handling empty classes for avro generation

- legend-engine-xt-diagram-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperDiagramBuilder.java
- legend-engine-xt-diagram-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestDiagramCompilationFromGrammar.java
Bug Fix
Fixes # https://github.com/finos/legend-engine/issues/1376
> fix compilation of diagram with association on milestone class

- legend-engine-xt-relationalStore-executionPlan/pom.xml
- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/AbstractTestSemiStructured.java
- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSemiStructuredFlattening.java
- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSemiStructuredInheritanceMapping.java
- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSemiStructuredJoinChainMapping.java
- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSemiStructuredParseJsonMapping.java
- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSimpleSemiStructuredMapping.java
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/lineage/scanColumns/scanColumns.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
Bug Fix
This PR fixes lineage calculation for semi structured queries
No
> Fix lineage calculation for semi structured queries

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/metaExtension.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/tests/metaExtension.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/simpleObject.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/simple.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/metaLibrary.pure
Improvement
add support for returning the type name and type path  from an instance of said type.
> add typeName and typePath support

- legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/fromPure/sdl/fromPure_sdl.pure
- legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/fromPure/sdl/tests/simpleTest.pure
- legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/deprecated/generation.pure
- legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/deprecated/tests/generationTests.pure
- legend-engine-xt-graphQL-query/src/test/java/org/finos/legend/engine/query/graphQL/api/test/TestGraphQLFileGeneration.java
- legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/ClassWithCustomScalars.graphql
- legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/scalarFileGeneration.json
- legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/scalars.graphql
> scalar Date, DateTime, BigDecimal in GraphQL schema generation

- legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/transformation/tests/testQueryToGraphFetch.pure
- legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/transformation/transformation_graphFetch.pure
> Add support for int, float, list in graphql arguments

- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperMappingGrammarComposer.java
- legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/to/TestMappingGrammarTo.java
- legend-engine-language-pure-grammar/src/test/resources/SimpleAggregationAwareMapping.json
Bug Fix
This PR fixes AggregationAware composer which currently generates grammar like - this$this, mapped$mapped
No
> Fix AggregationAware composer

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/tests/meta/testExtractEnumValue.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/metaLibrary.pure
Bug Fix
Users can use extractEnumValue in the model to take in function expressions as parameter.
Fixes #
No
> support Function Expression in ExtractEnumValue

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/platformBinding/typeInfo/typeInfo.pure
> Improve error message when multiple properties found with same name

- legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/testable/service/extension/ServiceTestRunner.java
- legend-engine-test-runner-service/src/test/java/org/finos/legend/engine/testable/service/TestServiceTestSuite.java
- legend-engine-test-runner-service/src/test/resources/testable/service/serviceGrammarWithTestKeys3.pure
This PR fixes bugs for running multi execution service tests for multiple tests with same key
Fixes #1388
No
> fix bug while running multiple tests of same keys

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/transfers/valueSpecification.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/preeval/preeval.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/preeval/tests.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/contract/storeContract.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/router/tests/testPreeval.pure
Improvement
Opensource preeval
Depends on - https://github.com/finos/legend-pure/pull/655
Fixes #
> Opensource preeval

- legend-engine-xt-relationalStore-dbExtension-archetype/src/main/resources/archetype-resources/legend-engine-xt-relationalStore-__dbtype__-execution-tests/pom.xml
- legend-engine-xt-relationalStore-dbExtension-archetype/src/main/resources/archetype-resources/legend-engine-xt-relationalStore-__dbtype__-pure/pom.xml
- legend-engine-xt-relationalStore-dbExtension-archetype/src/main/resources/archetype-resources/legend-engine-xt-relationalStore-__dbtype__-pure/src/main/resources/core_relational___dbtype__.definition.json
- legend-engine-xt-relationalStore-dbExtension-archetype/src/main/resources/archetype-resources/legend-engine-xt-relationalStore-__dbtype__-pure/src/test/java/org/finos/legend/pure/code/core/Test_Pure_Relational_DbSpecific___DbType__.java
Bug Fix
Fixes the relational extension archetype after the recent pure platform refactoring
No. It helps developers trying to create a new relational connector.
> fix relational extension archetype

- .github/workflows/database-athena-sql-generation-integration-test.yml
- .github/workflows/database-bigquery-sql-generation-integration-test.yml
- .github/workflows/database-databricks-sql-generation-integration-test.yml
- .github/workflows/database-mssqlserver-sql-generation-integration-test.yml
- .github/workflows/database-redshift-sql-generation-integration-test.yml
- .github/workflows/database-spanner-sql-generation-integration-test.yml
Improvement
Update sql test worflows to publish test results. See #1400 
Fixes #
No
> Update sql test worflows to publish test results

- legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/compiler/toPureGraph/ServiceCompilerExtensionImpl.java
- legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceCompilationFromGrammar.java
- Improvement
Avoid duplicate IDs for service validation assertions
No
> add service validation duplicate assertion ID check

- legend-engine-shared-javaCompiler/src/main/java/org/finos/legend/engine/shared/javaCompiler/StringJavaSource.java
Bug fix
Ensure we call end on Deflater and Inflater instances. It is important to call end to release resources, particularly native memory.
No
> Ensure we call end on Deflater and Inflater instances

- pom.xml
> bump to Pure 4.1.2

- legend-engine-pure-platform-functions-java/pom.xml
- legend-engine-xt-json-javaPlatformBinding-pure/pom.xml
- legend-engine-xt-relationalStore-sqlserver-pure/pom.xml
- legend-engine-xt-sql-pure/pom.xml
- pom.xml
> Upgrade to the new Pure version

- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestExtractFromSemiStructuredJoin.java
- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestExtractFromSemiStructuredSimple.java
- legend-engine-xt-relationalStore-executionPlan/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/extractFromSemiStructuredJoin.pure
- legend-engine-xt-relationalStore-executionPlan/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/extractFromSemiStructuredMappingSimple.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbExtension.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/h2/h2Extension.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/snowflake/snowflakeExtension.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/testSuiteCompletenessTests.pure
> dyna function for querying ssp

- legend-engine-test-reports/src/main/java/org/finos/legend/engine/test/LegendDatabaseSQLTestingReport.java
- legend-engine-test-reports/src/main/java/org/finos/legend/engine/test/LegendDatabaseTestingReportGenerator.java
- legend-engine-test-reports/src/main/java/org/finos/legend/engine/test/TestStatus.java
Improvement
Update sql testing report generator
Fixes #
No
> Update sql testing report generator

- legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/transformation/tests/testQueryToGraphFetch.pure
- legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/transformation/transformation_graphFetch.pure
- legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/Project1_Workspace1.pure
Bug Fix
Support for querying association properties using GraphQL
Fixes #
> Fix for association properties in GraphQL

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/domain/domainManagement.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/domain/tests/testDomainManagement.pure
- legend-engine-xt-graphQL-query/src/test/java/org/finos/legend/engine/query/graphQL/api/test/TestGraphQLAPI.java
- legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/Project1_Workspace1.pure
> Handle multiple statements in GraphQL

- legend-engine-xt-serviceStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/ServiceStoreProtocolExtension.java
- legend-engine-xt-serviceStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/AuthenticationSchemeRequirement.java
- legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/executionPlan/executionPlan_print.pure
- legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/metamodel/metamodelDiagram.pure
Cleanup
Cleanup ServiceStore Diagram
Fixes #
> Cleanup ServiceStore Diagram

- legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/to/HelperServiceGrammarComposer.java
- legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/to/ServiceGrammarComposerExtension.java
- legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceGrammarRoundtrip.java
- legend-engine-xt-mastery-grammar/src/test/java/org/finos/legend/engine/language/pure/dsl/mastery/compiler/test/TestMasteryCompilationFromGrammar.java
Cleanup
Delete empty legacy service tests at composer
Fixes #
> Delete empty legacy service tests at composer

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/tds/tdsSchema.pure
- legend-engine-xt-sql-grammar-integration/src/test/java/org/finos/legend/engine/language/sql/grammar/integration/test/TestSQLEmbedded.java
- legend-engine-xt-sql-grammar/src/main/antlr4/org/finos/legend/engine/language/sql/grammar/from/antlr4/SqlBaseLexer.g4
- legend-engine-xt-sql-grammar/src/main/antlr4/org/finos/legend/engine/language/sql/grammar/from/antlr4/SqlBaseParser.g4
- legend-engine-xt-sql-grammar/src/main/java/org/finos/legend/engine/language/sql/grammar/from/AbstractSqlBaseLexer.java
- legend-engine-xt-sql-grammar/src/main/java/org/finos/legend/engine/language/sql/grammar/from/SQLGrammarParser.java
- legend-engine-xt-sql-grammar/src/main/java/org/finos/legend/engine/language/sql/grammar/from/SqlVisitor.java
- legend-engine-xt-sql-grammar/src/main/java/org/finos/legend/engine/language/sql/grammar/to/SQLGrammarComposer.java
- legend-engine-xt-sql-grammar/src/test/java/org/finos/legend/engine/language/sql/grammar/test/roundtrip/TestSQLRoundTrip.java
- legend-engine-xt-sql-pure-metamodel/src/main/resources/core_external_query_sql_metamodel/metamodel.pure
- legend-engine-xt-sql-pure/pom.xml
- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql.definition.json
- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/fromPure.pure
- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/tests/shared.pure
- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/tests/testTranspile.pure
Improvement
Further support for translations in Legend SQL
Fixes #
> Legend SQL - Further translations for SQL functions

- legend-engine-xt-relationalStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/DatabaseType.java
Improvement
Add Trino DatabaseType. Also see finos/legend-pure#666 
Fixes #
No
> Add Trino DatabaseType

- legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withDatabricksTestConnection.json
Bug Fix
There was an hardcoded value in tests preventing from integration tests to run
No
> change hardcoded path to databricks finos instance

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/domain/domainManagement.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/domain/tests/testDomainManagement.pure
- legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/deprecated/tests/generationTests.pure
- legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/transformation/tests/testQueryToGraphFetch.pure
- legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/transformation/transformation_graphFetch.pure
- legend-engine-xt-graphQL-query/pom.xml
- legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/GraphQL.java
- legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/cache/GraphQLCacheKey.java
- legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/cache/GraphQLDevCacheKey.java
- legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/cache/GraphQLPlanCache.java
- legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/cache/GraphQLProdCacheKey.java
- legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/debug/GraphQLDebug.java
- legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/execute/GraphQLExecute.java
- legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/execute/GraphQLExecutionHelper.java
- legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/execute/SerializedNamedPlans.java
- legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/execute/model/GraphQLCachableVisitorHelper.java
- legend-engine-xt-graphQL-query/src/test/java/org/finos/legend/engine/query/graphQL/api/test/TestGraphQLAPI.java
- legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/Project1_Workspace1.pure
Improvement
This feature enables plan caching of graphql executions in order to speed up execution
> add support for plan caching on graphql

- legend-engine-pure-ide-light/src/main/resources/ideLightConfig.json
Bug Fix
Revert IDELight port change
Fixes #
> Revert IDELight port change

- legend-engine-executionPlan-execution/src/test/java/org/finos/legend/engine/plan/execution/concurrent/TestConcurrentExecutionNodeExecution.java
Bug Fix
Temporarily remove flaky assert to avoid transient test failures. This would be added back with code changes to avoid transient behaviour
Fixes #
> Temporarily remove flaky assert

- legend-engine-xt-relationalStore-executionPlan-connection-authentication-default/src/test/java/org/finos/legend/engine/authentication/flows/TestSnowflakeWithKeyPairFlow.java
Bug Fix
Ignore Snowflake Key Pair flaky tests
Fixes #
No
> Ignore Snowflake Key Pair tests

- legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig.json
- legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withMetadataFromIDELight.json
> update alloy metadata config to point to correct legend depot port and prefix

- pom.xml
> Update legend-pure to 4.3.0

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRuntimeBuilder.java
- legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestRuntimeCompilationFromGrammar.java
- legend-engine-pure-code-compiled-core/src/main/resources/core/legend/service/metamodel.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanExecutionTest.pure
…runtime
This PR will make legacy tests in a service optional as well as adding a warning if there is no mapping in the runtime.
These changes will allow users to migrate their legacy test to testSuite
Fixes #
> make legacy test optional, add warning for missing mapping in runtime

- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperDomainGrammarComposer.java
- legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestDomainGrammarRoundtrip.java
Bug Fix
For multiple statements in a qualified property we compose them without semi-colon `;` which is incorrect. The PR fixes that.
Fixes #
> Fix Qualified/Derived Property Composer for Multiple Statements

- legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/generation/conventions.pure
- legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/protocol/generation/generator.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/inMemory/graphFetchJson.pure
Performance improvement
This is a performance improvement in Java generation, which should particularly help plan generation where Java code is generated.
No
> Improve identifier sanitization by using a map of Java keyword replacements

- legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/StoreExecutableManager.java
- legend-engine-executionPlan-execution/src/test/java/org/finos/legend/engine/plan/execution/stores/TestStoreExecutableManager.java
- legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/RelationalResult.java
- Improvement
add logging for Store Executable cancellation
> add logging for Store Executable cancellation

- legend-engine-pure-code-compiled-core/src/main/resources/core/external/format/json/fromJSONSchema.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/external/format/json/tests/testFromJSONSchema.pure
- Improvement
add support for '$defs' and additionalProperty objects in jsonschema import
> add support for '$defs' and additionalProperty objects in jsonschema import

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/tests/testPropertyTreeConversion.pure
Improvement
adds tests
Fixes #
No
> add PropertyTreeCalc tests

- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/fromPure.pure
- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/tests/testTranspile.pure
Improvement
- Refactor function handling to introduce processors
- Case insensitive function matching
- Group by Index support
No
> Legend SQL - Assortment of updates

- legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/TestServiceRunner.java
- legend-engine-language-pure-dsl-service-execution/src/test/resources/org/finos/legend/engine/pure/dsl/service/execution/test/enumServiceParameter.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/relationalGraphFetch.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/relationalMappingExecution.pure
Improvement
Enable enum parameters in a service with Graph Fetch
Fixes https://jira.work.gs.com/browse/ALLOYEXEC-1591
No
> Enums as Service Params for Graph Fetch

- legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/GraphQL.java
- legend-engine-xt-graphQL-query/src/test/java/org/finos/legend/engine/query/graphQL/api/test/TestGraphQLAPI.java
- legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/Project3_Workspace1.pure
- legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/Project3_upstreamProjects.json
- legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/Project4_Version_2.0.1.pure
Improvement
Handle dependencies in GraphQL Dev API
Fixes #
> Handle dependencies in GraphQL Dev API

- legend-engine-executionPlan-execution/src/test/java/org/finos/legend/engine/plan/execution/concurrent/TestConcurrentExecutionNodeExecution.java
Improvement
Assert on concurrent poolstate
Fixes #
> Assert on concurrent poolstate

- .github/workflows/build.yml
- legend-engine-xt-data-space-pure-metamodel/src/main/resources/core_data_space_metamodel/metamodel.pure
> info: add diagram for data-space

- legend-engine-executionPlan-execution/pom.xml
- legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/PlanExecutor.java
- legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/state/ExecutionState.java
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/serialization/toPureGrammar.pure
- legend-engine-xt-authentication-implementation-core/src/main/java/org/finos/legend/authentication/credentialprovider/CredentialBuilder.java
- legend-engine-xt-authentication-implementation-core/src/main/java/org/finos/legend/authentication/credentialprovider/CredentialProvider.java
- legend-engine-xt-authentication-implementation-core/src/main/java/org/finos/legend/authentication/credentialprovider/CredentialProviderProvider.java
> Introduce credential builder/provider to execution plan

- .github/workflows/build.yml
- .github/workflows/test-result.yml
- CODEOWNERS
- legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/CorePureProtocolExtension.java
Bug Fix
As we missed this map, legend-sdlc entity serializer does not know how to convert an entity into `.pure` file in `Legend SDLC`
Fixes #
> Map classifier path for `Binding` and `SchemaSet`

- .github/workflows/database-trino-integration-test.yml
- .github/workflows/database-trino-sql-generation-integration-test.yml
Improvement
This enables test workflow for Trino connector.
NA
No
> Add trino integration test workflows

- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/mapping/extends/union/testExtendsForPropertyMappingWithUnion.pure
Bug Fix
This PR fixes an issue with property mapping overrides in the context of extend/union mapping
> Correctly handle property mapping overrides with extends and union mappings

- legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/StoreExecutableManager.java
- legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/RelationalResult.java
- legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/SQLExecutionResult.java
Improvement
extend cancel to SQLExecutionResult
> extend cancel to SQLExecutionResult

- legend-engine-xt-sql-grammar/src/main/antlr4/org/finos/legend/engine/language/sql/grammar/from/antlr4/SqlBaseParser.g4
- legend-engine-xt-sql-grammar/src/main/java/org/finos/legend/engine/language/sql/grammar/from/SqlVisitor.java
- legend-engine-xt-sql-grammar/src/main/java/org/finos/legend/engine/language/sql/grammar/to/SQLGrammarComposer.java
- legend-engine-xt-sql-grammar/src/test/java/org/finos/legend/engine/language/sql/grammar/test/roundtrip/TestSQLRoundTrip.java
- legend-engine-xt-sql-pure-metamodel/src/main/resources/core_external_query_sql_metamodel/metamodel.pure
- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/fromPure.pure
- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/tests/testTranspile.pure
Improvement
- Introduces many more sql function translations
- Introduces model/parse for window functions
No
> Legend SQL - add further function support

- legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/api/QueryStoreManager.java
- legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/model/QueryStoreStats.java
- legend-engine-application-query/src/test/java/org/finos/legend/engine/application/query/api/TestQueryStoreManager.java
Add queryCreatedFromDataSpaceCount as a query stat
Fixes #
> Add queryCreatedFromDataSpaceCount as a query stat

- legend-engine-server/src/main/java/org/finos/legend/engine/server/Server.java
- legend-engine-xt-sql-grammar/src/main/java/org/finos/legend/engine/language/sql/grammar/from/SQLGrammarParser.java
- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/fromPure.pure
- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/tests/shared.pure
- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/tests/testTranspile.pure
- legend-engine-xt-sql-query/pom.xml
- legend-engine-xt-sql-query/src/main/java/org/finos/legend/engine/query/sql/api/execute/SqlExecute.java
- legend-engine-xt-sql-query/src/main/java/org/finos/legend/engine/query/sql/api/sources/SQLContext.java
- legend-engine-xt-sql-query/src/main/java/org/finos/legend/engine/query/sql/api/sources/SQLSource.java
- legend-engine-xt-sql-query/src/main/java/org/finos/legend/engine/query/sql/api/sources/SQLSourceArgument.java
- legend-engine-xt-sql-query/src/main/java/org/finos/legend/engine/query/sql/api/sources/SQLSourceProvider.java
- legend-engine-xt-sql-query/src/main/java/org/finos/legend/engine/query/sql/api/sources/SQLSourceResolvedContext.java
- legend-engine-xt-sql-query/src/main/java/org/finos/legend/engine/query/sql/api/sources/SQLSourceTranslator.java
- legend-engine-xt-sql-query/src/main/java/org/finos/legend/engine/query/sql/api/sources/TableSource.java
- legend-engine-xt-sql-query/src/main/java/org/finos/legend/engine/query/sql/api/sources/TableSourceArgument.java
- legend-engine-xt-sql-query/src/main/java/org/finos/legend/engine/query/sql/api/sources/TableSourceExtractor.java
Improvement
Introduces the concept of sql source providers
No
> Legend SQL - introduce pluggable source providers

- legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/snowflake/SnowflakeCommands.java
- legend-engine-xt-relationalStore-executionPlan-connection/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/TestSnowflakeCommands.java
- Bug Fix
Fix snowflake path for temp stages
> Optimize sf stage copy

- legend-engine-xt-relationalStore-trino-execution-tests/pom.xml
- legend-engine-xt-relationalStore-trino-execution/pom.xml
- legend-engine-xt-relationalStore-trino-grammar/pom.xml
- legend-engine-xt-relationalStore-trino-protocol/pom.xml
- legend-engine-xt-relationalStore-trino-pure/pom.xml
Fix build
update legend-engine version to match master version
NA
Fixes #
NA
> Trino Connector | update legend-engine version to match the master version

- legend-engine-pure-runtime-execution/pom.xml
- legend-engine-pure-runtime-execution/src/main/resources/core_external_execution.definition.json
- legend-engine-pure-runtime-execution/src/main/resources/core_external_execution/execution.pure
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/pom.xml
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test.pure
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_test_utils.pure
Improvement 
This PR enables execute function to pick up available local platform binding and moves away from hard wired java platform binding dependency.
This will enable us to write platform binding agnostic tests.
Fixes #
No
> Use available local binding with legend execute

- legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/execute/GraphQLExecute.java
Improvement
Currently we don't propagate identity to plan executor in graphql, this PR improves that flow
Fixes #
yes, users will be able to use identity based auth flows with graphql
> Identity propagation in graphql

- .github/workflows/summarize-sql-generation-integration-tests-v2.yml
Improvement 
Add Trino to sql testing report generation
Fixes #
No
> Add Trino to sql testing report generation

- legend-engine-xt-authentication-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/authentication/compiler/toPureGraph/HelperAuthenticationBuilder.java
- legend-engine-xt-serviceStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperServiceStoreBuilder.java
> Refactor auth specification compilation to avoid duplication among modules using auth spec

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/preeval/preeval.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/preeval/tests.pure
Bug fix
Add support for Decimal primitive type in preeval
No
> Preeval: handle decimal type

- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/java/org/finos/legend/engine/plan/execution/stores/elasticsearch/test/shared/ElasticsearchCommands.java
> Use test container getHost as recommended by documentation

- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/fromPure.pure
- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/tests/testTranspile.pure
Improvement
Adds support for further aggregation translations from SQL to Pure.
No
> Legend SQL - further handling of aggregate expressions

- .gitignore
- legend-engine-pure-runtime-compiler/src/main/java/org/finos/legend/engine/pure/runtime/compiler/interpreted/natives/LegendCompileMixedProcessorSupport.java
- legend-engine-pure-runtime-compiler/src/test/java/org/finos/legend/engine/pure/runtime/compiler/test/LegendCompileTest.java
- pom.xml
Bug Fix
This PR add a test to confirm interoperability between compile and interpreted when using the compile() function.
This depends on https://github.com/finos/legend-pure/pull/679
Fixes #
> Support interoperability of VarCoreInstance and M3 instances

- .github/workflows/build.yml
- legend-engine-xt-nonrelationalStore-mongodb-pure/pom.xml
- legend-engine-xt-persistence-cloud-pure/pom.xml
- legend-engine-xt-persistence-pure/pom.xml
- legend-engine-xt-serviceStore-pure/pom.xml
Improvement
Enable sonar
Fixes #
> Enable sonar

- .github/workflows/build.yml
Bug Fix
Fix mvn command for master build
Fixes #
> Fix mvn command for master build

- legend-engine-server/pom.xml
- legend-engine-server/src/main/java/org/finos/legend/engine/server/Server.java
- legend-engine-xt-analytics-store-entitlement-api/pom.xml
- legend-engine-xt-analytics-store-entitlement-api/src/main/java/org/finos/legend/engine/api/analytics/StoreEntitlementAnalytics.java
- legend-engine-xt-analytics-store-entitlement-api/src/main/java/org/finos/legend/engine/api/analytics/model/StoreEntitlementAnalyticsInput.java
- legend-engine-xt-analytics-store-entitlement/pom.xml
- legend-engine-xt-analytics-store-entitlement/src/main/java/org/finos/legend/engine/entitlement/model/entitlementReport/DatasetEntitlementReport.java
- legend-engine-xt-analytics-store-entitlement/src/main/java/org/finos/legend/engine/entitlement/model/entitlementReport/EntitlementStatus.java
- legend-engine-xt-analytics-store-entitlement/src/main/java/org/finos/legend/engine/entitlement/model/specification/DatasetSpecification.java
- legend-engine-xt-analytics-store-entitlement/src/main/java/org/finos/legend/engine/entitlement/model/specification/relationalDatabase/RelationalDatabaseTableSpecification.java
- legend-engine-xt-analytics-store-entitlement/src/main/java/org/finos/legend/engine/entitlement/services/EntitlementServiceExtension.java
- legend-engine-xt-analytics-store-entitlement/src/main/java/org/finos/legend/engine/entitlement/services/EntitlementServiceExtensionLoader.java
- pom.xml
> support extensible entitlements analytics for dataspace

- legend-engine-xt-xml-javaPlatformBinding-pure/src/main/resources/core_external_format_xml_java_platform_binding/legendJavaPlatformBinding/internalize.pure
- legend-engine-xt-xml-runtime/src/test/java/org/finos/legend/engine/external/format/xml/test/TestXmlQueries.java
- legend-engine-xt-xml-runtime/src/test/resources/queries/allDataType.xml
- legend-engine-xt-xml-runtime/src/test/resources/queries/allDataTypeResult.json
Bug Fix
Fix dateTime processing for xml internalize
Fixes #
> Fix dateTime processing for xml internalize

- legend-engine-protocol-generation/src/main/java/org/finos/legend/engine/protocol/generation/GenerateMetamodelToProtocolTranslator.java
- legend-engine-protocol-generation/src/main/java/org/finos/legend/engine/protocol/generation/GenerateProtocolToMetamodelTranslator.java
- legend-engine-xt-daml-model/src/main/java/org/finos/legend/engine/external/format/daml/DamlFormatExtension.java
- legend-engine-xt-graphQL-compiler/pom.xml
- legend-engine-xt-graphQL-compiler/src/test/java/org/finos/legend/engine/protocol/graphQL/GenerateIntrospectionQueryBuilder.java
- legend-engine-xt-graphQL-compiler/src/test/java/org/finos/legend/engine/protocol/graphQL/GenerateTestQueryBuilder.java
- legend-engine-xt-graphQL-grammar-integration/src/main/java/org/finos/legend/engine/language/graphQL/grammar/integration/GraphQLCompilerExtension.java
- legend-engine-xt-graphQL-pure/src/test/java/org/finos/legend/engine/code/core/GenerateIntrospectionPureModel.java
- legend-engine-xt-graphQL-pure/src/test/java/org/finos/legend/engine/code/core/GeneratePureModelFromIntrospectionInstance.java
- legend-engine-xt-graphQL-pure/src/test/java/org/finos/legend/engine/code/core/TestTranslator.java
- legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/GraphQL.java
- legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/format/GraphQLFormatExtension.java
- legend-engine-xt-haskell-grammar/pom.xml
- legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/protocol/generation/generation.pure
- legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/protocol/generation/generation_test.pure
- legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/protocol/generation/generator.pure
- legend-engine-xt-protobuf/pom.xml
- legend-engine-xt-protobuf/src/main/java/org/finos/legend/engine/external/format/protobuf/ProtobufFormatExtension.java
- legend-engine-xt-sql-compiler/pom.xml
- legend-engine-xt-sql-compiler/src/test/java/org/finos/legend/engine/protocol/sql/GenerateTestQueryBuilder.java
- legend-engine-xt-sql-grammar-integration/src/main/java/org/finos/legend/engine/language/sql/grammar/integration/SQLCompilerExtension.java
- legend-engine-xt-sql-query/src/main/java/org/finos/legend/engine/query/sql/api/execute/SqlExecute.java
Improvement
Add support for MetamodelToProtocol Translation
Fixes #
> Add support for MetamodelToProtocol Translation

- legend-engine-server/pom.xml
- legend-engine-server/src/main/java/org/finos/legend/engine/server/Server.java
- legend-engine-xt-artifact-generation-api/pom.xml
- legend-engine-xt-artifact-generation-api/src/main/java/org/finos/legend/engine/generation/artifact/ArtifactGenerationFactory.java
- legend-engine-xt-artifact-generation-api/src/main/java/org/finos/legend/engine/generation/artifact/ArtifactGenerationResult.java
- legend-engine-xt-artifact-generation-api/src/main/java/org/finos/legend/engine/generation/artifact/GenerationOutput.java
- legend-engine-xt-artifact-generation-api/src/main/java/org/finos/legend/engine/generation/artifact/api/ArtifactGenerationExtensionApi.java
- legend-engine-xt-artifact-generation-api/src/main/java/org/finos/legend/engine/generation/artifact/api/ArtifactGenerationExtensionInput.java
- legend-engine-xt-artifact-generation-api/src/main/java/org/finos/legend/engine/generation/artifact/api/ArtifactGenerationExtensionOutput.java
- legend-engine-xt-artifact-generation-api/src/main/java/org/finos/legend/engine/generation/artifact/api/ArtifactGenerationLoggingEventType.java
- pom.xml
> add aritfact generation api

- legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java
- legend-engine-pure-code-compiled-core-configuration/pom.xml
- legend-engine-pure-code-compiled-core-configuration/src/main/resources/core_configuration.definition.json
- legend-engine-pure-code-compiled-core-configuration/src/main/resources/core_configuration/coreExtensions.pure
- legend-engine-xt-nonrelationalStore-mongodb-grammar-integration/pom.xml
- legend-engine-xt-nonrelationalStore-mongodb-grammar-integration/src/main/java/org/finos/legend/engine/language/pure/grammar/integration/plan/MongoDBPlanGeneratorExtension.java
- legend-engine-xt-nonrelationalStore-mongodb-grammar-integration/src/main/resources/META-INF/services/org.finos.legend.engine.plan.generation.extension.PlanGeneratorExtension
fix to remove mongo dependency on legend-engine-pure-code-compiled-core-configuration
Fix downstream build failures
> Fix to remove dependency on core-config

- docs/analytics/lineage/lineage.md
- docs/analytics/search/search.md
- docs/data-quality/data-quality-overview.md
Improvement
Additional documentation for lineage analytics features
No
> Updated docs for lineage analytics

- legend-engine-xt-nonrelationalStore-mongodb-executionPlan/pom.xml
- legend-engine-xt-nonrelationalStore-mongodb-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/mongodb/testsupport/InMemoryMongoDBSetupHelper.java
- legend-engine-xt-nonrelationalStore-mongodb-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/mongodb/testsupport/MongoDBStoreTestConnectionFactory.java
- legend-engine-xt-nonrelationalStore-mongodb-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/mongodb/testsupport/TestMongoDBStoreTestConnectionBuilder.java
Fix to downstream build failures.
Fixes netty version clashes in downstream builds
> Remove in-memory mongo dependency

- legend-engine-xt-analytics-store-entitlement-api/pom.xml
- legend-engine-xt-analytics-store-entitlement-api/src/main/java/org/finos/legend/engine/api/analytics/StoreEntitlementAnalytics.java
- legend-engine-xt-analytics-store-entitlement-api/src/main/java/org/finos/legend/engine/api/analytics/model/StoreEntitlementAnalyticsInput.java
- legend-engine-xt-analytics-store-entitlement/pom.xml
- legend-engine-xt-analytics-store-entitlement/src/main/java/org/finos/legend/engine/entitlement/services/EntitlementServiceExtension.java
fix a bug in extensible entitlements
Fixes #
> fix a bug in extensible entitlements

- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/fromPure.pure
- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/tests/testTranspile.pure
Improvement
Adds further support for window functions in sql -> pure
No
> Legend SQL - Further Window Function Support

- pom.xml
> Update legend-pure to 4.3.4

- legend-engine-executionPlan-execution-api/src/main/java/org/finos/legend/engine/plan/execution/api/ExecutePlan.java
- legend-engine-executionPlan-execution-api/src/main/java/org/finos/legend/engine/plan/execution/api/request/RequestContextHelper.java
- legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/PlanExecutor.java
- legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/state/ExecutionState.java
- legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/StoreExecutableManager.java
- legend-engine-query-pure/src/main/java/org/finos/legend/engine/query/pure/api/Execute.java
- legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/api/request/RequestContext.java
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-V7-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/elasticsearch/v7/result/ExecutionRequestVisitor.java
- legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/RelationalExecutor.java
- legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/RelationalResult.java
- legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/SQLExecutionResult.java
- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/TestRelationStoreExecutableManager.java
use a wrapper Request Context class to carry anything related to the request needed by plan execution 
Fixes #
> Replace sessionID with RequestContext

- legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/helpers/platform/JavaHelper.java
- legend-engine-external-shared-format-runtime/src/main/java/org/finos/legend/engine/external/shared/ExternalFormatJavaCompilerExtension.java
- legend-engine-shared-javaCompiler/src/main/java/org/finos/legend/engine/shared/javaCompiler/ClassJavaSource.java
- legend-engine-shared-javaCompiler/src/main/java/org/finos/legend/engine/shared/javaCompiler/ClassListFilter.java
- legend-engine-shared-javaCompiler/src/main/java/org/finos/legend/engine/shared/javaCompiler/ClassPathFilter.java
- legend-engine-shared-javaCompiler/src/main/java/org/finos/legend/engine/shared/javaCompiler/ClassPathFilters.java
- legend-engine-shared-javaCompiler/src/main/java/org/finos/legend/engine/shared/javaCompiler/CompositeClassPathFilter.java
- legend-engine-shared-javaCompiler/src/main/java/org/finos/legend/engine/shared/javaCompiler/EngineJavaCompiler.java
- legend-engine-shared-javaCompiler/src/main/java/org/finos/legend/engine/shared/javaCompiler/JavaCompileException.java
- legend-engine-shared-javaCompiler/src/main/java/org/finos/legend/engine/shared/javaCompiler/MemoryClassLoader.java
- legend-engine-shared-javaCompiler/src/main/java/org/finos/legend/engine/shared/javaCompiler/MemoryFileManager.java
- legend-engine-shared-javaCompiler/src/main/java/org/finos/legend/engine/shared/javaCompiler/SingleFileCompiler.java
- legend-engine-shared-javaCompiler/src/test/java/org/finos/legend/engine/shared/javaCompiler/test/TestJavaCompileClassPathFilter.java
- legend-engine-xt-flatdata-runtime/src/main/java/org/finos/legend/engine/external/format/flatdata/FlatDataJavaCompilerExtension.java
- legend-engine-xt-json-runtime/src/main/java/org/finos/legend/engine/external/format/json/JsonJavaCompilerExtension.java
- legend-engine-xt-xml-runtime/src/main/java/org/finos/legend/engine/external/format/xml/XmlJavaCompilerExtension.java
Improvement
Improvements to Java compilation, particularly for execution plans. This is primarily intended for speeding up cases where there are many plans requiring compilation of generated Java code.
No
> Engine Java compiler improvements

- legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/SQLExecutionResult.java
- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/TestRelationStoreExecutableManager.java
<!--
Improvement
Add tracking for sqlExecutionResult so that we can cancel executions
> Update SQLExecutionResult to track sessions

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PureModel.java
- legend-engine-pure-runtime-compiler/src/main/java/org/finos/legend/engine/pure/runtime/compiler/compiled/natives/LegendCompile.java
Bug Fix
This PR addresses following issues
- Lookup of association models from pure system code like we do for classes
- Sharing the metadata in compiled flow for legend compile function to avoid conflicts between Pure/Engine compiler
- Adding support for reflective evaluation of compile function
Fixes #
> Fix Legend Compile flow for local development

- legend-engine-pure-runtime-execution/pom.xml
- legend-engine-pure-runtime-execution/src/main/java/org/finos/legend/engine/pure/runtime/execution/compiled/natives/LegendExecute.java
- legend-engine-pure-runtime-execution/src/main/java/org/finos/legend/engine/pure/runtime/execution/interpreted/natives/LegendExecute.java
- legend-engine-pure-runtime-execution/src/test/java/org/finos/legend/engine/pure/runtime/execution/LegendExecuteTest.java
- legend-engine-pure-runtime-execution/src/test/resources/testModels.txt
Improvement
Add support for bytestream for legend execute flow
Fixes #
> Add support for bytestream for legend execute flow

- legend-engine-xt-authentication-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/authentication/AuthenticationParserGrammar.g4
- legend-engine-xt-authentication-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/authentication/grammar/to/AuthenticationSpecificationComposer.java
- legend-engine-xt-authentication-grammar/src/test/java/org/finos/legend/language/pure/dsl/authentication/grammar/test/TestAuthenticationGrammarParser_AuthenticationTypes.java
- legend-engine-xt-authentication-grammar/src/test/java/org/finos/legend/language/pure/dsl/authentication/grammar/test/TestAuthenticationGrammarParser_SecretTypes.java
- legend-engine-xt-authentication-grammar/src/test/java/org/finos/legend/language/pure/dsl/authentication/grammar/test/TestAuthenticationGrammarRoundtrip_AuthenticationTypes.java
- legend-engine-xt-authentication-grammar/src/test/java/org/finos/legend/language/pure/dsl/authentication/grammar/test/TestAuthenticationGrammarRoundtrip_SecretTypes.java
Improvement
Add semi colon at the end of all secret values to make grammar consistent.  
Fixes #
We only had it for password in UserPassword Authentication 
No
> Add semi colon at the end of secret values

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/preeval/preeval.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/preeval/tests.pure
- Improvement
- Added support for removing unnecessary toOne/toOneMany
- Add detection to prevent inlining of recursive single statement functions
- Fix for inlined functions that are let statements as the final statement
> Preeval enhancements

- legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/api/QueryStoreManager.java
- legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/model/QuerySearchSpecification.java
- legend-engine-application-query/src/test/java/org/finos/legend/engine/application/query/api/TestQueryStoreManager.java
Improvement
Modified search api so that you can
Fixes #
> Minor improvements to query search api

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_31_0/extension/extension.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_31_0/scan/buildBasePureModel.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/extension/extension.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/scan/buildBasePureModel.pure
- Improvement
Adding a new extension to get extra stores from stores
Fixes #
No
> Add a new extension to get extra stores from store information

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_30_0/invocations/testBuildExecutionInput.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_31_0/invocations/testBuildExecutionInput.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/invocations/testBuildExecutionInput.pure
- Improvement
Add unit tests for buildExecutionInput
Fixes #
No
> add unit tests to buildExecutionInput

- legend-engine-pure-code-compiled-core/src/main/resources/core/legend/tools/devUtils.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/testComplexTypeAutoMapping.pure
- legend-engine-xt-flatdata-javaPlatformBinding-pure/src/main/resources/core_external_format_flatdata_java_platform_binding/legendJavaPlatformBinding/tests/executionPlanExecution.pure
- legend-engine-xt-json-javaPlatformBinding-pure/src/main/resources/core_external_format_json_java_platform_binding/legendJavaPlatformBinding/tests/executionPlanExecution.pure
- legend-engine-xt-nonrelationalStore-mongodb-javaPlatformBinding-pure/src/main/resources/core_nonrelational_mongodb_java_platform_binding/test/testSetup.pure
- legend-engine-xt-xml-javaPlatformBinding-pure/src/main/resources/core_external_format_xml_java_platform_binding/legendJavaPlatformBinding/tests/executionPlanExecution.pure
Improvement
This PR adds developer functions in core which can be used by developers across modules instead of each module implementing reflection individually
Fixes #
> Add developer function utilities in core

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/routing/router_routing.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/milestoning/tests/testBusinessDateMilestoning.pure
Bug fix
bug fix for col function with parameters
Fixes #
> fix for col function with parameters

- legend-engine-xt-analytics-search-generation/src/test/java/org/finos/legend/engine/generation/TestSearchDocumentArtifactGenerationExtension.java
- legend-engine-xt-analytics-search-pure/pom.xml
- legend-engine-xt-analytics-search-pure/src/main/resources/core_analytics_search/diagram.pure
- legend-engine-xt-analytics-search-pure/src/main/resources/core_analytics_search/metamodel.pure
- legend-engine-xt-analytics-search-pure/src/main/resources/core_analytics_search/trans.pure
- legend-engine-xt-analytics-search-pure/src/main/resources/core_analytics_search/transTest.pure
- Improvement
updates search documents for all the packageable elements to include more information
No
> improvements for SearchDocumentGeneration

- legend-engine-xt-sql-grammar/src/main/antlr4/org/finos/legend/engine/language/sql/grammar/from/antlr4/SqlBaseParser.g4
- legend-engine-xt-sql-grammar/src/main/java/org/finos/legend/engine/language/sql/grammar/from/SqlVisitor.java
- legend-engine-xt-sql-grammar/src/main/java/org/finos/legend/engine/language/sql/grammar/to/SQLGrammarComposer.java
- legend-engine-xt-sql-grammar/src/test/java/org/finos/legend/engine/language/sql/grammar/test/roundtrip/TestSQLRoundTrip.java
- legend-engine-xt-sql-pure-metamodel/src/main/resources/core_external_query_sql_metamodel/metamodel.pure
- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/fromPure.pure
- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/tests/testTranspile.pure
- legend-engine-xt-sql-query/src/main/java/org/finos/legend/engine/query/sql/api/sources/TableSourceExtractor.java
Improvements/Bug Fixes
- basic interval support
- strpos, stdev
- ensure projected columns are correct and in correct order
No
> Legend SQL Updates

- legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/api/QueryStoreManager.java
- legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/model/QuerySearchSpecification.java
- legend-engine-application-query/src/test/java/org/finos/legend/engine/application/query/api/TestQueryStoreManager.java
- Improvement
Updating query search api to include a flag to allow the search to specify an exact match for the query name 
Fixes #1668
> update query search api for exact name search

- pom.xml
Legend version upgrade
Upgrade legend-pure to 4.4.0
> Upgrade legend-pure to 4.4.0

- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/DEPRECATED_PureGrammarComposerCore.java
- legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestLambdaPrettyRendering.java
Bug Fix
Fixed JSONto grammar transformation
Yes. UI tools will not throw errors anymore
> Fix Grammar Composer for OLAP functions

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/tests/sourceTreeCalc/testSourceTreeCalc.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/lineage/scanProperties.pure
Bug Fix
fixes java code generation and sourceTree calculation for if function
Fixes #
> fix scanProperties in if clauses

- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/fromPure.pure
- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/tests/testTranspile.pure
Bug Fix
Handles group by with no aggregates
No
> Legend SQL - handle groupby with no aggregates

- legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/to/ServiceGrammarComposerExtension.java
- legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceGrammarRoundtrip.java
Improvement 
Enables jsonToGrammar conversion for ###Service with combinational Service and Exec Env elements
Fixes #1612
No
> Adding fix for JsonToGrammar fix for Execution Environment

- legend-engine-testable/src/main/java/org/finos/legend/engine/testable/TestableRunner.java
Add method to run tests with compiled pureModel to avoid having to compile pureModel for each testsable if we want to run tests
Fixes #
> add doTests on Testable with compiled pureModel

- legend-engine-extensions-collection-generation/pom.xml
- legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java
- legend-engine-server/pom.xml
- legend-engine-server/src/main/java/org/finos/legend/engine/server/Server.java
- legend-engine-xt-analytics-store-entitlement-api/pom.xml
- legend-engine-xt-analytics-store-entitlement-api/src/main/java/org/finos/legend/engine/api/analytics/StoreEntitlementAnalytics.java
- legend-engine-xt-analytics-store-entitlement/pom.xml
- legend-engine-xt-analytics-store-entitlement/src/main/java/org/finos/legend/engine/entitlement/model/specification/DatasetSpecification.java
- legend-engine-xt-data-space-api/pom.xml
- legend-engine-xt-data-space-api/src/main/java/org/finos/legend/engine/api/analytics/DataSpaceAnalytics.java
- legend-engine-xt-data-space-api/src/test/java/org/finos/legend/engine/api/analytics/test/TestDataSpaceAnalyticsApi.java
- legend-engine-xt-data-space-generation/pom.xml
- legend-engine-xt-data-space-generation/src/main/java/org/finos/legend/engine/generation/DataSpaceAnalyticsArtifactGenerationExtension.java
- legend-engine-xt-data-space-generation/src/main/java/org/finos/legend/engine/generation/analytics/DataSpaceAnalyticsHelper.java
- legend-engine-xt-data-space-generation/src/test/java/org/finos/legend/engine/generation/TestDataSpaceAnalyticsArtifactGenerationExtension.java
- legend-engine-xt-relationalStore-store-entitlement-analytics/src/test/java/org/finos/legend/engine/entitlement/TestRelationalStoreEntitlementAnalytics.java
- legend-engine-xt-relationalStore-store-entitlement-analytics/src/test/resources/models/relationalModel.pure
- legend-engine-xt-relationalStore-store-entitlement-pure/pom.xml
> cleanup post #1678

- legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/propertyUnion.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/simpleObject.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/shared.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/simple.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/metaLibrary.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/shared/common.pure
Improvement
Enhance typeName and typePath function working
Fixes #
> Enhance typeName and typePath function working

- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestExtractFromSemiStructuredJoin.java
- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestExtractFromSemiStructuredSimple.java
- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSemiStructuredInheritanceMapping.java
- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSemiStructuredJoinChainMapping.java
- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSimpleSemiStructuredMapping.java
- legend-engine-xt-relationalStore-executionPlan/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/extractFromSemiStructuredJoin.pure
- legend-engine-xt-relationalStore-executionPlan/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/extractFromSemiStructuredMappingSimple.pure
- legend-engine-xt-relationalStore-executionPlan/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/semiStructuredInheritanceMapping.pure
- legend-engine-xt-relationalStore-executionPlan/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/semiStructuredJoinChainMapping.pure
- legend-engine-xt-relationalStore-executionPlan/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/simpleSemiStructuredMapping.pure
- legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalBuilder.java
- legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/RelationalParseTreeWalker.java
- legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperRelationalGrammarComposer.java
- legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalCompilationFromGrammar.java
- legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalMappingGrammarParser.java
- legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalMappingGrammarRoundtrip.java
- legend-engine-xt-relationalStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/datatype/DataType.java
- legend-engine-xt-relationalStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/datatype/Json.java
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/memSql/memSqlExtension.pure
Depends on https://github.com/finos/legend-pure/pull/685 for SingleStore JSON data type
> Add basic semistructured support against SingleStore JSON

- legend-engine-server/src/main/java/org/finos/legend/engine/server/Server.java
- legend-engine-xt-analytics-store-entitlement/src/main/java/org/finos/legend/engine/entitlement/model/specification/DatasetSpecification.java
- legend-engine-xt-relationalStore-store-entitlement-analytics/pom.xml
- legend-engine-xt-relationalStore-store-entitlement-analytics/src/main/java/org/finos/legend/engine/entitlement/model/specification/RelationalDatabaseTableSpecification.java
store-entitlement analytics minor fixes
> store-entitlement analytics minor fixes

- legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/testExplosion.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/inMemory/graphFetchInMemory.pure
Bug Fix
This PR handles enumeration mappings in the context of M2M explosion
> Fix bug with usage of enumeration mappings with M2M explosion

- legend-engine-xt-analytics-store-entitlement/src/main/java/org/finos/legend/engine/entitlement/model/entitlementReport/DatasetEntitlementAccessErrorReport.java
- legend-engine-xt-analytics-store-entitlement/src/main/java/org/finos/legend/engine/entitlement/model/entitlementReport/DatasetEntitlementReport.java
- legend-engine-xt-relationalStore-store-entitlement-analytics/src/main/java/org/finos/legend/engine/entitlement/services/RelationalDatabaseEntitlementServiceExtension.java
- legend-engine-xt-relationalStore-store-entitlement-analytics/src/test/java/org/finos/legend/engine/entitlement/TestRelationalStoreEntitlementAnalytics.java
- legend-engine-xt-relationalStore-store-entitlement-analytics/src/test/resources/models/relationalModel.pure
- legend-engine-xt-relationalStore-store-entitlement-pure/src/main/resources/core_relational_store_entitlement/utility/relationalTableAnalyzer.pure
> fix a bug in running mappers on table for entitlements

- legend-engine-xt-avro-pure/src/main/resources/core_external_format_avro/transformation/tests/testAvroSchemaGenerator.pure
- legend-engine-xt-avro-pure/src/main/resources/core_external_format_avro/transformation/transformation_avroSchemaGenerator.pure
> Fixing Avro Schema Generator -to form a single union for the type hierarchy 

- legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDomainCompilationFromGrammar.java
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/domain/DomainParseTreeWalker.java
- legend-engine-xt-analytics-mapping-pure/src/main/resources/core_analytics_mapping/modelCoverage/analytics.pure
- legend-engine-xt-analytics-mapping-pure/src/main/resources/core_analytics_mapping/modelCoverage/analyticsHelper.pure
Cleanup
Remove reference of binary data type
Fixes #
> Remove reference of binary data type

- legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/pom.xml
- legend-engine-xt-relationalStore-executionPlan-connection/pom.xml
- legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/DatabaseManager.java
- legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/mysql/MySQLCommands.java
- legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/mysql/MySQLDriver.java
- legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/mysql/MySQLManager.java
- legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/StreamResultToTempTableVisitor.java
- pom.xml
> Add MySQL Manager and Maria Driver

- legend-engine-pure-code-compiled-core/src/main/resources/core/external/format/json/jsonSchema.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/external/format/json/tests/testToJsonSchema.pure
- legend-engine-xt-json-pure/src/main/resources/core_external_format_json/binding/validation/validation.pure
Bug Fix
Fix json schema generation for date properties
Fixes #
> Fix json schema generation for date properties

- legend-engine-xt-analytics-search-generation/src/test/java/org/finos/legend/engine/generation/TestSearchDocumentArtifactGenerationExtension.java
- legend-engine-xt-analytics-search-pure/pom.xml
- legend-engine-xt-analytics-search-pure/src/main/resources/core_analytics_search/diagram.pure
- legend-engine-xt-analytics-search-pure/src/main/resources/core_analytics_search/metamodel.pure
- legend-engine-xt-analytics-search-pure/src/main/resources/core_analytics_search/trans.pure
- legend-engine-xt-analytics-search-pure/src/main/resources/core_analytics_search/transTest.pure
Restores https://github.com/finos/legend-engine/pull/1658
> Restore "improvements for SearchDocumentGeneration"

- pom.xml
> Upgrade Legend Pure to 4.5.1

- legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/store/inMemory/graphFetch/IInMemoryRootGraphFetchExecutionNodeSpecifics.java
- legend-engine-executionPlan-execution-store-inMemory/src/main/java/org/finos/legend/engine/plan/execution/stores/inMemory/plugin/InMemoryExecutionNodeExecutor.java
- legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/store/inMemory/InMemoryRootGraphFetchExecutionNode.java
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/tests/executionPlanTests.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphExtension.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphFetchExecutionPlan.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/tests/sourceTreeCalc/testSourceTreeCalc.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/modelToModel.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_31_0/models/executionPlan.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_31_0/transfers/executionPlan.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/models/executionPlan.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/transfers/executionPlan.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/filterGraphFetch.pure
- legend-engine-server/src/test/java/org/finos/legend/engine/server/test/pureClient/stores/Test_M2M_UsingPureClientTestSuite.java
- legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/metamodel_factories.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/inMemory/graphFetchInMemory.pure
Improvement
Adds support for filter on model store graphfetch executions
> add support for filter on graphfetch model store

- legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/execute/GraphQLExecute.java
- legend-engine-xt-graphQL-query/src/test/java/org/finos/legend/engine/query/graphQL/api/test/TestGraphQLAPI.java
Enhancement 
Fix exception handling for GraphQL to throw actual error instead of generic null pointer exception
Fixes #
No
> Fix Exception Handling for GraphQL

- legend-engine-xt-relationalStore-store-entitlement-analytics/src/test/java/org/finos/legend/engine/entitlement/TestRelationalStoreEntitlementAnalytics.java
- legend-engine-xt-relationalStore-store-entitlement-analytics/src/test/resources/models/relationalModel.pure
- legend-engine-xt-relationalStore-store-entitlement-pure/src/main/resources/core_relational_store_entitlement/utility/relationalTableAnalyzer.pure
Bug Fix
fix a bug in retrieving tables from a circular database
Fixes #
> entitlements - fix a bug in retrieving tables from a circular database

- .github/workflows/database-singlestore-integration-test.yml
- legend-engine-xt-relationalStore-memsql-execution-tests/pom.xml
- legend-engine-xt-relationalStore-memsql-execution-tests/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/memsql/test/MemSQLContainer.java
- legend-engine-xt-relationalStore-memsql-execution-tests/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/memsql/test/MemSQLTestContainerWrapper.java
- legend-engine-xt-relationalStore-memsql-execution-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/memsql/test/TestMemSQLTestContainerWrapper.java
- pom.xml
> Add MemSQL container and container wrapper for testing

- legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/AuthenticationContext.java
- legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/Messages.java
- legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/PostgresServer.java
- legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/PostgresWireProtocol.java
- legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/auth/AuthenticationMethodType.java
- legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/auth/GSSAuthenticationMethod.java
- legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/auth/KerberosIdentityProvider.java
- legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/config/Builder.java
- legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/config/GSSConfig.java
- legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/config/ServerConfig.java
- legend-engine-xt-sql-postgres-server/src/test/java/org/finos/legend/engine/postgres/PostgresServerTest.java
- legend-engine-xt-sql-postgres-server/src/test/java/org/finos/legend/engine/postgres/PostgresServerTypeMappingTest.java
- legend-engine-xt-sql-postgres-server/src/test/java/org/finos/legend/engine/postgres/TestPostgresServer.java
- legend-engine-xt-sql-postgres-server/src/test/resources/legendConfigWithKerberos.json
Improvement
Introduce Kerberos authentication and delegation to the Legend SQL engine
Fixes #
> Legend SQL - Add Kerberos authentication and delegation

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/executionPlan_generation.pure
- legend-engine-xt-flatdata-pure/src/main/resources/core_external_format_flatdata/executionPlan/tests/simple.pure
Improvement
Support input data modification with internalize
Fixes #
> Support input data modification with internalize

- legend-engine-server/src/test/java/org/finos/legend/engine/server/test/pureClient/executionPlan/Test_ExecutionPlan_JavaPlatform_CodeGeneration_UsingPureClient.java
- legend-engine-server/src/test/java/org/finos/legend/engine/server/test/shared/PureTestHelper.java
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/testUtils.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/platform/executionPlanNodes/platform/tests/javaGenerationTest.pure
> testSuite for java Generation for funcs inside meta::pure::functions

- legend-engine-xt-analytics-search-generation/pom.xml
- legend-engine-xt-analytics-search-generation/src/main/java/org/finos/legend/engine/generation/SearchDocumentArtifactGenerationExtension.java
- legend-engine-xt-analytics-search-generation/src/test/java/org/finos/legend/engine/generation/TestSearchDocumentArtifactGenerationExtension.java
- legend-engine-xt-analytics-search-generation/src/test/resources/models/Model.pure
> Enabling stereotype flag for Artifact Generation conditional 5-3-23

- legend-engine-xt-relationalStore-trino-execution/pom.xml
- legend-engine-xt-relationalStore-trino-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/authentication/strategy/TrinoDelegatedKerberosAuthenticationStrategyRuntime.java
- Bug Fix
We are adding a workaround for the Multiple Kerberos failure issue from the Trino client code.
Fixes the "Multiple Kerberos found" issue for Trino connector
Fixes #
NA
NA
> Trino | Fix Multiple Kerberos issue

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/dateExtension.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/tests/dateExtension.pure
- Improvement
Add helper functions for to/from epoch value for dates
> Add helper functions for to/from epoch value for dates

- legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/store/inMemory/InMemoryRootGraphFetchExecutionNode.java
Improvement
Setup POJO for accepting graphfetch filters
> update  InMemoryRootGraphFetchExecutionNode POJO with filter

- .github/workflows/legend-stack-release.yml
> Add legend stack release workflow

- legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/util/Library.java
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/mathLibrary.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/mathLibraryTests.pure
Improvement
The mod_Integer__Integer_Integer_ function was avalible in PURE, but had no implementation for Alloy. This PR adds this function and test for it.
It's a trivial function using Javas modulo operator.
No
> feature: added modulo function with test (alloy)

- legend-engine-xt-nonrelationalStore-mongodb-executionPlan-test/src/main/java/org/finos/legend/engine/plan/execution/stores/mongodb/test/shared/MongoDBCommands.java
- legend-engine-xt-nonrelationalStore-mongodb-executionPlan-test/src/main/resources/core_mongodb_execution_test/mongodb_execution_tests.pure
- legend-engine-xt-nonrelationalStore-mongodb-executionPlan-test/src/main/resources/core_mongodb_execution_test/test_setup/testSetupDSL.txt
- legend-engine-xt-nonrelationalStore-mongodb-grammar-integration/src/main/java/org/finos/legend/engine/language/pure/grammar/integration/connection/MongoDBConnectionParseTreeWalker.java
- legend-engine-xt-nonrelationalStore-mongodb-grammar-integration/src/test/java/org/finos/legend/engine/language/pure/grammar/integration/TestMongoDBConnectionGrammarRoundTrip.java
- legend-engine-xt-nonrelationalStore-mongodb-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/MongoDBConnectionLexerGrammar.g4
- legend-engine-xt-nonrelationalStore-mongodb-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/MongoDBConnectionParserGrammar.g4
- Bug Fix
Fix failing test - with the mongo hostname also parameterized in addition to port number.
> Set Mongo host from container host

- legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/to/ServiceGrammarComposerExtension.java
- legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceGrammarRoundtrip.java
> Condense Execution Environment logic for jsonToGrammar

- legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/store/inMemory/graphFetch/IInMemoryRootGraphFetchExecutionNodeSpecifics.java
- legend-engine-executionPlan-execution-store-inMemory/src/main/java/org/finos/legend/engine/plan/execution/stores/inMemory/plugin/InMemoryExecutionNodeExecutor.java
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/tests/executionPlanTests.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphExtension.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphFetchExecutionPlan.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/tests/sourceTreeCalc/testSourceTreeCalc.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/modelToModel.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/models/executionPlan.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/transfers/executionPlan.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/chain/simpleChain.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/filterGraphFetch.pure
- legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/metamodel_factories.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/inMemory/graphFetchInMemory.pure
Improvement
add support for graphfetchFilter on pureModel stores
> add support for graphfetchFilter on pureModel stores

- legend-engine-protocol-api/pom.xml
- legend-engine-protocol-api/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/PureProtocol.java
- legend-engine-server/pom.xml
- legend-engine-server/src/main/java/org/finos/legend/engine/server/Server.java
- pom.xml
needed by https://github.com/finos/legend-studio/issues/315 to produce the right classifier path for persistence to SDLC
> expose endpoint to get classifier path map

- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-V7-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/elasticsearch/v7/connection/ElasticsearchHttpContextUtil.java
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-V7-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/elasticsearch/v7/plugin/ElasticsearchV7ExecutionNodeExecutor.java
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-V7-protocol/src/main/java/org/finos/legend/engine/protocol/store/elasticsearch/v7/ElasticsearchV7ProtocolExtension.java
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-V7-pure-metamodel/src/main/resources/core_elasticsearch_seven_metamodel/protocol/vX_X_X/serialization.pure
> Implement missing serialization functions for elasticsearch extension

- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-V7-pure-metamodel/src/main/resources/core_elasticsearch_seven_metamodel/extensions/store_contract.pure
> Implement elasticsearch shouldStopPreeval

- legend-engine-xt-authentication-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/authentication/compiler/toPureGraph/HelperAuthenticationBuilder.java
> Don't throw on the "catch all" method to avoid failures when extending for other subtypes

- legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRoundTripWithPureTransformation.java
- legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/to/HelperServiceGrammarComposer.java
- legend-engine-language-pure-grammar-api/src/test/java/org/finos/legend/engine/language/pure/grammar/api/test/TestJsonToGrammarApi.java
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/DEPRECATED_PureGrammarComposerCore.java
- legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestDomainGrammarRoundtrip.java
- legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestMappingGrammarRoundtrip.java
- legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/embedded/TestExtendableEmbedded.java
- legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/valueSpecification/TestPrimitives.java
Make grammar rendering in `RenderStyle.PRETTY` looks better
> grammar composer: make function rendering prettier

- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/full/graphFetch/dataTypes/TestRelationalGraphFetchExecutionDataTypes.java
- legend-engine-xt-relationalStore-javaPlatformBinding-pure/src/main/resources/core_relational_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/relationalClassInstantiation/relationalClassResult.pure
Bug Fix
This PR fixes a bug with BIT columns as primary keys in relational graph fetch flow
> Fix bug with BIT column as a PK in graph fetch

- legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/chain.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure
BugFix
Fixes case where multiple aggregations are used in Model chain connections
Fixes #
> fix multipleAggregations in ModelChainConnection

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/preeval/preeval.pure
> Natively support stores on preeval

- pom.xml
update legend pure version
Fixes #
> update legend pure version

- legend-engine-xt-relationalStore-trino-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/authentication/strategy/TrinoDelegatedKerberosAuthenticationStrategyRuntime.java
Bug Fix
When multiple private credeentials of type KeberosTicket is present, It fails with error No Valid Credentials found if the ticket picked is type other than KRBTGT
Fixes ERROR:" No valid credentials provided (Mechanism level: Fail to create credential. (63) - No service creds) 
No changes required
> Trino filter valid krbtgt tickets

- legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/util/Library.java
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/mathLibrary.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/mathLibraryTests.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/platform/executionPlanNodes/platform/tests/javaGenerationTest.pure
> M2M feature parity: math functions

- legend-engine-server/src/test/java/org/finos/legend/engine/server/test/pureClient/executionPlan/Test_ExecutionPlan_JavaPlatform_CodeGeneration_UsingPureClient.java
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/testUtils.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/platform/executionPlanNodes/platform/tests/javaGenerationTest.pure
convert java generation test to Test.test from Test.testcollection
Bug Fix
convert java gen test to Test.test instead of testcollection due to high mem usage in testcollection
Fixes #
> convert java generation test to Test.test from Test.testcollection

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/preeval/tests.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/router/tests/testPreeval.pure
> Add preeval Store test case

- docs/store/extensions/Relational/Databases/snowflake/LocalMode.md
- legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/DatabaseManager.java
- legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/snowflake/SnowflakeManager.java
- legend-engine-xt-relationalStore-executionPlan-connection/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/snowflake/TestSnowflakeManager.java
- legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/manager/strategic/RelationalConnectionManager.java
- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/TestRelationalConnectionManagerLocalMode.java
- legend-engine-xt-relationalStore-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/RelationalDatabaseConnectionLexerGrammar.g4
- legend-engine-xt-relationalStore-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/RelationalDatabaseConnectionParserGrammar.g4
- legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalBuilder.java
- legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/RelationalDatabaseConnectionParseTreeWalker.java
- legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/RelationalGrammarComposerExtension.java
- legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalConnectionGrammarRoundtrip.java
- legend-engine-xt-relationalStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/RelationalDatabaseConnection.java
complete the work started in https://github.com/finos/legend-engine/pull/1807
> snowflake local connection support

- legend-engine-xt-relationalStore-memsql-pure/src/main/resources/core_relational_memsql/relational/sqlQueryToString/customMemSQLTests.pure
- legend-engine-xt-relationalStore-memsql-pure/src/main/resources/core_relational_memsql/relational/sqlQueryToString/memSQLExtension.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/transform/fromPure/toSQLString.pure
> Fix MemSQL quote identifiers bug

- legend-engine-external-shared-format-model/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ExternalFormatCompilerExtension.java
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/executionPlan_generation.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/model.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/functions/functions.pure
- legend-engine-xt-json-javaPlatformBinding-pure/pom.xml
- legend-engine-xt-json-javaPlatformBinding-pure/src/main/resources/core_external_format_json_java_platform_binding/legendJavaPlatformBinding/externalize.pure
- legend-engine-xt-serviceStore-pure/pom.xml
- legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/executionPlan/executionPlan_generation.pure
- legend-engine-xt-xml-pure/src/main/resources/core_external_format_xml/executionPlan/tests/executionPlanTest.pure
Cleanup
Delete externalize without tree
Fixes #
> Delete externalize without tree

- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/milestoning/milestoning.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/mapping/classMappingFilterWithInnerJoin/testClassMappingFilterWithInnerJoin.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/mapping/classMappingFilterWithInnerJoin/testRelationalSetUp.pure
Bug Fix
Reprocess alias while applying milestoning filters
Fixes #
> Reprocess alias while applying milestoning filters

- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/testDataGeneration/testDataGeneration.pure
Improvement
support test data generation for services with parameters
Fixes #
> support test data generation for services with parameters

- legend-engine-xt-sql-query/src/main/java/org/finos/legend/engine/query/sql/api/execute/SqlExecute.java
- legend-engine-xt-sql-query/src/main/java/org/finos/legend/engine/query/sql/api/sources/SQLSourceResolvedContext.java
Improvement
allows for return of multiple pointers to aid more efficient model fetch
No
> Legend SQL - Alloy Multiple PureResolved PureModelContext

- legend-engine-xt-sql-postgres-server/pom.xml
- legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/Messages.java
- legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/Session.java
- legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/handler/PostgresPreparedStatement.java
- legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/handler/legend/LegendPreparedStatement.java
- legend-engine-xt-sql-postgres-server/src/main/resources/log4j.properties
- legend-engine-xt-sql-postgres-server/src/test/java/org/finos/legend/engine/postgres/PostgresServerTest.java
- legend-engine-xt-sql-postgres-server/src/test/java/org/finos/legend/engine/postgres/handler/legend/LegendTdsTestClient.java
- legend-engine-xt-sql-postgres-server/src/test/resources/log4j.properties
- legend-engine-xt-sql-postgres-server/src/test/resources/logback-test.xml
- legend-engine-xt-sql-query/pom.xml
- legend-engine-xt-sql-query/src/test/java/org/finos/legend/engine/query/sql/api/execute/SqlExecuteTest.java
- legend-engine-xt-sql-query/src/test/java/org/finos/legend/engine/query/sql/api/sources/TestSQLSourceProvider.java
- legend-engine-xt-sql-query/src/test/resources/proj-1.pure
- pom.xml
- Bug Fix
Handle scenarios where parameter details are requested for prepared statements
No
> Handle prepared statements

- legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/serialization/StreamingTempTableResultCSVSerializer.java
> add csvFormat to StreamingTempTableResultCSVSerializer

- legend-engine-xt-nonrelationalStore-mongodb-grammar-integration/src/main/java/org/finos/legend/engine/language/pure/grammar/integration/plan/MongoDBPlanGeneratorExtension.java
- legend-engine-xt-nonrelationalStore-mongodb-javaPlatformBinding-pure/src/main/resources/core_nonrelational_mongodb_java_platform_binding/mongodbStoreLegendJavaPlatformBindingExtension.pure
Bug Fix
Avoid loading extensions loaded as part of core-extensions.  But load them for tests.
> Mongo execute p9

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/tds/tds.pure
- legend-engine-pure-runtime-compiler/src/main/java/org/finos/legend/engine/pure/runtime/compiler/interpreted/natives/LegendCompileMixedProcessorSupport.java
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-V7-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/elasticsearch/v7/result/ElasticsearchTDSResultHelper.java
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-V7-grammar/src/main/java/org/finos/legend/engine/language/stores/elasticsearch/v7/compiler/HelperElasticsearchPropertyBuilder.java
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-V7-protocol/src/main/java/org/finos/legend/engine/protocol/store/elasticsearch/v7/metamodel/tds/AbstractResultPathVisitor.java
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-V7-pure-metamodel/src/main/resources/core_elasticsearch_seven_metamodel/functions/pure_to_elasticsearch.pure
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-V7-pure-metamodel/src/main/resources/core_elasticsearch_seven_metamodel/functions/specification_utils.pure
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-V7-pure-metamodel/src/main/resources/core_elasticsearch_seven_metamodel/functions/tds_utils.pure
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-V7-pure-metamodel/src/main/resources/core_elasticsearch_seven_metamodel/protocol/vX_X_X/serialization.pure
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test.pure
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test_7.pure
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test_aggregation.pure
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test_filter.pure
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test_filter_float.pure
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test_filter_integer.pure
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test_filter_keyword.pure
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test_filter_text.pure
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/engineGrammar_7._pure_
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/test/java/org/finos/legend/engine/plan/execution/stores/elasticsearch/test/TestElasticsearchExecutionPlanFromGrammarIntegration.java
Improvement
Among changes, noticeable includes:
- Support for _id projection and filtering
- Support for in() function
- Support for Keyword contains() function
- Support for Text contains() function
- Support for property with inner fields
- More aggregation test cases, specially on nullable fields Test cases on equality on nullable fields
Fixes #
> Further support ElasticSearch operations.

- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/functions/tests/projection/testProjectWithWindowColumns.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/functions/tests/testFilters.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tds/tests/testTDSFilter.pure
> fix ordering of multiple tds filters

- legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/DatabaseManager.java
- legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/snowflake/SnowflakeManager.java
- legend-engine-xt-relationalStore-executionPlan-connection/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/snowflake/TestSnowflakeManager.java
- legend-engine-xt-relationalStore-executionPlan-connection/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/ExternalIntegration_TestConnectionObjectProtocol_SnowflakeDemo.java
- legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/manager/strategic/RelationalConnectionManager.java
- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/TestRelationalConnectionManagerLocalMode.java
- legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/RelationalDatabaseConnectionParseTreeWalker.java
- legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalConnectionCompilationRoundtrip.java
Bug Fix
Bug fix updates to Snowflake local mode
Fixes #
> Snowflake local mode

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/preeval/preeval.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/preeval/tests.pure
Bug Fix
Fix inScopeParams while processing function definition in preeval
Fixes #
> Fix inScopeParams while processing function definition in preeval

- legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ValueSpecificationBuilder.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/FunctionHandler.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/UserDefinedFunctionHandler.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/inference/ResolveTypeParameterInference.java
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/executionPlan_generation.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/functions/functions.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/externalFormat/routing.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/runtime/runtimeExtension.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/binding/shared.pure
- legend-engine-xt-json-javaPlatformBinding-pure/src/main/resources/core_external_format_json_java_platform_binding/legendJavaPlatformBinding/externalize.pure
- legend-engine-xt-json-javaPlatformBinding-pure/src/main/resources/core_external_format_json_java_platform_binding/legendJavaPlatformBinding/internalize.pure
- legend-engine-xt-json-model/pom.xml
- legend-engine-xt-json-model/src/main/java/org/finos/legend/engine/external/format/json/JsonExternalFormatExtension.java
- legend-engine-xt-json-model/src/main/java/org/finos/legend/engine/external/format/json/compile/JsonSchemaCompiler.java
- legend-engine-xt-json-model/src/main/resources/META-INF/services/org.finos.legend.engine.external.shared.format.model.ExternalFormatPureExtension
- legend-engine-xt-json-model/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.compiler.toPureGraph.extension.CompilerExtension
- legend-engine-xt-json-model/src/test/java/org/finos/legend/engine/external/format/json/TestJsonFunctionCompilation.java
- legend-engine-xt-json-pure/pom.xml
- legend-engine-xt-json-pure/src/main/resources/core_external_format_json.definition.json
- legend-engine-xt-json-pure/src/main/resources/core_external_format_json/executionPlan/tests/internalizeExternalizeWithContentType.pure
- legend-engine-xt-json-pure/src/main/resources/core_external_format_json/executionPlan/tests/utils.pure
- legend-engine-xt-json-pure/src/main/resources/core_external_format_json/functions/functions.pure
- legend-engine-xt-json-runtime/src/test/java/org/finos/legend/engine/external/format/json/read/test/TestJsonSchemaQueries.java
- legend-engine-xt-xml-model/src/main/resources/META-INF/services/org.finos.legend.engine.external.shared.format.model.ExternalFormatPureExtension
Improvement
This PR adds support for internalize and externalize without binding. It also adds functions fromJson/toJson for ease of use. It also adds mechanism to provide resolvedTypeParameters while compiling functions 
Fixes #
> Add support for internalize/externalize with contentType

- legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/operational/prometheus/MetricsHandler.java
- legend-engine-xt-relationalStore-executionPlan-connection/pom.xml
- legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/DataSourceSpecification.java
- legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/DataSourceWithStatistics.java
- legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/state/ConnectionStateManager.java
- legend-engine-xt-relationalStore-executionPlan-connection/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/state/TestConnectionStateManager.java
Improvement
Creating Prometheus metrics to observe Active and Built Connection Pools for connection pools
Fixes #
No
> Creating Observable Metrics for Connection Pools

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/collectionExtension.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/tests/collections/testMax.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/tests/collections/testMin.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/routing/router_routing.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/tds/tds.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/tds/tdsSchema.pure
- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/collectionsLibrary.pure
- legend-engine-xt-sql-pure/pom.xml
- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/fromPure.pure
- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/tests/shared.pure
- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/tests/testTranspile.pure
Improvement/Bug fix
- support for min/max
- handle further cast cases
- support length
- ensure correct from wrapping
- temporary mapping/runtime merge for plan generation.
No
> Legend SQL - assortment of improvements/fixes

- legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/compiler/toPureGraph/HelperServiceBuilder.java
- legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/compiler/toPureGraph/ServiceCompilerExtensionImpl.java
- legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceCompilationFromGrammar.java
Bug fix
fix a bug in service test parameter type validation
Fixes #
> fix a bug in service test parameter type validation

- legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/test/runner/service/ServiceTestGenerationHelper.java
> Remove external format connection test execution support

- legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/Session.java
- legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/SystemSchemas.java
- legend-engine-xt-sql-postgres-server/src/test/java/org/finos/legend/engine/postgres/SystemSchemasTest.java
- Improvement
Cleanup code to remove magic strings
> Introduce system schemas constants

- .github/workflows/build.yml
Adding monitoring for GitHub runner metrics through the workflow telemetry action
> Tracking worflow telemetry

- legend-engine-language-pure-modelManager-sdlc/src/main/java/org/finos/legend/engine/language/pure/modelManager/sdlc/SDLCLoader.java
Improvement
Add constructors in SDLCLoader
Fixes #
> Add constructors in SDLCLoader

- .github/workflows/legend-stack-release.yml
> Fix automated release workflow

- legend-engine-xt-nonrelationalStore-mongodb-executionPlan-test/pom.xml
- legend-engine-xt-nonrelationalStore-mongodb-executionPlan-test/src/main/java/org/finos/legend/engine/plan/execution/stores/mongodb/test/MongoTestContainer.java
- legend-engine-xt-nonrelationalStore-mongodb-executionPlan-test/src/main/java/org/finos/legend/engine/plan/execution/stores/mongodb/test/shared/MongoDBCommands.java
Bug Fix
The test container start up started failing internally but will need further investigation before making it consistent with MongoTestContainer class
> Revert MongoTestcontainer startup code 

- legend-engine-xt-sql-postgres-server/pom.xml
Bugfix
Fix docker build config for xt-sql-postgres-server
> Fix docker config for sql-postgres-server

- .github/workflows/legend-stack-release.yml
- .github/workflows/release-large-runner-serial.yml
- .github/workflows/release-large-runner.yml
- .github/workflows/release.yml
Adding a separate release action that builds modules in serial
> Adding a release action with a serial build

- legend-engine-xt-sql-postgres-server/pom.xml
- pom.xml
Improvement
Add Prometheus JMX agent to expose JVM platform jmx metrics for monitoring
Run configurations / scripts will need to be updated to activate / expose the JVM agent. See https://github.com/prometheus/jmx_exporter#running-the-java-agent for more details.
> Add Prometheus JMX agent to expose JVM platform jmx metrics for monitoring

- legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/data/ModelStoreData.java
- legend-engine-protocol-pure/src/test/java/org/finos/legend/engine/protocol/test/TestCompatibilityAndMigration.java
> add custom deserializer for modelStoreData

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperMappingBuilder.java
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/data/data.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/metamodel.pure
> change package of storeTestdata from test to data

- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/graphFetchCommon.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/relationalGraphFetch.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/helperFunctions/helperFunctions.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/mapping/embedded/testInlineEmbeddedMapping.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/mapping/embedded/testInlineEmbeddedNested.pure
Improvement
Users can now do graphFetch queries with InlineMappings, only TDS is supported earlier.
No
> Enable graphFetch for InlineMappings

- legend-engine-configuration/src/main/java/org/finos/legend/engine/plan/generation/extension/LegendPlanGeneratorExtension.java
- legend-engine-executionPlan-generation/src/main/java/org/finos/legend/engine/plan/generation/transformers/DevPlanTransformer.java
- legend-engine-executionPlan-generation/src/main/java/org/finos/legend/engine/plan/generation/transformers/LegendPlanTransformers.java
- legend-engine-language-pure-dsl-service-generation/src/main/java/org/finos/legend/engine/language/pure/dsl/service/generation/ServicePlanGenerator.java
- legend-engine-language-pure-dsl-service-generation/src/main/java/org/finos/legend/engine/language/pure/dsl/service/generation/extension/ServiceExecutionExtension.java
- legend-engine-query-pure/pom.xml
- legend-engine-query-pure/src/main/java/org/finos/legend/engine/query/pure/api/Execute.java
- legend-engine-service-post-validation-runner/src/main/java/org/finos/legend/engine/service/post/validation/runner/LegendServicePostValidationRunner.java
- legend-engine-service-post-validation-runner/src/main/java/org/finos/legend/engine/service/post/validation/runner/ServicePostValidationRunner.java
- legend-engine-test-runner-mapping/src/main/java/org/finos/legend/engine/test/runner/mapping/MappingTestRunner.java
- legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/test/runner/service/ServiceTestRunner.java
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-V7-grammar/src/main/java/org/finos/legend/engine/language/stores/elasticsearch/v7/plan/generation/ElasticsearchPlanGeneratorExtension.java
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/test/java/org/finos/legend/engine/plan/execution/stores/elasticsearch/test/TestElasticsearchExecutionPlanFromGrammarIntegration.java
- legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/execute/GraphQLExecute.java
- legend-engine-xt-nonrelationalStore-mongodb-grammar-integration/src/main/java/org/finos/legend/engine/language/pure/grammar/integration/plan/MongoDBPlanGeneratorExtension.java
- legend-engine-xt-sql-query/src/main/java/org/finos/legend/engine/query/sql/api/execute/SqlExecute.java
Bug Fix
LegendPlanTransformers.transformers is mutable and not thread safe. This makes it immutable (and therefore thread safe).
No
> Make LegendPlanTransformers.transformers immutable

- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/fromPure.pure
- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/tests/shared.pure
- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/tests/testTranspile.pure
Bug Fix
sets the correct function on the different join types
No
> Legend SQL - fix join function

- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/fromPure.pure
- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/tests/testTranspile.pure
Improvement
adding handling of trunc
No
> Legend SQL - support trunc

- legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/operational/prometheus/MetricsHandler.java
- legend-engine-xt-relationalStore-executionPlan-connection/pom.xml
- legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/DataSourceSpecification.java
- legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/DataSourceWithStatistics.java
- legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/state/ConnectionStateManager.java
- legend-engine-xt-relationalStore-executionPlan-connection/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/state/TestConnectionStateManager.java
Revert 
Reverting original commit as the metrics were not working as expected 
Fixes # https://github.com/finos/legend-engine/pull/1863/files
> revert connection metrics changes

- legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/PureClientVersions.java
- legend-engine-protocol-pure/src/test/java/org/finos/legend/engine/protocol/test/TestProtocolUpdates.java
Point production protcol version to v32
> Point production protcol version to v32

- legend-engine-xt-relationalStore-executionPlan-connection-api/pom.xml
- legend-engine-xt-relationalStore-executionPlan-connection-api/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/api/schema/SchemaExportation.java
- legend-engine-xt-relationalStore-executionPlan-connection-api/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/api/schema/TestSchemaExplorationSnowflake.java
- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/TestRelationalConnectionManagerLocalMode.java
- legend-engine-xt-snowflakeApp-api/pom.xml
- legend-engine-xt-snowflakeApp-api/src/main/java/org/finos/legend/engine/language/snowflakeApp/api/SnowflakeAppDeploymentTool.java
- legend-engine-xt-snowflakeApp-api/src/main/java/org/finos/legend/engine/language/snowflakeApp/api/SnowflakeAppService.java
- legend-engine-xt-snowflakeApp-api/src/test/java/org/finos/legend/engine/language/snowflakeApp/api/TestSnowflakeAppDeploymentTool.java
Improvement
Enables the use of Snowflake local connections in the schema exploration and function activation code paths.
Fixes #
No
> Update Snowflake local mode

- .github/workflows/legend-stack-release.yml
This reverts commit 55024c0555f9fdf9989d9af7509d4bbb3ea0ebeb.
Fixes #
> Revert "Adding a release action with a serial build (#1892)"

- legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/config/Builder.java
- legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/handler/legend/LegendTdsClient.java
- legend-engine-xt-sql-postgres-server/src/test/java/org/finos/legend/engine/postgres/PostgresServerTest.java
- legend-engine-xt-sql-postgres-server/src/test/java/org/finos/legend/engine/postgres/PostgresServerTypeMappingTest.java
- legend-engine-xt-sql-postgres-server/src/test/java/org/finos/legend/engine/postgres/handler/legend/LegendTdsTestClient.java
- legend-engine-xt-sql-query/src/test/resources/proj-1.pure
- Improvement
Multiple enhancements and bug fixes:
- Switch to use TDS schema API to get column metadata from lambda/query, previously metadata was retrieved by executing query. (Improves performance)
- Add handing values of "null" and "" to be handled as null values in query result datasets
- Updated LegendTdsTestClient  (used to route request in memory Alloy Execution Server) to override only routing logic methods.
> Multiple enhancements for SQL Engine

- legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/PlanExecutor.java
- legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/state/ExecutionState.java
- legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/RelationalExecutor.java
- legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/RelationalExecutionNodeExecutor.java
- legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/RelationalResult.java
- legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/SQLExecutionResult.java
- legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/TestRelationStoreExecutableManager.java
Improvement
Makes SQL Logging With Param Values Configurable via PlanExecutor
Fixes #
> Makes SQL Logging With Param Values Configurable

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PureModel.java
- legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDomainCompilationFromGrammar.java
> Prepare for deletion of binary primitive type

- legend-engine-xt-flatdata-driver-bloomberg/pom.xml
- legend-engine-xt-flatdata-driver-bloomberg/src/main/java/org/finos/legend/engine/external/format/flatdata/driver/bloomberg/BloombergDataReadDriver.java
- legend-engine-xt-flatdata-driver-bloomberg/src/main/java/org/finos/legend/engine/external/format/flatdata/driver/bloomberg/BloombergProcessor.java
- legend-engine-xt-flatdata-driver-bloomberg/src/test/java/org/finos/legend/engine/external/format/flatdata/grammar/driver/bloomberg/TestBloombergFlatDataQueries.java
- legend-engine-xt-flatdata-javaPlatformBinding-pure/src/main/resources/core_external_format_flatdata_java_platform_binding/legendJavaPlatformBinding/internalize.pure
- legend-engine-xt-flatdata-runtime/src/main/java/org/finos/legend/engine/external/format/flatdata/FlatDataContext.java
- legend-engine-xt-flatdata-shared/src/main/java/org/finos/legend/engine/external/format/flatdata/driver/core/StreamingSequentialSections.java
- legend-engine-xt-flatdata-shared/src/main/java/org/finos/legend/engine/external/format/flatdata/driver/spi/FlatDataProcessor.java
Improvement
Serializes schema object for multi section parsers where each section by it self is not a returnable object.
Fixes #
No
> Serialize schema object for multi section parsing

- legend-engine-xt-relationalStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/DatabaseType.java
Improvement
It adds a new enum for SingleStore DB
Fixes #
No
> Introduce new DB type SingleStore

- legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/handler/legend/LegendDataType.java
- legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/handler/legend/LegendResultSet.java
- legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/handler/legend/LegendResultSetMetaData.java
- legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/handler/legend/LegendTdsClient.java
- legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/handler/legend/TDSRow.java
- legend-engine-xt-sql-postgres-server/src/test/java/org/finos/legend/engine/postgres/PostgresServerTypeMappingTest.java
Improvement
- Enhanced to extract correct data type from JSON response, previously always retrieved text
- Add handling for null values
- Add parsing unit tests for strings, enums and nulls
> Fixed parsing of TDS results with null values

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/tds/tdsSchema.pure
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/tds/testTdsSchema.pure
- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/fromPure.pure
- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/tests/testTranspile.pure
Bug fix
- add cast to getEnum
- fix schema resolve on restrict
No
> Legend SQL - multiple fixes

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/store/builder.pure
- legend-engine-server/src/test/java/org/finos/legend/engine/server/test/pureClient/stores/Test_Relational_UsingPureClientTestSuite.java
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/relationalGraphFetch.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/tests/testCrossStoreGraphFetchMilestoning.pure
- Improvement
With the change, it is now possible to execute services with a mapping in which cross-store join is used to join JSON to milestoned relational data.
> Enable Cross store joins (M2R) with a milestoned relational store

- legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/context/PureModelContextPointer.java
- legend-engine-protocol-pure/src/test/java/org/finos/legend/engine/protocol/test/TestPureContextPointer.java
- legend-engine-xt-sql-query/pom.xml
- legend-engine-xt-sql-query/src/main/java/org/finos/legend/engine/query/sql/api/execute/SqlExecute.java
- legend-engine-xt-sql-query/src/main/java/org/finos/legend/engine/query/sql/api/sources/TableSource.java
- legend-engine-xt-sql-query/src/main/java/org/finos/legend/engine/query/sql/api/sources/TableSourceArgument.java
- legend-engine-xt-sql-query/src/main/java/org/finos/legend/engine/query/sql/api/sources/TableSourceExtractor.java
- legend-engine-xt-sql-query/src/test/java/org/finos/legend/engine/query/sql/api/execute/SqlExecuteTest.java
- legend-engine-xt-sql-query/src/test/java/org/finos/legend/engine/query/sql/api/sources/TableSourceExtractorTest.java
- Bug Fix
- PMCD Pointer -> ensure combine handles sdlc correctly
- Remove duplicate tables in extractor
No
> Legend SQL - assortment of fixes

- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/tests/testSimpleRelationalGraphFetch.pure
Bugfix
Use correct protocol version for graphfetchchecked batch size test
No
> Set correct min protocol for graphFetchChecked batch size test

- legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/graphFetchCommon.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/relationalGraphFetch.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/helperFunctions/helperFunctions.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/mapping/embedded/testInlineEmbeddedMapping.pure
- legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/mapping/embedded/testInlineEmbeddedNested.pure
This reverts commit 6e11c01a70cbe7d6815ebdc69825158e0a0fe3a9.
> Revert "Enable graphFetch for InlineMappings (#1898)"

- legend-engine-protocol-pure/src/test/java/org/finos/legend/engine/protocol/test/TestPureContextPointer.java
> Fix flaky PureModelContextPointer Test

- legend-engine-xt-sql-postgres-server/pom.xml
- legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/AuthenticationContext.java
- legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/PostgresServerLauncher.java
- legend-engine-xt-sql-postgres-server/src/test/resources/logback-test.xml
- legend-engine-xt-sql-query/src/main/java/org/finos/legend/engine/query/sql/api/execute/SqlExecute.java
- legend-engine-xt-sql-query/src/test/java/org/finos/legend/engine/query/sql/api/execute/SqlExecuteTest.java
- pom.xml
Improvement
- Add logging library runtime dependency (such as `logback-json`) to allow configuring this during runtime
- Add bridge from java-util-logging to SLF4J to allow consistent logging pattern
- Add connection user to context so it is logged
Sample logs from test:
```
{"timestamp":"2023-06-20 08:06:23.784","level":"DEBUG","thread":"nioEventLoopGroup-5-2","mdc":{"user":"dummy"},"logger":"org.finos.legend.engine.postgres.Session","message":"method=parse stmtName= query=SELECT * FROM service.\"/testData\" paramTypes=[]","context":"default"}
```
No
> Legend SQL - logging

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-V7-grammar/pom.xml
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-V7-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ElasticsearchLexerGrammar.g4
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-V7-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ElasticsearchParserGrammar.g4
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-V7-grammar/src/main/java/org/finos/legend/engine/language/stores/elasticsearch/v7/compiler/HelperElasticsearchPropertyBuilder.java
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-V7-grammar/src/main/java/org/finos/legend/engine/language/stores/elasticsearch/v7/from/ElasticsearchStoreParseTreeWalker.java
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-V7-grammar/src/main/java/org/finos/legend/engine/language/stores/elasticsearch/v7/to/HelperElasticsearchPropertyComposer.java
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-V7-grammar/src/test/java/org/finos/legend/engine/language/stores/elasticsearch/v7/compiler/TestElasticsearchCompiler.java
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-V7-grammar/src/test/java/org/finos/legend/engine/language/stores/elasticsearch/v7/to/TestElasticsearchGrammarRoundtrip.java
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-V7-pure-metamodel/src/main/resources/core_elasticsearch_seven_metamodel/functions/pure_to_elasticsearch.pure
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test.pure
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_plan_test_7.pure
- legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/engineGrammar_7._pure_
Improvement
This enhance ES to support Object field type.
Fixes #
> Support for parsing/composing/compiling Object and Nested types

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperMappingBuilder.java
- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/TestCompilerHelper.java
- legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestMappingCompilationFromGrammar.java
- legend-engine-language-pure-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/mapping/MappingParserGrammar.g4
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/mapping/MappingParseTreeWalker.java
- legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperMappingGrammarComposer.java
- legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/parser/TestMappingGrammarParser.java
- legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestMappingGrammarRoundtrip.java
- legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/CorePureProtocolExtension.java
- legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/extension/ConnectionFactoryExtension.java
- legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/data/EmbeddedDataHelper.java
- legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/mappingTest/MappingDataTest.java
- legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/mappingTest/MappingDataTestSuite.java
- legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/mappingTest/MappingFunctionTest.java
- legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/mappingTest/MappingFunctionTestSuite.java
- legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/mappingTest/MappingTest.java
- legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/modelToModel/connection/ModelStoreTestConnectionFactory.java
- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/metamodel.pure
- legend-engine-test-runner-mapping/pom.xml
- legend-engine-test-runner-mapping/src/main/java/org/finos/legend/engine/testable/mapping/extension/MappingTestRunner.java
- legend-engine-test-runner-mapping/src/main/java/org/finos/legend/engine/testable/mapping/extension/MappingTestRunnerContext.java
- legend-engine-test-runner-mapping/src/test/java/org/finos/legend/engine/testable/mapping/extension/TestMappingTestRunner.java
- legend-engine-test-runner-mapping/src/test/java/org/finos/legend/engine/testable/mapping/extension/TestRelationalMappingRunner.java
- legend-engine-xt-nonrelationalStore-mongodb-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/mongodb/testsupport/MongoDBStoreTestConnectionFactory.java
- legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/RelationalResult.java
- legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/test/RelationalConnectionFactory.java
- legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalMappingGrammarRoundtrip.java
- legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/test/ServiceStoreTestConnectionFactory.java
- legend-engine-xt-serviceStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/service/testable/mapping/TestMappingTestRunner.java
- legend-engine-xt-serviceStore-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceStoreMappingGrammarRoundtrip.java
Reverts finos/legend-engine#1915
> Revert "one query multi inputs"

- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/fromPure.pure
- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/tests/testTranspile.pure
Improvment
Handle comparison operators on enum columns
No
> Legend SQL - handle compare on enum columns

- legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/fromPure.pure
- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/tests/testTranspile.pure
Bug Fix/Improvement
- epoch handling 
- olap type argument fix
No
> Legend SQL - epoch handling and olap type argument fix

- legend-engine-xt-functionActivator-api/src/main/java/org/finos/legend/engine/functionActivator/api/FunctionActivatorAPI.java
- legend-engine-xt-functionActivator-api/src/main/java/org/finos/legend/engine/functionActivator/service/FunctionActivatorArtifact.java
- legend-engine-xt-functionActivator-api/src/main/java/org/finos/legend/engine/functionActivator/service/FunctionActivatorService.java
- legend-engine-xt-snowflakeApp-api/src/main/java/org/finos/legend/engine/language/snowflakeApp/api/SnowflakeAppArtifact.java
- legend-engine-xt-snowflakeApp-api/src/main/java/org/finos/legend/engine/language/snowflakeApp/api/SnowflakeAppService.java
Improvement
uplift function activator interface and add API for rendering generated artifact
Fixes #
No
> uplift function activator interface

- .github/workflows/legend-stack-release.yml
- .github/workflows/release-large-runner-serial.yml
- .github/workflows/release-large-runner.yml
- .github/workflows/release.yml
The workflow telemetry step will allow us to record build metrics
> Tracking build metrics

- legend-engine-xt-sql-grammar/src/main/java/org/finos/legend/engine/language/sql/grammar/from/SqlVisitor.java
- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/fromPure.pure
- legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/tests/testTranspile.pure
Bug Fix/Improvement
- coalesce support
- double precision support
- further expression stringification
- correct if statement multiplicity
- better handling of select items
No
> Legend SQL - assortment of changes

- legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/store/cluster.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tds/tests/testTDSJoin.pure
> TDSQueries Allocation Node Name

- legend-engine-xts-persistence/legend-engine-xt-persistence-target-relational-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/persistence/relational/temporality/sourcederived/SourceTimeFields.java
- legend-engine-xts-persistence/legend-engine-xt-persistence-target-relational-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/persistence/relational/temporality/updatesHandling/appendStrategy/AppendStrategy.java
- Bug Fix
Minor changes to JSON type names to sync with Studio
Fixes #
No
> Persistence V2: Rename JSON type names

- legend-engine-pure-ide/legend-engine-pure-ide-light/src/main/java/org/finos/legend/engine/ide/PureIDELight.java
- Bug Fix
Fixes IDE Light by updating paths of some modules
Fixes #
No
> Fix Pure IDE Light

- legend-engine-core-executionPlan-execution/legend-engine-executionPlan-execution-api/src/main/java/org/finos/legend/engine/plan/execution/api/request/RequestContextHelper.java
- legend-engine-core-executionPlan-execution/legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/cache/executionPlan/ExecutionPlanCache.java
- legend-engine-core-executionPlan-execution/legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/cache/executionPlan/ExecutionPlanCacheBuilder.java
- legend-engine-core-executionPlan-execution/legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/cache/executionPlan/PlanCacheKey.java
- legend-engine-core-executionPlan-execution/legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/parameterization/ParameterizedValueSpecification.java
- legend-engine-core-executionPlan-execution/legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/planHelper/PrimitiveValueSpecificationToObjectVisitor.java
- legend-engine-core-executionPlan-execution/legend-engine-executionPlan-execution/src/test/java/org/finos/legend/engine/plan/execution/parameterization/TestParameterizedValueSpecification.java
- legend-engine-core-executionPlan-execution/legend-engine-executionPlan-execution/src/test/resources/parameterization/lambdaWithFilter.json
- legend-engine-query-pure/pom.xml
- legend-engine-query-pure/src/main/java/org/finos/legend/engine/query/pure/api/Execute.java
- legend-engine-query-pure/src/main/java/org/finos/legend/engine/query/pure/cache/PureExecutionCacheKey.java
- legend-engine-query-pure/src/test/java/org/finos/legend/engine/query/pure/cache/TestExecutionPlanCache.java
- legend-engine-query-pure/src/test/java/org/finos/legend/engine/query/pure/cache/TestPureExecutionCacheKey.java
- legend-engine-query-pure/src/test/resources/org.finos.legend.engine.query.pure.cache/simpleQueryWithSDLCInfo.json
- legend-engine-server/src/main/java/org/finos/legend/engine/server/Server.java
- legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/testable/service/extension/ServiceTestRunner.java
- legend-engine-testable/src/main/java/org/finos/legend/engine/testable/assertion/TestAssertionEvaluator.java
> add initial support for plan caching of pure executions

- legend-engine-xts-rosetta/legend-engine-xt-rosetta-pure/src/main/resources/core_external_format_rosetta/transformation/transformation_model.pure
Bug Fix
Fix loading of rosetta repository
Fixes #
> Fix loading of rosetta repository

- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/autogeneration/relationalToPure.pure
**What type of PR is this?**
- Improvement
**What does this PR do / why is it needed ?**
This PR makes improvements on #2021. It removes logic involving plural nouns being converted to singular in class names, as this could be considered opinionated. As well, it replaces chained replace functions with a single fold, such that a given string is only iterated once, reducing time complexity. Lastly, some function names were modified to more accurately represent their implementation details.
**Which issue(s) this PR fixes:**
**Other notes for reviewers:**
**Does this PR introduce a user-facing change?**
> Improve class, column, and property name creation logic

- legend-engine-xts-changetoken/legend-engine-xt-changetoken-compiler/src/main/java/org/finos/legend/engine/changetoken/generation/GenerateCastFromJson.java
- legend-engine-xts-changetoken/legend-engine-xt-changetoken-compiler/src/main/java/org/finos/legend/engine/changetoken/generation/GenerateCastFromVersions.java
- legend-engine-xts-changetoken/legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCast4Test.java
- legend-engine-xts-changetoken/legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastChainTest.java
- legend-engine-xts-changetoken/legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastFromJsonTest.java
- legend-engine-xts-changetoken/legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastFromVersionsTest.java
- legend-engine-xts-changetoken/legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastTestBase.java
- legend-engine-xts-changetoken/legend-engine-xt-changetoken-pure/src/main/resources/core_pure_changetoken/cast_generation.pure
- legend-engine-xts-changetoken/legend-engine-xt-changetoken-pure/src/main/resources/core_pure_changetoken/changetoken_test.pure
Bug Fix
- When downcasting ignore null value fields
- Allow user to pass Versions or JSON String of Versions for processing
N/A
No
> Improve change token functionality

- legend-engine-xts-mastery/legend-engine-xt-mastery-pure/src/main/resources/core_mastery/mastery/metamodel.pure
Improvement
Updating Mastery precedence rule model to enforce more concrete types
Fixes #
> update mastery precedence rule model

- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-javaPlatformBinding-pure/src/main/resources/core_relational_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/graphFetchRelational.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/tests/testCrossStoreGraphFetchMilestoning.pure
<!--
- Improvement
->
All allVersions property to be used on a cross store execution
> fix use of allVersions on xstore queries

- pom.xml
> Update legend-pure to 4.5.9

- .github/workflows/database-athena-sql-generation-integration-test.yml
Bug Fix
Use new url for driver
> Update athena driver for integration tests

- legend-engine-xts-sql/legend-engine-xt-sql-postgres-server/pom.xml
- legend-engine-xts-sql/legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/AuthenticationContext.java
- legend-engine-xts-sql/legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/PostgresServer.java
- legend-engine-xts-sql/legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/PostgresWireProtocol.java
- legend-engine-xts-sql/legend-engine-xt-sql-postgres-server/src/main/java/org/finos/legend/engine/postgres/transport/Netty4OpenChannelsHandler.java
- legend-engine-xts-sql/legend-engine-xt-sql-postgres-server/src/test/java/org/finos/legend/engine/postgres/TestPostgresServer.java
- legend-engine-xts-sql/legend-engine-xt-sql-query/src/main/java/org/finos/legend/engine/query/sql/api/execute/SqlExecute.java
- pom.xml
Improvement
- Rename logger name to use Class name
- Bump netty version
- Use native netty handler when available 
- Add client IP to MDC
- Add username to MDC
- Previous addition of username to MDC only occurred for non-Kerberos modes of authentication. Proposed implementation moves it up so username is included for all modes of authentication
- Client IP is added on connection establishment (i.e. pre-authentication)
No
> Legend SQL - Update logging

- legend-engine-xts-persistence/legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/logicalplan/datasets/DataType.java
- legend-engine-xts-persistence/legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/util/LogicalPlanUtils.java
- legend-engine-xts-persistence/legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/main/java/org/finos/legend/engine/persistence/components/relational/ansi/sql/AnsiDatatypeMapping.java
- legend-engine-xts-persistence/legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/logicalplan/operations/BaseTestUtils.java
- legend-engine-xts-persistence/legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/logicalplan/operations/CreateTableTest.java
- legend-engine-xts-persistence/legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/relational/ansi/sql/DataTypeMappingTest.java
- legend-engine-xts-persistence/legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-bigquery/src/main/java/org/finos/legend/engine/persistence/components/relational/bigquery/BigQuerySink.java
- legend-engine-xts-persistence/legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-bigquery/src/main/java/org/finos/legend/engine/persistence/components/relational/bigquery/sql/BigQueryDataTypeMapping.java
- legend-engine-xts-persistence/legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-bigquery/src/test/java/org/finos/legend/engine/persistence/components/BaseTestUtils.java
- legend-engine-xts-persistence/legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-bigquery/src/test/java/org/finos/legend/engine/persistence/components/e2e/SchemaEvolutionTest.java
- legend-engine-xts-persistence/legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-bigquery/src/test/java/org/finos/legend/engine/persistence/components/logicalplan/operations/CreateTableTest.java
- legend-engine-xts-persistence/legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-bigquery/src/test/java/org/finos/legend/engine/persistence/components/relational/bigquery/sql/DataTypeMappingTest.java
- legend-engine-xts-persistence/legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/main/java/org/finos/legend/engine/persistence/components/relational/h2/sql/H2DataTypeMapping.java
- legend-engine-xts-persistence/legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/main/java/org/finos/legend/engine/persistence/components/relational/h2/sql/H2JdbcPropertiesToLogicalDataTypeMapping.java
- legend-engine-xts-persistence/legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/main/java/org/finos/legend/engine/persistence/components/relational/memsql/sql/MemSqlDataTypeMapping.java
- legend-engine-xts-persistence/legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/main/java/org/finos/legend/engine/persistence/components/relational/snowflake/SnowflakeSink.java
- legend-engine-xts-persistence/legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/main/java/org/finos/legend/engine/persistence/components/relational/snowflake/sql/SnowflakeDataTypeMapping.java
- Improvement
- Standardise the Logical Data types and remove the redundant ones
- Fix the mapping of Logical Data types including TIMESTAMP_TZ
NO
> Persistence Component: Fix Logical Data types and their mapping

- legend-engine-pure-code/legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/functionInMapping.pure
> updated serverVersion start for test

- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/milestoning/milestoning.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/milestoning/tests/testApplyMilestoningFilters.pure
Bug Fix
This change fixes milestoning filter application for semi structured flatten elements
> Handle semi structured flatten element in applyMilestoningFilters

- .github/workflows/database-athena-sql-generation-integration-test.yml
- .github/workflows/database-bigquery-sql-generation-integration-test.yml
- .github/workflows/database-databricks-sql-generation-integration-test.yml
- .github/workflows/database-h2-sql-generation-integration-test.yml
- .github/workflows/database-mssqlserver-sql-generation-integration-test.yml
- .github/workflows/database-postgresql-integration-test.yml
- .github/workflows/database-postgresql-sql-generation-integration-test.yml
- .github/workflows/database-redshift-sql-generation-integration-test.yml
- .github/workflows/database-singlestore-integration-test.yml
- .github/workflows/database-singlestore-sql-generation-integration-test.yml
- .github/workflows/database-snowflake-integration-test.yml
- .github/workflows/database-snowflake-sql-generation-integration-test.yml
- .github/workflows/database-spanner-sql-generation-integration-test.yml
- .github/workflows/database-trino-sql-generation-integration-test.yml
- .github/workflows/summarize-sql-generation-integration-tests-v2.yml
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-test-reports/pom.xml
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-test-reports/src/main/java/org/finos/legend/engine/test/LegendDatabaseSQLTestingReport.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-test-reports/src/main/java/org/finos/legend/engine/test/LegendDatabaseTestingReportGenerator.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-test-reports/src/main/java/org/finos/legend/engine/test/TestStatus.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/pom.xml
- pom.xml
Improvement
Re-add sql integration test report
> Re-add SQL Test Reports

- legend-engine-external-format-jsonSchema/src/main/java/org/finos/legend/engine/external/format/jsonSchema/schema/generations/JSONSchemaGenerationService.java
- legend-engine-external-shared-format-model/src/main/java/org/finos/legend/engine/external/shared/format/model/api/ExternalFormats.java
- legend-engine-xts-analytics/legend-engine-xts-analytics-store/legend-engine-xt-analytics-store-entitlement/src/main/java/org/finos/legend/engine/entitlement/services/EntitlementServiceExtensionLoader.java
- legend-engine-xts-generation/legend-engine-xt-artifact-generation-api/src/main/java/org/finos/legend/engine/generation/artifact/api/ArtifactGenerationExtensionApi.java
- legend-engine-xts-protobuf/legend-engine-xt-protobuf/src/main/java/org/finos/legend/engine/external/format/protobuf/deprecated/generation/ProtobufGenerationService.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-test-server/src/main/java/org/finos/legend/engine/server/test/shared/ExecuteInRelationalDb.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-test-server/src/main/java/org/finos/legend/engine/server/test/shared/TestConnectionProviderApi.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/RelationalExecutor.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/StreamResultToTempTableVisitor.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/blockConnection/BlockConnection.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/RelationalResult.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/ResultInterpreterExtensionLoader.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/SQLExecutionResult.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/SQLResult.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/SQLUpdateResult.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/VoidRelationalResult.java
- legend-engine-xts-rosetta/legend-engine-xt-rosetta/src/main/java/org/finos/legend/engine/external/format/rosetta/RosettaGenerationService.java
Improvement
Updating loggers to use class name
> Logger - use class names instead of string constant

- legend-engine-xts-flatdata/legend-engine-xt-flatdata-pure/src/main/resources/core_external_format_flatdata/executionPlan/tests/simple.pure
- legend-engine-xts-java/legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/binding/shared.pure
Bug Fix
Fix propagation of checked flag
Fixes #
> Fix propagation of checked flag

- legend-engine-core-executionPlan-execution/legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/InputStreamResult.java
- legend-engine-core-executionPlan-execution/legend-engine-executionPlan-execution/src/test/java/org/finos/legend/engine/plan/execution/result/TestInputStreamResult.java
- legend-engine-xts-serviceStore/legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/ServiceExecutor.java
> Correctly close service store result

- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/autogeneration/relationalToPure.pure
**What type of PR is this?**
- Bug Fix
**What does this PR do / why is it needed ?**
This PR fixes a bug in relationalToPure.pure where there's a mismatch in classpath between class mappings and associations that occurs while generating association mappings.
**Which issue(s) this PR fixes:**
Fixes #
**Other notes for reviewers:**
**Does this PR introduce a user-facing change?**
> Fix classpath mismatch bug in association mapping generation

- legend-engine-config/legend-engine-server-support-core/pom.xml
- legend-engine-config/legend-engine-server-support-core/src/main/java/org/finos/legend/engine/server/support/server/BaseServer.java
- legend-engine-config/legend-engine-server-support-core/src/main/java/org/finos/legend/engine/server/support/server/config/BaseServerConfiguration.java
- legend-engine-config/legend-engine-server-support-core/src/main/java/org/finos/legend/engine/server/support/server/config/CORSConfiguration.java
- legend-engine-config/legend-engine-server-support-core/src/main/java/org/finos/legend/engine/server/support/server/config/ErrorHandlingConfiguration.java
- legend-engine-config/legend-engine-server-support-core/src/main/java/org/finos/legend/engine/server/support/server/exception/ServerException.java
- legend-engine-config/legend-engine-server-support-core/src/main/java/org/finos/legend/engine/server/support/server/monitoring/ServerMetricsHandler.java
- legend-engine-config/legend-engine-server-support-core/src/main/java/org/finos/legend/engine/server/support/server/resources/BaseResource.java
- legend-engine-config/legend-engine-server-support-core/src/main/java/org/finos/legend/engine/server/support/server/tools/StringTools.java
- legend-engine-config/pom.xml
- legend-engine-core-shared/legend-engine-shared-core/src/main/resources/legendExecutionVersion.json
- legend-engine-xts-data-push/legend-engine-xt-data-push-server/pom.xml
- legend-engine-xts-data-push/legend-engine-xt-data-push-server/src/main/java/org/finos/legend/engine/datapush/server/BaseDataPushServer.java
- legend-engine-xts-data-push/legend-engine-xt-data-push-server/src/main/java/org/finos/legend/engine/datapush/server/config/DataPushServerConfiguration.java
- legend-engine-xts-data-push/legend-engine-xt-data-push-server/src/main/java/org/finos/legend/engine/datapush/server/resources/DataPushResource.java
- legend-engine-xts-data-push/legend-engine-xt-data-push-server/src/test/java/org/finos/legend/engine/datapush/server/TestDataPushResource.java
- legend-engine-xts-data-push/legend-engine-xt-data-push-server/src/test/java/org/finos/legend/engine/datapush/server/resources/DataPushTestResource.java
- legend-engine-xts-data-push/legend-engine-xt-data-push-server/src/test/java/org/finos/legend/engine/datapush/server/test/AbstractDataPushServerResourceTest.java
- legend-engine-xts-data-push/legend-engine-xt-data-push-server/src/test/java/org/finos/legend/engine/datapush/server/test/DataPushServerClientRule.java
- legend-engine-xts-data-push/legend-engine-xt-data-push-server/src/test/java/org/finos/legend/engine/datapush/server/test/DataPushServerForTest.java
- legend-engine-xts-data-push/legend-engine-xt-data-push-server/src/test/resources/config-test.yaml
- legend-engine-xts-data-push/pom.xml
- pom.xml
Improvement
Add first cut of Maven modules for data-push. 
Fixes #
> Add modules for data-push server

- legend-engine-xts-iceberg/legend-engine-xt-iceberg-test-support/src/test/java/org/finos/legend/tableformat/iceberg/testsupport/IceboxTest.java
> Ignore test case until we ensure can run on all CI's env

- legend-engine-xts-iceberg/legend-engine-xt-iceberg-test-support/src/main/java/org/finos/legend/tableformat/iceberg/testsupport/Icebox.java
- legend-engine-xts-iceberg/legend-engine-xt-iceberg-test-support/src/test/java/org/finos/legend/tableformat/iceberg/testsupport/IceboxTest.java
> Re-enable Icebox test case

- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/testDataGeneration/testDataGeneration.pure
Bug Fix
fix a bug where fail to autogenerate service test data when there is a milestoning parameter
Fixes #
> fix a bug where fail to autogenerate service test data when there is a milestoning parameter

- legend-engine-xts-java/legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/platform/executionPlanNodes/platform/serialize.pure
- legend-engine-xts-serviceStore/legend-engine-xt-serviceStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/service/showcase/jsonApis/ServiceStoreJsonShowcaseTest.java
Bug Fix
Fix algorithm to pick auxiliary tree
Fixes #
> Fix algorithm to pick auxiliary tree

- legend-engine-pure-code/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphFetch_routing.pure
- legend-engine-pure-code/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/store/builder.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/tests/testSubTypeGraphFetch.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/tests/union/relationalGraphFetchUnionWithMilestoning.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/tests/union/testUnionPropertyLevel_Relational.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/milestoning/tests/businessDateMilestoningSetUp.pure
-Improvement
This PR will allow milestoned or qualified property union in relationalGraphFetch
Yes
> support milestoned/qualified property union in relationalGraphFetch

- legend-engine-core-language-pure/legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestGrammarRoundtrip.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperRelationalGrammarComposer.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/RelationalGrammarComposerContext.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/RelationalGrammarComposerExtension.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalGrammarRoundtrip.java
Improvement
Autoformats Join statements when in RenderStyle.Pretty, using indents and tabs as necessary to make code readable
Fixes #
Fixes part of https://jira.work.gs.com/browse/ALLOYEXEC-1860.
> Added Autoformatting of Join Statements

- legend-engine-config/legend-engine-server/pom.xml
- legend-engine-config/legend-engine-server/src/main/java/org/finos/legend/engine/server/Server.java
- legend-engine-core-shared/legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/operational/logs/LoggingEventType.java
- legend-engine-test-data-generation/pom.xml
- legend-engine-test-data-generation/src/main/java/org/finos/legend/engine/testData/generation/api/TestDataGeneration.java
- legend-engine-test-data-generation/src/main/java/org/finos/legend/engine/testData/generation/model/TestDataGenerationInput.java
- legend-engine-test-data-generation/src/main/java/org/finos/legend/engine/testData/generation/model/TestDataGenerationResult.java
- legend-engine-test-data-generation/src/main/java/org/finos/legend/engine/testData/generation/service/TestDataGenerationService.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/testDataGeneration/testDataGeneration.pure
- pom.xml
Improvement
Test Data Generation I - support a new API to generate skeleton schema/table from query
Fixes #
> Test Data Generation I -  support a new API to generate skeleton schema/table from query

- legend-engine-test-data-generation/pom.xml
- legend-engine-test-data-generation/src/test/java/org.finos.legend.engine/testDataGeneration/TestDataGenerationTest.java
- legend-engine-test-data-generation/src/test/resources/models/relationalModelTestDataGenerationInput.json
Improvement 
add tests for the API which is to generate Skeleton schema/table
Fixes #
> add tests for the API which is to generate Skeleton schema/table

- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan-connection-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/ExternalIntegration_TestConnectionAcquisitionWithFlowProvider_Snowflake_TempTable.java
Bug Fix
Fix Asserts for temp table case tests (With this change, Snowflake Integration Test workflow is fixed : https://github.com/finos/legend-engine/actions/runs/5817757659)
Fixes #
>  Fix Snowflake Integration Test workflow

- legend-engine-xts-changetoken/legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastMoveExtractTest.java
- legend-engine-xts-changetoken/legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastMoveNestedTest.java
- legend-engine-xts-changetoken/legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastMoveTest.java
- legend-engine-xts-changetoken/legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastRemoveTest.java
- legend-engine-xts-changetoken/legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastRenameNestedPropertyTest.java
- legend-engine-xts-changetoken/legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastRenamePropertyTest.java
- legend-engine-xts-changetoken/legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastRenameTest.java
- legend-engine-xts-changetoken/legend-engine-xt-changetoken-pure/src/main/resources/core_pure_changetoken/cast_generation.pure
- legend-engine-xts-changetoken/legend-engine-xt-changetoken-pure/src/main/resources/core_pure_changetoken/changetoken.pure
- legend-engine-xts-changetoken/legend-engine-xt-changetoken-pure/src/main/resources/core_pure_changetoken/changetoken_test.pure
Improvement
Handle removing of a field in change tokens.
Handle renaming and moving of a field in change tokens.
N/A
N/A
With this improvement it is possible now to extract or aggregate properties, as well as simply remove or rename them.
> Handle RenameField and RemoveField

- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/helperFunctions/helperFunctions.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/DDL/testDDL.pure
- legend-engine-xts-service/legend-engine-test-runner-service/src/test/java/org/finos/legend/engine/testable/service/TestServiceTestSuite.java
- legend-engine-xts-service/legend-engine-test-runner-service/src/test/resources/testable/relational/legend-testable-relational-service-csv-test-data.pure
Improvement
remove leading and ending quotes for service test csv column value which contains comma
Fixes #
> remove leading and ending quotes for service test csv column value which contains comma

- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/testDataGeneration/testDataGeneration.pure
> add missing limit 20 to test data generation

- legend-engine-pure/legend-engine-pure-code/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphExtension.pure
- legend-engine-xts-java/legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/shared/constraints.pure
- legend-engine-xts-json/legend-engine-xt-json-pure/src/main/resources/core_external_format_json/executionPlan/tests/constraints.pure
- legend-engine-xts-json/legend-engine-xt-json-pure/src/main/resources/core_external_format_json/executionPlan/tests/resources/graphFetchCheckedUnexpandedWithSubTypes.json
- legend-engine-xts-json/legend-engine-xt-json-pure/src/main/resources/core_external_format_json/executionPlan/tests/resources/graphFetchCheckedWithSubtypes.json
- Improvement
It will allow users to specify multiple subtype trees at property level while internalization.
Yes
> Support multiple graphFetchSubTypeTrees at property level in external format

- legend-engine-config/legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java
- legend-engine-config/legend-engine-pure-code-compiled-core-configuration/src/main/resources/core_configuration/coreExtensions.pure
- legend-engine-xts-flatdata/legend-engine-xt-flatdata-javaPlatformBinding-pure/src/main/resources/core_external_format_flatdata_java_platform_binding/legendJavaPlatformBinding/descriptor.pure
- legend-engine-xts-flatdata/legend-engine-xt-flatdata-javaPlatformBinding-test/src/main/resources/core_external_format_flatdata_java_platform_binding_test/utils.pure
- legend-engine-xts-java/legend-engine-xt-javaPlatformBinding-pure/src/main/java/org/finos/legend/pure/code/core/BindingJavaBindingPureCoreExtension.java
- legend-engine-xts-java/legend-engine-xt-javaPlatformBinding-pure/src/main/resources/META-INF/services/org.finos.legend.engine.pure.code.core.PureCoreExtension
- legend-engine-xts-java/legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/binding/bindingLegendJavaPlatformBindingExtension.pure
- legend-engine-xts-java/legend-engine-xt-javaPlatformBinding-pure/src/test/java/org/finos/legend/engine/pure/code/core/java/binding/TestExtensionAvailable.java
- legend-engine-xts-json/legend-engine-xt-json-javaPlatformBinding-pure/src/main/resources/core_external_format_json_java_platform_binding/legendJavaPlatformBinding/descriptor.pure
- legend-engine-xts-json/legend-engine-xt-json-javaPlatformBinding-pure/src/test/java/org/finos/legend/engine/pure/code/core/json/binding/TestExtensionAvailable.java
- legend-engine-xts-json/legend-engine-xt-json-javaPlatformBinding-test/src/main/resources/core_external_format_json_java_platform_binding_test/utils.pure
- legend-engine-xts-mongodb/legend-engine-xt-nonrelationalStore-mongodb-javaPlatformBinding-pure/src/main/resources/core_nonrelational_mongodb_java_platform_binding/mongodbStoreLegendJavaPlatformBindingExtension.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-javaPlatformBinding-pure/src/main/resources/core_relational_java_platform_binding/legendJavaPlatformBinding/relationalLegendJavaPlatformBindingExtension.pure
- legend-engine-xts-serviceStore/legend-engine-xt-serviceStore-javaPlatformBinding-pure/src/main/resources/core_servicestore_java_platform_binding/legendJavaPlatformBinding/serviceStoreLegendJavaPlatformBindingExtension.pure
- legend-engine-xts-serviceStore/legend-engine-xt-serviceStore-javaPlatformBinding-pure/src/test/java/org/finos/legend/engine/pure/code/core/servicestore/binding/TestExtensionAvailable.java
- legend-engine-xts-xml/legend-engine-xt-xml-javaPlatformBinding-pure/src/main/resources/core_external_format_xml_java_platform_binding/legendJavaPlatformBinding/descriptor.pure
- legend-engine-xts-xml/legend-engine-xt-xml-javaPlatformBinding-pure/src/main/resources/core_external_format_xml_java_platform_binding/legendJavaPlatformBinding/tests/shared.pure
Bug Fix
Create unique id's for external format platform binding extension
Fixes #
> Create unique id's for external format platform binding extension

- pom.xml
Update legend-pure version
Fixes #
> Update legend-pure version

- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/postprocessor/defaultPostProcessor/dbSpecificProcessor.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbExtension.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/snowflake/snowflakeExtension.pure
Bug Fix
This will enable Query tags to be generated for legacy snowflake connections
No
> QueryTag for Legacy Connections

- legend-engine-pure/legend-engine-pure-code/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/routing/router_routing.pure
- legend-engine-pure/legend-engine-pure-code/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/store/routing.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSemiStructuredMultiBindingMapping.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSimpleSemiStructuredMapping.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/semiStructuredMultiBindingMapping.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/simpleSemiStructuredMapping.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalBuilder.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/contract/storeContract.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/helperFunctions/helperFunctions.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/lineage/scanColumns/scanColumns.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
Improvement
This mapping changes handling of semi structured mappings as auto mappings
No
> Handle semi structured mappings as auto mappings

- legend-engine-config/legend-engine-pure-code-compiled-core-configuration/src/main/resources/core_configuration/coreExtensions.pure
- legend-engine-pure/legend-engine-pure-code/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/platformBinding/platformBinding.pure
- legend-engine-pure/legend-engine-pure-code/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/extensions/extension.pure
- legend-engine-pure/legend-engine-pure-runtime/legend-engine-pure-runtime-execution/src/test/resources/testModels.txt
- legend-engine-xts-flatdata/legend-engine-xt-flatdata-javaPlatformBinding-pure/src/main/resources/core_external_format_flatdata_java_platform_binding/legendJavaPlatformBinding/descriptor.pure
- legend-engine-xts-flatdata/legend-engine-xt-flatdata-javaPlatformBinding-pure/src/test/java/org/finos/legend/engine/pure/code/core/flatdata/binding/TestExtensionAvailable.java
- legend-engine-xts-flatdata/legend-engine-xt-flatdata-javaPlatformBinding-test/src/main/resources/core_external_format_flatdata_java_platform_binding_test/utils.pure
- legend-engine-xts-java/legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/binding/bindingLegendJavaPlatformBindingExtension.pure
- legend-engine-xts-java/legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/legendJavaPlatformBinding.pure
- legend-engine-xts-java/legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/store/m2m/m2mLegendJavaPlatformBindingExtension.pure
- legend-engine-xts-java/legend-engine-xt-javaPlatformBinding-pure/src/test/java/org/finos/legend/engine/pure/code/core/java/binding/TestExtensionAvailable.java
- legend-engine-xts-json/legend-engine-xt-json-javaPlatformBinding-pure/src/main/resources/core_external_format_json_java_platform_binding/legendJavaPlatformBinding/descriptor.pure
- legend-engine-xts-json/legend-engine-xt-json-javaPlatformBinding-pure/src/test/java/org/finos/legend/engine/pure/code/core/json/binding/TestExtensionAvailable.java
- legend-engine-xts-json/legend-engine-xt-json-javaPlatformBinding-test/src/main/resources/core_external_format_json_java_platform_binding_test/utils.pure
- legend-engine-xts-mongodb/legend-engine-xt-nonrelationalStore-mongodb-javaPlatformBinding-pure/src/main/resources/core_nonrelational_mongodb_java_platform_binding/mongodbStoreLegendJavaPlatformBindingExtension.pure
- legend-engine-xts-mongodb/legend-engine-xt-nonrelationalStore-mongodb-javaPlatformBinding-pure/src/test/java/org/finos/legend/pure/code/core/mongodb/TestExtensionAvailable.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-javaPlatformBinding-pure/src/main/resources/core_relational_java_platform_binding/legendJavaPlatformBinding/relationalLegendJavaPlatformBindingExtension.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-javaPlatformBinding-pure/src/test/java/org/finos/legend/engine/pure/code/core/relational/binding/TestExtensionAvailable.java
- legend-engine-xts-serviceStore/legend-engine-xt-serviceStore-javaPlatformBinding-pure/src/main/resources/core_servicestore_java_platform_binding/legendJavaPlatformBinding/serviceStoreLegendJavaPlatformBindingExtension.pure
- legend-engine-xts-serviceStore/legend-engine-xt-serviceStore-javaPlatformBinding-pure/src/test/java/org/finos/legend/engine/pure/code/core/servicestore/binding/TestExtensionAvailable.java
- legend-engine-xts-xml/legend-engine-xt-xml-javaPlatformBinding-pure/src/main/resources/core_external_format_xml_java_platform_binding/legendJavaPlatformBinding/descriptor.pure
- legend-engine-xts-xml/legend-engine-xt-xml-javaPlatformBinding-pure/src/main/resources/core_external_format_xml_java_platform_binding/legendJavaPlatformBinding/tests/shared.pure
- legend-engine-xts-xml/legend-engine-xt-xml-javaPlatformBinding-pure/src/test/java/org/finos/legend/engine/pure/code/core/xml/binding/TestExtensionAvailable.java
Improvement
This PR adds extension printing support, and also improves names of platform binding extensions. Combined with getExtensions() function, it can help debug available feature support.
CodeBlock:
```
let extensions = meta::pure::extension::runtime::getExtensions();
$extensions->meta::pure::extension::print::printExtensions()->println();
```
Ouput:
```
[                                                                                                                                                                     
defaultExtensions                                                                                                                                                    
( …
```
> Extension printing + Fix platform binding extension names

- legend-engine-core/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperModelBuilder.java
- legend-engine-core/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperValueSpecificationBuilder.java
- legend-engine-core/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/Milestoning.java
- legend-engine-core/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/MilestoningDatePropagationHelper.java
- legend-engine-core/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestMilestonedPropertyUsageInGraphFetch.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/tests/testGraphFetchMilestoning.pure
.
Improvement
Adds support for milestoning date propagation in graphFetch  from left expression to No-Arg Milestoned properties in graph fetch tree
Fixes #
> Add support for milestoning date propagation in graphFetch in engine compiler

- legend-engine-core/legend-engine-core-language-pure/legend-engine-protocol-pure/pom.xml
> Fix dependencies

- legend-engine-xts-openapi/legend-engine-xt-openapi-pure/src/main/resources/core_external_format_openapi/metamodel/metamodel.pure
- legend-engine-xts-openapi/legend-engine-xt-openapi-pure/src/main/resources/core_external_format_openapi/toString.pure
- legend-engine-xts-openapi/legend-engine-xt-openapi-pure/src/main/resources/core_external_format_openapi/transformation/fromPure/pureToOpenApi.pure
- legend-engine-xts-openapi/legend-engine-xt-openapi-pure/src/main/resources/core_external_format_openapi/transformation/fromPure/tests/resources/testOpenApiSpecWithExtendAndManyParam.txt
- legend-engine-xts-openapi/legend-engine-xt-openapi-pure/src/main/resources/core_external_format_openapi/transformation/fromPure/tests/resources/testOpenApiSpecWithServiceParams.txt
- legend-engine-xts-openapi/legend-engine-xt-openapi-pure/src/main/resources/core_external_format_openapi/transformation/fromPure/tests/resources/testOpenApiSpecWithoutColumnSpec.txt
- legend-engine-xts-openapi/legend-engine-xt-openapi-pure/src/main/resources/core_external_format_openapi/transformation/fromPure/tests/tests.pure
> Add function param and function return type to open api spec

- legend-engine-xts-java/legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/langLibrary.pure
- legend-engine-xts-java/legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/langLibraryTests.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-javaPlatformBinding-pure/src/main/resources/core_relational_java_platform_binding/legendJavaPlatformBinding/executionPlanTest.pure
Reverts finos/legend-engine#2118
> Revert "improve  generated if compilation speed"

- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/query/testView.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/relationalSetUp.pure
Bug Fix
Resole view to table reference recursively to fetch defined primary keys
No
> Resole view to table recursively

- legend-engine-xts-service/legend-engine-language-pure-dsl-service-generation/pom.xml
- legend-engine-xts-service/legend-engine-language-pure-dsl-service-generation/src/main/java/org/finos/legend/engine/language/pure/dsl/service/generation/ServicePlanGenerator.java
Improvement
Allow parallelization in plan generation for multi-execution services.
No
> Multi exec plan gen

- legend-engine-xts-iceberg/legend-engine-xt-iceberg-test-support/pom.xml
- legend-engine-xts-iceberg/legend-engine-xt-iceberg-test-support/src/main/java/org/finos/legend/tableformat/iceberg/testsupport/IceboxSpark.java
- legend-engine-xts-iceberg/legend-engine-xt-iceberg-test-support/src/main/java/org/finos/legend/tableformat/iceberg/testsupport/IceboxTrino.java
- legend-engine-xts-iceberg/legend-engine-xt-iceberg-test-support/src/test/java/org/finos/legend/tableformat/iceberg/testsupport/IceboxSparkTest.java
- legend-engine-xts-iceberg/legend-engine-xt-iceberg-test-support/src/test/java/org/finos/legend/tableformat/iceberg/testsupport/IceboxTrinoTest.java
- legend-engine-xts-iceberg/legend-engine-xt-iceberg-test-support/src/test/resources/spark-defaults.conf
Improvement
Create a sample Icebox using Spark for creating and accessing Iceberg tables, and Nessie for the catalog.
Fixes #
> Icebox using Spark/nessie

- legend-engine-xts-changetoken/README.md
- legend-engine-xts-changetoken/legend-engine-xt-changetoken-pure/src/main/resources/core_pure_changetoken/cast_generation.pure
Documentation of change tokens functionality.
To provide users with basic module functionality
N/A
Described the most basic usage and restrictions.
Referenced unit test in the end of document as most up to date documentation.
No
> Document change tokens

- legend-engine-xts-iceberg/legend-engine-xt-iceberg-test-support/src/test/java/org/finos/legend/tableformat/iceberg/testsupport/IceboxSparkTest.java
> Enable spark/nessie test case

- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-api/src/test/resources/expectedJson.json
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/autogeneration/relationalToPure.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/autogeneration/tests/relationalToPure.pure
> remove any from generated models from store

- legend-engine-config/legend-engine-server/pom.xml
> add missing relational store grammar/protocol extensions to engine server

- legend-engine-pure/legend-engine-pure-code/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphFetch_routing.pure
Bug Fix
Some setImplementations were dropped in property union queries on graphFetch, This PR will eliminate that issue.
Yes
> small fix for property union in graphFetch

- legend-engine-pure/legend-engine-pure-code/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/externalFormat/routing.pure
- legend-engine-xts-json/legend-engine-xt-json-pure/src/main/resources/core_external_format_json/executionPlan/tests/simple.pure
Improvement
Add support for function expressions supplying input data to internalize
> External format: Fix routing of input data functions for internalize

- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tds/tests/testTDSFilter.pure
> Fix string concat in tds queries

- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/state/ConnectionStateManager.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan-connection/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/state/TestConnectionStateManager.java
- legend-engine-xts-service/legend-engine-language-pure-dsl-service-execution/pom.xml
- legend-engine-xts-service/legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/TestIdentityFactory.java
- legend-engine-xts-service/legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/TestServiceRunner.java
- legend-engine-xts-service/legend-engine-language-pure-dsl-service-execution/src/test/resources/META-INF/services/org.finos.legend.engine.shared.core.identity.factory.IdentityFactory
> check if identity is valid before obtaining connections

- legend-engine-xts-sql/legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/fromPure.pure
- legend-engine-xts-sql/legend-engine-xt-sql-query/src/main/java/org/finos/legend/engine/query/sql/api/sources/TableSourceExtractor.java
- legend-engine-xts-sql/legend-engine-xt-sql-query/src/test/java/org/finos/legend/engine/query/sql/api/execute/SqlExecuteTest.java
- legend-engine-xts-sql/legend-engine-xt-sql-query/src/test/resources/proj-1.pure
Improvement
Allows users to specify expressions in the table function arguments
> Legend SQL - Support Expression arguments

- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/RelationalExecutionNodeExecutor.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/RelationalGraphFetchUtils.java
- legend-engine-xts-service/legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/TestServiceRunner.java
- legend-engine-xts-service/legend-engine-language-pure-dsl-service-execution/src/test/resources/org/finos/legend/engine/pure/dsl/service/execution/test/xStorePropertyAccessServices.pure
Bug Fix
When invoking the obj which is an instance of generated java, identify the IChecked type and resolve the actual value wrapped within the object
No
> Fix XStore with GraphFetchChecked

- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-api/src/main/java/org/finos/legend/engine/language/pure/relational/api/relationalElement/RelationalElementAPI.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/autogeneration/relationalToPure.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/autogeneration/tests/relationalToPure.pure
> fix input for target package in db to model

- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/lineage/scanRelations/scanRelations.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/lineage/scanRelations/scanRelationsTestWithViewsAndUnions.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/testDataGeneration/testDataGeneration.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/testDataGeneration/tests/testDataGeneration.pure
Bug Fix 
Fix test data generation algorithm :
1. Correctly quote TableAliasColumn in generated joins for views
2.  Fix Relation Tree algorithm to account for views in schema different than main table
Fixes #
> Fix test data generation algorithm

- legend-engine-core/legend-engine-core-executionPlan-execution/legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/domain/date/PureDate.java
- legend-engine-core/legend-engine-core-executionPlan-execution/legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/util/Library.java
- pom.xml
Improvement
Fix number overflow issues with adjust operations on date
Fixes #
> Fix number overflow issues with adjust operations on date

- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/testDataGeneration/tests/testDataGeneration.pure
Bug Fix
Fix test failure in build
Fixes #
> Fix test failure in build

- legend-engine-core/legend-engine-core-language-pure/legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/CompositeExecutionPlan.java
fix assert not found from pom 
replacing assert with conditional runtime exception throw
Fixes #
no
> remove assert from CompositeExecutionPlan

- legend-engine-config/legend-engine-extensions-collection-generation/pom.xml
- legend-engine-config/legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java
- legend-engine-pure/legend-engine-pure-code/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/tds/tdsSchema.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/extensions/extension.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tds/tests/testTdsSchema.pure
- legend-engine-xts-sql/legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/fromPure.pure
- legend-engine-xts-sql/legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/tests/shared.pure
- legend-engine-xts-sql/legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/tests/testTranspile.pure
- legend-engine-xts-sql/legend-engine-xt-sql-query/src/main/java/org/finos/legend/engine/query/sql/api/sources/SQLSourceTranslator.java
Improvement
Handle tableToTDS functions
> Legend SQL - handle tableToTDS functions

- legend-engine-core/legend-engine-core-language-pure/legend-engine-language-pure-modelManager-sdlc/pom.xml
- legend-engine-core/legend-engine-core-language-pure/legend-engine-language-pure-modelManager-sdlc/src/main/java/org/finos/legend/engine/language/pure/modelManager/sdlc/SDLCLoader.java
- legend-engine-core/legend-engine-core-language-pure/legend-engine-language-pure-modelManager-sdlc/src/main/java/org/finos/legend/engine/language/pure/modelManager/sdlc/alloy/AlloySDLCLoader.java
- legend-engine-core/legend-engine-core-language-pure/legend-engine-language-pure-modelManager-sdlc/src/test/java/org/finos/legend/engine/language/pure/modelManager/sdlc/TestSDLCLoader.java
- pom.xml
Improvement
On some scenarios, metadata could fail with responses that are retriable.  Rather than failing immidiatly, we should back off and retry.  
Fixes #
> Retry metadata calls on some http response codes

- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-dbExtension/legend-engine-xt-relationalStore-snowflake/legend-engine-xt-relationalStore-snowflake-pure/src/main/resources/core_relational_snowflake/relational/sqlQueryToString/snowflakeExtension.pure
Bug Fix
Fix date diff in snowflake
> Datediff millisecond in snowflake

- legend-engine-core/legend-engine-core-language-pure/legend-engine-external-shared-format-model/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ExternalFormatCompilerExtension.java
- legend-engine-core/legend-engine-core-language-pure/legend-engine-external-shared-format-model/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestExternalFormatCompilation.java
Improvement
Add checked and defaultDefectTree function handlers
Fixes #
> Add checked and defaultDefectTree function handlers

- legend-engine-config/legend-engine-pure-code-compiled-core-configuration/src/main/resources/core_configuration/coreExtensions.pure
- legend-engine-pure/legend-engine-pure-code/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/platformBinding/platformBinding.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-javaPlatformBinding-pure/src/main/resources/core_relational_java_platform_binding/legendJavaPlatformBinding/relationalLegendJavaPlatformBindingExtension.pure
Delete deprecated local platform binding aspects
> Delete deprecated local platform binding aspects

- legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-V7-pure-metamodel/src/main/resources/core_elasticsearch_seven_metamodel/extensions/store_contract.pure
- legend-engine-xts-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/main/resources/core_elasticsearch_execution_test/elasticsearch_test_tds_schema.pure
Improvement
Adding schema resolve for indexToTDS
> ElasticSearch - IndexToTDS schema resolve

- legend-engine-xts-json/legend-engine-xt-json-runtime/src/main/java/org/finos/legend/engine/external/format/json/read/JsonDataReader.java
Improvement
Pre-compute declared methods to optimization deserialization of json
Fixes #
> Pre-compute declared methods to optimization deserialization of json

- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/testDataGeneration/testDataGeneration.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/testDataGeneration/tests/testDataGeneration.pure
Bug Fix
Fix test data generation for queries involving views. If view column is not 1-1 with mainTable column, it currently fails. This PR fixes such scenarios
Fixes #
> Fix test data generation for queries involving views

- legend-engine-xts-mastery/legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/from/acquisition/AcquisitionProtocolParseTreeWalker.java
- legend-engine-xts-mastery/legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/from/authentication/AuthenticationParseTreeWalker.java
- legend-engine-xts-mastery/legend-engine-xt-mastery-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/MasteryProtocolExtension.java
Bug Fix
The Decryption protocol extensions were missing for the subtypes of decryption
> Adding mastery decryption protocol extension

- pom.xml
Update legend-pure to 4.6.0
Fixes #
> Update legend-pure to 4.6.0

- legend-engine-core/legend-engine-core-test/legend-engine-test-data-generation/pom.xml
- legend-engine-core/legend-engine-core-test/legend-engine-test-data-generation/src/main/java/org/finos/legend/engine/testData/generation/api/TestDataGeneration.java
- legend-engine-core/legend-engine-core-test/legend-engine-test-data-generation/src/main/java/org/finos/legend/engine/testData/generation/service/TestDataGenerationService.java
- legend-engine-core/legend-engine-core-test/legend-engine-test-data-generation/src/test/java/org.finos.legend.engine/testDataGeneration/TestDataGenerationTest.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/milestoning/milestoning.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/testDataGeneration/testDataGeneration.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/testDataGeneration/tests/testDataGeneration.pure
Test Data Generation - only show necessary columns (**not null | primary key | used columns**) of tables used in query
Fixes #
> Test Data Generation - only show necessary columns of tables used in query

- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tds/tests/testTDSExtend.pure
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tds/tests/testTDSFilter.pure
- legend-engine-xts-sql/legend-engine-xt-sql-grammar/src/main/java/org/finos/legend/engine/language/sql/grammar/from/SqlVisitor.java
- legend-engine-xts-sql/legend-engine-xt-sql-grammar/src/main/java/org/finos/legend/engine/language/sql/grammar/to/SQLGrammarComposer.java
- legend-engine-xts-sql/legend-engine-xt-sql-grammar/src/test/java/org/finos/legend/engine/language/sql/grammar/test/roundtrip/TestSQLRoundTrip.java
- legend-engine-xts-sql/legend-engine-xt-sql-pure-metamodel/src/main/resources/core_external_query_sql_metamodel/metamodel.pure
- legend-engine-xts-sql/legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/fromPure.pure
- legend-engine-xts-sql/legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/tests/testTranspile.pure
Improvement
- support parseDate in post tds flow
- support getDecimal in post tds flow
- support firstNotNull in tds filter -> where
- legend sql - support cross join
- legend sql - support date arithmetic on aggregated values
> SQL - assortment of updates

- legend-engine-xts-mastery/legend-engine-xt-mastery-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/MasteryParserGrammar.g4
- legend-engine-xts-mastery/legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/from/MasteryParseTreeWalker.java
- legend-engine-xts-mastery/legend-engine-xt-mastery-grammar/src/test/java/org/finos/legend/engine/language/pure/dsl/mastery/compiler/test/TestMasteryCompilationFromGrammar.java
Bug Fix
When words that are defined as Lexer tokens are used in other fields, this was causing a parser error - this PR is to fix that
> fix mastery grammar when special tokens used

- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/RelationalExecutor.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-execution/legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/VoidRelationalResult.java
Bug Fix
Fixes logging in VoidRelationalResult in cases where server is configured to not log SQL because of sensitive values
Fixes #
Logging fix, no tests, manual checks only
No
> Flag for sql logging in VoidRelationalResult - used for temp table

- legend-engine-pure/legend-engine-pure-code/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/tests/executionPlanTests.pure
- legend-engine-pure/legend-engine-pure-code/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/metaExtension.pure
Improvement 
Add support for relaxed version of extractRuntimeFromFunction
Fixes #
> Add support for relaxed version of extractRuntimeFromFunction

- legend-engine-core/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PureModel.java
> Add date enums to pathToElement register

- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/autogeneration/relationalToPure.pure
> remove lowercase of generated models from db

- legend-engine-core/legend-engine-core-language-pure/legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PureModel.java
This reverts commit 1f83e05a4fdd8da2601be65befd0991a5737d2d1.
Reverting this change due to tc fails 
blocks 4.29.0 release flow 
Fixes #2290 
No
> Revert "Add date enums to pathToElement register (#2290)"

- pom.xml
> Upgrade legend pure to 4.7.0

- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-api/pom.xml
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-api/src/test/java/org/finos/legend/engine/language/pure/relational/api/relationalElement/test/TestRelationalElementApi.java
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-api/src/test/resources/expectedJson.json
- legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-api/src/test/resources/inputGrammar.pure
> enhance TestRelationalElementApi by adding compile phase

- legend-engine-xts-analytics/legend-engine-xts-analytics-mapping/legend-engine-xt-analytics-mapping-api/pom.xml
- legend-engine-xts-analytics/legend-engine-xts-analytics-mapping/legend-engine-xt-analytics-mapping-pure/pom.xml
- legend-engine-xts-analytics/legend-engine-xts-analytics-mapping/legend-engine-xt-analytics-mapping-pure/src/main/resources/core_analytics_mapping.definition.json
- legend-engine-xts-analytics/legend-engine-xts-analytics-mapping/legend-engine-xt-analytics-mapping-pure/src/main/resources/core_analytics_mapping/modelCoverage/analyticsTest.pure
- legend-engine-xts-analytics/legend-engine-xts-analytics-mapping/legend-engine-xt-analytics-mapping-pure/src/main/resources/core_analytics_mapping/modelCoverage/mappedEntityBuilder.pure
- legend-engine-xts-analytics/legend-engine-xts-analytics-search/legend-engine-xt-analytics-search-generation/pom.xml
- legend-engine-xts-analytics/legend-engine-xts-analytics-search/legend-engine-xt-analytics-search-pure/pom.xml
- legend-engine-xts-analytics/legend-engine-xts-analytics-search/legend-engine-xt-analytics-search-pure/src/main/resources/core_analytics_search.definition.json
- legend-engine-xts-data-space/legend-engine-xt-data-space-api/pom.xml
- legend-engine-xts-data-space/legend-engine-xt-data-space-generation/pom.xml
- legend-engine-xts-data-space/legend-engine-xt-data-space-pure/pom.xml
- legend-engine-xts-data-space/legend-engine-xt-data-space-pure/src/main/resources/core_data_space.definition.json
Improvement
Improve mapping coverage analysis algo to support analysis for binding queries
after: 
https://github.com/finos/legend-engine/assets/73408381/6b9a59b0-e595-4fb8-b565-987cace85440
Fixes #
> Improve mapping coverage analysis algo to support analysis for complex auto mapped

- legend-engine-xts-java/legend-engine-xt-javaGeneration-featureBased-pure/src/main/resources/core_external_language_java_feature_based_generation/generation.pure
- legend-engine-xts-java/legend-engine-xt-javaGeneration-featureBased-pure/src/main/resources/core_external_language_java_feature_based_generation/generationTest.pure
- legend-engine-xts-java/legend-engine-xt-javaGeneration-featureBased-pure/src/main/resources/core_external_language_java_feature_based_generation/resources/expectedSources.pure
Improvement
Introducing feature to provide Constructor injection with only getters
This is to support immutable POJOs
No
> Adding new features for Java code generation

- legend-engine-xts-analytics/legend-engine-xts-analytics-mapping/legend-engine-xt-analytics-mapping-pure/src/main/resources/core_analytics_mapping/modelCoverage/mappedEntityBuilder.pure
Bug Fix
fix mapping analysis algo
Fixes #
> fix mapping analysis algo

- legend-engine-pure/legend-engine-pure-code/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/tds/tdsSchema.pure
- legend-engine-pure/legend-engine-pure-code/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/tds/testTdsSchema.pure
Improvement
Support schema resolve of calls to tabular input functions
> resolveSchema - support calls to Tabular functions
